-- Generated by scripts/new-product-creation-plan.mjs
-- Batch: asiandeligo-new-products-folder14-20260713
-- Runtime channel guard: asiandeligo
-- Purpose: create owner-confirmed Asia Deli Go draft products with owner images.
-- Safe behavior: creates products as draft/unpublished/not-for-sale with retail_price=0 and price_pending metadata.
-- Media precondition: files must be uploaded before running this SQL so every target_url returns 200.
--
-- JOIN contract:
--   channels.slug resolves one active channel; channels.salon_id scopes all product/category/variant/image/translation writes.
--   products.category_id (uuid, FK) = categories.id (uuid, PK); categories.salon_id must equal target channel salon_id.
--   product_variants.template_id (uuid, FK) = products.id (uuid, PK); product_variants.salon_id = products.salon_id.
--   product_images.template_id (uuid, FK) = products.id (uuid, PK); product_images.variant_id remains NULL.
--   product_translations.template_id (uuid, FK) = products.id (uuid, PK).
--   Soft-delete: duplicate guards ignore rows with products/product_variants.deleted_at IS NOT NULL.
BEGIN;

CREATE TEMP TABLE _adg_new_product_source (
  product_id uuid NOT NULL DEFAULT gen_random_uuid(),
  variant_id uuid NOT NULL DEFAULT gen_random_uuid(),
  review_id text NOT NULL,
  draft_sku text NOT NULL,
  slug text NOT NULL,
  pl_name text NOT NULL,
  en_name text NOT NULL,
  brand text,
  size_label text,
  category_slug text NOT NULL,
  ean text,
  stock integer NOT NULL,
  dietary_tags jsonb NOT NULL DEFAULT '[]'::jsonb,
  allergens jsonb NOT NULL DEFAULT '[]'::jsonb,
  country_of_origin text,
  source_image text NOT NULL,
  target_url text NOT NULL,
  r2_key text NOT NULL,
  sha256 text NOT NULL,
  file_size integer NOT NULL,
  width integer NOT NULL,
  height integer NOT NULL,
  PRIMARY KEY (draft_sku),
  UNIQUE (slug),
  UNIQUE (target_url),
  UNIQUE (r2_key),
  UNIQUE (sha256)
) ON COMMIT DROP;

INSERT INTO _adg_new_product_source (
  review_id, draft_sku, slug, pl_name, en_name, brand, size_label, category_slug, ean, stock,
  dietary_tags, allergens, country_of_origin, source_image, target_url, r2_key, sha256, file_size, width, height
)
VALUES
  ('folder14-001', 'ADG-001792', 'asia-foods-red-sleeve-disposable-bamboo-chopsticks-paleczki-bambusowe-jednorazowego-uzytku', 'Asia Foods red-sleeve disposable bamboo chopsticks / Paleczki Bambusowe Jednorazowego Uzytku', 'Asia Foods red-sleeve disposable bamboo chopsticks / Paleczki Bambusowe Jednorazowego Uzytku', NULL, NULL, 'pałeczki-i-sztućce', NULL, 100, '[]'::jsonb, '[]'::jsonb, NULL, 'PETE7343.JPG', 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001792/01-PETE7343.JPG', 'owner-images/folder14/ADG-001792/01-PETE7343.JPG', 'caee49c914aaf2e8bd85c1e6a4031d49c6a137f6a95320f9fcda70a9f33ead5f', 5270088, 5760, 3840),
  ('folder14-002', 'ADG-001793', 'green-white-sleeve-disposable-chopsticks-exact-brand-count-unclear', 'Green-white sleeve disposable chopsticks, exact brand/count unclear', 'Green-white sleeve disposable chopsticks, exact brand/count unclear', NULL, NULL, 'pałeczki-i-sztućce', NULL, 100, '[]'::jsonb, '[]'::jsonb, NULL, 'PETE7879.JPG', 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001793/01-PETE7879.JPG', 'owner-images/folder14/ADG-001793/01-PETE7879.JPG', '5cc8910578e2e53465ba26704cdcb10c1669033a71978aa2a9bf1c96493ce429', 4401027, 5760, 3840),
  ('folder14-003', 'ADG-001794', 'huhtamaki-econo-xps-oval-plates-26-2-x-19-3cm-50-pcs', 'Huhtamaki Econo XPS oval plates 26.2 x 19.3cm, 50 pcs', 'Huhtamaki Econo XPS oval plates 26.2 x 19.3cm, 50 pcs', NULL, NULL, 'naczynia', NULL, 100, '[]'::jsonb, '[]'::jsonb, NULL, 'PETE7759.JPG', 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001794/01-PETE7759.JPG', 'owner-images/folder14/ADG-001794/01-PETE7759.JPG', '79253fc077ffda79bd3a81a57d6329f9372a2efd9b78d47db1873069614c5474', 4136010, 5760, 3840),
  ('folder14-004', 'ADG-001795', 'white-foam-takeaway-clamshell-food-boxes-multiple-compartments', 'White foam takeaway clamshell food boxes, multiple compartments', 'White foam takeaway clamshell food boxes, multiple compartments', NULL, NULL, 'naczynia', NULL, 100, '[]'::jsonb, '[]'::jsonb, NULL, 'PETE8028.JPG', 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001795/01-PETE8028.JPG', 'owner-images/folder14/ADG-001795/01-PETE8028.JPG', '4d939d9ed6adaccc7c4fab13c5ec62f4d085a2593197506de465e39af775f180', 5011352, 5760, 3840),
  ('folder14-005', 'ADG-001796', 'metal-wok-spatula-chinese-cooking-turner-with-wooden-handle', 'Metal wok spatula / Chinese cooking turner with wooden handle', 'Metal wok spatula / Chinese cooking turner with wooden handle', NULL, NULL, 'patelnie-wok-grill', NULL, 100, '[]'::jsonb, '[]'::jsonb, NULL, 'PETE8032.JPG', 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001796/01-PETE8032.JPG', 'owner-images/folder14/ADG-001796/01-PETE8032.JPG', 'c20db3cb2be0dad938c64923cd6fb217c67d16d84fa2d5cb04e9dcc41b1a72d3', 4543293, 5760, 3840),
  ('folder14-006', 'ADG-001797', 'ceramic-lidded-bowl-with-warmer-stand-ips-ceramic', 'Ceramic lidded bowl with warmer/stand, IPS Ceramic', 'Ceramic lidded bowl with warmer/stand, IPS Ceramic', NULL, NULL, 'miski', NULL, 100, '[]'::jsonb, '[]'::jsonb, NULL, 'PETE8037.JPG', 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001797/01-PETE8037.JPG', 'owner-images/folder14/ADG-001797/01-PETE8037.JPG', '7cb052bf489cc3625e332ef996f84e1fe0d4a8f048585ebfb27ac227bf02373a', 3986507, 5760, 3840),
  ('folder14-007', 'ADG-001798', 'bamboo-handle-wire-spider-strainer-skimmer', 'Bamboo-handle wire spider strainer / skimmer', 'Bamboo-handle wire spider strainer / skimmer', NULL, NULL, 'patelnie-wok-grill', NULL, 100, '[]'::jsonb, '[]'::jsonb, NULL, 'PETE8040.JPG', 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001798/01-PETE8040.JPG', 'owner-images/folder14/ADG-001798/01-PETE8040.JPG', '1d126098fce68322e12d0c0dfb036d007fde353e8c201270917ae39811ceaa44', 6636652, 5760, 3840),
  ('folder14-008', 'ADG-001799', 'carbon-steel-wok-with-single-wooden-handle-size-unclear', 'Carbon steel wok with single wooden handle, size unclear', 'Carbon steel wok with single wooden handle, size unclear', NULL, NULL, 'patelnie-wok-grill', NULL, 100, '[]'::jsonb, '[]'::jsonb, NULL, 'PETE8045.JPG', 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001799/01-PETE8045.JPG', 'owner-images/folder14/ADG-001799/01-PETE8045.JPG', '20fde276f7414f54937d60e65111f496603a89b30f40322d77cc4fcfc190cf80', 4975563, 5760, 3840),
  ('folder14-009', 'ADG-001800', 'carbon-steel-wok-with-two-side-handles-size-unclear', 'Carbon steel wok with two side handles, size unclear', 'Carbon steel wok with two side handles, size unclear', NULL, NULL, 'patelnie-wok-grill', NULL, 100, '[]'::jsonb, '[]'::jsonb, NULL, 'PETE8049.JPG', 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001800/01-PETE8049.JPG', 'owner-images/folder14/ADG-001800/01-PETE8049.JPG', '18ca92e3d0711206ae20ee7dabb535c15c9e02a3fc7ec7b885c38d1df27a05a7', 4988719, 5760, 3840),
  ('folder14-010', 'ADG-001801', 'stainless-perforated-colander-steamer-insert-bowl', 'Stainless perforated colander / steamer insert bowl', 'Stainless perforated colander / steamer insert bowl', NULL, NULL, 'patelnie-wok-grill', NULL, 100, '[]'::jsonb, '[]'::jsonb, NULL, 'PETE8050.JPG', 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001801/01-PETE8050.JPG', 'owner-images/folder14/ADG-001801/01-PETE8050.JPG', '606a52d325c1ce7fb7bd362fe8e661269c063b500bd66d48bd4511a9eb7e263e', 6457044, 5760, 3840),
  ('folder14-011', 'ADG-001802', 'wooden-handle-chinese-cleaver-kitchen-knife-exact-model-unclear', 'Wooden-handle Chinese cleaver / kitchen knife, exact model unclear', 'Wooden-handle Chinese cleaver / kitchen knife, exact model unclear', NULL, NULL, 'noże', NULL, 100, '[]'::jsonb, '[]'::jsonb, NULL, 'PETE8053.JPG', 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001802/01-PETE8053.JPG', 'owner-images/folder14/ADG-001802/01-PETE8053.JPG', '52cc1c59fa224abb4056c61fd36443240b607b932564313b4843840af217ec4b', 7976889, 5760, 3840),
  ('folder14-012', 'ADG-001803', 'stainless-handle-chinese-cleaver-exact-model-unclear', 'Stainless-handle Chinese cleaver, exact model unclear', 'Stainless-handle Chinese cleaver, exact model unclear', NULL, NULL, 'noże', NULL, 100, '[]'::jsonb, '[]'::jsonb, NULL, 'PETE8063.JPG', 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001803/01-PETE8063.JPG', 'owner-images/folder14/ADG-001803/01-PETE8063.JPG', '1e5ead86b5b7d1df2fb2ec78743666eb85b8ec97796f6b59f97a262aa384b818', 5686692, 5760, 3840),
  ('folder14-013', 'ADG-001804', 'round-ceramic-steaming-rack-trivet-size-unclear', 'Round ceramic steaming rack / trivet, size unclear', 'Round ceramic steaming rack / trivet, size unclear', NULL, NULL, 'naczynia', NULL, 100, '[]'::jsonb, '[]'::jsonb, NULL, 'PETE8057.JPG', 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001804/01-PETE8057.JPG', 'owner-images/folder14/ADG-001804/01-PETE8057.JPG', '0844fc89ae27f08c1ac3421147cbc571b5d7480ef977277b50ea53a9ada11ba0', 5918458, 5760, 3840),
  ('folder14-014', 'ADG-001805', 'assorted-metal-soup-ladles-multiple-handle-styles-sizes', 'Assorted metal soup ladles, multiple handle styles/sizes', 'Assorted metal soup ladles, multiple handle styles/sizes', NULL, NULL, 'naczynia', NULL, 100, '[]'::jsonb, '[]'::jsonb, NULL, 'PETE8067.JPG', 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001805/01-PETE8067.JPG', 'owner-images/folder14/ADG-001805/01-PETE8067.JPG', 'ff344b77e0141380c9cd17e7c513f0ea95d6599e0d12364c411054cadde987d4', 5121101, 5760, 3840),
  ('folder14-015', 'ADG-001806', 'wooden-handle-asian-chef-knife-santoku-style-knife-exact-model-unclear', 'Wooden-handle Asian chef knife / santoku-style knife, exact model unclear', 'Wooden-handle Asian chef knife / santoku-style knife, exact model unclear', NULL, NULL, 'noże', NULL, 100, '[]'::jsonb, '[]'::jsonb, NULL, 'PETE8092.JPG', 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001806/01-PETE8092.JPG', 'owner-images/folder14/ADG-001806/01-PETE8092.JPG', '864525ddf0d0e2673dd9c444b1e64dba5d9843d188fd9027338164150d379b00', 7241316, 5760, 3840),
  ('folder14-016', 'ADG-001807', 'black-handle-kitchen-knife-cleaver-exact-model-unclear', 'Black-handle kitchen knife / cleaver, exact model unclear', 'Black-handle kitchen knife / cleaver, exact model unclear', NULL, NULL, 'noże', NULL, 100, '[]'::jsonb, '[]'::jsonb, NULL, 'PETE8094.JPG', 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001807/01-PETE8094.JPG', 'owner-images/folder14/ADG-001807/01-PETE8094.JPG', '3636d7aa624d572f73591afeed7f45907d27a8174171e127cb674f8680e6275c', 7733311, 5760, 3840),
  ('folder14-017', 'ADG-001808', 'lct-long-cam-stainless-vietnamese-coffee-filter-phin-ca-phe', 'LCT Long Cam stainless Vietnamese coffee filter / phin ca phe', 'LCT Long Cam stainless Vietnamese coffee filter / phin ca phe', NULL, NULL, 'zaparzacze-do-kawy', NULL, 100, '[]'::jsonb, '[]'::jsonb, NULL, 'PETE8099.JPG', 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001808/01-PETE8099.JPG', 'owner-images/folder14/ADG-001808/01-PETE8099.JPG', '3ec4e90223289d454b219b1b7fba60c636e82716b78dfd5418b9af1c777120bf', 4913495, 5760, 3840),
  ('folder14-018', 'ADG-001809', 'bamboo-sushi-rolling-mat-makisu', 'Bamboo sushi rolling mat / makisu', 'Bamboo sushi rolling mat / makisu', NULL, NULL, 'maty-do-zwijania', NULL, 100, '[]'::jsonb, '[]'::jsonb, NULL, 'PETE8101.JPG', 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001809/01-PETE8101.JPG', 'owner-images/folder14/ADG-001809/01-PETE8101.JPG', 'bb7d17ba4aabe73c98bb3292975b8f2226abef3eaa869ce0203ee86f2c3add9a', 7617455, 5760, 3840),
  ('folder14-019', 'ADG-001810', 'black-chopsticks-bundle-unlabelled', 'Black chopsticks bundle, unlabelled', 'Black chopsticks bundle, unlabelled', NULL, NULL, 'pałeczki-i-sztućce', NULL, 100, '[]'::jsonb, '[]'::jsonb, NULL, 'PETE8102.JPG', 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001810/01-PETE8102.JPG', 'owner-images/folder14/ADG-001810/01-PETE8102.JPG', 'd6ae298f82387b1514302ac1c2728bf334e8ff2174c433848bccd5a9f37dca3b', 7696865, 5760, 3840),
  ('folder14-020', 'ADG-001811', 'stainless-handle-chinese-cleaver-kitchen-knife', 'Stainless-handle Chinese cleaver / kitchen knife', 'Stainless-handle Chinese cleaver / kitchen knife', NULL, NULL, 'noże', NULL, 100, '[]'::jsonb, '[]'::jsonb, NULL, 'PETE8104.JPG', 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001811/01-PETE8104.JPG', 'owner-images/folder14/ADG-001811/01-PETE8104.JPG', 'e51a856a30c62a39a3f0779ccc6c74f591762b6cd4030aa75a16ca7bd75b2184', 7683248, 5760, 3840),
  ('folder14-022', 'ADG-001812', 'tq-korean-style-wooden-chopsticks-set-5-pairs', 'TQ Korean-style wooden chopsticks set, 5 pairs', 'TQ Korean-style wooden chopsticks set, 5 pairs', NULL, NULL, 'pałeczki-i-sztućce', NULL, 100, '[]'::jsonb, '[]'::jsonb, NULL, 'PETE8106.JPG', 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001812/01-PETE8106.JPG', 'owner-images/folder14/ADG-001812/01-PETE8106.JPG', '000525b990fd42f0abe7fc9c885b525c9b300f3c65abfe2f15086cd2fd209c92', 7371486, 5760, 3840),
  ('folder14-023', 'ADG-001813', 'long-hot-pot-cooking-chopsticks-1-pair', 'Long hot-pot / cooking chopsticks, 1 pair', 'Long hot-pot / cooking chopsticks, 1 pair', NULL, NULL, 'pałeczki-i-sztućce', NULL, 100, '[]'::jsonb, '[]'::jsonb, NULL, 'PETE8107.JPG', 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001813/01-PETE8107.JPG', 'owner-images/folder14/ADG-001813/01-PETE8107.JPG', 'f8c632f82216c84a422ac011578026cd296e698203713c2faca455e5cd2d0211', 6228897, 5760, 3840),
  ('folder14-024', 'ADG-001814', 'bamboo-handle-wire-spider-strainer-skimmer-adg-001814', 'Bamboo-handle wire spider strainer / skimmer', 'Bamboo-handle wire spider strainer / skimmer', NULL, NULL, 'patelnie-wok-grill', NULL, 100, '[]'::jsonb, '[]'::jsonb, NULL, 'PETE8108.JPG', 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001814/01-PETE8108.JPG', 'owner-images/folder14/ADG-001814/01-PETE8108.JPG', '056836e8f92136ff5cdc8e82e0690ec93c6d52a7cea76e6d613428aea732fb56', 6294545, 5760, 3840),
  ('folder14-026', 'ADG-001815', 'best-888-playing-cards-red-pack', 'Best 888 playing cards, red pack', 'Best 888 playing cards, red pack', NULL, NULL, 'pozostałe-produkty', NULL, 100, '[]'::jsonb, '[]'::jsonb, NULL, 'PETE8113.JPG', 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001815/01-PETE8113.JPG', 'owner-images/folder14/ADG-001815/01-PETE8113.JPG', '9e74180cbf764250780b0a335dcc935aa033cdb682420755e3738d5e2214f3a3', 8661247, 5760, 3840),
  ('folder14-027', 'ADG-001816', 'rectangular-knife-sharpening-stone', 'Rectangular knife sharpening stone', 'Rectangular knife sharpening stone', NULL, NULL, 'noże', NULL, 100, '[]'::jsonb, '[]'::jsonb, NULL, 'PETE8114.JPG', 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001816/01-PETE8114.JPG', 'owner-images/folder14/ADG-001816/01-PETE8114.JPG', '120a68996117f198d5d7b3a26457e6ce99053ef83ecefe7eac5ed1201929130e', 10422696, 5760, 3840),
  ('folder14-028', 'ADG-001817', 'triple-gas-valve-burner-manifold-component', 'Triple gas valve / burner manifold component', 'Triple gas valve / burner manifold component', NULL, NULL, 'pozostałe-produkty', NULL, 100, '[]'::jsonb, '[]'::jsonb, NULL, 'PETE8116.JPG', 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001817/01-PETE8116.JPG', 'owner-images/folder14/ADG-001817/01-PETE8116.JPG', 'd1482afaf63c38e97ad9f1e1580cc0bdd21512dc6bbe2e25d99a304e33d2e6ed', 4778164, 5760, 3840),
  ('folder14-030', 'ADG-001818', 'red-chinese-vietnamese-hanging-lantern-decoration', 'Red Chinese/Vietnamese hanging lantern decoration', 'Red Chinese/Vietnamese hanging lantern decoration', NULL, NULL, 'koty-szczęścia-i-inne-gadżety', NULL, 100, '[]'::jsonb, '[]'::jsonb, NULL, 'PETE8121.JPG', 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001818/01-PETE8121.JPG', 'owner-images/folder14/ADG-001818/01-PETE8121.JPG', 'fc03bf33afc0996eed9af0b79d5235aee093cf89d62ee76d300cd6806727b4e0', 4982522, 5760, 3840),
  ('folder14-031', 'ADG-001819', 'bamboo-steamer-baskets-lids-size-variants-unclear', 'Bamboo steamer baskets/lids, size variants unclear', 'Bamboo steamer baskets/lids, size variants unclear', NULL, NULL, 'parowary-bambusowe', NULL, 100, '[]'::jsonb, '[]'::jsonb, NULL, 'PETE8129.JPG', 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001819/01-PETE8129.JPG', 'owner-images/folder14/ADG-001819/01-PETE8129.JPG', '6cdad1ebf4bb635e94ec3c7f062ea6bf1ce49bbbe52d97533105dc18db0ed79c', 5761737, 5760, 3840),
  ('folder14-032', 'ADG-001820', 'bamboo-plastic-rim-steamer-or-lidded-basket', 'Bamboo/plastic rim steamer or lidded basket', 'Bamboo/plastic rim steamer or lidded basket', NULL, NULL, 'parowary-bambusowe', NULL, 100, '[]'::jsonb, '[]'::jsonb, NULL, 'PETE8134.JPG', 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001820/01-PETE8134.JPG', 'owner-images/folder14/ADG-001820/01-PETE8134.JPG', 'a167289aa843cee0b08d1e1ff0a175c4de0e0eafabfdfb594930622018aa97b0', 5426834, 5760, 3840),
  ('folder14-033', 'ADG-001821', 'plain-white-ceramic-bowl', 'Plain white ceramic bowl', 'Plain white ceramic bowl', NULL, NULL, 'miski', NULL, 100, '[]'::jsonb, '[]'::jsonb, NULL, 'PETE8135.JPG', 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001821/01-PETE8135.JPG', 'owner-images/folder14/ADG-001821/01-PETE8135.JPG', '299575b3a0072b14e6e5670789a8284494cd88dd396cc361bc3a2124f5b2f3c4', 4988322, 5760, 3840),
  ('folder14-034', 'ADG-001822', 'blue-white-ceramic-rice-bowl', 'Blue-white ceramic rice bowl', 'Blue-white ceramic rice bowl', NULL, NULL, 'miski', NULL, 100, '[]'::jsonb, '[]'::jsonb, NULL, 'PETE8136.JPG', 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001822/01-PETE8136.JPG', 'owner-images/folder14/ADG-001822/01-PETE8136.JPG', '37935b8ffba692770c1b210daa9c9734731c1a1df34d918eeff90f706da772ae', 5175683, 5760, 3840),
  ('folder14-035', 'ADG-001823', 'white-ceramic-soup-spoons-with-green-pattern', 'White ceramic soup spoons with green pattern', 'White ceramic soup spoons with green pattern', NULL, NULL, 'naczynia', NULL, 100, '[]'::jsonb, '[]'::jsonb, NULL, 'PETE8138.JPG', 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001823/01-PETE8138.JPG', 'owner-images/folder14/ADG-001823/01-PETE8138.JPG', '8cb5dfc970b340c1c64abc53a4233acaca74dabf457e6cd720f5d564ce5cd102', 5374526, 5760, 3840),
  ('folder14-036', 'ADG-001824', 'cast-iron-oval-sizzling-plate-with-wooden-base', 'Cast iron oval sizzling plate with wooden base', 'Cast iron oval sizzling plate with wooden base', NULL, NULL, 'patelnie-wok-grill', NULL, 100, '[]'::jsonb, '[]'::jsonb, NULL, 'PETE8140.JPG', 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001824/01-PETE8140.JPG', 'owner-images/folder14/ADG-001824/01-PETE8140.JPG', '685470ab861724a28541bce96f7be1ce424da10fcac26dababb5cd4cb6b80ee1', 4746207, 5760, 3840),
  ('folder14-037', 'ADG-001825', 'cast-iron-decorative-sizzling-plate-with-wooden-base', 'Cast iron decorative sizzling plate with wooden base', 'Cast iron decorative sizzling plate with wooden base', NULL, NULL, 'patelnie-wok-grill', NULL, 100, '[]'::jsonb, '[]'::jsonb, NULL, 'PETE8141.JPG', 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001825/01-PETE8141.JPG', 'owner-images/folder14/ADG-001825/01-PETE8141.JPG', 'd413822e624d82190f65c810b8bc23fdf59526a897a237437ba6a4f8af872b02', 7868047, 5760, 3840),
  ('folder14-038', 'ADG-001826', 'boxed-ceremonial-altar-paper-decoration-set-size-variants-unclear', 'Boxed ceremonial / altar paper decoration set, size variants unclear', 'Boxed ceremonial / altar paper decoration set, size variants unclear', NULL, NULL, 'koty-szczęścia-i-inne-gadżety', NULL, 100, '[]'::jsonb, '[]'::jsonb, NULL, 'PETE8142.JPG', 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001826/01-PETE8142.JPG', 'owner-images/folder14/ADG-001826/01-PETE8142.JPG', '6e177a4f7c2e58ced2d5e02629307ca9070682dbfce53fb30f2f76e5acb0261b', 8229088, 5760, 3840),
  ('folder14-039', 'ADG-001827', 'three-chinese-vietnamese-deity-figurines-set', 'Three Chinese/Vietnamese deity figurines set', 'Three Chinese/Vietnamese deity figurines set', NULL, NULL, 'koty-szczęścia-i-inne-gadżety', NULL, 100, '[]'::jsonb, '[]'::jsonb, NULL, 'PETE8143.JPG', 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001827/01-PETE8143.JPG', 'owner-images/folder14/ADG-001827/01-PETE8143.JPG', '666202d1aaeaad8ee2f2a891e8f382705c5a7a25522ea0c326e7f72ddecc7e51', 6041875, 5760, 3840),
  ('folder14-040', 'ADG-001828', 'blue-white-ceramic-incense-burner-ashtray-style-pot', 'Blue-white ceramic incense burner / ashtray-style pot', 'Blue-white ceramic incense burner / ashtray-style pot', NULL, NULL, 'koty-szczęścia-i-inne-gadżety', NULL, 100, '[]'::jsonb, '[]'::jsonb, NULL, 'PETE8147.JPG', 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001828/01-PETE8147.JPG', 'owner-images/folder14/ADG-001828/01-PETE8147.JPG', '3a593f9b3b63db6c5c30db47feee2b6b778f3aecfb8199aa2756ce169a42b325', 4987038, 5760, 3840),
  ('folder14-041', 'ADG-001829', 'hang-viet-red-incense-sticks-nhang-viet-vietnam-origin', 'Hang Viet red incense sticks / Nhang Viet, Vietnam origin', 'Hang Viet red incense sticks / Nhang Viet, Vietnam origin', NULL, NULL, 'koty-szczęścia-i-inne-gadżety', NULL, 100, '[]'::jsonb, '[]'::jsonb, NULL, 'PETE8148.JPG', 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001829/01-PETE8148.JPG', 'owner-images/folder14/ADG-001829/01-PETE8148.JPG', 'a2f875c01708beca08ffae1b97b1522a1f87f275714ab04b28aef29952cd900a', 4546433, 5760, 3840),
  ('folder14-042', 'ADG-001830', 'joss-paper-ceremonial-imitation-money-pack', 'Joss paper / ceremonial imitation money pack', 'Joss paper / ceremonial imitation money pack', NULL, NULL, 'koty-szczęścia-i-inne-gadżety', NULL, 100, '[]'::jsonb, '[]'::jsonb, NULL, 'PETE8151.JPG', 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001830/01-PETE8151.JPG', 'owner-images/folder14/ADG-001830/01-PETE8151.JPG', '44b07c1c35523911c20e5b4a32c20001af7cc647aaf5677ac5e4df776c801879', 4960190, 5760, 3840),
  ('folder14-043', 'ADG-001831', 'gold-dragon-altar-hanging-decoration-piece', 'Gold dragon / altar hanging decoration piece', 'Gold dragon / altar hanging decoration piece', NULL, NULL, 'koty-szczęścia-i-inne-gadżety', NULL, 100, '[]'::jsonb, '[]'::jsonb, NULL, 'PETE8152.JPG', 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001831/01-PETE8152.JPG', 'owner-images/folder14/ADG-001831/01-PETE8152.JPG', 'ff552b9124cb7500e142841271ec311f43097c2add89bb4b59fb4b164148ea56', 7137173, 5760, 3840),
  ('folder14-044', 'ADG-001832', 'clear-plastic-lid-container-cover-unlabelled', 'Clear plastic lid / container cover, unlabelled', 'Clear plastic lid / container cover, unlabelled', NULL, NULL, 'naczynia', NULL, 100, '[]'::jsonb, '[]'::jsonb, NULL, 'PETE8161.JPG', 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001832/01-PETE8161.JPG', 'owner-images/folder14/ADG-001832/01-PETE8161.JPG', 'ad579a54d9a7c8fa3cf95eff8e3e3fc58e957a494c80ea14814d8c117a74d1a5', 4284643, 5760, 3840),
  ('folder14-046', 'ADG-001833', 'happy-new-year-red-paper-gift-bags-envelopes', 'Happy New Year red paper gift bags / envelopes', 'Happy New Year red paper gift bags / envelopes', NULL, NULL, 'prezenty', NULL, 100, '[]'::jsonb, '[]'::jsonb, NULL, 'PETE8167.JPG', 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001833/01-PETE8167.JPG', 'owner-images/folder14/ADG-001833/01-PETE8167.JPG', 'd58ff73d7da9f90f7954d96f332935291897356277aab0faf25748c99af81882', 6410417, 5760, 3840),
  ('folder14-047', 'ADG-001834', 'hiep-long-mut-tet-dried-fruit-mix-gift-box-600g', 'Hiep Long Mut Tet dried fruit mix gift box 600g', 'Hiep Long Mut Tet dried fruit mix gift box 600g', NULL, NULL, 'słodycze-przekąski', NULL, 100, '[]'::jsonb, '[]'::jsonb, NULL, 'PETE8168.JPG', 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001834/01-PETE8168.JPG', 'owner-images/folder14/ADG-001834/01-PETE8168.JPG', 'dfbb456a10f7ecd412cea98c071e4999be80c5720fec0e2d8d216244e379bfee', 6164428, 5760, 3840),
  ('folder14-048', 'ADG-001835', 'phuong-vy-green-tea-100g', 'Phuong Vy green tea 100g', 'Phuong Vy green tea 100g', NULL, NULL, 'herbaty', NULL, 100, '[]'::jsonb, '[]'::jsonb, NULL, 'PETE8170.JPG', 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001835/01-PETE8170.JPG', 'owner-images/folder14/ADG-001835/01-PETE8170.JPG', '8860b7b648ba05621d00b1137d4dcdf766d13b07588a33d70e421a89126889ff', 6340883, 5760, 3840),
  ('folder14-049', 'ADG-001836', 'minh-ngoc-green-bean-cake-banh-dau-xanh-300g', 'Minh Ngoc green bean cake / Banh dau xanh 300g', 'Minh Ngoc green bean cake / Banh dau xanh 300g', NULL, NULL, 'słodycze-przekąski', NULL, 100, '[]'::jsonb, '[]'::jsonb, NULL, 'PETE8171.JPG', 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001836/01-PETE8171.JPG', 'owner-images/folder14/ADG-001836/01-PETE8171.JPG', 'f64ff06fd9c65aed0c46687d4a2d008c5f8dd0eafa17cb4910116484962cc467', 9404892, 5760, 3840),
  ('folder14-050', 'ADG-001837', 'asia-foods-branded-paper-shopping-bags', 'Asia Foods branded paper shopping bags', 'Asia Foods branded paper shopping bags', NULL, NULL, 'pozostałe-produkty', NULL, 100, '[]'::jsonb, '[]'::jsonb, NULL, 'PETE8173.JPG', 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001837/01-PETE8173.JPG', 'owner-images/folder14/ADG-001837/01-PETE8173.JPG', 'f9b80d3327fd5710830ffb48b676aeeef773bf2923859ecfcc609a46b9f7ec07', 4919814, 5760, 3840),
  ('folder14-051', 'ADG-001838', 'cuckoo-electric-rice-cooker-model-unclear', 'Cuckoo electric rice cooker, model unclear', 'Cuckoo electric rice cooker, model unclear', NULL, NULL, 'pozostałe-produkty', NULL, 100, '[]'::jsonb, '[]'::jsonb, NULL, 'PETE8175.JPG', 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001838/01-PETE8175.JPG', 'owner-images/folder14/ADG-001838/01-PETE8175.JPG', '5626da6d69cf60ab83d0d2731afc9405708de5dc4ef627d750e71fdeaed430e2', 4796960, 5760, 3840),
  ('folder14-052', 'ADG-001839', 'brown-serving-tea-tray-with-gold-pattern', 'Brown serving / tea tray with gold pattern', 'Brown serving / tea tray with gold pattern', NULL, NULL, 'naczynia', NULL, 100, '[]'::jsonb, '[]'::jsonb, NULL, 'PETE8178.JPG', 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001839/01-PETE8178.JPG', 'owner-images/folder14/ADG-001839/01-PETE8178.JPG', '43cbbae5b5336ad9a1c99250bf02343c31bd46fe18e922877d41ff49afc05c25', 5229553, 5760, 3840),
  ('folder14-053', 'ADG-001840', 'large-stainless-stock-pot-with-lid-and-side-handles', 'Large stainless stock pot with lid and side handles', 'Large stainless stock pot with lid and side handles', NULL, NULL, 'naczynia', NULL, 100, '[]'::jsonb, '[]'::jsonb, NULL, 'PETE8181.JPG', 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001840/01-PETE8181.JPG', 'owner-images/folder14/ADG-001840/01-PETE8181.JPG', 'add912765846b2a85171fbe317e6827e10fac6e2bfa3dea52ed96c8f88893ed1', 5328604, 5760, 3840),
  ('folder14-054', 'ADG-001841', 'sona-sonarema-fondex-tabletop-gas-cooker-burner', 'Sona / SonaRema Fondex tabletop gas cooker / burner', 'Sona / SonaRema Fondex tabletop gas cooker / burner', NULL, NULL, 'pozostałe-produkty', NULL, 100, '[]'::jsonb, '[]'::jsonb, NULL, 'PETE8182.JPG', 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001841/01-PETE8182.JPG', 'owner-images/folder14/ADG-001841/01-PETE8182.JPG', 'c314989d83b6bfae79f13dd94e743952010dd880b76ea076b6db17b0d0f99c00', 5835072, 5760, 3840),
  ('folder14-055', 'ADG-001842', 'electric-rice-cooker-warmer-model-unclear', 'Electric rice cooker / warmer, model unclear', 'Electric rice cooker / warmer, model unclear', NULL, NULL, 'pozostałe-produkty', NULL, 100, '[]'::jsonb, '[]'::jsonb, NULL, 'PETE8199.JPG', 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001842/01-PETE8199.JPG', 'owner-images/folder14/ADG-001842/01-PETE8199.JPG', '9bf526e1f717087ed3359be21a1de3e24d1f2bb262a386225e79f9a54a3b2b31', 4882755, 5760, 3840),
  ('folder14-056', 'ADG-001843', 'manh-hung-stainless-multi-tier-steamer-pot-set', 'Manh Hung stainless multi-tier steamer / pot set', 'Manh Hung stainless multi-tier steamer / pot set', NULL, NULL, 'naczynia', NULL, 100, '[]'::jsonb, '[]'::jsonb, NULL, 'PETE8206.JPG', 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001843/01-PETE8206.JPG', 'owner-images/folder14/ADG-001843/01-PETE8206.JPG', 'af26fa41a6fe7fb07d4347573607e9054bcd4aed44c55aff02ac2c78fa1592d6', 5870215, 5760, 3840),
  ('folder14-057', 'ADG-001844', 'tam-nga-bamboo-toothpicks-200-pcs', 'Tam Nga bamboo toothpicks, 200 pcs', 'Tam Nga bamboo toothpicks, 200 pcs', NULL, NULL, 'pałeczki-i-sztućce', NULL, 100, '[]'::jsonb, '[]'::jsonb, NULL, 'PETE8209.JPG', 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001844/01-PETE8209.JPG', 'owner-images/folder14/ADG-001844/01-PETE8209.JPG', '4c0c635154bb6a95e037a3a684e5caaeb4f160d3a2ebf6668a10b0ee122684e2', 5205362, 5760, 3840);

DO $$
DECLARE
  target_salon_id uuid;
  source_count integer;
  category_count integer;
  existing_sku_count integer;
  existing_slug_count integer;
  existing_ean_count integer;
  existing_image_url_count integer;
  existing_image_hash_count integer;
BEGIN
  SELECT ch.salon_id INTO target_salon_id FROM channels ch WHERE ch.slug = 'asiandeligo' AND ch.is_active = true;
  IF target_salon_id IS NULL THEN
    RAISE EXCEPTION 'Target channel not found or inactive: asiandeligo';
  END IF;

  SELECT COUNT(*) INTO source_count FROM _adg_new_product_source;
  IF source_count <> 53 THEN
    RAISE EXCEPTION 'Expected 53 source products, got %', source_count;
  END IF;

  SELECT COUNT(DISTINCT c.slug) INTO category_count
  FROM _adg_new_product_source s
  JOIN categories c ON c.salon_id = target_salon_id AND c.slug = s.category_slug AND c.is_active = true;
  IF category_count <> (SELECT COUNT(DISTINCT category_slug) FROM _adg_new_product_source) THEN
    RAISE EXCEPTION 'Category guard failed: not all category slugs resolve in target salon';
  END IF;

  SELECT COUNT(*) INTO existing_sku_count
  FROM _adg_new_product_source s
  JOIN product_variants pv ON pv.salon_id = target_salon_id AND pv.deleted_at IS NULL AND pv.sku = s.draft_sku;
  IF existing_sku_count <> 0 THEN
    RAISE EXCEPTION 'SKU guard failed: % target SKUs already exist', existing_sku_count;
  END IF;

  SELECT COUNT(*) INTO existing_slug_count
  FROM _adg_new_product_source s
  JOIN products p ON p.salon_id = target_salon_id AND p.deleted_at IS NULL AND p.slug = s.slug;
  IF existing_slug_count <> 0 THEN
    RAISE EXCEPTION 'Slug guard failed: % target slugs already exist', existing_slug_count;
  END IF;

  SELECT COUNT(*) INTO existing_ean_count
  FROM _adg_new_product_source s
  JOIN product_variants pv ON pv.salon_id = target_salon_id AND pv.deleted_at IS NULL AND pv.ean = s.ean
  WHERE s.ean IS NOT NULL AND s.ean <> '';
  IF existing_ean_count <> 0 THEN
    RAISE EXCEPTION 'EAN guard failed: % researched EANs already exist', existing_ean_count;
  END IF;

  SELECT COUNT(*) INTO existing_image_url_count
  FROM _adg_new_product_source s
  JOIN product_images pi ON pi.salon_id = target_salon_id AND pi.image_large_url = s.target_url;
  IF existing_image_url_count <> 0 THEN
    RAISE EXCEPTION 'Image URL guard failed: % owner image URLs already exist', existing_image_url_count;
  END IF;

  SELECT COUNT(*) INTO existing_image_hash_count
  FROM _adg_new_product_source s
  JOIN product_images pi ON pi.salon_id = target_salon_id AND pi.file_hash = s.sha256;
  IF existing_image_hash_count <> 0 THEN
    RAISE EXCEPTION 'Image hash guard failed: % owner image hashes already exist', existing_image_hash_count;
  END IF;
END $$;

WITH target_channel AS (
  SELECT ch.salon_id FROM channels ch WHERE ch.slug = 'asiandeligo' AND ch.is_active = true
), resolved AS (
  SELECT s.*, tc.salon_id, c.id AS category_id
  FROM _adg_new_product_source s
  CROSS JOIN target_channel tc
  JOIN categories c ON c.salon_id = tc.salon_id AND c.slug = s.category_slug AND c.is_active = true
), inserted_products AS (
  INSERT INTO products (
    id, salon_id, category_id, name, description, product_type, image_url, images, retail_price,
    slug, is_active, status, is_published, brand, country_of_origin, allergens, dietary_tags,
    external_metadata, private_metadata, name_translations, created_at, updated_at
  )
  SELECT
    r.product_id,
    r.salon_id,
    r.category_id,
    r.pl_name,
    NULL::text,
    'stockable',
    r.target_url,
    jsonb_build_object(
      'desktop', r.target_url,
      'thumbnail', r.target_url,
      'source', 'owner_new_product_import',
      'batch', 'asiandeligo-new-products-folder14-20260713'
    ),
    0,
    r.slug,
    true,
    'draft',
    false,
    r.brand,
    NULLIF(r.country_of_origin, ''),
    r.allergens,
    r.dietary_tags,
    jsonb_build_object(
      'batch', 'asiandeligo-new-products-folder14-20260713',
      'review_id', r.review_id,
      'draft_sku', r.draft_sku,
      'price_pending', true,
      'owner_stock_default', r.stock,
      'source_image', r.source_image
    ),
    jsonb_build_object(
      'source', 'owner_image_review',
      'batch', 'asiandeligo-new-products-folder14-20260713',
      'review_id', r.review_id,
      'price_policy', 'owner_price_pending'
    ),
    jsonb_build_object('pl', r.pl_name, 'en', r.en_name),
    now(),
    now()
  FROM resolved r
  RETURNING id
), inserted_variants AS (
  INSERT INTO product_variants (
    id, salon_id, template_id, sku, barcode, ean, name, display_name, product_type,
    retail_price, currency, image_url, images, is_active, is_published, is_for_sale,
    total_stock, total_stock_qty, external_metadata, created_at, updated_at
  )
  SELECT
    r.variant_id,
    r.salon_id,
    r.product_id,
    r.draft_sku,
    NULLIF(r.ean, ''),
    NULLIF(r.ean, ''),
    r.pl_name,
    r.pl_name,
    'stockable',
    0,
    'PLN',
    r.target_url,
    jsonb_build_object('desktop', r.target_url, 'thumbnail', r.target_url),
    true,
    false,
    false,
    r.stock,
    r.stock,
    jsonb_build_object('batch', 'asiandeligo-new-products-folder14-20260713', 'review_id', r.review_id, 'price_pending', true),
    now(),
    now()
  FROM resolved r
  RETURNING id
), inserted_images AS (
  INSERT INTO product_images (
    salon_id, template_id, variant_id, category, priority, is_primary,
    image_large_url, image_medium_url, image_small_url, url_small, url_thumbnail, url_micro,
    image_id, mime_type, file_size, width, height, alt_text, r2_keys, file_hash, r2_synced,
    created_at, updated_at
  )
  SELECT
    r.salon_id,
    r.product_id,
    NULL::uuid,
    'LISTING'::product_image_category,
    0,
    true,
    r.target_url,
    r.target_url,
    r.target_url,
    r.target_url,
    r.target_url,
    r.target_url,
    r.source_image,
    'image/jpeg',
    r.file_size,
    r.width,
    r.height,
    r.pl_name,
    jsonb_build_array(r.r2_key),
    r.sha256,
    false,
    now(),
    now()
  FROM resolved r
  RETURNING id
), inserted_translations AS (
  INSERT INTO product_translations (salon_id, template_id, lang_id, product_name, slug, created_at, updated_at)
  SELECT r.salon_id, r.product_id, 'pl', r.pl_name, r.slug, now(), now() FROM resolved r
  UNION ALL
  SELECT r.salon_id, r.product_id, 'en', r.en_name, r.slug, now(), now() FROM resolved r
  RETURNING id
)
SELECT
  (SELECT COUNT(*) FROM inserted_products) AS products_inserted,
  (SELECT COUNT(*) FROM inserted_variants) AS variants_inserted,
  (SELECT COUNT(*) FROM inserted_images) AS images_inserted,
  (SELECT COUNT(*) FROM inserted_translations) AS translations_inserted;

DO $$
DECLARE
  product_count integer;
  variant_count integer;
  image_count integer;
  translation_count integer;
BEGIN
  SELECT COUNT(*) INTO product_count
  FROM _adg_new_product_source s
  JOIN products p ON p.slug = s.slug AND p.private_metadata->>'batch' = 'asiandeligo-new-products-folder14-20260713';
  SELECT COUNT(*) INTO variant_count
  FROM _adg_new_product_source s
  JOIN product_variants pv ON pv.sku = s.draft_sku AND pv.external_metadata->>'batch' = 'asiandeligo-new-products-folder14-20260713';
  SELECT COUNT(*) INTO image_count
  FROM _adg_new_product_source s
  JOIN product_images pi ON pi.image_large_url = s.target_url;
  SELECT COUNT(*) INTO translation_count
  FROM _adg_new_product_source s
  JOIN products p ON p.slug = s.slug AND p.private_metadata->>'batch' = 'asiandeligo-new-products-folder14-20260713'
  JOIN product_translations pt ON pt.template_id = p.id;

  IF product_count <> 53 THEN
    RAISE EXCEPTION 'Post-check failed: expected 53 products, got %', product_count;
  END IF;
  IF variant_count <> 53 THEN
    RAISE EXCEPTION 'Post-check failed: expected 53 variants, got %', variant_count;
  END IF;
  IF image_count <> 53 THEN
    RAISE EXCEPTION 'Post-check failed: expected 53 images, got %', image_count;
  END IF;
  IF translation_count <> 106 THEN
    RAISE EXCEPTION 'Post-check failed: expected 106 translations, got %', translation_count;
  END IF;
END $$;

COMMIT;
