\set ON_ERROR_STOP on
-- Generated by scripts/catalog-metadata-batch-plan.mjs
-- Purpose: apply the reviewed Asia Deli Go metadata batch.
-- Decision SHA-256: 0aff66c79c10e96e5ca614fa4b5a250ae4f236d784bea557a3d72fe9836d4e9c
--
-- JOIN contract (schema-introspect verified on production 2026-07-22):
--   product_variants.template_id (uuid) = products.id (uuid) — FK declared; sampled match OK.
--   products.category_id (uuid) = categories.id (uuid) — FK declared; sampled match OK.
--   channels.salon_id = products/product_variants/categories.salon_id (uuid) — tenant pinned on every table.
-- Status values: products.status=active; variant sync_status=synced and availability_status=IN_STOCK.
-- Soft-delete policy: products and variants require deleted_at IS NULL; category/channel require active.
-- Canonical tables only: products, product_variants, categories, channels; no backup/legacy table is joined.

BEGIN;
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
SET LOCAL search_path = pg_catalog, public;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '120s';

CREATE TEMP TABLE _adg_metadata_target_salon (
  salon_id uuid PRIMARY KEY,
  channel_slug text NOT NULL
) ON COMMIT DROP;

INSERT INTO _adg_metadata_target_salon (salon_id, channel_slug)
SELECT salon_id, slug
FROM public.channels
WHERE salon_id = 'e73271a9-53e3-4a20-a02e-791726b452aa'::uuid
  AND slug = 'asiandeligo'
  AND is_active = TRUE
FOR SHARE;

CREATE TEMP TABLE _adg_metadata_decisions (
  sku text PRIMARY KEY,
  product_id uuid UNIQUE NOT NULL,
  variant_id uuid UNIQUE NOT NULL,
  expected_name text NOT NULL,
  expected_slug text NOT NULL,
  expected_updated_at timestamptz NOT NULL,
  expected_allergens jsonb,
  target_allergens jsonb,
  expected_may_contain_allergens jsonb,
  target_may_contain_allergens jsonb,
  expected_storage_zone text,
  target_storage_zone text,
  expected_nutrition_facts jsonb,
  target_nutrition_facts jsonb,
  expected_country_of_origin text,
  target_country_of_origin text,
  expected_ingredients text,
  target_ingredients text,
  expected_price_per_unit numeric,
  expected_unit_of_measure text,
  category_id uuid NOT NULL,
  category_name text NOT NULL,
  category_slug text NOT NULL,
  changed_fields text[] NOT NULL
) ON COMMIT DROP;

INSERT INTO _adg_metadata_decisions VALUES
  (
    'ADG-000118'::text,
    '1e99d371-8e7d-484c-83d9-f83d5fb13ba2'::uuid,
    'ac65fc1f-3a82-4b13-ba27-0c2d7af4fbee'::uuid,
    'Trawa cytrynowa suszona w kawałkach 50g'::text,
    'trawa-cytrynowa-suszona-w-kawalkach-50g'::text,
    '2026-07-08T12:12:07.93723+00:00'::timestamptz,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    NULL::jsonb,
    NULL::jsonb,
    'Tajlandia'::text,
    'Tajlandia'::text,
    '100% suszonej trawy cytrynowej'::text,
    '100% suszonej trawy cytrynowej'::text,
    '159.80'::numeric,
    'KG'::text,
    '3a5525a6-7e8c-4d23-a80c-465177318f0a'::uuid,
    'Przyprawy'::text,
    'przyprawy'::text,
    ARRAY['storageZone'::text]::text[]
  ),
  (
    'ADG-000193'::text,
    '9a81adc5-a8cb-43ad-92b9-0f633c0afd1c'::uuid,
    'a53c3d52-d7a3-4145-978e-d4b26c886e76'::uuid,
    'Sos Hoisin 455ml - Flying Goose'::text,
    'sos-hoisin-455ml-flying-goose'::text,
    '2026-07-08T12:12:07.93723+00:00'::timestamptz,
    '[]'::jsonb,
    '["cereals","soybeans","sesame"]'::jsonb,
    '[]'::jsonb,
    '["peanuts"]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    NULL::jsonb,
    NULL::jsonb,
    'Tajlandia'::text,
    'Tajlandia'::text,
    'Woda, cukier, pasta sojowa 12%, sól, ocet spirytusowy, skrobia kukurydziana, czosnek, barwnik: E150; olej sezamowy, anyż, substancja konserwująca E202'::text,
    'Woda, cukier, pasta sojowa 12%, sól, ocet spirytusowy, skrobia kukurydziana, czosnek, barwnik: E150; olej sezamowy, anyż, substancja konserwująca E202'::text,
    '47.25'::numeric,
    'LITER'::text,
    '5a595c44-ad26-429f-ac6a-9cb0d2378f37'::uuid,
    'Sosy / Marynaty / Oleje'::text,
    'sosy-marynaty-oleje'::text,
    ARRAY['allergens'::text, 'mayContainAllergens'::text, 'storageZone'::text]::text[]
  ),
  (
    'ADG-000211'::text,
    '1d7b9985-bc5b-4994-83e5-e4704b70f260'::uuid,
    '6212acd9-101e-4778-b453-438319b54901'::uuid,
    'Ocet z brązowego ryżu 900ml - CJO Essential'::text,
    'ocet-z-brazowego-ryzu-900ml-cjo-essential'::text,
    '2026-07-08T12:12:07.93723+00:00'::timestamptz,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    NULL::jsonb,
    NULL::jsonb,
    'Korea Południowa'::text,
    'Korea Południowa'::text,
    'Woda (48%), ocet z ziaren ryżu, ektrakty z brązowego ryżu, syrop kukurydziany, izomalto-oligosacharidy, kwasek cytrynowy, aromat jabłkowy'::text,
    'Woda (48%), ocet z ziaren ryżu, ektrakty z brązowego ryżu, syrop kukurydziany, izomalto-oligosacharidy, kwasek cytrynowy, aromat jabłkowy'::text,
    '18.88'::numeric,
    'LITER'::text,
    '5b5e9a99-a4c6-4d2a-b542-cc678f688de9'::uuid,
    'Octy i winne przyprawy'::text,
    'octy-i-winne-przyprawy'::text,
    ARRAY['storageZone'::text]::text[]
  ),
  (
    'ADG-000270'::text,
    '7b2d6206-f0ec-4e73-b59c-6027f1ad4bae'::uuid,
    'b8619b0c-11be-471d-be31-12a34b437927'::uuid,
    'Suszone liście limonki kaffir, liście papedy całe 25g - Thai Dancer'::text,
    'suszone-liscie-limonki-kaffir-liscie-papedy-cale-25g-thai-dancer'::text,
    '2026-07-08T12:12:07.93723+00:00'::timestamptz,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    NULL::jsonb,
    NULL::jsonb,
    'Tajlandia'::text,
    'Tajlandia'::text,
    'Liście kaffiru, znane również jako makrut, to prawdziwy must-have dla fanów orientalnych przypraw i smaków. Te liście o intensywnym, cytrusowo-ziołowym aromacie są źródłem niepowtarzalnego smaku, który urozmaici każdą potrawę. Idealnie komponują się z daniami wymagającymi świeżej nuty, która przełamie cięższe smaki. Już niewielki dodatek wprowadzi do Twoich potraw odświeżający, prawdziwie egzotyczny charakter. Wyrazisty akcent liści kaffiru to jeden z sekretów autentycznego czerwonego curry czy ulubionej tom kha. Oprócz tradycyjnych dań, liście kaffiru doskonale sprawdzą się w ziołowych naparach, herbacie, a nawet w deserach, wnosząc powiew inspiracji do każdej kuchni.'::text,
    'Suszone liście limonki kaffir 100%'::text,
    '279.60'::numeric,
    'KG'::text,
    '3a5525a6-7e8c-4d23-a80c-465177318f0a'::uuid,
    'Przyprawy'::text,
    'przyprawy'::text,
    ARRAY['storageZone'::text, 'ingredients'::text]::text[]
  ),
  (
    'ADG-000372'::text,
    '9d96ed24-853b-428d-9e82-79520409a56c'::uuid,
    'be6359c1-efe0-4945-a223-1dd1bd197179'::uuid,
    'Sos sojowy o zmniejszonej zawartości soli 150ml - Kikkoman'::text,
    'sos-sojowy-o-zmniejszonej-zawartosci-soli-150ml-kikkoman'::text,
    '2026-07-08T12:12:07.93723+00:00'::timestamptz,
    '[]'::jsonb,
    '["cereals","soybeans"]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    '{"fat":0,"salt":9.1,"carbs":6.9,"sugar":3.9,"protein":9.7,"calories":107,"servingSize":"w 100g/100ml"}'::jsonb,
    '{"fat":0,"salt":9.1,"carbs":6.9,"sugar":3.9,"protein":9.7,"calories":107,"servingSize":"w 100g/100ml"}'::jsonb,
    NULL::text,
    NULL::text,
    'Woda, ziarna soi, pszenica, sól, ocet, alkohol etylowy, cukier'::text,
    'Woda, ziarna soi, pszenica, sól, ocet, alkohol etylowy, cukier'::text,
    '131.33'::numeric,
    'LITER'::text,
    'b063c79f-f940-4da4-abff-e23db6b09d8e'::uuid,
    'Sos sojowy'::text,
    'sos-sojowy'::text,
    ARRAY['allergens'::text, 'storageZone'::text]::text[]
  ),
  (
    'ADG-000437'::text,
    '53ea2d5e-70ce-4628-a83a-e30ccafff173'::uuid,
    '2743a625-8d9c-4388-9d56-9c0da1b19a02'::uuid,
    'Ocet ryżowy 1l - Asia Kitchen'::text,
    'ocet-ryzowy-1l-asia-kitchen'::text,
    '2026-07-08T12:12:07.93723+00:00'::timestamptz,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    NULL::jsonb,
    NULL::jsonb,
    'Chiny'::text,
    'Chiny'::text,
    'Woda, ryż 30%'::text,
    'Woda, ryż 30%'::text,
    '15.50'::numeric,
    'LITER'::text,
    '5b5e9a99-a4c6-4d2a-b542-cc678f688de9'::uuid,
    'Octy i winne przyprawy'::text,
    'octy-i-winne-przyprawy'::text,
    ARRAY['storageZone'::text]::text[]
  ),
  (
    'ADG-000455'::text,
    '1ac37bfa-e68d-4768-b780-2575f93a123a'::uuid,
    'b023ed41-1a0d-4af8-afd0-be8ea1e21cbc'::uuid,
    'Glutaminian sodu, Aji-no-Moto MSG 200g - Ajinomoto'::text,
    'glutaminian-sodu-aji-no-moto-msg-200g-ajinomoto'::text,
    '2026-07-08T12:12:07.93723+00:00'::timestamptz,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    NULL::jsonb,
    NULL::jsonb,
    'Francja'::text,
    'Francja'::text,
    'Glutaminian monosodowy (E621). Czystość powyżej 99%. Do stosowania w umiarkowanych ilościach'::text,
    'Glutaminian monosodowy (E621). Czystość powyżej 99%. Do stosowania w umiarkowanych ilościach'::text,
    '39.00'::numeric,
    'KG'::text,
    '3a5525a6-7e8c-4d23-a80c-465177318f0a'::uuid,
    'Przyprawy'::text,
    'przyprawy'::text,
    ARRAY['storageZone'::text]::text[]
  ),
  (
    'ADG-000497'::text,
    '91a4b6de-81e3-4c1a-9acc-536964cae9a5'::uuid,
    '255be9a3-b908-4ac1-af41-ebc551c760e6'::uuid,
    'Glutaminian sodu, Aji-no-Moto MSG 454g - Ajinomoto'::text,
    'glutaminian-sodu-aji-no-moto-msg-454g-ajinomoto'::text,
    '2026-07-08T12:12:07.93723+00:00'::timestamptz,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    NULL::jsonb,
    NULL::jsonb,
    'Francja'::text,
    'Francja'::text,
    'Glutaminian monosodowy (E621). Czystość powyżej 99%.Do stosowania w umiarkowanych ilościach'::text,
    'Glutaminian monosodowy (E621). Czystość powyżej 99%.Do stosowania w umiarkowanych ilościach'::text,
    '30.81'::numeric,
    'KG'::text,
    '3a5525a6-7e8c-4d23-a80c-465177318f0a'::uuid,
    'Przyprawy'::text,
    'przyprawy'::text,
    ARRAY['storageZone'::text]::text[]
  ),
  (
    'ADG-001241'::text,
    '570c6a24-2464-491f-ad48-f22b9a5ed7a4'::uuid,
    '7f10b4a1-6f64-468a-afb9-b7514b472bb7'::uuid,
    'Koreański sos rybny do kimchi Kanari Jeot 800g - YakMokCham'::text,
    'koreanski-sos-rybny-do-kimchi-kanari-jeot-800g-yakmokcham'::text,
    '2026-07-08T12:12:07.93723+00:00'::timestamptz,
    '[]'::jsonb,
    '["crustaceans","fish"]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    NULL::jsonb,
    NULL::jsonb,
    'Korea Południowa'::text,
    'Korea Południowa'::text,
    'Lanca piaskowa (Ammodytes hexapterus) 50%, krewetka opos (Leptomysis mediterranea) 25%, sól 25%.'::text,
    'Lanca piaskowa (Ammodytes hexapterus) 50%, krewetka opos (Leptomysis mediterranea) 25%, sól 25%.'::text,
    '68.63'::numeric,
    'KG'::text,
    '691e2a51-4453-4fd9-bd02-f9abdf9a0def'::uuid,
    'Sosy, marynaty'::text,
    'sosy-marynaty'::text,
    ARRAY['allergens'::text, 'storageZone'::text]::text[]
  ),
  (
    'ADG-000054'::text,
    '02fe4e19-1af4-4171-8703-27d8e35a9ed5'::uuid,
    'faf5972c-5553-490d-819e-a68bef457336'::uuid,
    'Pasta Curry Massaman 50g'::text,
    'pasta-curry-massaman-50g'::text,
    '2026-07-09T10:32:29.281246+00:00'::timestamptz,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    '{"salt":13.1,"carbs":2.1,"sugar":2.1,"protein":4.1,"calories":127,"servingSize":"w 100g/100ml"}'::jsonb,
    '{"salt":13.1,"carbs":2.1,"sugar":2.1,"protein":4.1,"calories":127,"servingSize":"w 100g/100ml"}'::jsonb,
    'Tajlandia'::text,
    'Tajlandia'::text,
    'Suszone chili czerwone 20%, czosnek, szalotka, sól, trawa cytrynowa, kminek, kurkuma, galangal'::text,
    'Suszone chili czerwone 20%, czosnek, szalotka, sól, trawa cytrynowa, kminek, kurkuma, galangal'::text,
    '110.00'::numeric,
    'KG'::text,
    '142af5dc-2ab5-4ae8-a44c-76ba71847c0f'::uuid,
    'Pasty smakowe'::text,
    'pasty-smakowe'::text,
    ARRAY['storageZone'::text]::text[]
  ),
  (
    'ADG-000055'::text,
    'da4e62d4-0ca7-4074-ab18-f3ce75df5d85'::uuid,
    '905530a3-8ee8-4558-a063-ab45f6b5e969'::uuid,
    'Pasta curry czerwona 50g'::text,
    'pasta-curry-czerwona-50g'::text,
    '2026-07-09T10:32:29.281246+00:00'::timestamptz,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    '{"fat":7.8,"salt":11.2,"carbs":4.6,"sugar":4.6,"protein":4.3,"calories":130,"servingSize":"w 100g/100ml"}'::jsonb,
    '{"fat":7.8,"salt":11.2,"carbs":4.6,"sugar":4.6,"protein":4.3,"calories":130,"servingSize":"w 100g/100ml"}'::jsonb,
    'Tajlandia'::text,
    'Tajlandia'::text,
    'Suszone chili czerwone 28%, trawa cytrynowa, czosnek, szalotka, sól, skórka limonki kaffir, galangal, nasiona kolendry, kmin'::text,
    'Suszone chili czerwone 28%, trawa cytrynowa, czosnek, szalotka, sól, skórka limonki kaffir, galangal, nasiona kolendry, kmin'::text,
    '99.80'::numeric,
    'KG'::text,
    '142af5dc-2ab5-4ae8-a44c-76ba71847c0f'::uuid,
    'Pasty smakowe'::text,
    'pasty-smakowe'::text,
    ARRAY['storageZone'::text]::text[]
  ),
  (
    'ADG-000056'::text,
    'dfbd5ffe-4745-4f6e-92de-ffe2aecc2c5a'::uuid,
    '87e1e167-7dfb-4b5a-a368-55e7fbe445aa'::uuid,
    'Pasta curry zielona 50g Cock Brand'::text,
    'pasta-curry-zielona-50g-cock-brand'::text,
    '2026-07-09T10:32:29.281246+00:00'::timestamptz,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    '{"fat":6.9,"salt":12.3,"carbs":2.9,"sugar":2.7,"protein":4.2,"calories":105,"servingSize":"w 100g/100ml"}'::jsonb,
    '{"fat":6.9,"salt":12.3,"carbs":2.9,"sugar":2.7,"protein":4.2,"calories":105,"servingSize":"w 100g/100ml"}'::jsonb,
    'Tajlandia'::text,
    'Tajlandia'::text,
    'Świeże chili zielone 33%, trawa cytrynowa, czosnek, szalotka, sól, galangal, kmin, nasiona kolendry'::text,
    'Świeże chili zielone 33%, trawa cytrynowa, czosnek, szalotka, sól, galangal, kmin, nasiona kolendry'::text,
    '99.80'::numeric,
    'KG'::text,
    '142af5dc-2ab5-4ae8-a44c-76ba71847c0f'::uuid,
    'Pasty smakowe'::text,
    'pasty-smakowe'::text,
    ARRAY['storageZone'::text]::text[]
  ),
  (
    'ADG-000073'::text,
    'a7afb846-034f-4204-87e6-f33846105833'::uuid,
    '4908c4dc-5604-417e-9e4f-0a3800e4332d'::uuid,
    'Galangal w proszku 100g Cock Brand'::text,
    'galangal-w-proszku-100g-cock-brand'::text,
    '2026-07-08T12:12:07.93723+00:00'::timestamptz,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    'AMBIENT'::text,
    'AMBIENT'::text,
    NULL::jsonb,
    '{"calories":273,"fat":0.7,"saturatedFat":0,"carbs":48,"sugar":0,"fiber":31,"protein":3.1,"salt":0.05,"servingSize":"100g"}'::jsonb,
    'Tajlandia'::text,
    'Tajlandia'::text,
    '100% galangal w proszku'::text,
    '100% galangal w proszku'::text,
    '104.90'::numeric,
    'KG'::text,
    '3a5525a6-7e8c-4d23-a80c-465177318f0a'::uuid,
    'Przyprawy'::text,
    'przyprawy'::text,
    ARRAY['nutritionFacts'::text]::text[]
  ),
  (
    'ADG-000078'::text,
    '157af52f-61b3-404c-8481-065a12269279'::uuid,
    'e7e5037b-9f96-4bb6-acf6-f003809f9439'::uuid,
    'Pasta z tamaryndowca 227g - Suree'::text,
    'pasta-z-tamaryndowca-227g-suree'::text,
    '2026-07-08T12:12:07.93723+00:00'::timestamptz,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    '{"salt":0.14,"carbs":25,"sugar":11,"protein":1,"calories":106,"servingSize":"w 100g/100ml"}'::jsonb,
    '{"salt":0.14,"carbs":25,"sugar":11,"protein":1,"calories":106,"servingSize":"w 100g/100ml"}'::jsonb,
    'Tajlandia'::text,
    'Tajlandia'::text,
    'Tamarynd 80%, woda, regulator kwasowości: kwas octowy; substancja konserwująca: benzoesan sodu'::text,
    'Tamarynd 80%, woda, regulator kwasowości: kwas octowy; substancja konserwująca: benzoesan sodu'::text,
    '47.14'::numeric,
    'KG'::text,
    '142af5dc-2ab5-4ae8-a44c-76ba71847c0f'::uuid,
    'Pasty smakowe'::text,
    'pasty-smakowe'::text,
    ARRAY['storageZone'::text]::text[]
  ),
  (
    'ADG-000079'::text,
    '66c1dd47-05d2-4610-8de8-f53f8d519c81'::uuid,
    '6a8c889c-6921-4648-b356-64809b7f65d7'::uuid,
    'Dhania, kolendra mielona 100g TRS'::text,
    'dhania-kolendra-mielona-100g-trs'::text,
    '2026-07-08T12:12:07.93723+00:00'::timestamptz,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '["peanuts","nuts","sesame","cereals","milk","celery","soybeans","mustard","sulphites"]'::jsonb,
    'AMBIENT'::text,
    'AMBIENT'::text,
    NULL::jsonb,
    NULL::jsonb,
    'Indie'::text,
    'Indie'::text,
    '100% kolendra'::text,
    '100% kolendra'::text,
    '69.90'::numeric,
    'KG'::text,
    '3a5525a6-7e8c-4d23-a80c-465177318f0a'::uuid,
    'Przyprawy'::text,
    'przyprawy'::text,
    ARRAY['mayContainAllergens'::text]::text[]
  ),
  (
    'ADG-000085'::text,
    'f238ff91-b625-4762-9aca-a6fa5e91a55a'::uuid,
    'd934f609-47c2-4167-b6e8-018301c5a57c'::uuid,
    'Pasta curry czerwona 400g'::text,
    'pasta-curry-czerwona-400g'::text,
    '2026-07-09T10:32:29.281246+00:00'::timestamptz,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    '{"fat":5.4,"salt":11.7,"carbs":10,"sugar":4,"protein":3.9,"calories":122,"servingSize":"w 100g/100ml","saturatedFat":2.8}'::jsonb,
    '{"fat":5.4,"salt":11.7,"carbs":10,"sugar":4,"protein":3.9,"calories":122,"servingSize":"w 100g/100ml","saturatedFat":2.8}'::jsonb,
    'Tajlandia'::text,
    'Tajlandia'::text,
    'Suszone chili czerwone 28%, trawa cytrynowa, czosnek, szalotka, sól, skórka limonki kaffir, galangal, nasiona kolendry, kmin'::text,
    'Suszone chili czerwone 28%, trawa cytrynowa, czosnek, szalotka, sól, skórka limonki kaffir, galangal, nasiona kolendry, kmin'::text,
    '37.48'::numeric,
    'KG'::text,
    '142af5dc-2ab5-4ae8-a44c-76ba71847c0f'::uuid,
    'Pasty smakowe'::text,
    'pasty-smakowe'::text,
    ARRAY['storageZone'::text]::text[]
  ),
  (
    'ADG-000091'::text,
    'f588dea3-e54b-4fc8-b2f9-56ca33933098'::uuid,
    '2ec4af02-7380-43b2-ac03-5286024a5150'::uuid,
    'Cukier trzcinowy (brązowy) nierafinowany 500g - Mauritius Golden Cane'::text,
    'cukier-trzcinowy-brazowy-nierafinowany-500g-mauritius-golden-cane'::text,
    '2026-07-08T12:12:07.93723+00:00'::timestamptz,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    '{"fat":0,"salt":0,"carbs":100,"sugar":100,"protein":0,"calories":400,"servingSize":"w 100g/100ml"}'::jsonb,
    '{"fat":0,"salt":0,"carbs":100,"sugar":100,"protein":0,"calories":400,"servingSize":"w 100g/100ml"}'::jsonb,
    'Mauritius'::text,
    'Mauritius'::text,
    '100% cukier trzcinowy'::text,
    '100% cukier trzcinowy'::text,
    '21.98'::numeric,
    'KG'::text,
    '38034a3f-033a-4272-b8a7-5f2f13d3d7a8'::uuid,
    'Przyprawy jednoskładnikowe'::text,
    'przyprawy-jednoskładnikowe'::text,
    ARRAY['storageZone'::text]::text[]
  ),
  (
    'ADG-000092'::text,
    'a490f812-95f6-4684-b022-4ced38007635'::uuid,
    'f1e960d3-3fba-4c27-b260-446898fe6387'::uuid,
    'Syrop kukurydziany 100% 700g - CJO Essential'::text,
    'syrop-kukurydziany-100-700g-cjo-essential'::text,
    '2026-07-08T12:12:07.93723+00:00'::timestamptz,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    '{"fat":0,"salt":0,"carbs":76,"sugar":76,"protein":3.4,"calories":304,"servingSize":"w 100g/100ml"}'::jsonb,
    '{"fat":0,"salt":0,"carbs":76,"sugar":76,"protein":3.4,"calories":304,"servingSize":"w 100g/100ml"}'::jsonb,
    'Korea Południowa'::text,
    'Korea Południowa'::text,
    'Syrop skrobiowy z kukurydzy 100%'::text,
    'Syrop skrobiowy z kukurydzy 100%'::text,
    '23.57'::numeric,
    'KG'::text,
    '691e2a51-4453-4fd9-bd02-f9abdf9a0def'::uuid,
    'Sosy, marynaty'::text,
    'sosy-marynaty'::text,
    ARRAY['storageZone'::text]::text[]
  ),
  (
    'ADG-000097'::text,
    'd41e1380-bb47-443d-867a-05c201800686'::uuid,
    '8ec6a18d-5792-4aea-abf0-b0e88668b1dc'::uuid,
    'Słodko-pikantny sos chili do kurczaka 650ml - Cock Brand'::text,
    'slodko-pikantny-sos-chili-do-kurczaka-650ml-cock-brand'::text,
    '2026-07-08T12:12:07.93723+00:00'::timestamptz,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    '{"fat":1,"salt":3,"carbs":51,"sugar":47,"protein":1,"calories":207,"servingSize":"w 100g/100ml"}'::jsonb,
    '{"fat":1,"salt":3,"carbs":51,"sugar":47,"protein":1,"calories":207,"servingSize":"w 100g/100ml"}'::jsonb,
    'Tajlandia'::text,
    'Tajlandia'::text,
    'Cukier, woda, czerwone chili (16%), czosnek, sól, modyfikowana skrobia kukurydziana, regulator kwasowości (E260)'::text,
    'Cukier, woda, czerwone chili (16%), czosnek, sól, modyfikowana skrobia kukurydziana, regulator kwasowości (E260)'::text,
    '30.00'::numeric,
    'LITER'::text,
    '691e2a51-4453-4fd9-bd02-f9abdf9a0def'::uuid,
    'Sosy, marynaty'::text,
    'sosy-marynaty'::text,
    ARRAY['storageZone'::text]::text[]
  ),
  (
    'ADG-000116'::text,
    '895634b9-1aa6-4257-b5f0-0597385c0991'::uuid,
    '92454c59-ddf4-4ec9-81ee-e51766bb669f'::uuid,
    'Mąka ryżowa, bezglutenowa 400g - Cock Brand'::text,
    'maka-ryzowa-bezglutenowa-400g-cock-brand'::text,
    '2026-07-08T12:12:07.93723+00:00'::timestamptz,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    '{"fat":0.5,"salt":0.02,"carbs":79,"sugar":0.5,"protein":6.8,"calories":343,"servingSize":"w 100g/100ml","saturatedFat":0.1}'::jsonb,
    '{"fat":0.5,"salt":0.02,"carbs":79,"sugar":0.5,"protein":6.8,"calories":343,"servingSize":"w 100g/100ml","saturatedFat":0.1}'::jsonb,
    'Tajlandia'::text,
    'Tajlandia'::text,
    'Ryż (98%), woda'::text,
    'Ryż (98%), woda'::text,
    '19.75'::numeric,
    'KG'::text,
    'ad59df51-8278-4ad5-8d6e-4f86256f9a4d'::uuid,
    'Mąki / Panierki / Tapioka'::text,
    'mąki-panierki-tapioka'::text,
    ARRAY['storageZone'::text]::text[]
  ),
  (
    'ADG-000117'::text,
    'e372e7da-30a3-4548-ab2f-f9da05ffee53'::uuid,
    '8830c299-7577-43c7-ba9a-0b66d8be3d13'::uuid,
    'Mąka ryżowa kleista 400g bezglutenowa - Cock Brand'::text,
    'maka-ryzowa-kleista-400g-bezglutenowa-cock-brand'::text,
    '2026-07-08T12:12:07.93723+00:00'::timestamptz,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    '{"fat":0.5,"salt":0.01,"carbs":81,"sugar":0.5,"protein":6.3,"calories":349,"servingSize":"w 100g/100ml","saturatedFat":0.1}'::jsonb,
    '{"fat":0.5,"salt":0.01,"carbs":81,"sugar":0.5,"protein":6.3,"calories":349,"servingSize":"w 100g/100ml","saturatedFat":0.1}'::jsonb,
    'Tajlandia'::text,
    'Tajlandia'::text,
    'Ryż (98%), woda'::text,
    'Ryż (98%), woda'::text,
    '21.75'::numeric,
    'KG'::text,
    'ad59df51-8278-4ad5-8d6e-4f86256f9a4d'::uuid,
    'Mąki / Panierki / Tapioka'::text,
    'mąki-panierki-tapioka'::text,
    ARRAY['storageZone'::text]::text[]
  ),
  (
    'ADG-000125'::text,
    'cb263336-13b4-47ab-86b9-9aeab82064b5'::uuid,
    '955938a4-5316-4862-b350-0fb97d07fe0b'::uuid,
    'Tapioka, perełki małe 400g - Cock Brand'::text,
    'tapioka-perelki-male-400g-cock-brand'::text,
    '2026-07-08T12:12:07.93723+00:00'::timestamptz,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    '{"fat":0.5,"salt":0.1,"carbs":86,"sugar":0.5,"protein":0.5,"calories":350,"servingSize":"w 100g/100ml","saturatedFat":0.1}'::jsonb,
    '{"fat":0.5,"salt":0.1,"carbs":86,"sugar":0.5,"protein":0.5,"calories":350,"servingSize":"w 100g/100ml","saturatedFat":0.1}'::jsonb,
    'Tajlandia'::text,
    'Tajlandia'::text,
    'Skrobia z tapioki 98%, woda'::text,
    'Skrobia z tapioki 98%, woda'::text,
    '24.97'::numeric,
    'KG'::text,
    'ad59df51-8278-4ad5-8d6e-4f86256f9a4d'::uuid,
    'Mąki / Panierki / Tapioka'::text,
    'mąki-panierki-tapioka'::text,
    ARRAY['storageZone'::text]::text[]
  ),
  (
    'ADG-000128'::text,
    '91dac45c-73ca-4cdd-9902-2789fbceaff2'::uuid,
    'f2f4a4c3-db01-4d10-a454-86ed5d1b0224'::uuid,
    'Tapioka, perełki duże 454g - Cock Brand'::text,
    'tapioka-perelki-duze-454g-cock-brand'::text,
    '2026-07-08T12:12:07.93723+00:00'::timestamptz,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    '{"fat":0.5,"salt":0.1,"carbs":86,"sugar":0.5,"protein":0.5,"calories":350,"servingSize":"w 100g/100ml","saturatedFat":0.1}'::jsonb,
    '{"fat":0.5,"salt":0.1,"carbs":86,"sugar":0.5,"protein":0.5,"calories":350,"servingSize":"w 100g/100ml","saturatedFat":0.1}'::jsonb,
    'Tajlandia'::text,
    'Tajlandia'::text,
    'Mąka tapioki, konserwant: E220'::text,
    'Mąka tapioki, konserwant: E220'::text,
    '27.47'::numeric,
    'KG'::text,
    'ad59df51-8278-4ad5-8d6e-4f86256f9a4d'::uuid,
    'Mąki / Panierki / Tapioka'::text,
    'mąki-panierki-tapioka'::text,
    ARRAY['storageZone'::text]::text[]
  );

DO $$
DECLARE affected integer;
BEGIN
  IF (SELECT COUNT(*) FROM _adg_metadata_target_salon) <> 1 THEN
    RAISE EXCEPTION 'Expected exactly one active pinned asiandeligo channel';
  END IF;
  IF (SELECT COUNT(*) FROM _adg_metadata_decisions) <> 23 THEN
    RAISE EXCEPTION 'Expected exactly 23 metadata decisions';
  END IF;
  IF to_regclass('public.asiandeligo_catalog_metadata_product_backup_20260722') IS NOT NULL
     OR to_regclass('public.asiandeligo_catalog_metadata_audit_20260722') IS NOT NULL THEN
    RAISE EXCEPTION 'Batch backup/audit table already exists; refusing duplicate apply';
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_catalog.pg_trigger
    WHERE tgrelid = 'public.products'::regclass
      AND tgname = 'zz_enforce_products_monotonic_updated_at'
      AND NOT tgisinternal
      AND tgenabled <> 'D'
  ) THEN
    RAISE EXCEPTION 'Required products monotonic updated_at trigger is missing';
  END IF;

  PERFORM 1
  FROM _adg_metadata_decisions decision
  CROSS JOIN _adg_metadata_target_salon tenant
  JOIN public.product_variants variant
    ON variant.id = decision.variant_id
   AND variant.sku = decision.sku
   AND variant.salon_id = tenant.salon_id
   AND variant.is_active = TRUE
   AND variant.is_published = FALSE
   AND variant.is_for_sale = TRUE
   AND variant.sync_status = 'synced'
   AND variant.availability_status = 'IN_STOCK'
   AND variant.deleted_at IS NULL
  JOIN public.products product
    ON product.id = decision.product_id
   AND product.id = variant.template_id
   AND product.salon_id = tenant.salon_id
   AND product.name = decision.expected_name
   AND product.slug = decision.expected_slug
   AND product.updated_at = decision.expected_updated_at
   AND product.is_active = TRUE
   AND product.is_published = TRUE
   AND product.is_visible = TRUE
   AND product.status = 'active'
   AND product.deleted_at IS NULL
  JOIN public.categories category
    ON category.id = decision.category_id
   AND category.id = product.category_id
   AND category.salon_id = tenant.salon_id
   AND category.name = decision.category_name
   AND category.slug = decision.category_slug
   AND category.is_active = TRUE
  WHERE product.allergens IS NOT DISTINCT FROM decision.expected_allergens
    AND product.may_contain_allergens IS NOT DISTINCT FROM decision.expected_may_contain_allergens
    AND product.storage_zone IS NOT DISTINCT FROM decision.expected_storage_zone
    AND product.nutrition_facts IS NOT DISTINCT FROM decision.expected_nutrition_facts
    AND product.country_of_origin IS NOT DISTINCT FROM decision.expected_country_of_origin
    AND product.ingredients IS NOT DISTINCT FROM decision.expected_ingredients
    AND product.price_per_unit IS NOT DISTINCT FROM decision.expected_price_per_unit
    AND product.unit_of_measure IS NOT DISTINCT FROM decision.expected_unit_of_measure
  ORDER BY product.id
  FOR UPDATE OF product, variant, category;
  GET DIAGNOSTICS affected = ROW_COUNT;
  IF affected <> 23 THEN
    RAISE EXCEPTION 'Expected 23 exact product row locks, got %', affected;
  END IF;
END $$;

CREATE TABLE public.asiandeligo_catalog_metadata_product_backup_20260722 (
  batch_key text NOT NULL CHECK (batch_key = 'asiandeligo-catalog-metadata-batch25-20260722-v1'),
  decision_sha256 text NOT NULL CHECK (decision_sha256 = '0aff66c79c10e96e5ca614fa4b5a250ae4f236d784bea557a3d72fe9836d4e9c'),
  channel_slug text NOT NULL CHECK (channel_slug = 'asiandeligo'),
  salon_id uuid NOT NULL CHECK (salon_id = 'e73271a9-53e3-4a20-a02e-791726b452aa'::uuid),
  sku text NOT NULL,
  product_id uuid NOT NULL,
  variant_id uuid NOT NULL,
  category_id uuid NOT NULL,
  changed_fields text[] NOT NULL,
  allergens jsonb,
  may_contain_allergens jsonb,
  storage_zone text,
  nutrition_facts jsonb,
  country_of_origin text,
  ingredients text,
  price_per_unit numeric,
  unit_of_measure text,
  original_updated_at timestamptz NOT NULL,
  applied_updated_at timestamptz,
  captured_at timestamptz NOT NULL DEFAULT transaction_timestamp(),
  PRIMARY KEY (batch_key, salon_id, sku),
  UNIQUE (batch_key, salon_id, product_id),
  UNIQUE (batch_key, salon_id, variant_id)
);

CREATE TABLE public.asiandeligo_catalog_metadata_audit_20260722 (
  batch_key text NOT NULL CHECK (batch_key = 'asiandeligo-catalog-metadata-batch25-20260722-v1'),
  decision_sha256 text NOT NULL CHECK (decision_sha256 = '0aff66c79c10e96e5ca614fa4b5a250ae4f236d784bea557a3d72fe9836d4e9c'),
  channel_slug text NOT NULL CHECK (channel_slug = 'asiandeligo'),
  salon_id uuid NOT NULL CHECK (salon_id = 'e73271a9-53e3-4a20-a02e-791726b452aa'::uuid),
  action text NOT NULL CHECK (action IN ('backup_captured', 'apply_complete', 'rollback_complete')),
  product_rows integer NOT NULL CHECK (product_rows = 23),
  transaction_id bigint NOT NULL DEFAULT txid_current(),
  recorded_at timestamptz NOT NULL DEFAULT transaction_timestamp(),
  PRIMARY KEY (batch_key, salon_id, action)
);

DO $$
DECLARE affected integer;
BEGIN
  INSERT INTO public.asiandeligo_catalog_metadata_product_backup_20260722 (
    batch_key, decision_sha256, channel_slug, salon_id, sku,
    product_id, variant_id, category_id, changed_fields,
    allergens, may_contain_allergens, storage_zone, nutrition_facts,
    country_of_origin, ingredients, price_per_unit, unit_of_measure,
    original_updated_at
  )
  SELECT
    'asiandeligo-catalog-metadata-batch25-20260722-v1', '0aff66c79c10e96e5ca614fa4b5a250ae4f236d784bea557a3d72fe9836d4e9c', tenant.channel_slug, tenant.salon_id,
    decision.sku, product.id, variant.id, category.id, decision.changed_fields,
    product.allergens, product.may_contain_allergens, product.storage_zone,
    product.nutrition_facts, product.country_of_origin, product.ingredients,
    product.price_per_unit, product.unit_of_measure, product.updated_at
  FROM _adg_metadata_decisions decision
  CROSS JOIN _adg_metadata_target_salon tenant
  JOIN public.product_variants variant
    ON variant.id = decision.variant_id
   AND variant.sku = decision.sku
   AND variant.salon_id = tenant.salon_id
   AND variant.deleted_at IS NULL
  JOIN public.products product
    ON product.id = decision.product_id
   AND product.id = variant.template_id
   AND product.salon_id = tenant.salon_id
   AND product.updated_at = decision.expected_updated_at
   AND product.deleted_at IS NULL
  JOIN public.categories category
    ON category.id = decision.category_id
   AND category.id = product.category_id
   AND category.salon_id = tenant.salon_id
   AND category.is_active = TRUE
  WHERE product.allergens IS NOT DISTINCT FROM decision.expected_allergens
    AND product.may_contain_allergens IS NOT DISTINCT FROM decision.expected_may_contain_allergens
    AND product.storage_zone IS NOT DISTINCT FROM decision.expected_storage_zone
    AND product.nutrition_facts IS NOT DISTINCT FROM decision.expected_nutrition_facts
    AND product.country_of_origin IS NOT DISTINCT FROM decision.expected_country_of_origin
    AND product.ingredients IS NOT DISTINCT FROM decision.expected_ingredients
    AND product.price_per_unit IS NOT DISTINCT FROM decision.expected_price_per_unit
    AND product.unit_of_measure IS NOT DISTINCT FROM decision.expected_unit_of_measure;
  GET DIAGNOSTICS affected = ROW_COUNT;
  IF affected <> 23 THEN
    RAISE EXCEPTION 'Expected 23 persistent product backup rows, got %', affected;
  END IF;

  INSERT INTO public.asiandeligo_catalog_metadata_audit_20260722 (
    batch_key, decision_sha256, channel_slug, salon_id, action, product_rows
  )
  SELECT 'asiandeligo-catalog-metadata-batch25-20260722-v1', '0aff66c79c10e96e5ca614fa4b5a250ae4f236d784bea557a3d72fe9836d4e9c', channel_slug, salon_id,
         'backup_captured', 23
  FROM _adg_metadata_target_salon;
END $$;

DO $$
DECLARE affected integer;
BEGIN
  UPDATE public.products product
  SET allergens = decision.target_allergens,
      may_contain_allergens = decision.target_may_contain_allergens,
      storage_zone = decision.target_storage_zone,
      nutrition_facts = decision.target_nutrition_facts,
      country_of_origin = decision.target_country_of_origin,
      ingredients = decision.target_ingredients
  FROM _adg_metadata_decisions decision,
       _adg_metadata_target_salon tenant,
       public.asiandeligo_catalog_metadata_product_backup_20260722 backup
  WHERE product.id = decision.product_id
    AND product.id = backup.product_id
    AND product.salon_id = tenant.salon_id
    AND backup.salon_id = tenant.salon_id
    AND backup.batch_key = 'asiandeligo-catalog-metadata-batch25-20260722-v1'
    AND backup.decision_sha256 = '0aff66c79c10e96e5ca614fa4b5a250ae4f236d784bea557a3d72fe9836d4e9c'
    AND backup.sku = decision.sku
    AND product.updated_at = decision.expected_updated_at
    AND product.deleted_at IS NULL
    AND product.allergens IS NOT DISTINCT FROM decision.expected_allergens
    AND product.may_contain_allergens IS NOT DISTINCT FROM decision.expected_may_contain_allergens
    AND product.storage_zone IS NOT DISTINCT FROM decision.expected_storage_zone
    AND product.nutrition_facts IS NOT DISTINCT FROM decision.expected_nutrition_facts
    AND product.country_of_origin IS NOT DISTINCT FROM decision.expected_country_of_origin
    AND product.ingredients IS NOT DISTINCT FROM decision.expected_ingredients
    AND product.price_per_unit IS NOT DISTINCT FROM decision.expected_price_per_unit
    AND product.unit_of_measure IS NOT DISTINCT FROM decision.expected_unit_of_measure;
  GET DIAGNOSTICS affected = ROW_COUNT;
  IF affected <> 23 THEN
    RAISE EXCEPTION 'Expected 23 exact product updates, got %', affected;
  END IF;

  UPDATE public.asiandeligo_catalog_metadata_product_backup_20260722 backup
  SET applied_updated_at = product.updated_at
  FROM public.products product,
       _adg_metadata_decisions decision,
       _adg_metadata_target_salon tenant
  WHERE backup.batch_key = 'asiandeligo-catalog-metadata-batch25-20260722-v1'
    AND backup.decision_sha256 = '0aff66c79c10e96e5ca614fa4b5a250ae4f236d784bea557a3d72fe9836d4e9c'
    AND backup.salon_id = tenant.salon_id
    AND backup.sku = decision.sku
    AND backup.product_id = product.id
    AND product.salon_id = tenant.salon_id
    AND product.updated_at > backup.original_updated_at
    AND product.deleted_at IS NULL
    AND product.allergens IS NOT DISTINCT FROM decision.target_allergens
    AND product.may_contain_allergens IS NOT DISTINCT FROM decision.target_may_contain_allergens
    AND product.storage_zone IS NOT DISTINCT FROM decision.target_storage_zone
    AND product.nutrition_facts IS NOT DISTINCT FROM decision.target_nutrition_facts
    AND product.country_of_origin IS NOT DISTINCT FROM decision.target_country_of_origin
    AND product.ingredients IS NOT DISTINCT FROM decision.target_ingredients
    AND product.price_per_unit IS NOT DISTINCT FROM decision.expected_price_per_unit
    AND product.unit_of_measure IS NOT DISTINCT FROM decision.expected_unit_of_measure;
  GET DIAGNOSTICS affected = ROW_COUNT;
  IF affected <> 23 THEN
    RAISE EXCEPTION 'Expected 23 applied updated_at captures, got %', affected;
  END IF;

  INSERT INTO public.asiandeligo_catalog_metadata_audit_20260722 (
    batch_key, decision_sha256, channel_slug, salon_id, action, product_rows
  )
  SELECT 'asiandeligo-catalog-metadata-batch25-20260722-v1', '0aff66c79c10e96e5ca614fa4b5a250ae4f236d784bea557a3d72fe9836d4e9c', channel_slug, salon_id,
         'apply_complete', 23
  FROM _adg_metadata_target_salon;
END $$;

SELECT backup.sku, backup.changed_fields, backup.original_updated_at,
       backup.applied_updated_at, audit.transaction_id
FROM public.asiandeligo_catalog_metadata_product_backup_20260722 backup
JOIN public.asiandeligo_catalog_metadata_audit_20260722 audit
  ON audit.batch_key = backup.batch_key
 AND audit.salon_id = backup.salon_id
 AND audit.action = 'apply_complete'
WHERE backup.batch_key = 'asiandeligo-catalog-metadata-batch25-20260722-v1'
  AND backup.decision_sha256 = '0aff66c79c10e96e5ca614fa4b5a250ae4f236d784bea557a3d72fe9836d4e9c'
  AND backup.salon_id = 'e73271a9-53e3-4a20-a02e-791726b452aa'::uuid
ORDER BY backup.sku;

COMMIT;
