-- Generated by scripts/catalog-blocker-unpublish-plan.mjs
-- Purpose: rollback publication for five Asia Deli Go products with verified image/product identity mismatches.
-- Transition: draft/unpublished -> active/published.
-- No SKU, slug, price, stock, image, content, category, variant, order, or reservation field is changed.
-- Reindex channel asiandeligo after commit so Meilisearch receives the publication-state change.
--
-- JOIN contract (schema-introspect verified on production 2026-07-13):
--   channels.salon_id (uuid) scopes products and product_variants.
--   product_variants.template_id (uuid) = products.id (uuid), FK declared and five target matches verified.
--   Every business-table join includes salon_id; products/variants exclude deleted_at rows.
--   Canonical tables only: channels/products/product_variants; backup tables are excluded.
--   products.status is varchar; live values active/draft were verified for the target salon.

\set ON_ERROR_STOP on
BEGIN;

CREATE TEMP TABLE _adg_blocker_target_salon (salon_id uuid PRIMARY KEY) ON COMMIT DROP;
INSERT INTO _adg_blocker_target_salon (salon_id)
SELECT salon_id FROM channels WHERE slug = 'asiandeligo' AND is_active = TRUE;

CREATE TEMP TABLE _adg_blocker_targets (
  sku text PRIMARY KEY,
  expected_name text NOT NULL,
  expected_slug text NOT NULL UNIQUE,
  expected_status text NOT NULL,
  target_status text NOT NULL,
  expected_published boolean NOT NULL,
  target_published boolean NOT NULL
) ON COMMIT DROP;
INSERT INTO _adg_blocker_targets (
  sku, expected_name, expected_slug, expected_status, target_status,
  expected_published, target_published
) VALUES
  ('ADG-001327', 'Zestaw do herbaty matcha zielony, 4 elementy - Edo Japan', 'zestaw-do-herbaty-matcha-zielony-4-elementy-edo-japan-adg001327', 'draft', 'active', FALSE, TRUE),
  ('ADG-001446', 'Mleko kokosowe (70% wyciągu z kokosa) 1L w kartonie AROY-D', 'mleko-kokosowe-70-wyciagu-z-kokosa-1l-w-kartonie-aroy-d-adg001446', 'draft', 'active', FALSE, TRUE),
  ('ADG-001463', 'Kaki no Tane, przyprawione krakersy ryżowe arare z orzeszkami 180g (6 x 30g) - KAMEDA', 'kaki-no-tane-przyprawione-krakersy-ryzowe-arare-z-orzeszkami-180g-6-x-30g-kameda-adg001463', 'draft', 'active', FALSE, TRUE),
  ('ADG-001666', 'Sos rybny Myeolchi Aekjeot z anchois 870ml - Hansung', 'sos-rybny-myeolchi-aekjeot-z-anchois-870ml-hansung-adg001666', 'draft', 'active', FALSE, TRUE),
  ('ADG-001782', 'Ryż jaśminowy Fragrant Jasmine Rice 1kg Tilda', 'ryz-jasminowy-fragrant-jasmine-rice-1kg-tilda-adg001782', 'draft', 'active', FALSE, TRUE);

DO $$
DECLARE
  affected integer;
BEGIN
  IF (SELECT COUNT(*) FROM _adg_blocker_target_salon) <> 1 THEN
    RAISE EXCEPTION 'Expected exactly one active Asia Deli Go channel';
  END IF;

  IF EXISTS (
    SELECT target.sku
    FROM _adg_blocker_targets target
    CROSS JOIN _adg_blocker_target_salon tenant
    LEFT JOIN product_variants variant
      ON variant.salon_id = tenant.salon_id
     AND variant.sku = target.sku
     AND variant.is_active = TRUE
     AND variant.deleted_at IS NULL
    LEFT JOIN products product
      ON product.salon_id = tenant.salon_id
     AND product.id = variant.template_id
     AND product.is_active = TRUE
     AND product.deleted_at IS NULL
    GROUP BY target.sku, target.expected_name, target.expected_slug,
             target.expected_status, target.expected_published
    HAVING COUNT(DISTINCT variant.id) <> 1
       OR COUNT(DISTINCT product.id) <> 1
       OR MIN(product.name) IS DISTINCT FROM target.expected_name
       OR MIN(product.slug) IS DISTINCT FROM target.expected_slug
       OR MIN(product.status) IS DISTINCT FROM target.expected_status
       OR BOOL_OR(product.is_published) IS DISTINCT FROM target.expected_published
  ) THEN
    RAISE EXCEPTION 'Blocker publication precondition failed; aborting all changes';
  END IF;

  UPDATE products product
  SET status = target.target_status,
      is_published = target.target_published,
      updated_at = NOW()
  FROM _adg_blocker_target_salon tenant,
       _adg_blocker_targets target,
       product_variants variant
  WHERE product.salon_id = tenant.salon_id
    AND variant.salon_id = tenant.salon_id
    AND variant.template_id = product.id
    AND variant.sku = target.sku
    AND variant.is_active = TRUE
    AND variant.deleted_at IS NULL
    AND product.is_active = TRUE
    AND product.deleted_at IS NULL
    AND product.name = target.expected_name
    AND product.slug = target.expected_slug
    AND product.status = target.expected_status
    AND product.is_published = target.expected_published;
  GET DIAGNOSTICS affected = ROW_COUNT;
  IF affected <> 5 THEN
    RAISE EXCEPTION 'Expected 5 publication updates, got %', affected;
  END IF;

  IF EXISTS (
    SELECT target.sku
    FROM _adg_blocker_targets target
    CROSS JOIN _adg_blocker_target_salon tenant
    JOIN product_variants variant
      ON variant.salon_id = tenant.salon_id
     AND variant.sku = target.sku
     AND variant.deleted_at IS NULL
    JOIN products product
      ON product.salon_id = tenant.salon_id
     AND product.id = variant.template_id
     AND product.deleted_at IS NULL
    WHERE product.status IS DISTINCT FROM target.target_status
       OR product.is_published IS DISTINCT FROM target.target_published
       OR product.is_active IS DISTINCT FROM TRUE
  ) THEN
    RAISE EXCEPTION 'Blocker publication postcondition failed; aborting all changes';
  END IF;
END $$;

SELECT variant.sku, product.name, product.slug, product.status, product.is_active, product.is_published
FROM _adg_blocker_target_salon tenant
JOIN product_variants variant ON variant.salon_id = tenant.salon_id
JOIN _adg_blocker_targets target ON target.sku = variant.sku
JOIN products product ON product.salon_id = tenant.salon_id AND product.id = variant.template_id
ORDER BY variant.sku;

COMMIT;
