\set ON_ERROR_STOP on
-- Generated by scripts/catalog-metadata-batch8-plan.mjs
-- Purpose: roll back the reviewed Asia Deli Go metadata batch.
-- Decision SHA-256: b7f405d8eea6aa7465f63ba05f9e00ed8c14bea2525675db003041775b99ca93
--
-- JOIN contract (schema-introspect verified on production 2026-07-22):
--   product_variants.template_id (uuid) = products.id (uuid) — FK declared; sampled match OK.
--   products.category_id (uuid) = categories.id (uuid) — FK declared; sampled match OK.
--   channels.salon_id = products/product_variants/categories.salon_id (uuid) — tenant pinned on every table.
-- Status values: products.status=active; variant sync_status=synced and availability_status=IN_STOCK.
-- Soft-delete policy: products and variants require deleted_at IS NULL; category/channel require active.
-- Canonical tables only: products, product_variants, categories, channels; no backup/legacy table is joined.

BEGIN;
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
SET LOCAL search_path = pg_catalog, public;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '120s';

CREATE TEMP TABLE _adg_metadata_target_salon (
  salon_id uuid PRIMARY KEY,
  channel_slug text NOT NULL
) ON COMMIT DROP;

INSERT INTO _adg_metadata_target_salon (salon_id, channel_slug)
SELECT salon_id, slug
FROM public.channels
WHERE salon_id = 'e73271a9-53e3-4a20-a02e-791726b452aa'::uuid
  AND slug = 'asiandeligo'
  AND is_active = TRUE
FOR SHARE;

CREATE TEMP TABLE _adg_metadata_decisions (
  sku text PRIMARY KEY,
  product_id uuid UNIQUE NOT NULL,
  variant_id uuid UNIQUE NOT NULL,
  expected_name text NOT NULL,
  expected_slug text NOT NULL,
  expected_updated_at timestamptz NOT NULL,
  expected_allergens jsonb,
  target_allergens jsonb,
  expected_may_contain_allergens jsonb,
  target_may_contain_allergens jsonb,
  expected_storage_zone text,
  target_storage_zone text,
  expected_nutrition_facts jsonb,
  target_nutrition_facts jsonb,
  expected_country_of_origin text,
  target_country_of_origin text,
  expected_ingredients text,
  target_ingredients text,
  expected_price_per_unit numeric,
  expected_unit_of_measure text,
  category_id uuid NOT NULL,
  category_name text NOT NULL,
  category_slug text NOT NULL,
  changed_fields text[] NOT NULL
) ON COMMIT DROP;

INSERT INTO _adg_metadata_decisions VALUES
  (
    'ADG-000492'::text,
    'cc9d23b3-fb57-4788-8a28-e73456484a76'::uuid,
    '663f9e87-1a33-485f-b3f7-8b04817fa5ea'::uuid,
    'Algi Sushi Nori Premium Gold 3 x 10 szt - Asia Kitchen'::text,
    'algi-sushi-nori-premium-gold-3-x-10-szt-asia-kitchen'::text,
    '2026-07-08 12:12:07.93723+00:00'::timestamptz,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    '{"fat":5.52,"carbs":36.9,"sugar":0,"protein":44.1,"calories":356,"servingSize":"w 100g/100ml","saturatedFat":2.17}'::jsonb,
    '{"fat":5.52,"carbs":36.9,"sugar":0,"protein":44.1,"calories":356,"servingSize":"w 100g/100ml","saturatedFat":2.17}'::jsonb,
    'Korea Południowa'::text,
    'Korea Południowa'::text,
    'Arkusze z suszonych wodorostów, prażone 78g'::text,
    'Arkusze z suszonych wodorostów, prażone 78g'::text,
    NULL::numeric,
    NULL::text,
    '265455d4-4635-430a-bb50-9d8f3d4fcc25'::uuid,
    'Arkusze Nori / Gim'::text,
    'arkusze-nori-gim'::text,
    ARRAY['storageZone'::text]::text[]
  ),
  (
    'ADG-000493'::text,
    '15562453-ea2a-486c-af9b-69f839c457e8'::uuid,
    'd1cfe5cb-f48b-4582-acc5-4e762661b18d'::uuid,
    'Algi Sushi Nori Premium Gold 5 x 10 szt - Asia Kitchen'::text,
    'algi-sushi-nori-premium-gold-5-x-10-szt-asia-kitchen'::text,
    '2026-07-08 12:12:07.93723+00:00'::timestamptz,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    '{"fat":5.52,"carbs":36.9,"sugar":0,"protein":44.1,"calories":356,"servingSize":"w 100g/100ml","saturatedFat":2.17}'::jsonb,
    '{"fat":5.52,"carbs":36.9,"sugar":0,"protein":44.1,"calories":356,"servingSize":"w 100g/100ml","saturatedFat":2.17}'::jsonb,
    'Korea Południowa'::text,
    'Korea Południowa'::text,
    'Arkusze z suszonych wodorostów, prażone 130g'::text,
    'Arkusze z suszonych wodorostów, prażone 130g'::text,
    NULL::numeric,
    NULL::text,
    '265455d4-4635-430a-bb50-9d8f3d4fcc25'::uuid,
    'Arkusze Nori / Gim'::text,
    'arkusze-nori-gim'::text,
    ARRAY['storageZone'::text]::text[]
  ),
  (
    'ADG-000537'::text,
    '8fca21b8-f8b4-4f3d-9145-94286bea5193'::uuid,
    'ba395725-3da2-4eb1-a4c3-5699f35e79bb'::uuid,
    'Glony do sushi Yaki Nori GOLD 10 szt. - KC'::text,
    'glony-do-sushi-yaki-nori-gold-10-szt-kc'::text,
    '2026-07-08 12:12:07.93723+00:00'::timestamptz,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    '{"fat":4.46,"salt":1.1,"carbs":40.9,"sugar":0,"protein":44.5,"calories":382,"servingSize":"w 100g/100ml","saturatedFat":1.94}'::jsonb,
    '{"fat":4.46,"salt":1.1,"carbs":40.9,"sugar":0,"protein":44.5,"calories":382,"servingSize":"w 100g/100ml","saturatedFat":1.94}'::jsonb,
    'Korea Południowa'::text,
    'Korea Południowa'::text,
    '10 arkuszy prażonych nori klasy Gold - 25g'::text,
    '10 arkuszy prażonych nori klasy Gold - 25g'::text,
    NULL::numeric,
    NULL::text,
    '265455d4-4635-430a-bb50-9d8f3d4fcc25'::uuid,
    'Arkusze Nori / Gim'::text,
    'arkusze-nori-gim'::text,
    ARRAY['storageZone'::text]::text[]
  ),
  (
    'ADG-000538'::text,
    '0526158d-78a8-42d8-8967-79c48996af93'::uuid,
    '0b046b5c-ff12-46fd-b108-b1202d912a99'::uuid,
    'Glony do sushi Yaki Nori GOLD 3 x 10 szt. - KC'::text,
    'glony-do-sushi-yaki-nori-gold-3-x-10-szt-kc'::text,
    '2026-07-08 12:12:07.93723+00:00'::timestamptz,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    '{"fat":4.46,"salt":1.1,"carbs":40.9,"sugar":0,"protein":44.5,"calories":382,"servingSize":"w 100g/100ml","saturatedFat":1.94}'::jsonb,
    '{"fat":4.46,"salt":1.1,"carbs":40.9,"sugar":0,"protein":44.5,"calories":382,"servingSize":"w 100g/100ml","saturatedFat":1.94}'::jsonb,
    'Korea Południowa'::text,
    'Korea Południowa'::text,
    '10 arkuszy prażonych nori klasy Gold - 25g'::text,
    '10 arkuszy prażonych nori klasy Gold - 25g'::text,
    NULL::numeric,
    NULL::text,
    '265455d4-4635-430a-bb50-9d8f3d4fcc25'::uuid,
    'Arkusze Nori / Gim'::text,
    'arkusze-nori-gim'::text,
    ARRAY['storageZone'::text]::text[]
  ),
  (
    'ADG-000539'::text,
    '83158f9d-da2a-4cd7-acbe-e486b3819dca'::uuid,
    '24e45455-25fb-4465-abaa-368275afadee'::uuid,
    'Glony do sushi Yaki Nori GOLD 5 x 10 szt. - KC'::text,
    'glony-do-sushi-yaki-nori-gold-5-x-10-szt-kc'::text,
    '2026-07-08 12:12:07.93723+00:00'::timestamptz,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    '{"fat":4.46,"salt":1.1,"carbs":40.9,"sugar":0,"protein":44.5,"calories":382,"servingSize":"w 100g/100ml","saturatedFat":1.94}'::jsonb,
    '{"fat":4.46,"salt":1.1,"carbs":40.9,"sugar":0,"protein":44.5,"calories":382,"servingSize":"w 100g/100ml","saturatedFat":1.94}'::jsonb,
    'Korea Południowa'::text,
    'Korea Południowa'::text,
    '10 arkuszy prażonych nori klasy Gold - 25g'::text,
    '10 arkuszy prażonych nori klasy Gold - 25g'::text,
    NULL::numeric,
    NULL::text,
    '265455d4-4635-430a-bb50-9d8f3d4fcc25'::uuid,
    'Arkusze Nori / Gim'::text,
    'arkusze-nori-gim'::text,
    ARRAY['storageZone'::text]::text[]
  ),
  (
    'ADG-000564'::text,
    '9772939b-e59e-4f3f-b110-0c629561662a'::uuid,
    '5352ac81-e706-4ea3-85c5-2763a33955ac'::uuid,
    'Algi Sushi Nori Gold 50 szt. - Sen Soy'::text,
    'algi-sushi-nori-gold-50-szt-sen-soy'::text,
    '2026-07-08 12:12:07.93723+00:00'::timestamptz,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    '{"fat":2.5,"carbs":42,"sugar":0,"protein":42.5,"calories":361,"servingSize":"w 100g/100ml"}'::jsonb,
    '{"fat":2.5,"carbs":42,"sugar":0,"protein":42.5,"calories":361,"servingSize":"w 100g/100ml"}'::jsonb,
    'Korea Południowa'::text,
    'Korea Południowa'::text,
    'Suszone algi morskie Nori 125g'::text,
    'Suszone algi morskie Nori 125g'::text,
    NULL::numeric,
    NULL::text,
    '265455d4-4635-430a-bb50-9d8f3d4fcc25'::uuid,
    'Arkusze Nori / Gim'::text,
    'arkusze-nori-gim'::text,
    ARRAY['storageZone'::text]::text[]
  ),
  (
    'ADG-000234'::text,
    '1f5af118-c419-4fbb-b1cd-1c9689105e76'::uuid,
    '1ca36038-05ca-4117-b22e-2aa93ac6421b'::uuid,
    'Wakame (miyeok) suszone wodorosty sałatkowe 25g - CJO Essential'::text,
    'wakame-miyeok-suszone-wodorosty-salatkowe-25g-cjo-essential'::text,
    '2026-07-08 12:12:07.93723+00:00'::timestamptz,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    '{"fat":4,"carbs":39.78,"protein":22,"calories":207,"servingSize":"w 100g/100ml"}'::jsonb,
    '{"fat":4,"carbs":39.78,"protein":22,"calories":207,"servingSize":"w 100g/100ml"}'::jsonb,
    'Korea Południowa'::text,
    'Korea Południowa'::text,
    '100% suszone wakame'::text,
    '100% suszone wakame'::text,
    '348.00'::numeric,
    'KG'::text,
    'a7edbaad-4696-4d12-bba0-588a39971511'::uuid,
    'Wakame / Miyeok'::text,
    'wakame-miyeok'::text,
    ARRAY['storageZone'::text]::text[]
  ),
  (
    'ADG-000352'::text,
    '3b327d75-8dbf-488f-b314-4ce50670ff0b'::uuid,
    '6abf1f95-1bc1-4713-b45e-669362efedc0'::uuid,
    'Wakame, suszone wodorosty 100g - Eagle Brand'::text,
    'wakame-suszone-wodorosty-100g-eagle-brand'::text,
    '2026-07-08 12:12:07.93723+00:00'::timestamptz,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    '{"fat":4,"salt":23.75,"carbs":41.8,"sugar":0,"protein":18,"calories":138,"servingSize":"w 100g/100ml"}'::jsonb,
    '{"fat":4,"salt":23.75,"carbs":41.8,"sugar":0,"protein":18,"calories":138,"servingSize":"w 100g/100ml"}'::jsonb,
    'Chiny'::text,
    'Chiny'::text,
    '100% suszone wodorosty morskie wakame'::text,
    '100% suszone wodorosty morskie wakame'::text,
    '135.00'::numeric,
    'KG'::text,
    'a7edbaad-4696-4d12-bba0-588a39971511'::uuid,
    'Wakame / Miyeok'::text,
    'wakame-miyeok'::text,
    ARRAY['storageZone'::text]::text[]
  ),
  (
    'ADG-000025'::text,
    '12ce76e0-949b-4a99-acde-fb8643d64880'::uuid,
    'ff73cc9c-6ef1-402b-ba02-7e4aae2e93bf'::uuid,
    'Wodorosty kombu 100g Asia Kitchen'::text,
    'wodorosty-kombu-100g-asia-kitchen'::text,
    '2026-07-08 12:12:07.93723+00:00'::timestamptz,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    NULL::jsonb,
    NULL::jsonb,
    'Chiny'::text,
    'Chiny'::text,
    '100% alg morskich kombu'::text,
    '100% alg morskich kombu'::text,
    '155.00'::numeric,
    'KG'::text,
    '9f4269f0-a59e-4c3f-89c1-08de03b8b9cc'::uuid,
    'Kombu / Dasima'::text,
    'kombu-dasima'::text,
    ARRAY['storageZone'::text]::text[]
  ),
  (
    'ADG-000069'::text,
    '8c8ec793-c6a8-4c5e-ad09-5a6e44578392'::uuid,
    '75e6979f-233f-4a2a-8c03-6d4d003abb34'::uuid,
    'Grzyby shiitake w zalewie 284g Diamond'::text,
    'grzyby-shiitake-w-zalewie-284g-diamond'::text,
    '2026-07-08 12:12:07.93723+00:00'::timestamptz,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    '{"fat":0.5,"salt":0.86,"carbs":0.5,"sugar":0.5,"protein":1.6,"calories":15,"servingSize":"w 100g/100ml"}'::jsonb,
    '{"fat":0.5,"salt":0.86,"carbs":0.5,"sugar":0.5,"protein":1.6,"calories":15,"servingSize":"w 100g/100ml"}'::jsonb,
    'Chiny'::text,
    'Chiny'::text,
    'Grzyby shiitake, woda, sól, regulator kwasowości: kwas cytrynowy'::text,
    'Grzyby shiitake, woda, sól, regulator kwasowości: kwas cytrynowy'::text,
    '23.24'::numeric,
    'KG'::text,
    '63153137-4198-4c98-871b-a7d35caf221d'::uuid,
    'Grzyby shiitake'::text,
    'grzyby-shiitake'::text,
    ARRAY['storageZone'::text]::text[]
  ),
  (
    'ADG-000089'::text,
    '86eba157-77c4-47a8-9e10-465f49055467'::uuid,
    '530a0635-d103-4656-9977-2332aaf43e61'::uuid,
    'Grzyby słomiane (pochwiaki) 425g - Diamond'::text,
    'grzyby-slomiane-pochwiaki-425g-diamond'::text,
    '2026-07-08 12:12:07.93723+00:00'::timestamptz,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    '{"fat":0.5,"salt":0.66,"carbs":1.6,"sugar":0.5,"protein":2.9,"calories":24,"servingSize":"w 100g/100ml","saturatedFat":0.1}'::jsonb,
    '{"fat":0.5,"salt":0.66,"carbs":1.6,"sugar":0.5,"protein":2.9,"calories":24,"servingSize":"w 100g/100ml","saturatedFat":0.1}'::jsonb,
    'Chiny'::text,
    'Chiny'::text,
    'Grzyby słomiane (Volvariella volvacea), woda, sól'::text,
    'Grzyby słomiane (Volvariella volvacea), woda, sól'::text,
    '25.86'::numeric,
    'KG'::text,
    '7be2022f-8bd6-4c59-ae49-0091d5b40d69'::uuid,
    'Inne grzyby azjatyckie'::text,
    'inne-grzyby-azjatyckie'::text,
    ARRAY['storageZone'::text]::text[]
  ),
  (
    'ADG-000957'::text,
    '753061da-9a37-4ca8-9d5c-bb5166850fe6'::uuid,
    'e9fe7c19-e20a-4ac7-848e-a5a9c1afe84c'::uuid,
    'Grzyby shiitake w zalewie 284g - House of Asia'::text,
    'grzyby-shiitake-w-zalewie-284g-house-of-asia'::text,
    '2026-07-08 12:12:07.93723+00:00'::timestamptz,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    '{"fat":0,"salt":0.72,"carbs":0,"sugar":0,"protein":1.6,"calories":15,"servingSize":"w 100g/100ml","saturatedFat":0}'::jsonb,
    '{"fat":0,"salt":0.72,"carbs":0,"sugar":0,"protein":1.6,"calories":15,"servingSize":"w 100g/100ml","saturatedFat":0}'::jsonb,
    'Chiny'::text,
    'Chiny'::text,
    'Grzyby shiitake (Lentinus edodes (Berk.) Singer) 54,9%, woda, sól.'::text,
    'Grzyby shiitake (Lentinus edodes (Berk.) Singer) 54,9%, woda, sól.'::text,
    '37.32'::numeric,
    'KG'::text,
    '63153137-4198-4c98-871b-a7d35caf221d'::uuid,
    'Grzyby shiitake'::text,
    'grzyby-shiitake'::text,
    ARRAY['storageZone'::text]::text[]
  ),
  (
    'ADG-000308'::text,
    'af4d6e84-9d20-41c9-8da7-c9a73c340942'::uuid,
    'cc8803b8-192e-472b-8f71-8995a89430f0'::uuid,
    'Yuba, suszone płaty tofu 200g - Swallow Sailing'::text,
    'yuba-suszone-platy-tofu-200g-swallow-sailing'::text,
    '2026-07-08 12:12:07.93723+00:00'::timestamptz,
    '["soybeans"]'::jsonb,
    '["soybeans"]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    '{"fat":9,"carbs":9,"sugar":0,"protein":19,"calories":190,"servingSize":"w 100g/100ml","saturatedFat":8}'::jsonb,
    '{"fat":9,"carbs":9,"sugar":0,"protein":19,"calories":190,"servingSize":"w 100g/100ml","saturatedFat":8}'::jsonb,
    'Chiny'::text,
    'Chiny'::text,
    'Soja, woda'::text,
    'Soja, woda'::text,
    '133.50'::numeric,
    'KG'::text,
    'd7442ca6-6767-46e4-9e12-ff8d0f824d89'::uuid,
    'Tofu'::text,
    'tofu'::text,
    ARRAY['storageZone'::text]::text[]
  );

DO $$
DECLARE affected integer;
BEGIN
  IF (SELECT COUNT(*) FROM _adg_metadata_target_salon) <> 1 THEN
    RAISE EXCEPTION 'Expected exactly one active pinned asiandeligo channel';
  END IF;
  IF to_regclass('public.asiandeligo_catalog_metadata_batch8_product_backup_20260722') IS NULL
     OR to_regclass('public.asiandeligo_catalog_metadata_batch8_audit_20260722') IS NULL THEN
    RAISE EXCEPTION 'Required batch backup/audit table is missing';
  END IF;
  IF (
    SELECT COUNT(*)
    FROM public.asiandeligo_catalog_metadata_batch8_product_backup_20260722
    WHERE batch_key = 'asiandeligo-catalog-metadata-batch8-20260722-v1'
      AND decision_sha256 = 'b7f405d8eea6aa7465f63ba05f9e00ed8c14bea2525675db003041775b99ca93'
      AND salon_id = 'e73271a9-53e3-4a20-a02e-791726b452aa'::uuid
  ) <> 13 THEN
    RAISE EXCEPTION 'Expected exactly 13 tenant- and decision-scoped backup rows';
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM public.asiandeligo_catalog_metadata_batch8_audit_20260722
    WHERE batch_key = 'asiandeligo-catalog-metadata-batch8-20260722-v1'
      AND decision_sha256 = 'b7f405d8eea6aa7465f63ba05f9e00ed8c14bea2525675db003041775b99ca93'
      AND salon_id = 'e73271a9-53e3-4a20-a02e-791726b452aa'::uuid
      AND action = 'backup_captured'
      AND product_rows = 13
  ) OR NOT EXISTS (
    SELECT 1 FROM public.asiandeligo_catalog_metadata_batch8_audit_20260722
    WHERE batch_key = 'asiandeligo-catalog-metadata-batch8-20260722-v1'
      AND decision_sha256 = 'b7f405d8eea6aa7465f63ba05f9e00ed8c14bea2525675db003041775b99ca93'
      AND salon_id = 'e73271a9-53e3-4a20-a02e-791726b452aa'::uuid
      AND action = 'apply_complete'
      AND product_rows = 13
  ) OR EXISTS (
    SELECT 1 FROM public.asiandeligo_catalog_metadata_batch8_audit_20260722
    WHERE batch_key = 'asiandeligo-catalog-metadata-batch8-20260722-v1'
      AND decision_sha256 = 'b7f405d8eea6aa7465f63ba05f9e00ed8c14bea2525675db003041775b99ca93'
      AND salon_id = 'e73271a9-53e3-4a20-a02e-791726b452aa'::uuid
      AND action = 'rollback_complete'
  ) THEN
    RAISE EXCEPTION 'Required apply audit chain is incomplete or rollback already completed';
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_catalog.pg_trigger
    WHERE tgrelid = 'public.products'::regclass
      AND tgname = 'zz_enforce_products_monotonic_updated_at'
      AND NOT tgisinternal
      AND tgenabled = 'O'
  ) OR EXISTS (
    SELECT 1
    FROM _adg_metadata_decisions decision
    CROSS JOIN _adg_metadata_target_salon tenant
    LEFT JOIN public.asiandeligo_catalog_metadata_batch8_product_backup_20260722 backup
      ON backup.batch_key = 'asiandeligo-catalog-metadata-batch8-20260722-v1'
     AND backup.decision_sha256 = 'b7f405d8eea6aa7465f63ba05f9e00ed8c14bea2525675db003041775b99ca93'
     AND backup.salon_id = tenant.salon_id
     AND backup.sku = decision.sku
     AND backup.product_id = decision.product_id
    AND backup.variant_id = decision.variant_id
    AND backup.category_id = decision.category_id
    AND backup.changed_fields = decision.changed_fields
    AND backup.original_updated_at = decision.expected_updated_at
    AND backup.applied_updated_at IS NOT NULL
    AND backup.applied_updated_at > backup.original_updated_at
    AND backup.allergens IS NOT DISTINCT FROM decision.expected_allergens
    AND backup.may_contain_allergens IS NOT DISTINCT FROM decision.expected_may_contain_allergens
    AND backup.storage_zone IS NOT DISTINCT FROM decision.expected_storage_zone
    AND backup.nutrition_facts IS NOT DISTINCT FROM decision.expected_nutrition_facts
    AND backup.country_of_origin IS NOT DISTINCT FROM decision.expected_country_of_origin
    AND backup.ingredients IS NOT DISTINCT FROM decision.expected_ingredients
    AND backup.price_per_unit IS NOT DISTINCT FROM decision.expected_price_per_unit
    AND backup.unit_of_measure IS NOT DISTINCT FROM decision.expected_unit_of_measure
    WHERE backup.sku IS NULL
  ) THEN
    RAISE EXCEPTION 'Required timestamp trigger or exact reviewed backup snapshot is missing';
  END IF;

  PERFORM 1
  FROM _adg_metadata_decisions decision
  CROSS JOIN _adg_metadata_target_salon tenant
  JOIN public.asiandeligo_catalog_metadata_batch8_product_backup_20260722 backup
    ON backup.batch_key = 'asiandeligo-catalog-metadata-batch8-20260722-v1'
   AND backup.decision_sha256 = 'b7f405d8eea6aa7465f63ba05f9e00ed8c14bea2525675db003041775b99ca93'
   AND backup.salon_id = tenant.salon_id
   AND backup.sku = decision.sku
   AND backup.product_id = decision.product_id
    AND backup.variant_id = decision.variant_id
    AND backup.category_id = decision.category_id
    AND backup.changed_fields = decision.changed_fields
    AND backup.original_updated_at = decision.expected_updated_at
    AND backup.applied_updated_at IS NOT NULL
    AND backup.applied_updated_at > backup.original_updated_at
    AND backup.allergens IS NOT DISTINCT FROM decision.expected_allergens
    AND backup.may_contain_allergens IS NOT DISTINCT FROM decision.expected_may_contain_allergens
    AND backup.storage_zone IS NOT DISTINCT FROM decision.expected_storage_zone
    AND backup.nutrition_facts IS NOT DISTINCT FROM decision.expected_nutrition_facts
    AND backup.country_of_origin IS NOT DISTINCT FROM decision.expected_country_of_origin
    AND backup.ingredients IS NOT DISTINCT FROM decision.expected_ingredients
    AND backup.price_per_unit IS NOT DISTINCT FROM decision.expected_price_per_unit
    AND backup.unit_of_measure IS NOT DISTINCT FROM decision.expected_unit_of_measure
  JOIN public.product_variants variant
    ON variant.id = decision.variant_id
    AND variant.sku = decision.sku
    AND variant.salon_id = tenant.salon_id
   AND variant.is_active = TRUE
   AND variant.is_published = FALSE
   AND variant.is_for_sale = TRUE
   AND variant.sync_status = 'synced'
   AND variant.availability_status = 'IN_STOCK'
    AND variant.deleted_at IS NULL
  JOIN public.products product
    ON product.id = decision.product_id
    AND product.id = variant.template_id
    AND product.salon_id = tenant.salon_id
   AND product.name = decision.expected_name
   AND product.slug = decision.expected_slug
    AND product.updated_at = backup.applied_updated_at
   AND product.is_active = TRUE
   AND product.is_published = TRUE
   AND product.is_visible = TRUE
   AND product.status = 'active'
    AND product.deleted_at IS NULL
  JOIN public.categories category
    ON category.id = decision.category_id
   AND category.id = product.category_id
   AND category.salon_id = tenant.salon_id
   AND category.name = decision.category_name
   AND category.slug = decision.category_slug
   AND category.is_active = TRUE
  WHERE product.allergens IS NOT DISTINCT FROM decision.target_allergens
    AND product.may_contain_allergens IS NOT DISTINCT FROM decision.target_may_contain_allergens
    AND product.storage_zone IS NOT DISTINCT FROM decision.target_storage_zone
    AND product.nutrition_facts IS NOT DISTINCT FROM decision.target_nutrition_facts
    AND product.country_of_origin IS NOT DISTINCT FROM decision.target_country_of_origin
    AND product.ingredients IS NOT DISTINCT FROM decision.target_ingredients
    AND product.price_per_unit IS NOT DISTINCT FROM decision.expected_price_per_unit
    AND product.unit_of_measure IS NOT DISTINCT FROM decision.expected_unit_of_measure
  ORDER BY product.id
  FOR UPDATE OF product, variant, category;
  GET DIAGNOSTICS affected = ROW_COUNT;
  IF affected <> 13 THEN
    RAISE EXCEPTION 'Expected 13 exact target row locks; refusing to overwrite intervening edits';
  END IF;
END $$;

DO $$
DECLARE affected integer;
BEGIN
  UPDATE public.products product
  SET allergens = backup.allergens,
      may_contain_allergens = backup.may_contain_allergens,
      storage_zone = backup.storage_zone,
      nutrition_facts = backup.nutrition_facts,
      country_of_origin = backup.country_of_origin,
      ingredients = backup.ingredients
  FROM _adg_metadata_decisions decision,
       _adg_metadata_target_salon tenant,
       public.asiandeligo_catalog_metadata_batch8_product_backup_20260722 backup
  WHERE backup.batch_key = 'asiandeligo-catalog-metadata-batch8-20260722-v1'
    AND backup.decision_sha256 = 'b7f405d8eea6aa7465f63ba05f9e00ed8c14bea2525675db003041775b99ca93'
    AND backup.salon_id = tenant.salon_id
    AND backup.sku = decision.sku
    AND backup.product_id = product.id
    AND product.salon_id = tenant.salon_id
    AND product.name = decision.expected_name
    AND product.slug = decision.expected_slug
    AND product.updated_at = backup.applied_updated_at
    AND product.is_active = TRUE
    AND product.is_published = TRUE
    AND product.is_visible = TRUE
    AND product.status = 'active'
    AND product.deleted_at IS NULL
    AND backup.product_id = decision.product_id
    AND backup.variant_id = decision.variant_id
    AND backup.category_id = decision.category_id
    AND backup.changed_fields = decision.changed_fields
    AND backup.original_updated_at = decision.expected_updated_at
    AND backup.applied_updated_at IS NOT NULL
    AND backup.applied_updated_at > backup.original_updated_at
    AND backup.allergens IS NOT DISTINCT FROM decision.expected_allergens
    AND backup.may_contain_allergens IS NOT DISTINCT FROM decision.expected_may_contain_allergens
    AND backup.storage_zone IS NOT DISTINCT FROM decision.expected_storage_zone
    AND backup.nutrition_facts IS NOT DISTINCT FROM decision.expected_nutrition_facts
    AND backup.country_of_origin IS NOT DISTINCT FROM decision.expected_country_of_origin
    AND backup.ingredients IS NOT DISTINCT FROM decision.expected_ingredients
    AND backup.price_per_unit IS NOT DISTINCT FROM decision.expected_price_per_unit
    AND backup.unit_of_measure IS NOT DISTINCT FROM decision.expected_unit_of_measure
    AND product.allergens IS NOT DISTINCT FROM decision.target_allergens
    AND product.may_contain_allergens IS NOT DISTINCT FROM decision.target_may_contain_allergens
    AND product.storage_zone IS NOT DISTINCT FROM decision.target_storage_zone
    AND product.nutrition_facts IS NOT DISTINCT FROM decision.target_nutrition_facts
    AND product.country_of_origin IS NOT DISTINCT FROM decision.target_country_of_origin
    AND product.ingredients IS NOT DISTINCT FROM decision.target_ingredients
    AND product.price_per_unit IS NOT DISTINCT FROM decision.expected_price_per_unit
    AND product.unit_of_measure IS NOT DISTINCT FROM decision.expected_unit_of_measure;
  GET DIAGNOSTICS affected = ROW_COUNT;
  IF affected <> 13 THEN
    RAISE EXCEPTION 'Expected 13 exact product restorations, got %', affected;
  END IF;

  IF (
    SELECT COUNT(*)
    FROM public.products product
    JOIN public.asiandeligo_catalog_metadata_batch8_product_backup_20260722 backup
      ON backup.product_id = product.id
     AND backup.batch_key = 'asiandeligo-catalog-metadata-batch8-20260722-v1'
     AND backup.decision_sha256 = 'b7f405d8eea6aa7465f63ba05f9e00ed8c14bea2525675db003041775b99ca93'
     AND backup.salon_id = product.salon_id
    WHERE product.salon_id = 'e73271a9-53e3-4a20-a02e-791726b452aa'::uuid
      AND product.updated_at > backup.applied_updated_at
      AND product.allergens IS NOT DISTINCT FROM backup.allergens
      AND product.may_contain_allergens IS NOT DISTINCT FROM backup.may_contain_allergens
      AND product.storage_zone IS NOT DISTINCT FROM backup.storage_zone
      AND product.nutrition_facts IS NOT DISTINCT FROM backup.nutrition_facts
      AND product.country_of_origin IS NOT DISTINCT FROM backup.country_of_origin
      AND product.ingredients IS NOT DISTINCT FROM backup.ingredients
      AND product.price_per_unit IS NOT DISTINCT FROM backup.price_per_unit
      AND product.unit_of_measure IS NOT DISTINCT FROM backup.unit_of_measure
  ) <> 13 THEN
    RAISE EXCEPTION 'Rollback post-state verification failed';
  END IF;

  INSERT INTO public.asiandeligo_catalog_metadata_batch8_audit_20260722 (
    batch_key, decision_sha256, channel_slug, salon_id, action, product_rows
  )
  SELECT 'asiandeligo-catalog-metadata-batch8-20260722-v1', 'b7f405d8eea6aa7465f63ba05f9e00ed8c14bea2525675db003041775b99ca93', channel_slug, salon_id,
         'rollback_complete', 13
  FROM _adg_metadata_target_salon;
END $$;

SELECT backup.sku, backup.changed_fields, audit.recorded_at, audit.transaction_id
FROM public.asiandeligo_catalog_metadata_batch8_product_backup_20260722 backup
JOIN public.asiandeligo_catalog_metadata_batch8_audit_20260722 audit
  ON audit.batch_key = backup.batch_key
 AND audit.salon_id = backup.salon_id
 AND audit.action = 'rollback_complete'
WHERE backup.batch_key = 'asiandeligo-catalog-metadata-batch8-20260722-v1'
  AND backup.decision_sha256 = 'b7f405d8eea6aa7465f63ba05f9e00ed8c14bea2525675db003041775b99ca93'
  AND backup.salon_id = 'e73271a9-53e3-4a20-a02e-791726b452aa'::uuid
ORDER BY backup.sku;

COMMIT;
