-- Generated by scripts/owner-image-import-sql-plan.mjs
-- Batch: asiandeligo-owner-images-folder01-20260709
-- Purpose: attach reviewed owner-provided Asia Deli Go product images to product_images.
-- Safe behavior: backs up affected products/product_images; validates exact row counts; aborts on missing product, multi-salon source, duplicate target URL/hash, or rerun.
-- Media precondition: files must be uploaded before running this SQL so every target_url returns 200.
--
-- JOIN contract:
--   _adg_owner_image_source.target_product_id (uuid, from reviewed SKU migration dry-run) = products.id (uuid, PK) - semantic verified against the reviewed catalog mapping.
--   product_images.template_id (uuid, FK) = products.id (uuid, PK); product_images.salon_id = products.salon_id for tenant isolation.
--   product_images.variant_id remains NULL; chk_product_images_entity requires exactly one of template_id/variant_id.
--   Soft-delete: products filtered deleted_at IS NULL; product_images has no deleted_at column.
--   Slug guard accepts either reviewed current KIMCHI slug or reviewed new ADG slug so the plan works before or after SKU/slug migration.
BEGIN;

CREATE TEMP TABLE _adg_owner_image_source (
  target_sku text NOT NULL,
  target_product_id uuid NOT NULL,
  current_slug text NOT NULL,
  new_slug text NOT NULL,
  review_id text NOT NULL,
  image_file text NOT NULL,
  image_order integer NOT NULL,
  target_url text NOT NULL,
  r2_key text NOT NULL,
  sha256 text NOT NULL,
  file_size integer NOT NULL,
  width integer NOT NULL,
  height integer NOT NULL,
  owner_notes text,
  import_rule text NOT NULL,
  PRIMARY KEY (target_product_id, image_file),
  UNIQUE (target_url),
  UNIQUE (r2_key)
) ON COMMIT DROP;

INSERT INTO _adg_owner_image_source (
  target_sku, target_product_id, current_slug, new_slug, review_id, image_file, image_order,
  target_url, r2_key, sha256, file_size, width, height, owner_notes, import_rule
)
VALUES
  ('ADG-000406', '093cc2e3-6114-4fa8-b3bd-c50948963212'::uuid, 'KIMCHI-2172', 'pudding-owocowy-z-nata-de-coco-rozne-smaki-6-x-80g', 'folder01-001', 'SAU_9282.jpg', 1, 'https://img.zira.pl/asiandeligo/owner-images/folder01/ADG-000406/01-SAU_9282.jpg', 'owner-images/folder01/ADG-000406/01-SAU_9282.jpg', '0e8e61b302e8a499a0c37579f1a2705c1a04bd20bcb76e8ec22e63ff8980aa14', 1398992, 2048, 1365, NULL, 'CSV decision approve; import as owner-provided product photo.'),
  ('ADG-000019', '7b815bb4-d6c3-40db-bb53-a1f64b4c6dee'::uuid, 'KIMCHI-59', 'matcha-sproszkowana-zielona-herbata-w-puszce-80g-tian-hu-shan', 'folder01-002', 'SAU_9301.jpg', 1, 'https://img.zira.pl/asiandeligo/owner-images/folder01/ADG-000019/01-SAU_9301.jpg', 'owner-images/folder01/ADG-000019/01-SAU_9301.jpg', '5d5fa55c5b1de586cb06ae59b21a10c64f0bd4edf5ceef930ae54116dedec0e1', 1439548, 2048, 1365, NULL, 'CSV decision approve; import as owner-provided product photo.'),
  ('ADG-000055', 'da4e62d4-0ca7-4074-ab18-f3ce75df5d85'::uuid, 'KIMCHI-191', 'pasta-curry-czerwona-50g', 'folder01-003', 'SAU_9579.jpg', 1, 'https://img.zira.pl/asiandeligo/owner-images/folder01/ADG-000055/01-SAU_9579.jpg', 'owner-images/folder01/ADG-000055/01-SAU_9579.jpg', 'cdafa1d56d5a94d6c8c08e0709b7f7c5c1cbe7b9ecce20e786cf5e504a1f3569', 1261074, 2048, 1365, NULL, 'CSV decision approve; import as owner-provided product photo.'),
  ('ADG-000054', '02fe4e19-1af4-4171-8703-27d8e35a9ed5'::uuid, 'KIMCHI-190', 'pasta-curry-massaman-50g', 'folder01-004', 'SAU_9580.jpg', 1, 'https://img.zira.pl/asiandeligo/owner-images/folder01/ADG-000054/01-SAU_9580.jpg', 'owner-images/folder01/ADG-000054/01-SAU_9580.jpg', '110b49f0868f23ac7110843f7fa15e0eee60c3fb48b39cac3744f5ea75536094', 1572899, 2048, 1620, NULL, 'CSV decision approve; import as owner-provided product photo.'),
  ('ADG-000056', 'dfbd5ffe-4745-4f6e-92de-ffe2aecc2c5a'::uuid, 'KIMCHI-192', 'pasta-curry-zielona-50g-cock-brand', 'folder01-005', 'SAU_9587.jpg', 1, 'https://img.zira.pl/asiandeligo/owner-images/folder01/ADG-000056/01-SAU_9587.jpg', 'owner-images/folder01/ADG-000056/01-SAU_9587.jpg', 'a2171389757723445fc74fbadfc799f8d95f8bbd43ec34acb635e1fbeb57fa3d', 1284980, 2048, 1455, NULL, 'CSV decision approve; import as owner-provided product photo.'),
  ('ADG-000058', 'd83b9620-c45e-4949-a7e4-6b964a283c99'::uuid, 'KIMCHI-194', 'pasta-tom-yum-30g-lobo', 'folder01-006', 'SAU_9591.jpg', 1, 'https://img.zira.pl/asiandeligo/owner-images/folder01/ADG-000058/01-SAU_9591.jpg', 'owner-images/folder01/ADG-000058/01-SAU_9591.jpg', '20dd4bcd647384588ab562c9b228008b56af17bc74094e6bc74e2354c4be0dd2', 1256378, 2048, 1516, NULL, 'CSV decision approve; import as owner-provided product photo.'),
  ('ADG-000498', 'c97ddfb0-2ba9-4c58-beca-71caffda254b'::uuid, 'KIMCHI-2537', 'teriyaki-sos-do-gotowania-80g-sen-soy', 'folder01-007', 'SAU_9602.jpg', 1, 'https://img.zira.pl/asiandeligo/owner-images/folder01/ADG-000498/01-SAU_9602.jpg', 'owner-images/folder01/ADG-000498/01-SAU_9602.jpg', '9f8792a059baf23a39ce78d1a77d00502d2c6fe12e8cacbf6b25467769ce3499', 1495658, 2048, 1365, NULL, 'CSV decision approve; import as owner-provided product photo.'),
  ('ADG-000499', 'ac5f717d-5b27-4bcc-9471-f51b046b47c3'::uuid, 'KIMCHI-2538', 'sos-do-makaronu-pad-thai-80g-sen-soy', 'folder01-008', 'SAU_9608.jpg', 1, 'https://img.zira.pl/asiandeligo/owner-images/folder01/ADG-000499/01-SAU_9608.jpg', 'owner-images/folder01/ADG-000499/01-SAU_9608.jpg', '568dcffe64cfbd2d6c2481a9f8e077f50855be005841c741e39e8d9b886e4210', 1681938, 2048, 1365, NULL, 'CSV decision approve; import as owner-provided product photo.'),
  ('ADG-000506', 'dda2f6bc-84b6-4ecb-afe1-e3c4d36882fd'::uuid, 'KIMCHI-2578', 'baza-do-zupy-pho-lagodna-80g-sen-soy', 'folder01-009', 'SAU_9612.jpg', 1, 'https://img.zira.pl/asiandeligo/owner-images/folder01/ADG-000506/01-SAU_9612.jpg', 'owner-images/folder01/ADG-000506/01-SAU_9612.jpg', '03b8f341ea43acb814d79b4257fa1df829c1d66243462e72994ce254d169d919', 1492191, 2048, 1444, NULL, 'CSV decision approve; import as owner-provided product photo.'),
  ('ADG-000507', 'c9fb3005-1b8c-440e-8390-122b1c88a26a'::uuid, 'KIMCHI-2579', 'baza-do-zupy-tom-yum-lagodna-80g-sen-soy', 'folder01-010', 'SAU_9613.jpg', 1, 'https://img.zira.pl/asiandeligo/owner-images/folder01/ADG-000507/01-SAU_9613.jpg', 'owner-images/folder01/ADG-000507/01-SAU_9613.jpg', 'c574d11ad30658a956311790913d0c0d4b8f945dbe1f80eccdf326d38fa5e8c7', 1470460, 2048, 1365, NULL, 'CSV decision approve; import as owner-provided product photo.'),
  ('ADG-000302', '42af6909-eeae-4777-89ab-4351769f12e6'::uuid, 'KIMCHI-1217', 'koncentrat-z-tamaryndowca-454g-cock-brand', 'folder01-011', 'SAU_9631.jpg', 1, 'https://img.zira.pl/asiandeligo/owner-images/folder01/ADG-000302/01-SAU_9631.jpg', 'owner-images/folder01/ADG-000302/01-SAU_9631.jpg', '248801a33e759695f96a122afb7657bf978af28bbf827cd58be553049773d28d', 1138196, 1365, 2048, NULL, 'CSV decision approve; import as owner-provided product photo.'),
  ('ADG-000302', '42af6909-eeae-4777-89ab-4351769f12e6'::uuid, 'KIMCHI-1217', 'koncentrat-z-tamaryndowca-454g-cock-brand', 'folder01-011', 'SAU_9632.jpg', 2, 'https://img.zira.pl/asiandeligo/owner-images/folder01/ADG-000302/02-SAU_9632.jpg', 'owner-images/folder01/ADG-000302/02-SAU_9632.jpg', '0926be828c11e1571adf27738e061ad80cda4529a7283008de6efa53423ea59e', 975709, 1365, 2048, NULL, 'CSV decision approve; import as owner-provided product photo.'),
  ('ADG-000095', 'cad06094-f283-4097-a19f-a4f857ed0e66'::uuid, 'KIMCHI-354', 'sos-rybny-725ml-squid', 'folder01-012', 'SAU_9646.jpg', 1, 'https://img.zira.pl/asiandeligo/owner-images/folder01/ADG-000095/01-SAU_9646.jpg', 'owner-images/folder01/ADG-000095/01-SAU_9646.jpg', 'bb3056defc88e18b4561702d0490eeef697244dbbd971424dd468da03172677b', 1049130, 1250, 2048, NULL, 'CSV decision approve; import as owner-provided product photo.'),
  ('ADG-000691', '17b738bf-f3fd-4e61-8d94-a52f1d279bdf'::uuid, 'KIMCHI-3264', 'sos-z-czarnym-pieprzem-350g-lee-kum-kee', 'folder01-013', 'SAU_9653.jpg', 1, 'https://img.zira.pl/asiandeligo/owner-images/folder01/ADG-000691/01-SAU_9653.jpg', 'owner-images/folder01/ADG-000691/01-SAU_9653.jpg', 'a486121ba0aa6dff6cf3283a03e19a7f3d352aaffd03411c58eb8762906b2ead', 1023308, 1425, 2048, NULL, 'CSV decision approve; import as owner-provided product photo.'),
  ('ADG-000082', '2da0ffb1-645f-4aff-be6d-89e8814d0c99'::uuid, 'KIMCHI-301', 'sos-hoisin-397g-lee-kum-kee', 'folder01-014', 'SAU_9655.jpg', 1, 'https://img.zira.pl/asiandeligo/owner-images/folder01/ADG-000082/01-SAU_9655.jpg', 'owner-images/folder01/ADG-000082/01-SAU_9655.jpg', '03f357f70e887866b6e25542dd6df38f2581dae9cdec78438fe9db5a7c45fe6c', 974147, 1365, 2048, NULL, 'CSV decision approve; import as owner-provided product photo.'),
  ('ADG-000195', 'e3b70c6c-5b9f-4081-8918-94df3c9e621f'::uuid, 'KIMCHI-811', 'sos-chili-sriracha-mayoo-lagodnie-pikantny-chili-20-200ml-flying-goose', 'folder01-016', 'SAU_9748.jpg', 1, 'https://img.zira.pl/asiandeligo/owner-images/folder01/ADG-000195/01-SAU_9748.jpg', 'owner-images/folder01/ADG-000195/01-SAU_9748.jpg', 'dc6486e77588c60985801c5da78e758be22c5c845b599ddec84dd5ed254d5465', 744776, 1365, 2048, NULL, 'CSV decision approve; import as owner-provided product photo.'),
  ('ADG-000052', '287915de-af7b-43a0-b9da-aff6835edddd'::uuid, 'KIMCHI-183', 'sos-chili-sriracha-bardzo-ostry-chili-61-200ml-flying-goose', 'folder01-017', 'SAU_9749.jpg', 1, 'https://img.zira.pl/asiandeligo/owner-images/folder01/ADG-000052/01-SAU_9749.jpg', 'owner-images/folder01/ADG-000052/01-SAU_9749.jpg', '9acb5e71037661e6f4698c846084f08034d0a8650e6a72e17edc117df4f7c744', 752813, 1365, 2048, NULL, 'CSV decision approve; import as owner-provided product photo.'),
  ('ADG-000210', '53be2a53-534e-40d5-aec7-5a5a9caa1973'::uuid, 'KIMCHI-861', 'pasta-nam-prik-pao-chili-z-krewetkami-513g-mae-pranom', 'folder01-018', 'SAU_9759.jpg', 1, 'https://img.zira.pl/asiandeligo/owner-images/folder01/ADG-000210/01-SAU_9759.jpg', 'owner-images/folder01/ADG-000210/01-SAU_9759.jpg', '0a956de41efe2b413eb067a868fcf4373ef51e3ef28b888938dec6b5d520c8ab', 977973, 1365, 2048, NULL, 'CSV decision approve; import as owner-provided product photo.'),
  ('ADG-000202', '981fc95c-4f7d-4109-a85b-3a660ef90156'::uuid, 'KIMCHI-840', 'fermentowana-czarna-soja-w-oleju-chili-280g-lao-gan-ma', 'folder01-019', 'SAU_9763.jpg', 1, 'https://img.zira.pl/asiandeligo/owner-images/folder01/ADG-000202/01-SAU_9763.jpg', 'owner-images/folder01/ADG-000202/01-SAU_9763.jpg', '4a87e41714616f4b9eb641d468ba018b57a76f57118d69e0ebbc093707063576', 905863, 1365, 2048, NULL, 'CSV decision approve; import as owner-provided product photo.'),
  ('ADG-000114', 'eee329a6-9d3a-4969-b877-f1b10871b978'::uuid, 'KIMCHI-424', 'pasta-sojowa-ssamjang-pikantna-500g-sempio', 'folder01-023', 'SAU_9779.jpg', 1, 'https://img.zira.pl/asiandeligo/owner-images/folder01/ADG-000114/01-SAU_9779.jpg', 'owner-images/folder01/ADG-000114/01-SAU_9779.jpg', '7d0c85ad22e0dc41b74c00f7cd5cece23d367c944c7e7ad88eec3b54ad004d08', 954519, 2048, 1410, NULL, 'CSV decision approve; import as owner-provided product photo.'),
  ('ADG-000114', 'eee329a6-9d3a-4969-b877-f1b10871b978'::uuid, 'KIMCHI-424', 'pasta-sojowa-ssamjang-pikantna-500g-sempio', 'folder01-023', 'SAU_9780.jpg', 2, 'https://img.zira.pl/asiandeligo/owner-images/folder01/ADG-000114/02-SAU_9780.jpg', 'owner-images/folder01/ADG-000114/02-SAU_9780.jpg', '68e64435e0c79a8b4a9f60b52a59f74a85a6a773803660a77a9ed5e595898a3e', 968436, 2048, 1334, NULL, 'CSV decision approve; import as owner-provided product photo.'),
  ('ADG-000114', 'eee329a6-9d3a-4969-b877-f1b10871b978'::uuid, 'KIMCHI-424', 'pasta-sojowa-ssamjang-pikantna-500g-sempio', 'folder01-023', 'SAU_9781.jpg', 3, 'https://img.zira.pl/asiandeligo/owner-images/folder01/ADG-000114/03-SAU_9781.jpg', 'owner-images/folder01/ADG-000114/03-SAU_9781.jpg', 'c2c4d82c230f2fa1cf473a15fe1ac9075cea312fd432d6f6896084b9057e76e4', 1152996, 2048, 1396, NULL, 'CSV decision approve; import as owner-provided product photo.'),
  ('ADG-000275', '6c088eb6-5a2c-4ebc-9c53-77b060bad412'::uuid, 'KIMCHI-1141', 'sos-sojowy-klasyczny-koikuchi-naturalnie-warzony-1l-kikkoman', 'folder01-024', 'SAU_9785.jpg', 1, 'https://img.zira.pl/asiandeligo/owner-images/folder01/ADG-000275/01-SAU_9785.jpg', 'owner-images/folder01/ADG-000275/01-SAU_9785.jpg', 'dee21016a9d236255f5ab0e312114fde82271b0bdb3efc06f67fdf3e0ba635d5', 944394, 1365, 2048, NULL, 'CSV decision approve; import as owner-provided product photo.'),
  ('ADG-000907', 'fac463d0-6e72-4a76-8c2f-4f5c2b7e5e9a'::uuid, 'KIMCHI-4135', 'ocet-z-brazowego-ryzu-100-500ml-sempio', 'folder01-025', 'SAU_9787.jpg', 1, 'https://img.zira.pl/asiandeligo/owner-images/folder01/ADG-000907/01-SAU_9787.jpg', 'owner-images/folder01/ADG-000907/01-SAU_9787.jpg', '98c225faa7805a7ce12757c0b62f5e1871c23171fd32a4f5b0d6154dbb4dec34', 813014, 1365, 2048, NULL, 'CSV decision approve; import as owner-provided product photo.'),
  ('ADG-000272', 'f2d4144a-7e0e-443e-bfac-703313735954'::uuid, 'KIMCHI-1137', 'sos-sojowy-koikuchi-z-dyspenserem-150ml-kikkoman', 'folder01-026', 'SAU_9790.jpg', 1, 'https://img.zira.pl/asiandeligo/owner-images/folder01/ADG-000272/01-SAU_9790.jpg', 'owner-images/folder01/ADG-000272/01-SAU_9790.jpg', '29d4b1b8532d534ff3cde2f4e9fc454c798e401c8c17a311678dc62eea2c4afe', 697103, 1365, 2048, NULL, 'CSV decision approve; import as owner-provided product photo.'),
  ('ADG-000510', '21a03eae-439a-4983-99ac-e4af117cad8b'::uuid, 'KIMCHI-2587', 'chipsy-nori-teriyaki-4-5g-sen-soy', 'folder01-027', 'SAU_9792.jpg', 1, 'https://img.zira.pl/asiandeligo/owner-images/folder01/ADG-000510/01-SAU_9792.jpg', 'owner-images/folder01/ADG-000510/01-SAU_9792.jpg', 'e4208e818ab8823ffbcd4b4adc360652b5653c6b17982093c8d79ae8f909b848', 823251, 1365, 2048, NULL, 'CSV decision approve; import as owner-provided product photo.'),
  ('ADG-000509', '7bce1ed3-a9c9-4c89-8798-a881caf1d6ac'::uuid, 'KIMCHI-2586', 'chipsy-nori-kimchi-4-5g-sen-soy', 'folder01-028', 'SAU_9793.jpg', 1, 'https://img.zira.pl/asiandeligo/owner-images/folder01/ADG-000509/01-SAU_9793.jpg', 'owner-images/folder01/ADG-000509/01-SAU_9793.jpg', '69dfd3dc8a80e25569b33f1dc44e953b9054b9b4f44e7077fc23fef6f6977040', 820325, 1365, 2048, NULL, 'CSV decision approve; import as owner-provided product photo.'),
  ('ADG-000512', '59863b97-c0df-43ff-b9e7-9c8ee0fb0937'::uuid, 'KIMCHI-2592', 'pasta-sojowa-miso-500g-sempio', 'folder01-029', 'SAU_9794.jpg', 1, 'https://img.zira.pl/asiandeligo/owner-images/folder01/ADG-000512/01-SAU_9794.jpg', 'owner-images/folder01/ADG-000512/01-SAU_9794.jpg', '67eb1dcab0601cec596240792d04ff382b1f6b9a485615caacb609d2a6bd4461', 1001499, 1365, 2048, NULL, 'CSV decision approve; import as owner-provided product photo.'),
  ('ADG-000508', '7eff19f6-4ff1-49ac-b715-1d0141c8ce4d'::uuid, 'KIMCHI-2585', 'chipsy-nori-wasabi-4-5g-sen-soy', 'folder01-030', 'SAU_9800.jpg', 1, 'https://img.zira.pl/asiandeligo/owner-images/folder01/ADG-000508/01-SAU_9800.jpg', 'owner-images/folder01/ADG-000508/01-SAU_9800.jpg', '54527d07094d464166a39e233feb06af33d491f44669760cbc44be8ddb8a1439', 931923, 2048, 1365, NULL, 'CSV decision approve; import as owner-provided product photo.'),
  ('ADG-000350', '75d84337-0e30-46b5-bfef-4990d9796d25'::uuid, 'KIMCHI-1445', 'suszone-grzyby-mun-nitki-50g-green-pagoda', 'folder01-031', 'SAU_9801.jpg', 1, 'https://img.zira.pl/asiandeligo/owner-images/folder01/ADG-000350/01-SAU_9801.jpg', 'owner-images/folder01/ADG-000350/01-SAU_9801.jpg', '69feb028fef9677377376f2e6eb324fd7c8d9c5fae5746e7295afd69d1d6c8a9', 1081302, 1365, 2048, NULL, 'CSV decision approve; import as owner-provided product photo.'),
  ('ADG-000349', '827cd31c-bca0-471d-951b-84c12f99edea'::uuid, 'KIMCHI-1444', 'suszone-grzyby-mun-cale-50g-green-pagoda', 'folder01-032', 'SAU_9804.jpg', 1, 'https://img.zira.pl/asiandeligo/owner-images/folder01/ADG-000349/01-SAU_9804.jpg', 'owner-images/folder01/ADG-000349/01-SAU_9804.jpg', '825fabb26ed8e68a57e698e650e959cf855c80a86985c2c86d28c4e0e5e29112', 1071460, 1365, 2048, NULL, 'CSV decision approve; import as owner-provided product photo.'),
  ('ADG-000522', '3846c4e9-4736-4d4b-84ab-dcc51e520e93'::uuid, 'KIMCHI-2613', 'chipsy-nori-original-z-sola-4-5g-sen-soy', 'folder01-033', 'SAU_9809.jpg', 1, 'https://img.zira.pl/asiandeligo/owner-images/folder01/ADG-000522/01-SAU_9809.jpg', 'owner-images/folder01/ADG-000522/01-SAU_9809.jpg', 'a245eb117547308d537e62fc0499fa808108c3b0d67293ca11d7c3eb6775244c', 921110, 1365, 2048, NULL, 'CSV decision approve; import as owner-provided product photo.'),
  ('ADG-000046', '69404314-95dd-4b37-841a-0d0db9639d7d'::uuid, 'KIMCHI-156', 'makaron-soba-300g-chunsi', 'folder01-034', 'SAU_9814.jpg', 1, 'https://img.zira.pl/asiandeligo/owner-images/folder01/ADG-000046/01-SAU_9814.jpg', 'owner-images/folder01/ADG-000046/01-SAU_9814.jpg', '5fa55859a1a8b000c08ed452e47c708a44182a6bca9dc31654613079eaf83e14', 1072924, 1365, 2048, NULL, 'CSV decision approve; import as owner-provided product photo.'),
  ('ADG-000046', '69404314-95dd-4b37-841a-0d0db9639d7d'::uuid, 'KIMCHI-156', 'makaron-soba-300g-chunsi', 'folder01-034', 'SAU_9815.jpg', 2, 'https://img.zira.pl/asiandeligo/owner-images/folder01/ADG-000046/02-SAU_9815.jpg', 'owner-images/folder01/ADG-000046/02-SAU_9815.jpg', '5fdc6e48fc49b8937f98b79e3bdfa3f22dcd475842d4f3b118c3b75b8dbd2a74', 1277748, 1365, 2048, NULL, 'CSV decision approve; import as owner-provided product photo.'),
  ('ADG-000013', 'fcb4e219-4932-4bf0-8774-4e1e0b481849'::uuid, 'KIMCHI-38', 'makaron-ryzowy-lami-m-do-pho-500g-hiep-long', 'folder01-035', 'SAU_9821.jpg', 1, 'https://img.zira.pl/asiandeligo/owner-images/folder01/ADG-000013/01-SAU_9821.jpg', 'owner-images/folder01/ADG-000013/01-SAU_9821.jpg', 'b0fb00c346ca2f5e65643740adac694e7168801137b2e8c6630ad5a3796b0660', 1271075, 1365, 2048, NULL, 'CSV decision approve; import as owner-provided product photo.'),
  ('ADG-000284', '8b5ac857-d038-4ad5-ac19-7c3f95372eba'::uuid, 'KIMCHI-1170', 'panierka-maka-tempura-500g-uncle-barns', 'folder01-036', 'SAU_9848.jpg', 1, 'https://img.zira.pl/asiandeligo/owner-images/folder01/ADG-000284/01-SAU_9848.jpg', 'owner-images/folder01/ADG-000284/01-SAU_9848.jpg', '7c603052705e4e5a40a95c36034f2735cbce12771a278f6de3dbba89395d22d2', 1434486, 1365, 2048, NULL, 'CSV decision approve; import as owner-provided product photo.'),
  ('ADG-000085', 'f238ff91-b625-4762-9aca-a6fa5e91a55a'::uuid, 'KIMCHI-318', 'pasta-curry-czerwona-400g', 'folder01-048', 'SAU_9627.jpg', 1, 'https://img.zira.pl/asiandeligo/owner-images/folder01/ADG-000085/01-SAU_9627.jpg', 'owner-images/folder01/ADG-000085/01-SAU_9627.jpg', '08650d6f6fd331e4bb086875c06cbfb53469d507abc96a545ee6aa718bc1c6a4', 1293396, 1365, 2048, NULL, 'CSV decision approve; import as owner-provided product photo.'),
  ('ADG-000083', '5a04bbec-ccc3-4428-bf07-96c9f1902b69'::uuid, 'KIMCHI-304', 'pasta-tom-yum-900g-cock-brand', 'folder01-049', 'SAU_9641.jpg', 1, 'https://img.zira.pl/asiandeligo/owner-images/folder01/ADG-000083/01-SAU_9641.jpg', 'owner-images/folder01/ADG-000083/01-SAU_9641.jpg', '752c89e363f1b0576ca4f5aa46382386eaaab3aa146e4576eb24a2313b588508', 936540, 1365, 2048, NULL, 'CSV decision approve; import as owner-provided product photo.'),
  ('ADG-000063', 'f9e24a1c-90a2-4eff-8a0d-b162187ec8ef'::uuid, 'KIMCHI-225', 'sos-chili-sambal-oelek-360g-wendjoe', 'folder01-061', 'SAU_9753.jpg', 1, 'https://img.zira.pl/asiandeligo/owner-images/folder01/ADG-000063/01-SAU_9753.jpg', 'owner-images/folder01/ADG-000063/01-SAU_9753.jpg', '59a5a0d0db7541cb32ac1d471c04f6ebb7edb76ea8d8f6e6ea0a6667ec6848a9', 709626, 1365, 2048, NULL, 'CSV decision approve; import as owner-provided product photo.'),
  ('ADG-000052', '287915de-af7b-43a0-b9da-aff6835edddd'::uuid, 'KIMCHI-183', 'sos-chili-sriracha-bardzo-ostry-chili-61-200ml-flying-goose', 'folder01-063', 'SAU_9762.jpg', 2, 'https://img.zira.pl/asiandeligo/owner-images/folder01/ADG-000052/02-SAU_9762.jpg', 'owner-images/folder01/ADG-000052/02-SAU_9762.jpg', '30ec6563c322796b44884e429c59f6c520693a462bbc0cf40767cfc7804d7117', 731917, 1365, 2048, NULL, 'CSV decision approve; import as owner-provided product photo.'),
  ('ADG-000134', 'aa1fcd5b-3545-4d46-aed3-88a96cee9499'::uuid, 'KIMCHI-512', 'pasta-sojowa-z-przyprawami-sunchang-ssamjang-500g-cjo-classic', 'folder01-064', 'SAU_9782.jpg', 1, 'https://img.zira.pl/asiandeligo/owner-images/folder01/ADG-000134/01-SAU_9782.jpg', 'owner-images/folder01/ADG-000134/01-SAU_9782.jpg', '5cba791414de5ee879b3982ca3857bcb7b3272b13e172d99df9a5b889c12db66', 1184609, 2048, 1233, NULL, 'CSV decision approve; import as owner-provided product photo.'),
  ('ADG-000134', 'aa1fcd5b-3545-4d46-aed3-88a96cee9499'::uuid, 'KIMCHI-512', 'pasta-sojowa-z-przyprawami-sunchang-ssamjang-500g-cjo-classic', 'folder01-064', 'SAU_9783.jpg', 2, 'https://img.zira.pl/asiandeligo/owner-images/folder01/ADG-000134/02-SAU_9783.jpg', 'owner-images/folder01/ADG-000134/02-SAU_9783.jpg', '0486ebe72f78fc7fc54e04eead5299e0783057353536f61a7234da9d24d83a4b', 1239173, 2048, 1365, NULL, 'CSV decision approve; import as owner-provided product photo.'),
  ('ADG-000134', 'aa1fcd5b-3545-4d46-aed3-88a96cee9499'::uuid, 'KIMCHI-512', 'pasta-sojowa-z-przyprawami-sunchang-ssamjang-500g-cjo-classic', 'folder01-064', 'SAU_9784.jpg', 3, 'https://img.zira.pl/asiandeligo/owner-images/folder01/ADG-000134/03-SAU_9784.jpg', 'owner-images/folder01/ADG-000134/03-SAU_9784.jpg', '181ffb6c9156268abcf1bfd21ed14d2490b5e368f13485612bd818069a871ed6', 1224756, 2048, 1365, NULL, 'CSV decision approve; import as owner-provided product photo.'),
  ('ADG-000814', '3268426b-e6ca-4f9f-80fa-0f68eafd1899'::uuid, 'KIMCHI-3808', 'chipsy-krewetkowe-prazynki-do-smazenia-1kg-sa-giang', 'folder01-068', 'SAU_9844.jpg', 1, 'https://img.zira.pl/asiandeligo/owner-images/folder01/ADG-000814/01-SAU_9844.jpg', 'owner-images/folder01/ADG-000814/01-SAU_9844.jpg', '831c0ee550c2bd6c723f5014374fdea4b0946491c5c356245f5c32504b8d2142', 1233575, 1365, 2048, NULL, 'CSV decision approve; import as owner-provided product photo.'),
  ('ADG-000115', 'a3c519da-1a34-4126-9df2-7b234db81181'::uuid, 'KIMCHI-425', 'pasta-sojowa-doenjang-460g-sempio', 'folder01-020', 'SAU_9771.jpg', 1, 'https://img.zira.pl/asiandeligo/owner-images/folder01/ADG-000115/01-SAU_9771.jpg', 'owner-images/folder01/ADG-000115/01-SAU_9771.jpg', '7a584be42922108ad9af293bf3083e152bea5374849f2a4fe25f3c436c2a9882', 1063463, 2048, 1385, 'the 4th image is from another product. the first 3 are good, same product as in the current web.', 'Manual correction from owner note: import only first three Doenjang images; exclude SAU_9774.'),
  ('ADG-000115', 'a3c519da-1a34-4126-9df2-7b234db81181'::uuid, 'KIMCHI-425', 'pasta-sojowa-doenjang-460g-sempio', 'folder01-020', 'SAU_9772.jpg', 2, 'https://img.zira.pl/asiandeligo/owner-images/folder01/ADG-000115/02-SAU_9772.jpg', 'owner-images/folder01/ADG-000115/02-SAU_9772.jpg', 'e1c9d5d213ce2b833b2d3a2115e976bbf7cd0fae23d1e30c351233ff43828821', 1149258, 2048, 1365, 'the 4th image is from another product. the first 3 are good, same product as in the current web.', 'Manual correction from owner note: import only first three Doenjang images; exclude SAU_9774.'),
  ('ADG-000115', 'a3c519da-1a34-4126-9df2-7b234db81181'::uuid, 'KIMCHI-425', 'pasta-sojowa-doenjang-460g-sempio', 'folder01-020', 'SAU_9773.jpg', 3, 'https://img.zira.pl/asiandeligo/owner-images/folder01/ADG-000115/03-SAU_9773.jpg', 'owner-images/folder01/ADG-000115/03-SAU_9773.jpg', 'e25a85d128b3238673d4bdf5ea9ffa230b8b83cca4768dbc59f6b5c635d4d246', 1345371, 2048, 1435, 'the 4th image is from another product. the first 3 are good, same product as in the current web.', 'Manual correction from owner note: import only first three Doenjang images; exclude SAU_9774.'),
  ('ADG-000093', 'cf0821aa-14b3-47f0-9ccc-ba490a7c8bfb'::uuid, 'KIMCHI-350', 'pasta-paprykowa-gochujang-ostra-500g-sempio', 'folder01-021', 'SAU_9774.jpg', 1, 'https://img.zira.pl/asiandeligo/owner-images/folder01/ADG-000093/01-SAU_9774.jpg', 'owner-images/folder01/ADG-000093/01-SAU_9774.jpg', 'e8fc3bd645aee63f46fa76ae5e7d577252dc766d999cef69015559cfc5960ef1', 1113110, 2048, 1399, '4th image from the previous product belongs to this product.', 'Manual correction from owner note: move SAU_9774 from folder01-020 to Gochujang and import with SAU_9775/SAU_9776.'),
  ('ADG-000093', 'cf0821aa-14b3-47f0-9ccc-ba490a7c8bfb'::uuid, 'KIMCHI-350', 'pasta-paprykowa-gochujang-ostra-500g-sempio', 'folder01-021', 'SAU_9775.jpg', 2, 'https://img.zira.pl/asiandeligo/owner-images/folder01/ADG-000093/02-SAU_9775.jpg', 'owner-images/folder01/ADG-000093/02-SAU_9775.jpg', 'ff629d8387b782938c280e2e4f6ae477e108f04e7332788b87aaccb505fc5d63', 1358578, 2048, 1427, '4th image from the previous product belongs to this product.', 'Manual correction from owner note: move SAU_9774 from folder01-020 to Gochujang and import with SAU_9775/SAU_9776.'),
  ('ADG-000093', 'cf0821aa-14b3-47f0-9ccc-ba490a7c8bfb'::uuid, 'KIMCHI-350', 'pasta-paprykowa-gochujang-ostra-500g-sempio', 'folder01-021', 'SAU_9776.jpg', 3, 'https://img.zira.pl/asiandeligo/owner-images/folder01/ADG-000093/03-SAU_9776.jpg', 'owner-images/folder01/ADG-000093/03-SAU_9776.jpg', '5fff4562129a81b485b6db3d6fad280fcc6bae2dd4f2bdbc1c7134ffad641448', 1022208, 2048, 1428, '4th image from the previous product belongs to this product.', 'Manual correction from owner note: move SAU_9774 from folder01-020 to Gochujang and import with SAU_9775/SAU_9776.'),
  ('ADG-000792', 'ca46d35f-5ae1-4abe-8dc8-1c70d4416d22'::uuid, 'KIMCHI-3755', 'kostki-bulionowe-pho-ga-drobiowe-75g-ong-chava', 'folder01-047', 'SAU_9593.jpg', 1, 'https://img.zira.pl/asiandeligo/owner-images/folder01/ADG-000792/01-SAU_9593.jpg', 'owner-images/folder01/ADG-000792/01-SAU_9593.jpg', '6bf9cb5fb9d2cb1f6d0d0f30a279c3e881115061da0b74fb9bf857687f7dc15b', 862844, 2048, 1365, 'yes, these are 2 different products, one is beef and the other is pork cubes flavor. Visual label shows Pho Ga/chicken for this image.', 'Manual variant split: visual label SAU_9593 is Pho Ga, map to ADG-000792.'),
  ('ADG-000791', 'f29fd859-037d-4582-99c4-f05ba2d796af'::uuid, 'KIMCHI-3754', 'kostki-bulionowe-pho-bo-wolowe-75g-ong-chava', 'folder01-047', 'SAU_9594.jpg', 1, 'https://img.zira.pl/asiandeligo/owner-images/folder01/ADG-000791/01-SAU_9594.jpg', 'owner-images/folder01/ADG-000791/01-SAU_9594.jpg', '2beea75d0954b4c9cd030bb771e90f52f586281fdc4a15b31d9ca0610331e5a3', 897680, 2048, 1365, 'yes, these are 2 different products, one is beef and the other is pork cubes flavor. Visual label shows Pho Bo/beef for this image.', 'Manual variant split: visual label SAU_9594 is Pho Bo, map to ADG-000791.');

DO $$
DECLARE
  source_count integer;
  product_count integer;
  matched_count integer;
  live_count integer;
  distinct_salon_count integer;
  slug_guard_match_count integer;
  existing_target_url_count integer;
  existing_target_hash_count integer;
BEGIN
  SELECT COUNT(*), COUNT(DISTINCT target_product_id) INTO source_count, product_count FROM _adg_owner_image_source;
  IF source_count <> 52 THEN
    RAISE EXCEPTION 'Expected 52 source image rows, got %', source_count;
  END IF;
  IF product_count <> 41 THEN
    RAISE EXCEPTION 'Expected 41 source products, got %', product_count;
  END IF;

  SELECT COUNT(*),
         COUNT(*) FILTER (WHERE p.deleted_at IS NULL),
         COUNT(DISTINCT p.salon_id),
         COUNT(*) FILTER (WHERE p.slug = s.current_slug OR p.slug = s.new_slug)
    INTO matched_count, live_count, distinct_salon_count, slug_guard_match_count
  FROM _adg_owner_image_source s
  JOIN products p ON p.id = s.target_product_id;

  IF matched_count <> source_count THEN
    RAISE EXCEPTION 'Product match count mismatch: source %, matched %', source_count, matched_count;
  END IF;
  IF live_count <> source_count THEN
    RAISE EXCEPTION 'Some target products are soft-deleted: live %, source %', live_count, source_count;
  END IF;
  IF distinct_salon_count <> 1 THEN
    RAISE EXCEPTION 'Source products span % salons; aborting tenant-unsafe write', distinct_salon_count;
  END IF;
  IF slug_guard_match_count <> source_count THEN
    RAISE EXCEPTION 'Slug guard failed: %/% source rows match expected current KIMCHI slug or new ADG slug', slug_guard_match_count, source_count;
  END IF;

  SELECT COUNT(*) INTO existing_target_url_count
  FROM _adg_owner_image_source s
  JOIN products p ON p.id = s.target_product_id AND p.deleted_at IS NULL
  JOIN product_images pi ON pi.salon_id = p.salon_id AND pi.image_large_url = s.target_url;
  IF existing_target_url_count <> 0 THEN
    RAISE EXCEPTION 'Target owner image URLs already exist (% rows); aborting to avoid duplicate import', existing_target_url_count;
  END IF;

  SELECT COUNT(*) INTO existing_target_hash_count
  FROM _adg_owner_image_source s
  JOIN products p ON p.id = s.target_product_id AND p.deleted_at IS NULL
  JOIN product_images pi ON pi.salon_id = p.salon_id AND pi.template_id = p.id AND pi.file_hash = s.sha256;
  IF existing_target_hash_count <> 0 THEN
    RAISE EXCEPTION 'Target owner image hashes already exist on target products (% rows); aborting to avoid duplicate import', existing_target_hash_count;
  END IF;
END $$;

CREATE TABLE adg_owner_img_f01_20260709_products_bak_20260709 AS
SELECT p.*, now() AS backup_created_at
FROM products p
JOIN (SELECT DISTINCT target_product_id FROM _adg_owner_image_source) s ON s.target_product_id = p.id
WHERE p.deleted_at IS NULL;

CREATE TABLE adg_owner_img_f01_20260709_images_bak_20260709 AS
SELECT pi.*, now() AS backup_created_at
FROM product_images pi
JOIN products p ON p.id = pi.template_id AND p.salon_id = pi.salon_id AND p.deleted_at IS NULL
JOIN (SELECT DISTINCT target_product_id FROM _adg_owner_image_source) s ON s.target_product_id = p.id;

WITH target_products AS (
  SELECT DISTINCT p.id AS target_product_id, p.salon_id
  FROM _adg_owner_image_source s
  JOIN products p ON p.id = s.target_product_id AND p.deleted_at IS NULL
)
UPDATE product_images pi
SET is_primary = false,
    priority = 1000 + COALESCE(pi.priority, 0),
    updated_at = now()
FROM target_products tp
WHERE pi.template_id = tp.target_product_id
  AND pi.salon_id = tp.salon_id;

INSERT INTO product_images (
  salon_id, template_id, variant_id, category, priority, is_primary,
  image_large_url, image_medium_url, image_small_url, url_small, url_thumbnail, url_micro,
  image_id, mime_type, file_size, width, height, alt_text, r2_keys, file_hash, r2_synced,
  created_at, updated_at
)
SELECT
  p.salon_id,
  p.id,
  NULL::uuid,
  CASE WHEN s.image_order = 1 THEN 'LISTING'::product_image_category ELSE 'GALLERY'::product_image_category END,
  s.image_order - 1,
  s.image_order = 1,
  s.target_url,
  s.target_url,
  s.target_url,
  s.target_url,
  s.target_url,
  s.target_url,
  s.image_file,
  'image/jpeg',
  s.file_size,
  s.width,
  s.height,
  p.name,
  jsonb_build_array(s.r2_key),
  s.sha256,
  false,
  now(),
  now()
FROM _adg_owner_image_source s
JOIN products p ON p.id = s.target_product_id AND p.deleted_at IS NULL
ORDER BY s.target_sku, s.image_order;

WITH first_images AS (
  SELECT DISTINCT ON (s.target_product_id)
    s.target_product_id, p.salon_id, s.target_url
  FROM _adg_owner_image_source s
  JOIN products p ON p.id = s.target_product_id AND p.deleted_at IS NULL
  ORDER BY s.target_product_id, s.image_order ASC
)
UPDATE products p
SET image_url = f.target_url,
    images = COALESCE(p.images, '{}'::jsonb) || jsonb_build_object(
      'desktop', f.target_url,
      'thumbnail', f.target_url,
      'source', 'owner_image_import',
      'batch', 'asiandeligo-owner-images-folder01-20260709'
    ),
    updated_at = now()
FROM first_images f
WHERE p.id = f.target_product_id
  AND p.salon_id = f.salon_id
  AND p.deleted_at IS NULL;

DO $$
DECLARE
  inserted_count integer;
  primary_count integer;
  updated_products integer;
BEGIN
  SELECT COUNT(*) INTO inserted_count
  FROM _adg_owner_image_source s
  JOIN products p ON p.id = s.target_product_id AND p.deleted_at IS NULL
  JOIN product_images pi ON pi.salon_id = p.salon_id AND pi.template_id = p.id AND pi.image_large_url = s.target_url;
  SELECT COUNT(*) INTO primary_count
  FROM _adg_owner_image_source s
  JOIN products p ON p.id = s.target_product_id AND p.deleted_at IS NULL
  JOIN product_images pi ON pi.salon_id = p.salon_id AND pi.template_id = p.id AND pi.image_large_url = s.target_url
  WHERE pi.is_primary = true AND pi.category = 'LISTING'::product_image_category;
  SELECT COUNT(*) INTO updated_products
  FROM (SELECT DISTINCT target_product_id FROM _adg_owner_image_source) s
  JOIN products p ON p.id = s.target_product_id AND p.deleted_at IS NULL
  JOIN _adg_owner_image_source first_s ON first_s.target_product_id = p.id AND first_s.image_order = 1
  WHERE p.image_url = first_s.target_url;

  IF inserted_count <> 52 THEN
    RAISE EXCEPTION 'Post-check failed: expected 52 inserted owner images, got %', inserted_count;
  END IF;
  IF primary_count <> 41 THEN
    RAISE EXCEPTION 'Post-check failed: expected 41 primary LISTING images, got %', primary_count;
  END IF;
  IF updated_products <> 41 THEN
    RAISE EXCEPTION 'Post-check failed: expected 41 product image_url updates, got %', updated_products;
  END IF;
END $$;

SELECT
  p.salon_id,
  COUNT(*) AS owner_images_inserted,
  COUNT(DISTINCT p.id) AS products_updated,
  COUNT(*) FILTER (WHERE pi.category = 'LISTING'::product_image_category AND pi.is_primary = true) AS primary_listing_images
FROM _adg_owner_image_source s
JOIN products p ON p.id = s.target_product_id
JOIN product_images pi ON pi.template_id = p.id AND pi.salon_id = p.salon_id AND pi.image_large_url = s.target_url
GROUP BY p.salon_id;

COMMIT;
