-- Generated by scripts/new-product-creation-plan.mjs
-- Batch: asiandeligo-new-products-folder01-review2-20260709
-- Runtime channel guard: kenmito
-- Purpose: create owner-confirmed Asia Deli Go draft products with owner images.
-- Safe behavior: creates products as draft/unpublished/not-for-sale with retail_price=0 and price_pending metadata.
-- Media precondition: files must be uploaded before running this SQL so every target_url returns 200.
--
-- JOIN contract:
--   channels.slug resolves one active channel; channels.salon_id scopes all product/category/variant/image/translation writes.
--   products.category_id (uuid, FK) = categories.id (uuid, PK); categories.salon_id must equal target channel salon_id.
--   product_variants.template_id (uuid, FK) = products.id (uuid, PK); product_variants.salon_id = products.salon_id.
--   product_images.template_id (uuid, FK) = products.id (uuid, PK); product_images.variant_id remains NULL.
--   product_translations.template_id (uuid, FK) = products.id (uuid, PK).
--   Soft-delete: duplicate guards ignore rows with products/product_variants.deleted_at IS NOT NULL.
BEGIN;

CREATE TEMP TABLE _adg_new_product_source (
  product_id uuid NOT NULL DEFAULT gen_random_uuid(),
  variant_id uuid NOT NULL DEFAULT gen_random_uuid(),
  review_id text NOT NULL,
  draft_sku text NOT NULL,
  slug text NOT NULL,
  pl_name text NOT NULL,
  en_name text NOT NULL,
  brand text,
  size_label text,
  category_slug text NOT NULL,
  ean text,
  stock integer NOT NULL,
  dietary_tags jsonb NOT NULL DEFAULT '[]'::jsonb,
  allergens jsonb NOT NULL DEFAULT '[]'::jsonb,
  country_of_origin text,
  source_image text NOT NULL,
  target_url text NOT NULL,
  r2_key text NOT NULL,
  sha256 text NOT NULL,
  file_size integer NOT NULL,
  width integer NOT NULL,
  height integer NOT NULL,
  PRIMARY KEY (draft_sku),
  UNIQUE (slug),
  UNIQUE (target_url),
  UNIQUE (r2_key),
  UNIQUE (sha256)
) ON COMMIT DROP;

INSERT INTO _adg_new_product_source (
  review_id, draft_sku, slug, pl_name, en_name, brand, size_label, category_slug, ean, stock,
  dietary_tags, allergens, country_of_origin, source_image, target_url, r2_key, sha256, file_size, width, height
)
VALUES
  ('folder01-040', 'ADG-001785', 'hoang-long-tra-che-nhai-dac-biet-100g', 'Hoang Long Tra Che Nhai Dac Biet 100g', 'Hoang Long Tra Che Nhai Dac Biet 100g', 'Hoang Long', '100g', 'herbaty', NULL, 100, '[]'::jsonb, '[]'::jsonb, NULL, 'SAU_9284.jpg', 'https://img.zira.pl/asiandeligo/owner-images/folder01/ADG-001785/01-SAU_9284.jpg', 'owner-images/folder01/ADG-001785/01-SAU_9284.jpg', 'd84a3e566a6987bfeccc859bbdfa0f1f800a7dfdcbe07b8b27b4b8e67156e5d8', 1357076, 2048, 1365),
  ('folder01-041', 'ADG-001786', 'koh-kae-peanuts-coconut-cream-flavour-coated', 'Koh-Kae Peanuts Coconut Cream Flavour Coated', 'Koh-Kae Peanuts Coconut Cream Flavour Coated', 'Koh-Kae', '230g', 'słodycze-przekąski', '8852023664248', 100, '[]'::jsonb, '[]'::jsonb, NULL, 'SAU_9304.jpg', 'https://img.zira.pl/asiandeligo/owner-images/folder01/ADG-001786/01-SAU_9304.jpg', 'owner-images/folder01/ADG-001786/01-SAU_9304.jpg', '43c974eaa7133529fa198bb2771d03be8fcb0d78b472eda45b7cd5e5b85be42e', 1415894, 2048, 1365),
  ('folder01-050', 'ADG-001787', 'lee-kum-kee-chicken-marinade-410ml', 'Lee Kum Kee Chicken Marinade 410ml', 'Lee Kum Kee Chicken Marinade 410ml', 'Lee Kum Kee', '410ml', 'sosy-marynaty', '0007889580031', 100, '[]'::jsonb, '[]'::jsonb, NULL, 'SAU_9667.jpg', 'https://img.zira.pl/asiandeligo/owner-images/folder01/ADG-001787/01-SAU_9667.jpg', 'owner-images/folder01/ADG-001787/01-SAU_9667.jpg', '1958e16158c9dbf430ee02a66b097da7e7d13892663de9bd38c0b66ff8984fb8', 965098, 1323, 2048),
  ('folder01-051', 'ADG-001788', 'sen-soy-premium-soy-sauce', 'Sen Soy Premium soy sauce', 'Sen Soy Premium soy sauce', 'Sen Soy', 'unclear', 'sos-sojowy', NULL, 100, '[]'::jsonb, '[]'::jsonb, NULL, 'SAU_9668.jpg', 'https://img.zira.pl/asiandeligo/owner-images/folder01/ADG-001788/01-SAU_9668.jpg', 'owner-images/folder01/ADG-001788/01-SAU_9668.jpg', '4ded3dd8d9131f0fa3fcc846a7b46a0b62a810ea98d4716fd71a407aacd1c901', 900664, 1365, 2048),
  ('folder01-053', 'ADG-001789', 'megachef-gluten-free-soy-sauce-200ml', 'Megachef Gluten-Free Soy Sauce 200ml', 'Megachef Gluten-Free Soy Sauce 200ml', 'Megachef', '200ml', 'sos-sojowy', '8857118730556', 100, '["gluten-free"]'::jsonb, '[]'::jsonb, NULL, 'SAU_9670.jpg', 'https://img.zira.pl/asiandeligo/owner-images/folder01/ADG-001789/01-SAU_9670.jpg', 'owner-images/folder01/ADG-001789/01-SAU_9670.jpg', '201c18c587fc7a792eafdb6f32cd03d30be60d2df3016f65d4577ea57af03724', 1056738, 1210, 2048),
  ('folder01-054', 'ADG-001790', 'megachef-gluten-free-soy-sauce-500ml', 'Megachef Gluten-Free Soy Sauce 500ml', 'Megachef Gluten-Free Soy Sauce 500ml', 'Megachef', '500ml', 'sos-sojowy', '8857118730570', 100, '["gluten-free"]'::jsonb, '[]'::jsonb, NULL, 'SAU_9677.jpg', 'https://img.zira.pl/asiandeligo/owner-images/folder01/ADG-001790/01-SAU_9677.jpg', 'owner-images/folder01/ADG-001790/01-SAU_9677.jpg', '3c1f1671cd2a818ac5cc77eb0308c132afeff8ba2cb9c39cb39a4fb924bfc286', 887236, 1311, 2048),
  ('folder01-055', 'ADG-001791', 'megachef-premium-mushroom-sauce-570g', 'Megachef Premium Mushroom Sauce 570g', 'Megachef Premium Mushroom Sauce 570g', 'Megachef', '570g', 'sosy-marynaty', '8857118730679', 100, '["gluten-free","vegan"]'::jsonb, '[]'::jsonb, NULL, 'SAU_9679.jpg', 'https://img.zira.pl/asiandeligo/owner-images/folder01/ADG-001791/01-SAU_9679.jpg', 'owner-images/folder01/ADG-001791/01-SAU_9679.jpg', 'aee3d062347b9c88e8964fa1be0fbb5606888d2f5671b2c6e0e50ef170ecfdfb', 911251, 1305, 2048);

DO $$
DECLARE
  target_salon_id uuid;
  source_count integer;
  category_count integer;
  existing_sku_count integer;
  existing_slug_count integer;
  existing_ean_count integer;
  existing_image_url_count integer;
  existing_image_hash_count integer;
BEGIN
  SELECT ch.salon_id INTO target_salon_id FROM channels ch WHERE ch.slug = 'kenmito' AND ch.is_active = true;
  IF target_salon_id IS NULL THEN
    RAISE EXCEPTION 'Target channel not found or inactive: kenmito';
  END IF;

  SELECT COUNT(*) INTO source_count FROM _adg_new_product_source;
  IF source_count <> 7 THEN
    RAISE EXCEPTION 'Expected 7 source products, got %', source_count;
  END IF;

  SELECT COUNT(DISTINCT c.slug) INTO category_count
  FROM _adg_new_product_source s
  JOIN categories c ON c.salon_id = target_salon_id AND c.slug = s.category_slug AND c.is_active = true;
  IF category_count <> (SELECT COUNT(DISTINCT category_slug) FROM _adg_new_product_source) THEN
    RAISE EXCEPTION 'Category guard failed: not all category slugs resolve in target salon';
  END IF;

  SELECT COUNT(*) INTO existing_sku_count
  FROM _adg_new_product_source s
  JOIN product_variants pv ON pv.salon_id = target_salon_id AND pv.deleted_at IS NULL AND pv.sku = s.draft_sku;
  IF existing_sku_count <> 0 THEN
    RAISE EXCEPTION 'SKU guard failed: % target SKUs already exist', existing_sku_count;
  END IF;

  SELECT COUNT(*) INTO existing_slug_count
  FROM _adg_new_product_source s
  JOIN products p ON p.salon_id = target_salon_id AND p.deleted_at IS NULL AND p.slug = s.slug;
  IF existing_slug_count <> 0 THEN
    RAISE EXCEPTION 'Slug guard failed: % target slugs already exist', existing_slug_count;
  END IF;

  SELECT COUNT(*) INTO existing_ean_count
  FROM _adg_new_product_source s
  JOIN product_variants pv ON pv.salon_id = target_salon_id AND pv.deleted_at IS NULL AND pv.ean = s.ean
  WHERE s.ean IS NOT NULL AND s.ean <> '';
  IF existing_ean_count <> 0 THEN
    RAISE EXCEPTION 'EAN guard failed: % researched EANs already exist', existing_ean_count;
  END IF;

  SELECT COUNT(*) INTO existing_image_url_count
  FROM _adg_new_product_source s
  JOIN product_images pi ON pi.salon_id = target_salon_id AND pi.image_large_url = s.target_url;
  IF existing_image_url_count <> 0 THEN
    RAISE EXCEPTION 'Image URL guard failed: % owner image URLs already exist', existing_image_url_count;
  END IF;

  SELECT COUNT(*) INTO existing_image_hash_count
  FROM _adg_new_product_source s
  JOIN product_images pi ON pi.salon_id = target_salon_id AND pi.file_hash = s.sha256;
  IF existing_image_hash_count <> 0 THEN
    RAISE EXCEPTION 'Image hash guard failed: % owner image hashes already exist', existing_image_hash_count;
  END IF;
END $$;

WITH target_channel AS (
  SELECT ch.salon_id FROM channels ch WHERE ch.slug = 'kenmito' AND ch.is_active = true
), resolved AS (
  SELECT s.*, tc.salon_id, c.id AS category_id
  FROM _adg_new_product_source s
  CROSS JOIN target_channel tc
  JOIN categories c ON c.salon_id = tc.salon_id AND c.slug = s.category_slug AND c.is_active = true
), inserted_products AS (
  INSERT INTO products (
    id, salon_id, category_id, name, description, product_type, image_url, images, retail_price,
    slug, is_active, status, is_published, brand, country_of_origin, allergens, dietary_tags,
    external_metadata, private_metadata, name_translations, created_at, updated_at
  )
  SELECT
    r.product_id,
    r.salon_id,
    r.category_id,
    r.pl_name,
    NULL::text,
    'stockable',
    r.target_url,
    jsonb_build_object(
      'desktop', r.target_url,
      'thumbnail', r.target_url,
      'source', 'owner_new_product_import',
      'batch', 'asiandeligo-new-products-folder01-review2-20260709'
    ),
    0,
    r.slug,
    true,
    'draft',
    false,
    r.brand,
    NULLIF(r.country_of_origin, ''),
    r.allergens,
    r.dietary_tags,
    jsonb_build_object(
      'batch', 'asiandeligo-new-products-folder01-review2-20260709',
      'review_id', r.review_id,
      'draft_sku', r.draft_sku,
      'price_pending', true,
      'owner_stock_default', r.stock,
      'source_image', r.source_image
    ),
    jsonb_build_object(
      'source', 'owner_image_review',
      'batch', 'asiandeligo-new-products-folder01-review2-20260709',
      'review_id', r.review_id,
      'price_policy', 'owner_price_pending'
    ),
    jsonb_build_object('pl', r.pl_name, 'en', r.en_name),
    now(),
    now()
  FROM resolved r
  RETURNING id
), inserted_variants AS (
  INSERT INTO product_variants (
    id, salon_id, template_id, sku, barcode, ean, name, display_name, product_type,
    retail_price, currency, image_url, images, is_active, is_published, is_for_sale,
    total_stock, total_stock_qty, external_metadata, created_at, updated_at
  )
  SELECT
    r.variant_id,
    r.salon_id,
    r.product_id,
    r.draft_sku,
    NULLIF(r.ean, ''),
    NULLIF(r.ean, ''),
    r.pl_name,
    r.pl_name,
    'stockable',
    0,
    'PLN',
    r.target_url,
    jsonb_build_object('desktop', r.target_url, 'thumbnail', r.target_url),
    true,
    false,
    false,
    r.stock,
    r.stock,
    jsonb_build_object('batch', 'asiandeligo-new-products-folder01-review2-20260709', 'review_id', r.review_id, 'price_pending', true),
    now(),
    now()
  FROM resolved r
  RETURNING id
), inserted_images AS (
  INSERT INTO product_images (
    salon_id, template_id, variant_id, category, priority, is_primary,
    image_large_url, image_medium_url, image_small_url, url_small, url_thumbnail, url_micro,
    image_id, mime_type, file_size, width, height, alt_text, r2_keys, file_hash, r2_synced,
    created_at, updated_at
  )
  SELECT
    r.salon_id,
    r.product_id,
    NULL::uuid,
    'LISTING'::product_image_category,
    0,
    true,
    r.target_url,
    r.target_url,
    r.target_url,
    r.target_url,
    r.target_url,
    r.target_url,
    r.source_image,
    'image/jpeg',
    r.file_size,
    r.width,
    r.height,
    r.pl_name,
    jsonb_build_array(r.r2_key),
    r.sha256,
    false,
    now(),
    now()
  FROM resolved r
  RETURNING id
), inserted_translations AS (
  INSERT INTO product_translations (salon_id, template_id, lang_id, product_name, slug, created_at, updated_at)
  SELECT r.salon_id, r.product_id, 'pl', r.pl_name, r.slug, now(), now() FROM resolved r
  UNION ALL
  SELECT r.salon_id, r.product_id, 'en', r.en_name, r.slug, now(), now() FROM resolved r
  RETURNING id
)
SELECT
  (SELECT COUNT(*) FROM inserted_products) AS products_inserted,
  (SELECT COUNT(*) FROM inserted_variants) AS variants_inserted,
  (SELECT COUNT(*) FROM inserted_images) AS images_inserted,
  (SELECT COUNT(*) FROM inserted_translations) AS translations_inserted;

DO $$
DECLARE
  product_count integer;
  variant_count integer;
  image_count integer;
  translation_count integer;
BEGIN
  SELECT COUNT(*) INTO product_count
  FROM _adg_new_product_source s
  JOIN products p ON p.slug = s.slug AND p.private_metadata->>'batch' = 'asiandeligo-new-products-folder01-review2-20260709';
  SELECT COUNT(*) INTO variant_count
  FROM _adg_new_product_source s
  JOIN product_variants pv ON pv.sku = s.draft_sku AND pv.external_metadata->>'batch' = 'asiandeligo-new-products-folder01-review2-20260709';
  SELECT COUNT(*) INTO image_count
  FROM _adg_new_product_source s
  JOIN product_images pi ON pi.image_large_url = s.target_url;
  SELECT COUNT(*) INTO translation_count
  FROM _adg_new_product_source s
  JOIN products p ON p.slug = s.slug AND p.private_metadata->>'batch' = 'asiandeligo-new-products-folder01-review2-20260709'
  JOIN product_translations pt ON pt.template_id = p.id;

  IF product_count <> 7 THEN
    RAISE EXCEPTION 'Post-check failed: expected 7 products, got %', product_count;
  END IF;
  IF variant_count <> 7 THEN
    RAISE EXCEPTION 'Post-check failed: expected 7 variants, got %', variant_count;
  END IF;
  IF image_count <> 7 THEN
    RAISE EXCEPTION 'Post-check failed: expected 7 images, got %', image_count;
  END IF;
  IF translation_count <> 14 THEN
    RAISE EXCEPTION 'Post-check failed: expected 14 translations, got %', translation_count;
  END IF;
END $$;

COMMIT;
