-- Generated by scripts/catalog-public-taxonomy-remediation-plan.mjs
-- Purpose: roll back the exact-ten Asia Deli Go public-category coverage remediation.
-- Batch: asiandeligo-public-taxonomy-backup-20260720-v1
-- No product price, stock, content, publication, order, reservation, or translation field is changed.
-- No row is deleted. Historical duplicate-category consolidation is outside this batch.
--
-- JOIN contract (schema-introspect verified against production 2026-07-20):
--   product_variants.template_id (uuid) = products.id (uuid), FK declared.
--   products.category_id (uuid) = categories.id (uuid), FK declared.
--   channels.salon_id/categories.salon_id/products.salon_id/product_variants.salon_id are uuid.
-- Assumptions:
--   1. Every canonical business-table join is scoped by the one active asiandeligo salon_id.
--   2. Products and variants exclude deleted_at rows and must remain active/published for mutation.
--   3. The dated backup tables below are intentional recovery artifacts, never canonical product sources.

\set ON_ERROR_STOP on
BEGIN;
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '120s';
SET LOCAL search_path = public, pg_catalog;

CREATE TEMP TABLE _adg_public_taxonomy_target_salon (salon_id uuid PRIMARY KEY) ON COMMIT DROP;
INSERT INTO _adg_public_taxonomy_target_salon (salon_id)
SELECT salon_id
FROM channels
WHERE salon_id = 'e73271a9-53e3-4a20-a02e-791726b452aa'::uuid
  AND slug = 'asiandeligo'
  AND is_active = TRUE;

CREATE TEMP TABLE _adg_public_taxonomy_run (
  batch_key text PRIMARY KEY,
  channel_slug text NOT NULL,
  salon_id uuid NOT NULL UNIQUE,
  recorded_at timestamptz NOT NULL
) ON COMMIT DROP;
INSERT INTO _adg_public_taxonomy_run (batch_key, channel_slug, salon_id, recorded_at)
SELECT 'asiandeligo-public-taxonomy-backup-20260720-v1', 'asiandeligo', salon_id, transaction_timestamp()
FROM _adg_public_taxonomy_target_salon;

CREATE TEMP TABLE _adg_public_taxonomy_moves (
  sku text PRIMARY KEY,
  source_category_slug text NOT NULL,
  target_category_slug text NOT NULL,
  mapping_type text NOT NULL CHECK (mapping_type = 'business'),
  confidence text NOT NULL CHECK (confidence IN ('high', 'medium'))
) ON COMMIT DROP;
INSERT INTO _adg_public_taxonomy_moves (
  sku, source_category_slug, target_category_slug, mapping_type, confidence
) VALUES
  ('ADG-000103', 'unmapped', 'sosy-marynaty', 'business', 'high'),
  ('ADG-000277', 'pozostałe-produkty', 'ryż-i-inne-ziarna', 'business', 'medium'),
  ('ADG-000393', 'unmapped', 'ryż-i-inne-ziarna', 'business', 'high'),
  ('ADG-000607', 'kategoria-tymczasowa', 'prezenty', 'business', 'high'),
  ('ADG-000641', 'unmapped', 'pasty-smakowe', 'business', 'medium'),
  ('ADG-000648', 'unmapped', 'pasty-smakowe', 'business', 'high'),
  ('ADG-000690', 'kategoria-tymczasowa', 'przyprawy', 'business', 'high'),
  ('ADG-000781', 'unmapped', 'ryż-i-inne-ziarna', 'business', 'high'),
  ('ADG-000791', 'unmapped', 'buliony', 'business', 'high'),
  ('ADG-001694', 'kategoria-tymczasowa', 'przyprawy', 'business', 'high');

CREATE TEMP TABLE _adg_public_taxonomy_category_state (
  slug text PRIMARY KEY,
  original_active boolean NOT NULL,
  target_active boolean NOT NULL,
  expected_products_before integer NOT NULL
) ON COMMIT DROP;
INSERT INTO _adg_public_taxonomy_category_state (
  slug, original_active, target_active, expected_products_before
) VALUES
  ('kategoria-tymczasowa', TRUE, FALSE, 3),
  ('unmapped', TRUE, FALSE, 6);

CREATE TEMP TABLE _adg_public_taxonomy_retained_category (
  slug text PRIMARY KEY,
  expected_active boolean NOT NULL,
  expected_products_before integer NOT NULL,
  expected_products_after integer NOT NULL
) ON COMMIT DROP;
INSERT INTO _adg_public_taxonomy_retained_category (
  slug, expected_active, expected_products_before, expected_products_after
) VALUES
  ('pozostałe-produkty', TRUE, 7, 6);

DO $$
BEGIN
  IF (SELECT COUNT(*) FROM _adg_public_taxonomy_target_salon) <> 1 THEN
    RAISE EXCEPTION 'Expected exactly one active Asia Deli Go channel';
  END IF;
  IF (SELECT COUNT(*) FROM _adg_public_taxonomy_moves) <> 10 THEN
    RAISE EXCEPTION 'Expected exactly 10 public-category decisions';
  END IF;
  IF (SELECT COUNT(*) FROM _adg_public_taxonomy_category_state) <> 2 THEN
    RAISE EXCEPTION 'Expected exactly 2 category-state decisions';
  END IF;
  IF (SELECT COUNT(*) FROM _adg_public_taxonomy_retained_category) <> 1 THEN
    RAISE EXCEPTION 'Expected exactly 1 retained-category check';
  END IF;

  IF (
    SELECT COUNT(*) FROM asiandeligo_public_taxonomy_product_backup_20260720 backup
    JOIN _adg_public_taxonomy_run run
      ON backup.batch_key = run.batch_key
     AND backup.channel_slug = run.channel_slug
     AND backup.salon_id = run.salon_id
  ) <> 10 THEN
    RAISE EXCEPTION 'Expected exactly 10 tenant-scoped product backup rows';
  END IF;
  IF (
    SELECT COUNT(*) FROM asiandeligo_public_taxonomy_category_backup_20260720 backup
    JOIN _adg_public_taxonomy_run run
      ON backup.batch_key = run.batch_key
     AND backup.channel_slug = run.channel_slug
     AND backup.salon_id = run.salon_id
  ) <> 2 THEN
    RAISE EXCEPTION 'Expected exactly 2 tenant-scoped category backup rows';
  END IF;
  IF EXISTS (
    SELECT move.sku
    FROM _adg_public_taxonomy_moves move
    CROSS JOIN _adg_public_taxonomy_run run
    LEFT JOIN asiandeligo_public_taxonomy_product_backup_20260720 backup
      ON backup.batch_key = run.batch_key
     AND backup.channel_slug = run.channel_slug
     AND backup.salon_id = run.salon_id
     AND backup.sku = move.sku
    WHERE backup.product_id IS NULL
       OR backup.original_category_slug <> move.source_category_slug
       OR backup.target_category_slug <> move.target_category_slug
       OR backup.mapping_type <> move.mapping_type
       OR backup.confidence <> move.confidence
  ) THEN
    RAISE EXCEPTION 'Product backup does not exactly match the approved decision set';
  END IF;
  IF EXISTS (
    SELECT state.slug
    FROM _adg_public_taxonomy_category_state state
    CROSS JOIN _adg_public_taxonomy_run run
    LEFT JOIN asiandeligo_public_taxonomy_category_backup_20260720 backup
      ON backup.batch_key = run.batch_key
     AND backup.channel_slug = run.channel_slug
     AND backup.salon_id = run.salon_id
     AND backup.category_slug = state.slug
    WHERE backup.category_id IS NULL
       OR backup.original_is_active IS DISTINCT FROM state.original_active
       OR backup.target_is_active IS DISTINCT FROM state.target_active
       OR backup.product_count_before <> state.expected_products_before
  ) THEN
    RAISE EXCEPTION 'Category backup does not exactly match the approved decision set';
  END IF;
  IF (
    SELECT COUNT(*) FROM asiandeligo_public_taxonomy_audit_20260720 audit
    JOIN _adg_public_taxonomy_run run
      ON audit.batch_key = run.batch_key
     AND audit.channel_slug = run.channel_slug
     AND audit.salon_id = run.salon_id
    WHERE audit.action IN ('backup_captured', 'apply_complete')
  ) <> 2 OR EXISTS (
    SELECT 1 FROM asiandeligo_public_taxonomy_audit_20260720 audit
    JOIN _adg_public_taxonomy_run run
      ON audit.batch_key = run.batch_key
     AND audit.channel_slug = run.channel_slug
     AND audit.salon_id = run.salon_id
    WHERE audit.action = 'rollback_complete'
  ) THEN
    RAISE EXCEPTION 'Apply audit precondition failed or batch was already rolled back';
  END IF;

  IF EXISTS (
    SELECT backup.sku
    FROM asiandeligo_public_taxonomy_product_backup_20260720 backup
    JOIN _adg_public_taxonomy_run run
      ON backup.batch_key = run.batch_key
     AND backup.channel_slug = run.channel_slug
     AND backup.salon_id = run.salon_id
    LEFT JOIN product_variants variant
      ON variant.salon_id = run.salon_id
     AND variant.id = backup.variant_id
     AND variant.sku = backup.sku
     AND variant.is_active = TRUE
     AND variant.deleted_at IS NULL
    LEFT JOIN products product
      ON product.salon_id = run.salon_id
     AND product.id = backup.product_id
     AND product.id = variant.template_id
     AND product.category_id = backup.target_category_id
     AND product.is_active = TRUE
     AND product.is_published = TRUE
     AND product.deleted_at IS NULL
    LEFT JOIN categories target_category
      ON target_category.salon_id = run.salon_id
     AND target_category.id = backup.target_category_id
     AND target_category.slug = backup.target_category_slug
     AND target_category.is_active = TRUE
    LEFT JOIN categories original_category
      ON original_category.salon_id = run.salon_id
     AND original_category.id = backup.original_category_id
     AND original_category.slug = backup.original_category_slug
    LEFT JOIN _adg_public_taxonomy_category_state state
      ON state.slug = backup.original_category_slug
    WHERE variant.id IS NULL
       OR product.id IS NULL
       OR target_category.id IS NULL
       OR original_category.id IS NULL
       OR original_category.is_active IS DISTINCT FROM COALESCE(state.target_active, TRUE)
  ) THEN
    RAISE EXCEPTION 'Exact product post-apply state precondition failed; aborting rollback';
  END IF;
  IF EXISTS (
    SELECT backup.category_slug
    FROM asiandeligo_public_taxonomy_category_backup_20260720 backup
    JOIN _adg_public_taxonomy_run run
      ON backup.batch_key = run.batch_key
     AND backup.channel_slug = run.channel_slug
     AND backup.salon_id = run.salon_id
    LEFT JOIN categories category
      ON category.salon_id = run.salon_id
     AND category.id = backup.category_id
     AND category.slug = backup.category_slug
    LEFT JOIN products product
      ON product.salon_id = run.salon_id
     AND product.category_id = backup.category_id
     AND product.deleted_at IS NULL
    GROUP BY backup.category_slug, backup.target_is_active, backup.applied_updated_at,
             category.id, category.is_active, category.updated_at
    HAVING category.id IS NULL
       OR category.is_active IS DISTINCT FROM backup.target_is_active
       OR backup.applied_updated_at IS NULL
       OR category.updated_at IS DISTINCT FROM backup.applied_updated_at
       OR COUNT(product.id) <> 0
  ) THEN
    RAISE EXCEPTION 'Exact category post-apply state precondition failed; aborting rollback';
  END IF;
  IF EXISTS (
    SELECT retained.slug
    FROM _adg_public_taxonomy_retained_category retained
    CROSS JOIN _adg_public_taxonomy_target_salon tenant
    LEFT JOIN categories category
      ON category.salon_id = tenant.salon_id
     AND category.slug = retained.slug
    LEFT JOIN products product
      ON product.salon_id = tenant.salon_id
     AND product.category_id = category.id
     AND product.deleted_at IS NULL
    GROUP BY retained.slug, retained.expected_active, retained.expected_products_after
    HAVING COUNT(DISTINCT category.id) <> 1
       OR BOOL_OR(category.is_active) IS DISTINCT FROM retained.expected_active
       OR COUNT(DISTINCT product.id) <> retained.expected_products_after
  ) THEN
    RAISE EXCEPTION 'Retained category exact post-apply state precondition failed; aborting rollback';
  END IF;
END $$;

DO $$
DECLARE
  affected integer;
BEGIN
  UPDATE categories category
  SET is_active = backup.original_is_active,
      updated_at = GREATEST(category.updated_at + INTERVAL '1 microsecond', clock_timestamp())
  FROM _adg_public_taxonomy_run run,
       asiandeligo_public_taxonomy_category_backup_20260720 backup
  WHERE backup.batch_key = run.batch_key
    AND backup.channel_slug = run.channel_slug
    AND backup.salon_id = run.salon_id
    AND category.salon_id = run.salon_id
    AND category.id = backup.category_id
    AND category.slug = backup.category_slug
    AND category.is_active = backup.target_is_active
    AND category.updated_at = backup.applied_updated_at;
  GET DIAGNOSTICS affected = ROW_COUNT;
  IF affected <> 2 THEN
    RAISE EXCEPTION 'Expected 2 category restorations from backup, got %', affected;
  END IF;

  UPDATE products product
  SET category_id = backup.original_category_id
  FROM _adg_public_taxonomy_run run,
       asiandeligo_public_taxonomy_product_backup_20260720 backup,
       product_variants variant
  WHERE backup.batch_key = run.batch_key
    AND backup.channel_slug = run.channel_slug
    AND backup.salon_id = run.salon_id
    AND product.salon_id = run.salon_id
    AND product.id = backup.product_id
    AND product.category_id = backup.target_category_id
    AND product.is_active = TRUE
    AND product.is_published = TRUE
    AND product.deleted_at IS NULL
    AND variant.salon_id = run.salon_id
    AND variant.id = backup.variant_id
    AND variant.template_id = product.id
    AND variant.sku = backup.sku
    AND variant.is_active = TRUE
    AND variant.deleted_at IS NULL;
  GET DIAGNOSTICS affected = ROW_COUNT;
  IF affected <> 10 THEN
    RAISE EXCEPTION 'Expected 10 product restorations from backup, got %', affected;
  END IF;

  IF EXISTS (
    SELECT backup.sku
    FROM asiandeligo_public_taxonomy_product_backup_20260720 backup
    JOIN _adg_public_taxonomy_run run
      ON backup.batch_key = run.batch_key
     AND backup.channel_slug = run.channel_slug
     AND backup.salon_id = run.salon_id
    JOIN products product
      ON product.salon_id = run.salon_id
     AND product.id = backup.product_id
    WHERE product.category_id IS DISTINCT FROM backup.original_category_id
  ) OR EXISTS (
    SELECT backup.category_slug
    FROM asiandeligo_public_taxonomy_category_backup_20260720 backup
    JOIN _adg_public_taxonomy_run run
      ON backup.batch_key = run.batch_key
     AND backup.channel_slug = run.channel_slug
     AND backup.salon_id = run.salon_id
    JOIN categories category
      ON category.salon_id = run.salon_id
     AND category.id = backup.category_id
    WHERE category.is_active IS DISTINCT FROM backup.original_is_active
       OR category.updated_at <= backup.applied_updated_at
  ) THEN
    RAISE EXCEPTION 'Backup restoration verification failed';
  END IF;

  IF EXISTS (
    SELECT retained.slug
    FROM _adg_public_taxonomy_retained_category retained
    CROSS JOIN _adg_public_taxonomy_target_salon tenant
    LEFT JOIN categories category
      ON category.salon_id = tenant.salon_id
     AND category.slug = retained.slug
    LEFT JOIN products product
      ON product.salon_id = tenant.salon_id
     AND product.category_id = category.id
     AND product.deleted_at IS NULL
    GROUP BY retained.slug, retained.expected_active, retained.expected_products_before
    HAVING COUNT(DISTINCT category.id) <> 1
       OR BOOL_OR(category.is_active) IS DISTINCT FROM retained.expected_active
       OR COUNT(DISTINCT product.id) <> retained.expected_products_before
  ) THEN
    RAISE EXCEPTION 'Retained category rollback count verification failed';
  END IF;

  INSERT INTO asiandeligo_public_taxonomy_audit_20260720 (
    batch_key, channel_slug, salon_id, recorded_at, action, product_rows, category_rows
  )
  SELECT batch_key, channel_slug, salon_id, clock_timestamp(), 'rollback_complete',
         10, 2
  FROM _adg_public_taxonomy_run;
  GET DIAGNOSTICS affected = ROW_COUNT;
  IF affected <> 1 THEN
    RAISE EXCEPTION 'Expected one rollback audit row, got %', affected;
  END IF;
END $$;

SELECT backup.sku, product.name, backup.target_category_slug, backup.original_category_slug,
       backup.mapping_type, backup.confidence, audit.recorded_at AS rolled_back_at
FROM _adg_public_taxonomy_run run
JOIN asiandeligo_public_taxonomy_product_backup_20260720 backup
  ON backup.batch_key = run.batch_key
 AND backup.channel_slug = run.channel_slug
 AND backup.salon_id = run.salon_id
JOIN products product
  ON product.salon_id = run.salon_id
 AND product.id = backup.product_id
JOIN asiandeligo_public_taxonomy_audit_20260720 audit
  ON audit.batch_key = run.batch_key
 AND audit.channel_slug = run.channel_slug
 AND audit.salon_id = run.salon_id
 AND audit.action = 'rollback_complete'
ORDER BY backup.sku;

COMMIT;
