-- Generated by scripts/folder14-duplicate-merge-plan.mjs
-- Roll back the ADG-001811 -> ADG-001803 soft merge.
-- Run this before the duplicate or survivor receives later manual admin edits.

BEGIN;

WITH target_channel AS (
  SELECT salon_id FROM channels WHERE slug = 'asiandeligo' AND is_active = true
)
UPDATE products p
SET deleted_at = NULL,
    is_active = true,
    is_published = false,
    external_metadata = COALESCE(p.external_metadata, '{}'::jsonb)
      - 'merged_into_sku' - 'merge_confirmed_at'
FROM target_channel tc
WHERE p.salon_id = tc.salon_id
  AND p.external_metadata->>'batch' = 'asiandeligo-new-products-folder14-20260713'
  AND p.external_metadata->>'review_id' = 'folder14-020';

WITH target_channel AS (
  SELECT salon_id FROM channels WHERE slug = 'asiandeligo' AND is_active = true
), duplicate_product AS (
  SELECT p.id, tc.salon_id
  FROM target_channel tc
  JOIN products p
    ON p.salon_id = tc.salon_id
   AND p.deleted_at IS NULL
   AND p.external_metadata->>'review_id' = 'folder14-020'
)
UPDATE product_variants pv
SET deleted_at = NULL,
    is_active = true,
    is_published = false,
    is_for_sale = false,
    external_metadata = COALESCE(pv.external_metadata, '{}'::jsonb)
      - 'merged_into_sku' - 'merge_confirmed_at'
FROM duplicate_product d
WHERE pv.salon_id = d.salon_id
  AND pv.template_id = d.id
  AND pv.sku = 'ADG-001811';

WITH target_channel AS (
  SELECT salon_id FROM channels WHERE slug = 'asiandeligo' AND is_active = true
), resolved AS (
  SELECT survivor.id AS survivor_id, duplicate.id AS duplicate_id, tc.salon_id
  FROM target_channel tc
  JOIN products survivor
    ON survivor.salon_id = tc.salon_id
   AND survivor.deleted_at IS NULL
   AND survivor.external_metadata->>'review_id' = 'folder14-012'
  JOIN products duplicate
    ON duplicate.salon_id = tc.salon_id
   AND duplicate.deleted_at IS NULL
   AND duplicate.external_metadata->>'review_id' = 'folder14-020'
)
UPDATE product_images pi
SET template_id = r.duplicate_id,
    priority = 0,
    is_primary = true,
    image_large_url = 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001811/01-PETE8104.JPG',
    image_medium_url = 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001811/01-PETE8104.JPG',
    image_small_url = 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001811/01-PETE8104.JPG',
    url_small = 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001811/01-PETE8104.JPG',
    url_thumbnail = 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001811/01-PETE8104.JPG',
    url_micro = 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001811/01-PETE8104.JPG',
    r2_keys = jsonb_build_array('owner-images/folder14/ADG-001811/01-PETE8104.JPG'),
    alt_text = 'Stainless-handle Chinese cleaver / kitchen knife'
FROM resolved r
WHERE pi.salon_id = r.salon_id
  AND pi.template_id = r.survivor_id
  AND pi.image_large_url = 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001803/02-PETE8104.JPG'
  AND pi.file_hash = 'e51a856a30c62a39a3f0779ccc6c74f591762b6cd4030aa75a16ca7bd75b2184';

WITH target_channel AS (
  SELECT salon_id FROM channels WHERE slug = 'asiandeligo' AND is_active = true
)
UPDATE products p
SET external_metadata = COALESCE(p.external_metadata, '{}'::jsonb) - 'merged_duplicate_skus'
FROM target_channel tc
WHERE p.salon_id = tc.salon_id
  AND p.deleted_at IS NULL
  AND p.external_metadata->>'review_id' = 'folder14-012';

COMMIT;
