\set ON_ERROR_STOP on
-- Generated by scripts/catalog-metadata-batch2-plan.mjs
-- Purpose: roll back the reviewed Asia Deli Go metadata batch.
-- Decision SHA-256: 792e0c4277c96bc5a49edcd988b268ea178c0d93176ddfd5d3dd770fe2922732
--
-- JOIN contract (schema-introspect verified on production 2026-07-22):
--   product_variants.template_id (uuid) = products.id (uuid) — FK declared; sampled match OK.
--   products.category_id (uuid) = categories.id (uuid) — FK declared; sampled match OK.
--   channels.salon_id = products/product_variants/categories.salon_id (uuid) — tenant pinned on every table.
-- Status values: products.status=active; variant sync_status=synced and availability_status=IN_STOCK.
-- Soft-delete policy: products and variants require deleted_at IS NULL; category/channel require active.
-- Canonical tables only: products, product_variants, categories, channels; no backup/legacy table is joined.

BEGIN;
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
SET LOCAL search_path = pg_catalog, public;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '120s';

CREATE TEMP TABLE _adg_metadata_target_salon (
  salon_id uuid PRIMARY KEY,
  channel_slug text NOT NULL
) ON COMMIT DROP;

INSERT INTO _adg_metadata_target_salon (salon_id, channel_slug)
SELECT salon_id, slug
FROM public.channels
WHERE salon_id = 'e73271a9-53e3-4a20-a02e-791726b452aa'::uuid
  AND slug = 'asiandeligo'
  AND is_active = TRUE
FOR SHARE;

CREATE TEMP TABLE _adg_metadata_decisions (
  sku text PRIMARY KEY,
  product_id uuid UNIQUE NOT NULL,
  variant_id uuid UNIQUE NOT NULL,
  expected_name text NOT NULL,
  expected_slug text NOT NULL,
  expected_updated_at timestamptz NOT NULL,
  expected_allergens jsonb,
  target_allergens jsonb,
  expected_may_contain_allergens jsonb,
  target_may_contain_allergens jsonb,
  expected_storage_zone text,
  target_storage_zone text,
  expected_nutrition_facts jsonb,
  target_nutrition_facts jsonb,
  expected_country_of_origin text,
  target_country_of_origin text,
  expected_ingredients text,
  target_ingredients text,
  expected_price_per_unit numeric,
  expected_unit_of_measure text,
  category_id uuid NOT NULL,
  category_name text NOT NULL,
  category_slug text NOT NULL,
  changed_fields text[] NOT NULL
) ON COMMIT DROP;

INSERT INTO _adg_metadata_decisions VALUES
  (
    'ADG-000155'::text,
    '613b56fb-6482-4a28-8569-e3f9a774ec4b'::uuid,
    'a07cedb2-3995-4d23-95cf-65148d1a945c'::uuid,
    'Płatki suszonego tuńczyka bonito, Katsuobushi 20g'::text,
    'platki-suszonego-tunczyka-bonito-katsuobushi-20g'::text,
    '2026-07-08T12:12:07.937230+00:00'::timestamptz,
    '["fish"]'::jsonb,
    '["fish"]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    'AMBIENT'::text,
    'AMBIENT'::text,
    NULL::jsonb,
    NULL::jsonb,
    NULL::text,
    'Hiszpania'::text,
    'Płatki suszonego tuńczyka bonito 100%'::text,
    'Płatki suszonego tuńczyka bonito 100%'::text,
    '625.00'::numeric,
    'KG'::text,
    '05955e9b-c202-4954-bddc-557a59563373'::uuid,
    'Buliony'::text,
    'buliony'::text,
    ARRAY['countryOfOrigin'::text]::text[]
  ),
  (
    'ADG-000163'::text,
    'dde98b49-679c-4555-a3c9-76fa8685e152'::uuid,
    'ab72c0c5-cdad-4bfc-9c8a-3028fa7de366'::uuid,
    'Mleko kokosowe (70% wyciągu z kokosa) w kartonie 500ml - AROY-D'::text,
    'mleko-kokosowe-70-wyciagu-z-kokosa-w-kartonie-500ml-aroy-d'::text,
    '2026-07-08T12:12:07.937230+00:00'::timestamptz,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    'AMBIENT'::text,
    'AMBIENT'::text,
    '{"fat":19,"salt":0.05,"carbs":2,"sugar":2,"protein":1.6,"calories":185,"servingSize":"w 100g/100ml","saturatedFat":17}'::jsonb,
    '{"fat":19,"salt":0.05,"carbs":2,"sugar":2,"protein":1.6,"calories":185,"servingSize":"w 100g/100ml","saturatedFat":17}'::jsonb,
    NULL::text,
    'Tajlandia'::text,
    'Ekstrakt z orzecha kokosowego 70%, woda, emulgator: polisorbat 65 (E436)'::text,
    'Ekstrakt z orzecha kokosowego 70%, woda, emulgator: polisorbat 65 (E436)'::text,
    '27.98'::numeric,
    'LITER'::text,
    '55cb91c3-2987-4fd8-b3ea-14a5ebc4448c'::uuid,
    'Mleczko kokosowe'::text,
    'mleczko-kokosowe'::text,
    ARRAY['countryOfOrigin'::text]::text[]
  ),
  (
    'ADG-000168'::text,
    'a2b30fec-71ef-480d-ab87-857a66c7ba28'::uuid,
    '47931bd2-d720-4f92-8cce-14cce17fa69c'::uuid,
    'Pasta Harissa ostra (chili 87%) 135g - Le Phare Du Cap Bon'::text,
    'pasta-harissa-ostra-chili-87-135g-le-phare-du-cap-bon'::text,
    '2026-07-08T12:12:07.937230+00:00'::timestamptz,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    '{"fat":2.6,"salt":2.3,"carbs":8.3,"sugar":2.6,"protein":3.1,"calories":69,"servingSize":"w 100g/100ml"}'::jsonb,
    '{"fat":2.6,"salt":2.3,"carbs":8.3,"sugar":2.6,"protein":3.1,"calories":69,"servingSize":"w 100g/100ml"}'::jsonb,
    'Tunezja'::text,
    'Tunezja'::text,
    'Czerwona papryka ostra 87%, czosnek, kolendra, sól, kminek'::text,
    'Czerwona papryka ostra 87%, czosnek, kolendra, sól, kminek'::text,
    '51.78'::numeric,
    'KG'::text,
    '142af5dc-2ab5-4ae8-a44c-76ba71847c0f'::uuid,
    'Pasty smakowe'::text,
    'pasty-smakowe'::text,
    ARRAY['storageZone'::text]::text[]
  ),
  (
    'ADG-000177'::text,
    '34717b00-9905-410c-9334-38a545df6271'::uuid,
    '520fafe1-0819-4381-97b8-1d4372700e8a'::uuid,
    'Papryka Gochugaru do kimchi 500g - Ourhome'::text,
    'papryka-gochugaru-do-kimchi-500g-ourhome'::text,
    '2026-07-08T12:12:07.937230+00:00'::timestamptz,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    '{"fat":0,"salt":0,"carbs":1,"sugar":1,"protein":1,"calories":17,"servingSize":"w 5g","saturatedFat":0.1}'::jsonb,
    '{"fat":0,"salt":0,"carbs":1,"sugar":1,"protein":1,"calories":17,"servingSize":"w 5g","saturatedFat":0.1}'::jsonb,
    'Chiny'::text,
    'Chiny'::text,
    '100% czerwona papryka'::text,
    '100% czerwona papryka'::text,
    '59.00'::numeric,
    'KG'::text,
    '3a5525a6-7e8c-4d23-a80c-465177318f0a'::uuid,
    'Przyprawy'::text,
    'przyprawy'::text,
    ARRAY['storageZone'::text]::text[]
  ),
  (
    'ADG-000191'::text,
    'b8ab7c3a-fbf6-4138-b53b-91401309982b'::uuid,
    '34157548-6fe3-4e45-8cde-f0fa3af7ac61'::uuid,
    'Chrzan wasabi w proszku S&B puszka 30g'::text,
    'chrzan-wasabi-w-proszku-s-and-b-puszka-30g'::text,
    '2026-07-08T12:12:07.937230+00:00'::timestamptz,
    '["mustard"]'::jsonb,
    '["mustard"]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    NULL::jsonb,
    '{"calories":378,"fat":9.1,"saturatedFat":0.7,"carbs":50,"sugar":29,"protein":15,"salt":0.12,"servingSize":"100g"}'::jsonb,
    'Japonia'::text,
    'Japonia'::text,
    'Chrzan 76%, gorczyca, skrobia z tapioki, Wasabi Japonica 2%'::text,
    'Chrzan 76%, gorczyca, skrobia z tapioki, Wasabi Japonica 2%'::text,
    '366.33'::numeric,
    'KG'::text,
    '3c32e788-02b4-4906-a4ff-9e245aa61eda'::uuid,
    'Wasabi'::text,
    'wasabi'::text,
    ARRAY['storageZone'::text, 'nutritionFacts'::text]::text[]
  ),
  (
    'ADG-000199'::text,
    '28810d83-1b5b-453d-b678-1936013f7f67'::uuid,
    '87399e81-7f15-4b13-8f71-e87f38af644e'::uuid,
    'Sos chili Sriracha z czosnkiem, ostry (51% chili) 730ml - Flying Goose'::text,
    'sos-chili-sriracha-z-czosnkiem-ostry-51-chili-730ml-flying-goose'::text,
    '2026-07-08T12:12:07.937230+00:00'::timestamptz,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    '{"fat":0.9,"salt":9,"carbs":26,"sugar":23,"protein":3.1,"calories":132,"servingSize":"w 100g/100ml","saturatedFat":0.2}'::jsonb,
    '{"fat":0.9,"salt":9,"carbs":26,"sugar":23,"protein":3.1,"calories":132,"servingSize":"w 100g/100ml","saturatedFat":0.2}'::jsonb,
    'Indie'::text,
    'Indie'::text,
    'Chili 51%, czosnek 22%, cukier, sól, woda, regulator kwasowości E330, substancja wzmacniająca E621, stabilizator E415, substancja konserwująca E202, E220'::text,
    'Chili 51%, czosnek 22%, cukier, sól, woda, regulator kwasowości E330, substancja wzmacniająca E621, stabilizator E415, substancja konserwująca E202, E220'::text,
    '41.78'::numeric,
    'LITER'::text,
    '691e2a51-4453-4fd9-bd02-f9abdf9a0def'::uuid,
    'Sosy, marynaty'::text,
    'sosy-marynaty'::text,
    ARRAY['storageZone'::text]::text[]
  ),
  (
    'ADG-000200'::text,
    'b738fcfa-dba8-44a1-b496-dfb2a8dcb59b'::uuid,
    '2a31a8f8-958e-40e0-a412-2c3b3b0fb2cb'::uuid,
    'Sos chili Sriracha, bardzo ostry (chili 61%) 730ml - Flying Goose'::text,
    'sos-chili-sriracha-bardzo-ostry-chili-61-730ml-flying-goose'::text,
    '2026-07-08T12:12:07.937230+00:00'::timestamptz,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    '{"fat":1.3,"salt":7.2,"carbs":59,"sugar":18,"protein":1.8,"calories":122,"servingSize":"w 100g/100ml","saturatedFat":0.1}'::jsonb,
    '{"fat":1.3,"salt":7.2,"carbs":59,"sugar":18,"protein":1.8,"calories":122,"servingSize":"w 100g/100ml","saturatedFat":0.1}'::jsonb,
    'Indie'::text,
    'Indie'::text,
    'Chili 61%, cukier, czosnek, sól, woda, kwasek cytrynowy E330, E260, wzmacniacz smaku: glutamat E621, środek zagęszczający ksantan E415, konserwant E20'::text,
    'Chili 61%, cukier, czosnek, sól, woda, kwasek cytrynowy E330, E260, wzmacniacz smaku: glutamat E621, środek zagęszczający ksantan E415, konserwant E20'::text,
    '34.93'::numeric,
    'LITER'::text,
    '691e2a51-4453-4fd9-bd02-f9abdf9a0def'::uuid,
    'Sosy, marynaty'::text,
    'sosy-marynaty'::text,
    ARRAY['storageZone'::text]::text[]
  ),
  (
    'ADG-000201'::text,
    'a938c19f-4922-4203-af85-360607fe85e5'::uuid,
    '00fb0562-c43b-4a6a-a43c-e8b82d008f03'::uuid,
    'Syrop kukurydziany 100% 2,45kg - CJO Essential'::text,
    'syrop-kukurydziany-100-2-45kg-cjo-essential'::text,
    '2026-07-08T12:12:07.937230+00:00'::timestamptz,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    '{"fat":0,"salt":0,"carbs":76,"sugar":76,"protein":0,"calories":304,"servingSize":"w 100g/100ml"}'::jsonb,
    '{"fat":0,"salt":0,"carbs":76,"sugar":76,"protein":0,"calories":304,"servingSize":"w 100g/100ml"}'::jsonb,
    'Korea Południowa'::text,
    'Korea Południowa'::text,
    'Syrop glukozowy z kukurydzy 100%'::text,
    'Syrop glukozowy z kukurydzy 100%'::text,
    '23.22'::numeric,
    'KG'::text,
    '691e2a51-4453-4fd9-bd02-f9abdf9a0def'::uuid,
    'Sosy, marynaty'::text,
    'sosy-marynaty'::text,
    ARRAY['storageZone'::text]::text[]
  ),
  (
    'ADG-000206'::text,
    'f0d8fa02-6e6b-4b63-8a69-6dfd5bedde59'::uuid,
    '42a0d380-2e0a-4757-a131-0383cbff8568'::uuid,
    'Pasta Harissa ostra (chili 87%) 70g - Le Phare Du Cap Bon'::text,
    'pasta-harissa-ostra-chili-87-70g-le-phare-du-cap-bon'::text,
    '2026-07-08T12:12:07.937230+00:00'::timestamptz,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    '{"fat":2.6,"salt":2.3,"carbs":8.3,"sugar":2.6,"protein":3.1,"calories":69,"servingSize":"w 100g/100ml"}'::jsonb,
    '{"fat":2.6,"salt":2.3,"carbs":8.3,"sugar":2.6,"protein":3.1,"calories":69,"servingSize":"w 100g/100ml"}'::jsonb,
    'Tunezja'::text,
    'Tunezja'::text,
    'Czerwona papryka ostra 87%, czosnek, kolendra, sól, kminek'::text,
    'Czerwona papryka ostra 87%, czosnek, kolendra, sól, kminek'::text,
    '99.86'::numeric,
    'KG'::text,
    '142af5dc-2ab5-4ae8-a44c-76ba71847c0f'::uuid,
    'Pasty smakowe'::text,
    'pasty-smakowe'::text,
    ARRAY['storageZone'::text]::text[]
  ),
  (
    'ADG-000209'::text,
    'd56cf741-5152-46ae-a325-738965bccaf9'::uuid,
    '1cf4c050-6180-4bac-8b25-8120d61cb3f7'::uuid,
    'Sos chili Sambal Oelek (chili 86%) 750g - Windmill'::text,
    'sos-chili-sambal-oelek-chili-86-750g-windmill'::text,
    '2026-07-08T12:12:07.937230+00:00'::timestamptz,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    'AMBIENT'::text,
    'AMBIENT'::text,
    '{"fat":0.5,"salt":11.5,"carbs":3.6,"sugar":3.6,"protein":1.6,"calories":31,"servingSize":"w 100g/100ml","saturatedFat":0.1}'::jsonb,
    '{"fat":0.5,"salt":11.5,"carbs":3.6,"sugar":3.6,"protein":1.6,"calories":31,"servingSize":"w 100g/100ml","saturatedFat":0.1}'::jsonb,
    NULL::text,
    'Holandia'::text,
    'Chili (86%), sól, regulatory kwasowości: kwas octowy (E260), kwas cytrynowy (E330); substancja konserwująca: benzoesan sodu (E211)'::text,
    'Chili (86%), sól, regulatory kwasowości: kwas octowy (E260), kwas cytrynowy (E330); substancja konserwująca: benzoesan sodu (E211)'::text,
    '25.32'::numeric,
    'KG'::text,
    '691e2a51-4453-4fd9-bd02-f9abdf9a0def'::uuid,
    'Sosy, marynaty'::text,
    'sosy-marynaty'::text,
    ARRAY['countryOfOrigin'::text]::text[]
  ),
  (
    'ADG-000213'::text,
    'cefdee71-32c7-4a38-8d6f-15cb95873846'::uuid,
    '1cc5a067-c59c-4a08-a4f2-d4f7822e1864'::uuid,
    'Pasta Inaka Aka Miso, ciemna 400g - Hikari Miso'::text,
    'pasta-inaka-aka-miso-ciemna-400g-hikari-miso'::text,
    '2026-07-08T12:12:07.937230+00:00'::timestamptz,
    '[]'::jsonb,
    '["soybeans"]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    'CHILLED'::text,
    'CHILLED'::text,
    '{"fat":5.8,"salt":11.3,"carbs":25,"sugar":11.5,"protein":10,"calories":194,"servingSize":"w 100g/100ml","saturatedFat":0.9}'::jsonb,
    '{"fat":5.8,"salt":11.3,"carbs":25,"sugar":11.5,"protein":10,"calories":194,"servingSize":"w 100g/100ml","saturatedFat":0.9}'::jsonb,
    'Japonia'::text,
    'Japonia'::text,
    NULL::text,
    'Woda, soja, ryż, sól, alkohol.'::text,
    '27.47'::numeric,
    'KG'::text,
    '35345a48-aebd-4dc5-a6d1-7bc6c27a9183'::uuid,
    'Pasta miso'::text,
    'pasta-miso'::text,
    ARRAY['allergens'::text, 'ingredients'::text]::text[]
  ),
  (
    'ADG-000246'::text,
    '3dbd7fe1-78ee-47c9-b16e-fc2d23724d74'::uuid,
    '4bbf8ce8-152e-4d2b-8bc2-332d6211534b'::uuid,
    'Wino ryżowe do gotowania Mijak (Mirin) imbirowo-śliwkowe 410ml - CJO Essential'::text,
    'wino-ryzowe-do-gotowania-mijak-mirin-imbirowo-sliwkowe-410ml-cjo-essential'::text,
    '2026-07-08T12:12:07.937230+00:00'::timestamptz,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    '{"fat":0.1,"salt":1.1,"carbs":38.7,"sugar":34.8,"protein":0.1,"calories":156,"servingSize":"w 100g/100ml"}'::jsonb,
    '{"fat":0.1,"salt":1.1,"carbs":38.7,"sugar":34.8,"protein":0.1,"calories":156,"servingSize":"w 100g/100ml"}'::jsonb,
    'Korea Południowa'::text,
    'Korea Południowa'::text,
    'Woda, syrop kukurydziany, cukier, ocet, ekstrakt imbirowy, sól, wino ryżowe, kwas cytrynowy, kwas jabłkowy, kwas mlekowy, kwas bursztynowy, koncentrat ze śliwki'::text,
    'Woda, syrop kukurydziany, cukier, ocet, ekstrakt imbirowy, sól, wino ryżowe, kwas cytrynowy, kwas jabłkowy, kwas mlekowy, kwas bursztynowy, koncentrat ze śliwki'::text,
    '41.95'::numeric,
    'LITER'::text,
    '5b5e9a99-a4c6-4d2a-b542-cc678f688de9'::uuid,
    'Octy i winne przyprawy'::text,
    'octy-i-winne-przyprawy'::text,
    ARRAY['storageZone'::text]::text[]
  ),
  (
    'ADG-000248'::text,
    '4b6f2741-deb9-45b7-ab4e-dd17443e8f0c'::uuid,
    'e5b92453-ce20-430f-a133-eb86181ff12e'::uuid,
    'Syrop ryżowy 100% 700g - CJO Essential'::text,
    'syrop-ryzowy-100-700g-cjo-essential'::text,
    '2026-07-08T12:12:07.937230+00:00'::timestamptz,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    '{"fat":0,"salt":0,"carbs":79.2,"sugar":55.8,"protein":0.9,"calories":320,"servingSize":"w 100g/100ml"}'::jsonb,
    '{"fat":0,"salt":0,"carbs":79.2,"sugar":55.8,"protein":0.9,"calories":320,"servingSize":"w 100g/100ml"}'::jsonb,
    'Korea Południowa'::text,
    'Korea Południowa'::text,
    'Skrobia ryżowa 100%'::text,
    'Skrobia ryżowa 100%'::text,
    '32.71'::numeric,
    'KG'::text,
    '691e2a51-4453-4fd9-bd02-f9abdf9a0def'::uuid,
    'Sosy, marynaty'::text,
    'sosy-marynaty'::text,
    ARRAY['storageZone'::text]::text[]
  ),
  (
    'ADG-000255'::text,
    '369bef7e-2187-4b02-b56b-e112ad3b6c11'::uuid,
    'bff19bcf-a0e9-4fe9-a6d3-27e05aa52671'::uuid,
    'Zaprawa do ryżu 500ml - Miyata'::text,
    'zaprawa-do-ryzu-500ml-miyata'::text,
    '2026-07-08T12:12:07.937230+00:00'::timestamptz,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    '{"fat":1,"salt":6.2,"carbs":37,"sugar":36,"protein":0.5,"calories":147,"servingSize":"w 100g/100ml","saturatedFat":0.1}'::jsonb,
    '{"fat":1,"salt":6.2,"carbs":37,"sugar":36,"protein":0.5,"calories":147,"servingSize":"w 100g/100ml","saturatedFat":0.1}'::jsonb,
    'Chiny'::text,
    'Chiny'::text,
    'Ocet 55%, cukier, sól'::text,
    'Ocet 55%, cukier, sól'::text,
    '39.20'::numeric,
    'LITER'::text,
    '5b5e9a99-a4c6-4d2a-b542-cc678f688de9'::uuid,
    'Octy i winne przyprawy'::text,
    'octy-i-winne-przyprawy'::text,
    ARRAY['storageZone'::text]::text[]
  ),
  (
    'ADG-000154'::text,
    'ce3e9adb-083c-4b07-b5b2-2bcda8671cb5'::uuid,
    '9dcca02b-1692-4fa5-92e0-a4a5a98830b2'::uuid,
    'Ryż do sushi Calrose Kimpo 4,5kg'::text,
    'ryz-do-sushi-calrose-kimpo-4-5kg'::text,
    '2026-07-08T12:12:07.937230+00:00'::timestamptz,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    NULL::jsonb,
    NULL::jsonb,
    NULL::text,
    'USA'::text,
    '100% ziaren ryżu Calrose'::text,
    '100% ziaren ryżu Calrose'::text,
    '18.20'::numeric,
    'KG'::text,
    '62db9128-0d76-4643-87fb-e9c5e875e9cf'::uuid,
    'Ryż i inne ziarna'::text,
    'ryż-i-inne-ziarna'::text,
    ARRAY['storageZone'::text, 'countryOfOrigin'::text]::text[]
  ),
  (
    'ADG-000174'::text,
    'acbbe570-b0a7-4021-9531-7beea26e4764'::uuid,
    '59d88dba-1a95-4d6e-bc3f-67083406157e'::uuid,
    'Makaron ryżowy czerwony Hiep Long 500g'::text,
    'makaron-ryzowy-czerwony-hiep-long-500g'::text,
    '2026-07-08T12:12:07.937230+00:00'::timestamptz,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    NULL::jsonb,
    '{"calories":350,"fat":0.01,"saturatedFat":0,"carbs":78,"protein":5,"servingSize":"100g"}'::jsonb,
    'Wietnam'::text,
    'Wietnam'::text,
    'Ryż, woda, sól'::text,
    'Ryż, woda, sól'::text,
    '23.98'::numeric,
    'KG'::text,
    'f331b4dd-5539-4137-8320-e14795d23f5f'::uuid,
    'Makaron ryżowy'::text,
    'makaron-ryżowy'::text,
    ARRAY['storageZone'::text, 'nutritionFacts'::text]::text[]
  ),
  (
    'ADG-000301'::text,
    '8a55515a-bece-45f7-80b7-376097b6c012'::uuid,
    'e43114f5-64f1-4089-b77c-fc41966844f0'::uuid,
    'Makaron z brązowego ryżu Vermicelli, nitki 200g - MAMA'::text,
    'makaron-z-brazowego-ryzu-vermicelli-nitki-200g-mama'::text,
    '2026-07-08T12:12:07.937230+00:00'::timestamptz,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    NULL::jsonb,
    '{"calories":350,"fat":1.5,"saturatedFat":0.5,"carbs":72,"sugar":0,"protein":8.8,"salt":0.08,"servingSize":"100g"}'::jsonb,
    'Tajlandia'::text,
    'Tajlandia'::text,
    'Ryż pełnoziarnisty (brązowy) 60%, ryż 20%, otręby ryżowe 15%, skrobia z tapioki 5%'::text,
    'Ryż pełnoziarnisty (brązowy) 60%, ryż 20%, otręby ryżowe 15%, skrobia z tapioki 5%'::text,
    '49.95'::numeric,
    'KG'::text,
    'f331b4dd-5539-4137-8320-e14795d23f5f'::uuid,
    'Makaron ryżowy'::text,
    'makaron-ryżowy'::text,
    ARRAY['storageZone'::text, 'nutritionFacts'::text]::text[]
  ),
  (
    'ADG-000405'::text,
    'ed06e3fe-ff8a-4b32-ac90-b9de823754fa'::uuid,
    '8c6aec81-4ba7-496a-957d-09f2b00aa250'::uuid,
    'Jjajang Men, makaron z sosem z czarnej fasoli, łagodny 200g - Paldo'::text,
    'jjajang-men-makaron-z-sosem-z-czarnej-fasoli-lagodny-200g-paldo'::text,
    '2026-07-08T12:12:07.937230+00:00'::timestamptz,
    '[]'::jsonb,
    '["cereals","soybeans"]'::jsonb,
    '[]'::jsonb,
    '["fish","crustaceans","molluscs","milk","eggs","nuts","peanuts","celery","mustard","sesame","sulphites"]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    NULL::jsonb,
    '{"calories":286,"fat":10,"saturatedFat":2.7,"carbs":44,"sugar":4,"protein":6.6,"salt":2.04,"servingSize":"100g"}'::jsonb,
    'Korea Południowa'::text,
    'Korea Południowa'::text,
    'strong>Makaron: mąka pszenna, olej palmowy, modyfikowana skrobia ziemniaczana, sól, olej emulgowany (pestki słonecznika, lecytyna sojowa), regulatory kwasowości: E501, E500, E339, ekstrakt z cebuli, zagęszczacz: E412, skrobia ziemniaczana, olej rzepakowy Sos: cebula, woda, sos z czarnej fasoli (pszenica, soja, sól), olej rzepakowy, kapusta, ziemniaki, cukier, sos sojowy w proszku (soja, pszenica, sól), białko sojowe, skrobia ziemniaczana, sól, ekstrakt z imbiru, wzmacniacz smaku: E635, regulator kwasowości: E500'::text,
    'Makaron: mąka pszenna, olej palmowy, modyfikowana skrobia ziemniaczana, sól, olej emulgowany (pestki słonecznika, lecytyna sojowa), regulatory kwasowości: E501, E500, E339, ekstrakt z cebuli, zagęszczacz: E412, skrobia ziemniaczana, olej rzepakowy. Sos: cebula, woda, sos z czarnej fasoli (pszenica, soja, sól), olej rzepakowy, kapusta, ziemniaki, cukier, sos sojowy w proszku (soja, pszenica, sól), białko sojowe, skrobia ziemniaczana, sól, ekstrakt z imbiru, wzmacniacz smaku: E635, regulator kwasowości: E500'::text,
    '39.95'::numeric,
    'KG'::text,
    '7da30509-aad0-475e-ab39-ca7764bffda2'::uuid,
    'Ramyun / Ramen'::text,
    'ramyun-ramen'::text,
    ARRAY['allergens'::text, 'mayContainAllergens'::text, 'storageZone'::text, 'nutritionFacts'::text, 'ingredients'::text]::text[]
  ),
  (
    'ADG-001154'::text,
    '8cc82ac5-1ffb-4fe4-8ac6-ddfe6bfd8ce4'::uuid,
    '29994e05-9254-43c7-8737-226ce77a45cf'::uuid,
    'Ramen Kumamoto Mokkosu o smaku tonkotsu 104g - Itsuki'::text,
    'ramen-kumamoto-mokkosu-o-smaku-tonkotsu-104g-itsuki'::text,
    '2026-07-08T12:12:07.937230+00:00'::timestamptz,
    '[]'::jsonb,
    '["cereals","soybeans","sesame"]'::jsonb,
    '[]'::jsonb,
    '["milk","eggs","fish","crustaceans"]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    NULL::jsonb,
    NULL::jsonb,
    'Japonia'::text,
    'Japonia'::text,
    'Makaron: mąka pszenna , sól, węglan sodu. Zupa: hydrolizowane białko (kukurydziane, pszenne , sojowe ), sól, cebula w proszku, sproszkowane mleko sojowe , cukier, ekstrakt drożdży, sos sojowy w proszku (odtłuszczona soja , pszenica , sól, soja , dekstryna), sproszkowany olej palmowy (dekstryna, sól sodowa oktenylobursztynianu skrobiowego), glutaminian sodu, czosnek w proszku, zielona cebulka w proszku, miso w proszku ( soja , ryż, sól), imbir w proszku, przyprawy, rybonukleotydy disodowe. Olej: aromatyzowany olej palmowy, czosnek, olej sezamowy , ekstrakt z przypraw.'::text,
    'Makaron: mąka pszenna , sól, węglan sodu. Zupa: hydrolizowane białko (kukurydziane, pszenne , sojowe ), sól, cebula w proszku, sproszkowane mleko sojowe , cukier, ekstrakt drożdży, sos sojowy w proszku (odtłuszczona soja , pszenica , sól, soja , dekstryna), sproszkowany olej palmowy (dekstryna, sól sodowa oktenylobursztynianu skrobiowego), glutaminian sodu, czosnek w proszku, zielona cebulka w proszku, miso w proszku ( soja , ryż, sól), imbir w proszku, przyprawy, rybonukleotydy disodowe. Olej: aromatyzowany olej palmowy, czosnek, olej sezamowy , ekstrakt z przypraw.'::text,
    '133.65'::numeric,
    'KG'::text,
    '7da30509-aad0-475e-ab39-ca7764bffda2'::uuid,
    'Ramyun / Ramen'::text,
    'ramyun-ramen'::text,
    ARRAY['allergens'::text, 'mayContainAllergens'::text, 'storageZone'::text]::text[]
  ),
  (
    'ADG-001210'::text,
    '9f872603-dec3-447e-9c8f-c6704f3a50a6'::uuid,
    '0ab7f872-b3cb-49e6-9378-99727467f28a'::uuid,
    'Ryż Basmati Everyday 1kg - India Gate'::text,
    'ryz-basmati-everyday-1kg-india-gate'::text,
    '2026-07-08T12:12:07.937230+00:00'::timestamptz,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    NULL::jsonb,
    NULL::jsonb,
    'Indie'::text,
    'Indie'::text,
    '100% ryż basmati'::text,
    '100% ryż basmati'::text,
    '18.20'::numeric,
    'KG'::text,
    '62db9128-0d76-4643-87fb-e9c5e875e9cf'::uuid,
    'Ryż i inne ziarna'::text,
    'ryż-i-inne-ziarna'::text,
    ARRAY['storageZone'::text]::text[]
  ),
  (
    'ADG-001374'::text,
    'cbdef7c1-deaf-493a-a97e-8e9b8c314377'::uuid,
    '6a7c343b-ff4a-4be2-86c4-58bb66eb8875'::uuid,
    'Danie makaronowe Bodle Bodle Stir-fry Cheese Ramen o smaku serowym, lekko pikantne 120g - Ottogi'::text,
    'danie-makaronowe-bodle-bodle-stir-fry-cheese-ramen-o-smaku-serowym-lekko-pikantne-120g-ottogi'::text,
    '2026-07-08T12:12:07.937230+00:00'::timestamptz,
    '[]'::jsonb,
    '["cereals","soybeans","milk"]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    NULL::jsonb,
    NULL::jsonb,
    'Korea Południowa'::text,
    'Korea Południowa'::text,
    'Mąka pszenna , modyfikowana skrobia z tapioki, olej palmowy, ser ( ser , pszenica , olej palmowy, dekstryna), gluten pszenny , sól, aromat serowy (cukier, glukoza, sól, sztuczne aromaty), cukier, pszenica , zemulgowany olej (oligosacharyd, olej sojowy , tokoferol, lecytyna, mono- i diglicerydy kwasów tłuszczowych), glukoza, przyprawa drożdżowa (sól, dekstryna, ekstrakt drożdżowy), ekstrakt drożdżowy, skrobia ziemniaczana, regulatory kwasowości (węglan sodu, węglan potasu, trójpolifosforan sodu, kwasowy pirofosforan sodu), śmietanka w proszku ( mleko ), glutaminian sodu, sproszkowane warzywa (czosnek, dekstryna, cebula), glicyna, guma ksantanowa, sproszkowana czerwona papryka, pietruszka, ekstrakt drożdżowy, inozynian disodu, guanylan disodowy, ekstrakt chili, kurkuma, ekstrakt z zielonej herbaty, ryboflawina.'::text,
    'Mąka pszenna , modyfikowana skrobia z tapioki, olej palmowy, ser ( ser , pszenica , olej palmowy, dekstryna), gluten pszenny , sól, aromat serowy (cukier, glukoza, sól, sztuczne aromaty), cukier, pszenica , zemulgowany olej (oligosacharyd, olej sojowy , tokoferol, lecytyna, mono- i diglicerydy kwasów tłuszczowych), glukoza, przyprawa drożdżowa (sól, dekstryna, ekstrakt drożdżowy), ekstrakt drożdżowy, skrobia ziemniaczana, regulatory kwasowości (węglan sodu, węglan potasu, trójpolifosforan sodu, kwasowy pirofosforan sodu), śmietanka w proszku ( mleko ), glutaminian sodu, sproszkowane warzywa (czosnek, dekstryna, cebula), glicyna, guma ksantanowa, sproszkowana czerwona papryka, pietruszka, ekstrakt drożdżowy, inozynian disodu, guanylan disodowy, ekstrakt chili, kurkuma, ekstrakt z zielonej herbaty, ryboflawina.'::text,
    '67.50'::numeric,
    'KG'::text,
    '7da30509-aad0-475e-ab39-ca7764bffda2'::uuid,
    'Ramyun / Ramen'::text,
    'ramyun-ramen'::text,
    ARRAY['allergens'::text, 'storageZone'::text]::text[]
  ),
  (
    'ADG-000047'::text,
    '6a1f47f9-7b57-4832-9795-3dd3e442a21b'::uuid,
    '5104733a-fc84-4a97-9874-5b109e15dcfb'::uuid,
    'Makaron ryżowy 3mm 400g Farmer'::text,
    'makaron-ryzowy-3mm-400g-farmer'::text,
    '2026-07-08T12:12:07.937230+00:00'::timestamptz,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    '{"fat":0.8,"carbs":80.3,"sugar":0,"protein":7,"calories":356,"servingSize":"w 100g/100ml","saturatedFat":0.3}'::jsonb,
    '{"fat":0.8,"carbs":80.3,"sugar":0,"protein":7,"calories":356,"servingSize":"w 100g/100ml","saturatedFat":0.3}'::jsonb,
    'Tajlandia'::text,
    'Tajlandia'::text,
    'Mąka ryżowa 90%, woda'::text,
    'Mąka ryżowa 90%, woda'::text,
    '22.47'::numeric,
    'KG'::text,
    'f331b4dd-5539-4137-8320-e14795d23f5f'::uuid,
    'Makaron ryżowy'::text,
    'makaron-ryżowy'::text,
    ARRAY['storageZone'::text]::text[]
  ),
  (
    'ADG-000048'::text,
    'd7a3e40d-8c0b-4fa2-87b4-eda855f18c80'::uuid,
    'd91b353e-cb5b-46c2-8ae5-5ddc34df5dfe'::uuid,
    'Makaron ryżowy 5mm 400g Farmer'::text,
    'makaron-ryzowy-5mm-400g-farmer'::text,
    '2026-07-08T12:12:07.937230+00:00'::timestamptz,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    '{"fat":0.8,"salt":0.01,"carbs":80,"sugar":0,"protein":7,"calories":356,"servingSize":"w 100g/100ml","saturatedFat":0.3}'::jsonb,
    '{"fat":0.8,"salt":0.01,"carbs":80,"sugar":0,"protein":7,"calories":356,"servingSize":"w 100g/100ml","saturatedFat":0.3}'::jsonb,
    'Tajlandia'::text,
    'Tajlandia'::text,
    'Mąka ryżowa 90%, woda'::text,
    'Mąka ryżowa 90%, woda'::text,
    '22.47'::numeric,
    'KG'::text,
    'f331b4dd-5539-4137-8320-e14795d23f5f'::uuid,
    'Makaron ryżowy'::text,
    'makaron-ryżowy'::text,
    ARRAY['storageZone'::text]::text[]
  ),
  (
    'ADG-000059'::text,
    '7884aa86-036b-4036-994a-b1c040deba29'::uuid,
    '21949b47-1ab3-46d9-9293-b7290bcda8a0'::uuid,
    'Ryż do sushi Kimpo Calrose 9,07 kg'::text,
    'ryz-do-sushi-kimpo-calrose-9-07-kg'::text,
    '2026-07-08T12:12:07.937230+00:00'::timestamptz,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    'AMBIENT'::text,
    'AMBIENT'::text,
    '{"fat":0.5,"salt":0.06,"carbs":78.5,"sugar":0.3,"protein":7.7,"calories":349,"servingSize":"w 100g/100ml","saturatedFat":0.22}'::jsonb,
    '{"fat":0.5,"salt":0.06,"carbs":78.5,"sugar":0.3,"protein":7.7,"calories":349,"servingSize":"w 100g/100ml","saturatedFat":0.22}'::jsonb,
    NULL::text,
    'USA'::text,
    '100% ziaren ryżu'::text,
    '100% ziaren ryżu'::text,
    '13.78'::numeric,
    'KG'::text,
    '62db9128-0d76-4643-87fb-e9c5e875e9cf'::uuid,
    'Ryż i inne ziarna'::text,
    'ryż-i-inne-ziarna'::text,
    ARRAY['countryOfOrigin'::text]::text[]
  );

DO $$
DECLARE affected integer;
BEGIN
  IF (SELECT COUNT(*) FROM _adg_metadata_target_salon) <> 1 THEN
    RAISE EXCEPTION 'Expected exactly one active pinned asiandeligo channel';
  END IF;
  IF to_regclass('public.asiandeligo_catalog_metadata_batch2_product_backup_20260722') IS NULL
     OR to_regclass('public.asiandeligo_catalog_metadata_batch2_audit_20260722') IS NULL THEN
    RAISE EXCEPTION 'Required batch backup/audit table is missing';
  END IF;
  IF (
    SELECT COUNT(*)
    FROM public.asiandeligo_catalog_metadata_batch2_product_backup_20260722
    WHERE batch_key = 'asiandeligo-catalog-metadata-batch2-20260722-v1'
      AND decision_sha256 = '792e0c4277c96bc5a49edcd988b268ea178c0d93176ddfd5d3dd770fe2922732'
      AND salon_id = 'e73271a9-53e3-4a20-a02e-791726b452aa'::uuid
  ) <> 24 THEN
    RAISE EXCEPTION 'Expected exactly 24 tenant- and decision-scoped backup rows';
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM public.asiandeligo_catalog_metadata_batch2_audit_20260722
    WHERE batch_key = 'asiandeligo-catalog-metadata-batch2-20260722-v1'
      AND decision_sha256 = '792e0c4277c96bc5a49edcd988b268ea178c0d93176ddfd5d3dd770fe2922732'
      AND salon_id = 'e73271a9-53e3-4a20-a02e-791726b452aa'::uuid
      AND action = 'backup_captured'
      AND product_rows = 24
  ) OR NOT EXISTS (
    SELECT 1 FROM public.asiandeligo_catalog_metadata_batch2_audit_20260722
    WHERE batch_key = 'asiandeligo-catalog-metadata-batch2-20260722-v1'
      AND decision_sha256 = '792e0c4277c96bc5a49edcd988b268ea178c0d93176ddfd5d3dd770fe2922732'
      AND salon_id = 'e73271a9-53e3-4a20-a02e-791726b452aa'::uuid
      AND action = 'apply_complete'
      AND product_rows = 24
  ) OR EXISTS (
    SELECT 1 FROM public.asiandeligo_catalog_metadata_batch2_audit_20260722
    WHERE batch_key = 'asiandeligo-catalog-metadata-batch2-20260722-v1'
      AND decision_sha256 = '792e0c4277c96bc5a49edcd988b268ea178c0d93176ddfd5d3dd770fe2922732'
      AND salon_id = 'e73271a9-53e3-4a20-a02e-791726b452aa'::uuid
      AND action = 'rollback_complete'
  ) THEN
    RAISE EXCEPTION 'Required apply audit chain is incomplete or rollback already completed';
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_catalog.pg_trigger
    WHERE tgrelid = 'public.products'::regclass
      AND tgname = 'zz_enforce_products_monotonic_updated_at'
      AND NOT tgisinternal
      AND tgenabled <> 'D'
  ) OR EXISTS (
    SELECT 1
    FROM _adg_metadata_decisions decision
    CROSS JOIN _adg_metadata_target_salon tenant
    LEFT JOIN public.asiandeligo_catalog_metadata_batch2_product_backup_20260722 backup
      ON backup.batch_key = 'asiandeligo-catalog-metadata-batch2-20260722-v1'
     AND backup.decision_sha256 = '792e0c4277c96bc5a49edcd988b268ea178c0d93176ddfd5d3dd770fe2922732'
     AND backup.salon_id = tenant.salon_id
     AND backup.sku = decision.sku
     AND backup.product_id = decision.product_id
    AND backup.variant_id = decision.variant_id
    AND backup.category_id = decision.category_id
    AND backup.changed_fields = decision.changed_fields
    AND backup.original_updated_at = decision.expected_updated_at
    AND backup.applied_updated_at IS NOT NULL
    AND backup.applied_updated_at > backup.original_updated_at
    AND backup.allergens IS NOT DISTINCT FROM decision.expected_allergens
    AND backup.may_contain_allergens IS NOT DISTINCT FROM decision.expected_may_contain_allergens
    AND backup.storage_zone IS NOT DISTINCT FROM decision.expected_storage_zone
    AND backup.nutrition_facts IS NOT DISTINCT FROM decision.expected_nutrition_facts
    AND backup.country_of_origin IS NOT DISTINCT FROM decision.expected_country_of_origin
    AND backup.ingredients IS NOT DISTINCT FROM decision.expected_ingredients
    AND backup.price_per_unit IS NOT DISTINCT FROM decision.expected_price_per_unit
    AND backup.unit_of_measure IS NOT DISTINCT FROM decision.expected_unit_of_measure
    WHERE backup.sku IS NULL
  ) THEN
    RAISE EXCEPTION 'Required timestamp trigger or exact reviewed backup snapshot is missing';
  END IF;

  PERFORM 1
  FROM _adg_metadata_decisions decision
  CROSS JOIN _adg_metadata_target_salon tenant
  JOIN public.asiandeligo_catalog_metadata_batch2_product_backup_20260722 backup
    ON backup.batch_key = 'asiandeligo-catalog-metadata-batch2-20260722-v1'
   AND backup.decision_sha256 = '792e0c4277c96bc5a49edcd988b268ea178c0d93176ddfd5d3dd770fe2922732'
   AND backup.salon_id = tenant.salon_id
   AND backup.sku = decision.sku
   AND backup.product_id = decision.product_id
    AND backup.variant_id = decision.variant_id
    AND backup.category_id = decision.category_id
    AND backup.changed_fields = decision.changed_fields
    AND backup.original_updated_at = decision.expected_updated_at
    AND backup.applied_updated_at IS NOT NULL
    AND backup.applied_updated_at > backup.original_updated_at
    AND backup.allergens IS NOT DISTINCT FROM decision.expected_allergens
    AND backup.may_contain_allergens IS NOT DISTINCT FROM decision.expected_may_contain_allergens
    AND backup.storage_zone IS NOT DISTINCT FROM decision.expected_storage_zone
    AND backup.nutrition_facts IS NOT DISTINCT FROM decision.expected_nutrition_facts
    AND backup.country_of_origin IS NOT DISTINCT FROM decision.expected_country_of_origin
    AND backup.ingredients IS NOT DISTINCT FROM decision.expected_ingredients
    AND backup.price_per_unit IS NOT DISTINCT FROM decision.expected_price_per_unit
    AND backup.unit_of_measure IS NOT DISTINCT FROM decision.expected_unit_of_measure
  JOIN public.product_variants variant
    ON variant.id = decision.variant_id
    AND variant.sku = decision.sku
    AND variant.salon_id = tenant.salon_id
   AND variant.is_active = TRUE
   AND variant.is_published = FALSE
   AND variant.is_for_sale = TRUE
   AND variant.sync_status = 'synced'
   AND variant.availability_status = 'IN_STOCK'
    AND variant.deleted_at IS NULL
  JOIN public.products product
    ON product.id = decision.product_id
    AND product.id = variant.template_id
    AND product.salon_id = tenant.salon_id
   AND product.name = decision.expected_name
   AND product.slug = decision.expected_slug
    AND product.updated_at = backup.applied_updated_at
   AND product.is_active = TRUE
   AND product.is_published = TRUE
   AND product.is_visible = TRUE
   AND product.status = 'active'
    AND product.deleted_at IS NULL
  JOIN public.categories category
    ON category.id = decision.category_id
   AND category.id = product.category_id
   AND category.salon_id = tenant.salon_id
   AND category.name = decision.category_name
   AND category.slug = decision.category_slug
   AND category.is_active = TRUE
  WHERE product.allergens IS NOT DISTINCT FROM decision.target_allergens
    AND product.may_contain_allergens IS NOT DISTINCT FROM decision.target_may_contain_allergens
    AND product.storage_zone IS NOT DISTINCT FROM decision.target_storage_zone
    AND product.nutrition_facts IS NOT DISTINCT FROM decision.target_nutrition_facts
    AND product.country_of_origin IS NOT DISTINCT FROM decision.target_country_of_origin
    AND product.ingredients IS NOT DISTINCT FROM decision.target_ingredients
    AND product.price_per_unit IS NOT DISTINCT FROM decision.expected_price_per_unit
    AND product.unit_of_measure IS NOT DISTINCT FROM decision.expected_unit_of_measure
  ORDER BY product.id
  FOR UPDATE OF product, variant, category;
  GET DIAGNOSTICS affected = ROW_COUNT;
  IF affected <> 24 THEN
    RAISE EXCEPTION 'Expected 24 exact target row locks; refusing to overwrite intervening edits';
  END IF;
END $$;

DO $$
DECLARE affected integer;
BEGIN
  UPDATE public.products product
  SET allergens = backup.allergens,
      may_contain_allergens = backup.may_contain_allergens,
      storage_zone = backup.storage_zone,
      nutrition_facts = backup.nutrition_facts,
      country_of_origin = backup.country_of_origin,
      ingredients = backup.ingredients
  FROM _adg_metadata_decisions decision,
       _adg_metadata_target_salon tenant,
       public.asiandeligo_catalog_metadata_batch2_product_backup_20260722 backup
  WHERE backup.batch_key = 'asiandeligo-catalog-metadata-batch2-20260722-v1'
    AND backup.decision_sha256 = '792e0c4277c96bc5a49edcd988b268ea178c0d93176ddfd5d3dd770fe2922732'
    AND backup.salon_id = tenant.salon_id
    AND backup.sku = decision.sku
    AND backup.product_id = product.id
    AND product.salon_id = tenant.salon_id
    AND product.name = decision.expected_name
    AND product.slug = decision.expected_slug
    AND product.updated_at = backup.applied_updated_at
    AND product.is_active = TRUE
    AND product.is_published = TRUE
    AND product.is_visible = TRUE
    AND product.status = 'active'
    AND product.deleted_at IS NULL
    AND backup.product_id = decision.product_id
    AND backup.variant_id = decision.variant_id
    AND backup.category_id = decision.category_id
    AND backup.changed_fields = decision.changed_fields
    AND backup.original_updated_at = decision.expected_updated_at
    AND backup.applied_updated_at IS NOT NULL
    AND backup.applied_updated_at > backup.original_updated_at
    AND backup.allergens IS NOT DISTINCT FROM decision.expected_allergens
    AND backup.may_contain_allergens IS NOT DISTINCT FROM decision.expected_may_contain_allergens
    AND backup.storage_zone IS NOT DISTINCT FROM decision.expected_storage_zone
    AND backup.nutrition_facts IS NOT DISTINCT FROM decision.expected_nutrition_facts
    AND backup.country_of_origin IS NOT DISTINCT FROM decision.expected_country_of_origin
    AND backup.ingredients IS NOT DISTINCT FROM decision.expected_ingredients
    AND backup.price_per_unit IS NOT DISTINCT FROM decision.expected_price_per_unit
    AND backup.unit_of_measure IS NOT DISTINCT FROM decision.expected_unit_of_measure
    AND product.allergens IS NOT DISTINCT FROM decision.target_allergens
    AND product.may_contain_allergens IS NOT DISTINCT FROM decision.target_may_contain_allergens
    AND product.storage_zone IS NOT DISTINCT FROM decision.target_storage_zone
    AND product.nutrition_facts IS NOT DISTINCT FROM decision.target_nutrition_facts
    AND product.country_of_origin IS NOT DISTINCT FROM decision.target_country_of_origin
    AND product.ingredients IS NOT DISTINCT FROM decision.target_ingredients
    AND product.price_per_unit IS NOT DISTINCT FROM decision.expected_price_per_unit
    AND product.unit_of_measure IS NOT DISTINCT FROM decision.expected_unit_of_measure;
  GET DIAGNOSTICS affected = ROW_COUNT;
  IF affected <> 24 THEN
    RAISE EXCEPTION 'Expected 24 exact product restorations, got %', affected;
  END IF;

  IF (
    SELECT COUNT(*)
    FROM public.products product
    JOIN public.asiandeligo_catalog_metadata_batch2_product_backup_20260722 backup
      ON backup.product_id = product.id
     AND backup.batch_key = 'asiandeligo-catalog-metadata-batch2-20260722-v1'
     AND backup.decision_sha256 = '792e0c4277c96bc5a49edcd988b268ea178c0d93176ddfd5d3dd770fe2922732'
     AND backup.salon_id = product.salon_id
    WHERE product.salon_id = 'e73271a9-53e3-4a20-a02e-791726b452aa'::uuid
      AND product.updated_at > backup.applied_updated_at
      AND product.allergens IS NOT DISTINCT FROM backup.allergens
      AND product.may_contain_allergens IS NOT DISTINCT FROM backup.may_contain_allergens
      AND product.storage_zone IS NOT DISTINCT FROM backup.storage_zone
      AND product.nutrition_facts IS NOT DISTINCT FROM backup.nutrition_facts
      AND product.country_of_origin IS NOT DISTINCT FROM backup.country_of_origin
      AND product.ingredients IS NOT DISTINCT FROM backup.ingredients
      AND product.price_per_unit IS NOT DISTINCT FROM backup.price_per_unit
      AND product.unit_of_measure IS NOT DISTINCT FROM backup.unit_of_measure
  ) <> 24 THEN
    RAISE EXCEPTION 'Rollback post-state verification failed';
  END IF;

  INSERT INTO public.asiandeligo_catalog_metadata_batch2_audit_20260722 (
    batch_key, decision_sha256, channel_slug, salon_id, action, product_rows
  )
  SELECT 'asiandeligo-catalog-metadata-batch2-20260722-v1', '792e0c4277c96bc5a49edcd988b268ea178c0d93176ddfd5d3dd770fe2922732', channel_slug, salon_id,
         'rollback_complete', 24
  FROM _adg_metadata_target_salon;
END $$;

SELECT backup.sku, backup.changed_fields, audit.recorded_at, audit.transaction_id
FROM public.asiandeligo_catalog_metadata_batch2_product_backup_20260722 backup
JOIN public.asiandeligo_catalog_metadata_batch2_audit_20260722 audit
  ON audit.batch_key = backup.batch_key
 AND audit.salon_id = backup.salon_id
 AND audit.action = 'rollback_complete'
WHERE backup.batch_key = 'asiandeligo-catalog-metadata-batch2-20260722-v1'
  AND backup.decision_sha256 = '792e0c4277c96bc5a49edcd988b268ea178c0d93176ddfd5d3dd770fe2922732'
  AND backup.salon_id = 'e73271a9-53e3-4a20-a02e-791726b452aa'::uuid
ORDER BY backup.sku;

COMMIT;
