\set ON_ERROR_STOP on
-- Generated by scripts/catalog-metadata-batch6-plan.mjs
-- Purpose: roll back the reviewed Asia Deli Go metadata batch.
-- Decision SHA-256: 19d2a71766d82e9ac4089b60472959412bd49b772820b75521260ae112e7844f
--
-- JOIN contract (schema-introspect verified on production 2026-07-22):
--   product_variants.template_id (uuid) = products.id (uuid) — FK declared; sampled match OK.
--   products.category_id (uuid) = categories.id (uuid) — FK declared; sampled match OK.
--   channels.salon_id = products/product_variants/categories.salon_id (uuid) — tenant pinned on every table.
-- Status values: products.status=active; variant sync_status=synced and availability_status=IN_STOCK.
-- Soft-delete policy: products and variants require deleted_at IS NULL; category/channel require active.
-- Canonical tables only: products, product_variants, categories, channels; no backup/legacy table is joined.

BEGIN;
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
SET LOCAL search_path = pg_catalog, public;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '120s';

CREATE TEMP TABLE _adg_metadata_target_salon (
  salon_id uuid PRIMARY KEY,
  channel_slug text NOT NULL
) ON COMMIT DROP;

INSERT INTO _adg_metadata_target_salon (salon_id, channel_slug)
SELECT salon_id, slug
FROM public.channels
WHERE salon_id = 'e73271a9-53e3-4a20-a02e-791726b452aa'::uuid
  AND slug = 'asiandeligo'
  AND is_active = TRUE
FOR SHARE;

CREATE TEMP TABLE _adg_metadata_decisions (
  sku text PRIMARY KEY,
  product_id uuid UNIQUE NOT NULL,
  variant_id uuid UNIQUE NOT NULL,
  expected_name text NOT NULL,
  expected_slug text NOT NULL,
  expected_updated_at timestamptz NOT NULL,
  expected_allergens jsonb,
  target_allergens jsonb,
  expected_may_contain_allergens jsonb,
  target_may_contain_allergens jsonb,
  expected_storage_zone text,
  target_storage_zone text,
  expected_nutrition_facts jsonb,
  target_nutrition_facts jsonb,
  expected_country_of_origin text,
  target_country_of_origin text,
  expected_ingredients text,
  target_ingredients text,
  expected_price_per_unit numeric,
  expected_unit_of_measure text,
  category_id uuid NOT NULL,
  category_name text NOT NULL,
  category_slug text NOT NULL,
  changed_fields text[] NOT NULL
) ON COMMIT DROP;

INSERT INTO _adg_metadata_decisions VALUES
  (
    'ADG-000556'::text,
    '96fa6853-7b5d-402e-afec-9412e30310fd'::uuid,
    '63b730be-da32-43da-a45c-f8c7945c7e4b'::uuid,
    'Matcha, sproszkowana zielona herbata w puszce 80g x 2 - Tian Hu Shan'::text,
    'matcha-sproszkowana-zielona-herbata-w-puszce-80g-x-2-tian-hu-shan'::text,
    '2026-07-08 12:12:07.93723+00:00'::timestamptz,
    '["eggs","milk"]'::jsonb,
    '["eggs","milk"]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    NULL::jsonb,
    NULL::jsonb,
    'Chiny'::text,
    'Chiny'::text,
    '100% naturalna zielona herbata'::text,
    '100% naturalna zielona herbata'::text,
    '424.75'::numeric,
    'KG'::text,
    '94c0da76-0649-45aa-a990-09aa949c8407'::uuid,
    'Herbaty'::text,
    'herbaty'::text,
    ARRAY['storageZone'::text]::text[]
  ),
  (
    'ADG-000859'::text,
    'e7e3bf86-4cda-483e-9d85-177427a39ed0'::uuid,
    '5c3ef4d8-ac32-4436-ac7c-1eecf7bbb99e'::uuid,
    'Sok z limonki 250ml - Golden Turtle'::text,
    'sok-z-limonki-250ml-golden-turtle'::text,
    '2026-07-08 12:12:07.93723+00:00'::timestamptz,
    '[]'::jsonb,
    '["sulphites"]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    'AMBIENT'::text,
    'AMBIENT'::text,
    NULL::jsonb,
    NULL::jsonb,
    'Belgia'::text,
    'Belgia'::text,
    'Sok z limonki z koncentratu soku z limonki, olejek z limonki, substancja konserwująca: pirosiarczyn potasu (E224)'::text,
    'Sok z limonki z koncentratu soku z limonki, olejek z limonki, substancja konserwująca: pirosiarczyn potasu (E224)'::text,
    '30.00'::numeric,
    'LITER'::text,
    '6682de83-41a7-4294-86f4-05ede2ae3bbf'::uuid,
    'Napoje'::text,
    'napoje'::text,
    ARRAY['allergens'::text]::text[]
  ),
  (
    'ADG-000526'::text,
    '1822ef89-da85-4fa5-bc38-5242c10d3a37'::uuid,
    '130530c8-30d9-44d9-96a3-071c03a68613'::uuid,
    'Mielonka wieprzowa Luncheon Meat 340g - Chung Jung One'::text,
    'mielonka-wieprzowa-luncheon-meat-340g-chung-jung-one'::text,
    '2026-07-08 12:12:07.93723+00:00'::timestamptz,
    '[]'::jsonb,
    '[]'::jsonb,
    '["milk"]'::jsonb,
    '["milk"]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    '{"fat":27,"salt":2.5,"carbs":0,"sugar":0,"protein":14,"calories":299,"servingSize":"w 100g/100ml","saturatedFat":10}'::jsonb,
    '{"fat":27,"salt":2.5,"carbs":0,"sugar":0,"protein":14,"calories":299,"servingSize":"w 100g/100ml","saturatedFat":10}'::jsonb,
    NULL::text,
    'Dania'::text,
    'Wieprzowina 93%, woda, sól, cukier, stabilizator: trifosforany (E451); wzmacniacz smaku: glutaminian sodu (E621); cebula w proszku, ekstrakty przypraw, przeciwutleniacz: askorbinian sodu (E301), substancja konserwująca: azotyn sodu (E250)'::text,
    'Wieprzowina 93%, woda, sól, cukier, stabilizator: trifosforany (E451); wzmacniacz smaku: glutaminian sodu (E621); cebula w proszku, ekstrakty przypraw, przeciwutleniacz: askorbinian sodu (E301), substancja konserwująca: azotyn sodu (E250)'::text,
    '80.00'::numeric,
    'KG'::text,
    '43098ab7-106a-47f1-b91b-aa497c1c62db'::uuid,
    'Dania gotowe'::text,
    'dania-gotowe'::text,
    ARRAY['storageZone'::text, 'countryOfOrigin'::text]::text[]
  ),
  (
    'ADG-000655'::text,
    '4da56e11-a287-4c6b-83ea-2a7fb945c29b'::uuid,
    '639faae3-3ce9-4cc8-8c33-254b0273b7db'::uuid,
    'Garlic Tteokbokki, kluski ryżowe w sosie czosnkowo-paprykowym 260g - O''Food'::text,
    'garlic-tteokbokki-kluski-ryzowe-w-sosie-czosnkowo-paprykowym-260g-o-food'::text,
    '2026-07-08 12:12:07.93723+00:00'::timestamptz,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    '{"fat":2,"carbs":67,"sugar":12,"protein":5,"calories":300,"servingSize":"w porcji 130g"}'::jsonb,
    '{"fat":2,"carbs":67,"sugar":12,"protein":5,"calories":300,"servingSize":"w porcji 130g"}'::jsonb,
    'Korea Południowa'::text,
    'Korea Południowa'::text,
    'Kluski ryżowe: ryż, woda, sól, zagęstnik: kwas cytrynowy (E330); alkohol Sos: cukier, woda, czerwona papryka w proszku, sól, cebula, ekstrakt drożdżowy, mniej niż 2%: alkohol etylowy (dla zachowania świeżości), wzmacniacze smaku: guanylan disodowy (E627), inozynian disodowy (E631); zagęstniki: kwas cytrynowy (E330), guma ksantanowa (E415); sztuczny aromat, barwnik: papryka'::text,
    'Kluski ryżowe: ryż, woda, sól, zagęstnik: kwas cytrynowy (E330); alkohol Sos: cukier, woda, czerwona papryka w proszku, sól, cebula, ekstrakt drożdżowy, mniej niż 2%: alkohol etylowy (dla zachowania świeżości), wzmacniacze smaku: guanylan disodowy (E627), inozynian disodowy (E631); zagęstniki: kwas cytrynowy (E330), guma ksantanowa (E415); sztuczny aromat, barwnik: papryka'::text,
    '96.12'::numeric,
    'KG'::text,
    '43098ab7-106a-47f1-b91b-aa497c1c62db'::uuid,
    'Dania gotowe'::text,
    'dania-gotowe'::text,
    ARRAY['storageZone'::text]::text[]
  ),
  (
    'ADG-000656'::text,
    'a4e3169b-f42b-4b33-ab7e-c0a3cbc43494'::uuid,
    '08d5a086-7cd5-4b81-8cad-38c15afb5812'::uuid,
    'Original Tteokbokki, kluski ryżowe w sosie gochujang 260g - O''Food'::text,
    'original-tteokbokki-kluski-ryzowe-w-sosie-gochujang-260g-o-food'::text,
    '2026-07-08 12:12:07.93723+00:00'::timestamptz,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    '{"fat":2,"carbs":67,"sugar":12,"protein":5,"calories":310,"servingSize":"w porcji 130g"}'::jsonb,
    '{"fat":2,"carbs":67,"sugar":12,"protein":5,"calories":310,"servingSize":"w porcji 130g"}'::jsonb,
    'Korea Południowa'::text,
    'Korea Południowa'::text,
    'Kluski ryżowe: ryż, woda, sól, zagęstnik: kwas cytrynowy (E330); alkohol Sos: cukier, pasta z czerwonej papryki (woda, syrop z tapioki, ryż brązowy, czerwona papryka w proszku, sól, alkohol , czosnek, cebula), woda, cebula, sól, mniej niż 2%: ekstrakt z drożdży, alkohol etylowy (dla zachowania świeżości), czosnek, wzmacniacze smaku: guanylan disodowy (E627), inozynian disodowy (E631); barwnik: papryka; sztuczny aromat, zagęstnik: guma ksantanowa (E415); czarny pieprz w proszku'::text,
    'Kluski ryżowe: ryż, woda, sól, zagęstnik: kwas cytrynowy (E330); alkohol Sos: cukier, pasta z czerwonej papryki (woda, syrop z tapioki, ryż brązowy, czerwona papryka w proszku, sól, alkohol , czosnek, cebula), woda, cebula, sól, mniej niż 2%: ekstrakt z drożdży, alkohol etylowy (dla zachowania świeżości), czosnek, wzmacniacze smaku: guanylan disodowy (E627), inozynian disodowy (E631); barwnik: papryka; sztuczny aromat, zagęstnik: guma ksantanowa (E415); czarny pieprz w proszku'::text,
    '99.96'::numeric,
    'KG'::text,
    '43098ab7-106a-47f1-b91b-aa497c1c62db'::uuid,
    'Dania gotowe'::text,
    'dania-gotowe'::text,
    ARRAY['storageZone'::text]::text[]
  ),
  (
    'ADG-000901'::text,
    'd2274c7c-6ad5-484f-8256-b66c5d771c66'::uuid,
    '784dd0ab-4b3f-4575-89b1-7862fa49ea05'::uuid,
    'Danie instant Tteokbokki, kluski ryżowe w pikantnym sosie 160g - Sempio'::text,
    'danie-instant-tteokbokki-kluski-ryzowe-w-pikantnym-sosie-160g-sempio'::text,
    '2026-07-08 12:12:07.93723+00:00'::timestamptz,
    '["cereals","soybeans"]'::jsonb,
    '["cereals","soybeans"]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    '{"fat":0.6,"salt":1.5,"carbs":50.8,"sugar":8.2,"protein":3.9,"calories":227,"servingSize":"w 100g/100ml","saturatedFat":0.2}'::jsonb,
    '{"fat":0.6,"salt":1.5,"carbs":50.8,"sugar":8.2,"protein":3.9,"calories":227,"servingSize":"w 100g/100ml","saturatedFat":0.2}'::jsonb,
    'Korea Południowa'::text,
    'Korea Południowa'::text,
    'Kluski ryżowe: ryż, alkohol, sól, dekstryna, estry gliceryny kwasów tłuszczowych, modyfikowana skrobia z tapioki, substancja słodząca: E422. Sos: pasta gochujang (syrop kukurydziany, woda, mąka pszenna , czerwona papryka, sproszkowana pszenica , sól, alkohol, hydrolizowane białko pszenicy , soja , koji), syrop kukurydziany o wysokiej zawartości fruktozy, cukier, woda, mieszanka przypraw (czerwona papryka w proszku, woda, czosnek, cebula, sól), przyprawa sojowa (fermentowany peptyd sojowy , gluten pszenny , woda, sól, naturalnie fermentowany koncentrat sosu sojowego , alkohol, ekstrakt z drożdży), sos sojowy (woda, odtłuszczona soja , sól, syrop kukurydziany o wysokiej zawartości fruktozy, alkohol, pszenica , ekstrakt z drożdży w proszku, konserwant: E211; substancja słodząca: E955), sos pomidorowy (woda, pasta pomidorowa, syrop kukurydziany o wysokiej zawartości fruktozy, ocet, sól, cukier, skrobia modyfikowana, przyprawy), alkohol, czosnek, regulator kwasowości: E574, ekstrakt z pszenicy , skrobia modyfikowana, przecier ananasowy, sól, ekstrakt z drożdży w proszku, ekstrakt z cebuli (konserwant: E270, koncentrat cebuli, syrop kukurydziany, ekstrakt cebuli, maltodekstryna, sól, stabilizator: E414, olejek eteryczny z cebuli), oleożywica Capsicum.'::text,
    'Kluski ryżowe: ryż, alkohol, sól, dekstryna, estry gliceryny kwasów tłuszczowych, modyfikowana skrobia z tapioki, substancja słodząca: E422. Sos: pasta gochujang (syrop kukurydziany, woda, mąka pszenna , czerwona papryka, sproszkowana pszenica , sól, alkohol, hydrolizowane białko pszenicy , soja , koji), syrop kukurydziany o wysokiej zawartości fruktozy, cukier, woda, mieszanka przypraw (czerwona papryka w proszku, woda, czosnek, cebula, sól), przyprawa sojowa (fermentowany peptyd sojowy , gluten pszenny , woda, sól, naturalnie fermentowany koncentrat sosu sojowego , alkohol, ekstrakt z drożdży), sos sojowy (woda, odtłuszczona soja , sól, syrop kukurydziany o wysokiej zawartości fruktozy, alkohol, pszenica , ekstrakt z drożdży w proszku, konserwant: E211; substancja słodząca: E955), sos pomidorowy (woda, pasta pomidorowa, syrop kukurydziany o wysokiej zawartości fruktozy, ocet, sól, cukier, skrobia modyfikowana, przyprawy), alkohol, czosnek, regulator kwasowości: E574, ekstrakt z pszenicy , skrobia modyfikowana, przecier ananasowy, sól, ekstrakt z drożdży w proszku, ekstrakt z cebuli (konserwant: E270, koncentrat cebuli, syrop kukurydziany, ekstrakt cebuli, maltodekstryna, sól, stabilizator: E414, olejek eteryczny z cebuli), oleożywica Capsicum.'::text,
    '74.38'::numeric,
    'KG'::text,
    '43098ab7-106a-47f1-b91b-aa497c1c62db'::uuid,
    'Dania gotowe'::text,
    'dania-gotowe'::text,
    ARRAY['storageZone'::text]::text[]
  ),
  (
    'ADG-000902'::text,
    '73f84fcb-c4f7-488c-b7dc-db881e153c46'::uuid,
    '04acd115-395a-44de-9984-3bef9458242f'::uuid,
    'Danie instant Tteokbokki, kluski ryżowe w słodko-pikantnym sosie 160g - Sempio'::text,
    'danie-instant-tteokbokki-kluski-ryzowe-w-slodko-pikantnym-sosie-160g-sempio'::text,
    '2026-07-08 12:12:07.93723+00:00'::timestamptz,
    '["cereals","soybeans"]'::jsonb,
    '["cereals","soybeans"]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    '{"fat":0.6,"salt":1.5,"carbs":50.8,"sugar":8.2,"protein":3.9,"calories":227,"servingSize":"w 100g/100ml","saturatedFat":0.2}'::jsonb,
    '{"fat":0.6,"salt":1.5,"carbs":50.8,"sugar":8.2,"protein":3.9,"calories":227,"servingSize":"w 100g/100ml","saturatedFat":0.2}'::jsonb,
    'Korea Południowa'::text,
    'Korea Południowa'::text,
    'Kluski ryżowe: ryż, mniej niż 2%: alkohol, sól, dekstryna, estry gliceryny i kwasów tłuszczowych, modyfikowana skrobia z tapioki, glicerol. Sos: pasta gochujang(syrop kukurydziany, woda, mąka pszenna , przyprawa z czerwonej papryki, sproszkowana pszenica , sól, alkohol, hydrolizowane białko pszenicy , soja , koji), syrop kukurydziany o wysokiej zawartości fruktozy, cukier, syrop kukurydziany, woda, przyprawa sojowa (fermentowany peptyd sojowy , gluten pszenny , woda, sól, naturalnie fermentowany koncentrat sosu sojowego , alkohol, ekstrakt drożdżowy), sos pomidorowy (woda, koncentrat pomidorowy, syrop kukurydziany o wysokiej zawartości fruktozy, ocet, sól, cukier, skrobia modyfikowana, przyprawa), mieszanka przypraw (czerwona papryka w proszku, (woda, czosnek, cebula, sól), sos sojowy (woda, odtłuszczona soja , sól, syrop kukurydziany o wysokiej zawartości fruktozy, alkohol, pszenica , ekstrakt drożdżowy w proszku, benzoesan sodu, sukraloza), przecier ananasowy, alkohol, skrobia modyfikowana, ekstrakt pszenny , kwas glukonowy, sól, ekstrakt drożdżowy w proszku, ekstrakt z cebuli (mieszanina kwasu mlekowego, koncentrat cebuli, syrop kukurydziany, ekstrakt z cebuli, maltodekstryna, sól, guma arabska, olejek eteryczny z cebuli), olej paprykowy (olej sojowy, oleożywica z papryki, estry gliceryny i kwasów tłuszczowych)'::text,
    'Kluski ryżowe: ryż, mniej niż 2%: alkohol, sól, dekstryna, estry gliceryny i kwasów tłuszczowych, modyfikowana skrobia z tapioki, glicerol. Sos: pasta gochujang(syrop kukurydziany, woda, mąka pszenna , przyprawa z czerwonej papryki, sproszkowana pszenica , sól, alkohol, hydrolizowane białko pszenicy , soja , koji), syrop kukurydziany o wysokiej zawartości fruktozy, cukier, syrop kukurydziany, woda, przyprawa sojowa (fermentowany peptyd sojowy , gluten pszenny , woda, sól, naturalnie fermentowany koncentrat sosu sojowego , alkohol, ekstrakt drożdżowy), sos pomidorowy (woda, koncentrat pomidorowy, syrop kukurydziany o wysokiej zawartości fruktozy, ocet, sól, cukier, skrobia modyfikowana, przyprawa), mieszanka przypraw (czerwona papryka w proszku, (woda, czosnek, cebula, sól), sos sojowy (woda, odtłuszczona soja , sól, syrop kukurydziany o wysokiej zawartości fruktozy, alkohol, pszenica , ekstrakt drożdżowy w proszku, benzoesan sodu, sukraloza), przecier ananasowy, alkohol, skrobia modyfikowana, ekstrakt pszenny , kwas glukonowy, sól, ekstrakt drożdżowy w proszku, ekstrakt z cebuli (mieszanina kwasu mlekowego, koncentrat cebuli, syrop kukurydziany, ekstrakt z cebuli, maltodekstryna, sól, guma arabska, olejek eteryczny z cebuli), olej paprykowy (olej sojowy, oleożywica z papryki, estry gliceryny i kwasów tłuszczowych)'::text,
    '74.38'::numeric,
    'KG'::text,
    '43098ab7-106a-47f1-b91b-aa497c1c62db'::uuid,
    'Dania gotowe'::text,
    'dania-gotowe'::text,
    ARRAY['storageZone'::text]::text[]
  ),
  (
    'ADG-000943'::text,
    '93f1960c-343c-42b3-9968-6f4a090a3782'::uuid,
    'dbcff121-00f5-4a35-b336-887444b72cec'::uuid,
    'Makaron stir-fry instant o smaku solonego jajka 85g - MAMA Oriental Kitchen'::text,
    'makaron-stir-fry-instant-o-smaku-solonego-jajka-85g-mama-oriental-kitchen'::text,
    '2026-07-08 12:12:07.93723+00:00'::timestamptz,
    '["cereals","soybeans","eggs","milk"]'::jsonb,
    '["cereals","soybeans","eggs","milk"]'::jsonb,
    '["crustaceans","eggs","milk","celery","sesame","molluscs"]'::jsonb,
    '["crustaceans","eggs","milk","celery","sesame","molluscs"]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    '{"fat":7.8,"salt":1.5,"carbs":26.3,"sugar":2.9,"protein":3.9,"calories":191,"servingSize":"w 100g/100ml","saturatedFat":3.4}'::jsonb,
    '{"fat":7.8,"salt":1.5,"carbs":26.3,"sugar":2.9,"protein":3.9,"calories":191,"servingSize":"w 100g/100ml","saturatedFat":3.4}'::jsonb,
    'Tajlandia'::text,
    'Tajlandia'::text,
    'Mąka pszenna 56%, olej palmowy, skrobia modyfikowana z tapioki, cukier, jaja w proszku 3,61%, sól, aromat ( mleko , soja ) 1,04%, przyprawy, wzmacniacz smaku (E621, E635), chilli w proszku, regulator kwasowości (E500, E501, E451), suszona szalotka, substancja zagęszczająca (E466), substancja przeciwzbrylająca (E551), regulator kwasowości (E330), barwnik (E150a), oleorezynowy ekstrakt z papryki, ekstrakt z rozmarynu.'::text,
    'Mąka pszenna 56%, olej palmowy, skrobia modyfikowana z tapioki, cukier, jaja w proszku 3,61%, sól, aromat ( mleko , soja ) 1,04%, przyprawy, wzmacniacz smaku (E621, E635), chilli w proszku, regulator kwasowości (E500, E501, E451), suszona szalotka, substancja zagęszczająca (E466), substancja przeciwzbrylająca (E551), regulator kwasowości (E330), barwnik (E150a), oleorezynowy ekstrakt z papryki, ekstrakt z rozmarynu.'::text,
    '82.24'::numeric,
    'KG'::text,
    '43098ab7-106a-47f1-b91b-aa497c1c62db'::uuid,
    'Dania gotowe'::text,
    'dania-gotowe'::text,
    ARRAY['storageZone'::text]::text[]
  ),
  (
    'ADG-001068'::text,
    '8f609ee0-5dc2-437f-bee9-d5f9f80ad85e'::uuid,
    '6f8c8902-a9e3-4060-8272-e115be2b1472'::uuid,
    'BBQ Tteokbokki, kluski ryżowe w sosie barbecue 260g - O''Food'::text,
    'bbq-tteokbokki-kluski-ryzowe-w-sosie-barbecue-260g-o-food'::text,
    '2026-07-08 12:12:07.93723+00:00'::timestamptz,
    '["soybeans"]'::jsonb,
    '["soybeans"]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    '{"fat":1.8,"salt":1.1,"carbs":53.3,"sugar":6.2,"protein":4,"calories":245,"servingSize":"w 100g/100ml","saturatedFat":0.4}'::jsonb,
    '{"fat":1.8,"salt":1.1,"carbs":53.3,"sugar":6.2,"protein":4,"calories":245,"servingSize":"w 100g/100ml","saturatedFat":0.4}'::jsonb,
    'Korea Południowa'::text,
    'Korea Południowa'::text,
    'Kluski ryżowe: ryż, woda, sól, regulator kwasowości: kwas cytrynowy (E330); alkohol Sos: cukier, woda, sos sojowy 14,5% ( soja , sól, woda), olej sojowy, czosnek, cebula, alkohol, ekstrakt drożdżowy, bulion w proszku (maltodekstryna, sól, dekstroza), sztuczny aromat, modyfikowana skrobia kukurydziana, hydrolizowane białko sojowe , czarny pieprz w proszku 0,1%, wzmacniacze smaku: E627, E631; regulator kwasowości: E330; substancja zagęszczająca: E415.'::text,
    'Kluski ryżowe: ryż, woda, sól, regulator kwasowości: kwas cytrynowy (E330); alkohol Sos: cukier, woda, sos sojowy 14,5% ( soja , sól, woda), olej sojowy, czosnek, cebula, alkohol, ekstrakt drożdżowy, bulion w proszku (maltodekstryna, sól, dekstroza), sztuczny aromat, modyfikowana skrobia kukurydziana, hydrolizowane białko sojowe , czarny pieprz w proszku 0,1%, wzmacniacze smaku: E627, E631; regulator kwasowości: E330; substancja zagęszczająca: E415.'::text,
    '118.85'::numeric,
    'KG'::text,
    '43098ab7-106a-47f1-b91b-aa497c1c62db'::uuid,
    'Dania gotowe'::text,
    'dania-gotowe'::text,
    ARRAY['storageZone'::text]::text[]
  ),
  (
    'ADG-001120'::text,
    'f6bdd14a-4db0-440d-ab1f-7455ff157663'::uuid,
    '837d615f-2fd0-4b98-847d-9c15a9c49481'::uuid,
    'Danie makaron carbonara o smaku bekonu 85g - MAMA Oriental Kitchen'::text,
    'danie-makaron-carbonara-o-smaku-bekonu-85g-mama-oriental-kitchen'::text,
    '2026-07-08 12:12:07.93723+00:00'::timestamptz,
    '["cereals","eggs","soybeans","milk"]'::jsonb,
    '["cereals","eggs","soybeans","milk"]'::jsonb,
    '["crustaceans","celery","sesame","molluscs"]'::jsonb,
    '["crustaceans","celery","sesame","molluscs"]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    '{"fat":7.8,"salt":1.5,"carbs":26.3,"sugar":2.9,"protein":3.9,"calories":191,"servingSize":"w 100g/100ml","saturatedFat":3.4}'::jsonb,
    '{"fat":7.8,"salt":1.5,"carbs":26.3,"sugar":2.9,"protein":3.9,"calories":191,"servingSize":"w 100g/100ml","saturatedFat":3.4}'::jsonb,
    'Tajlandia'::text,
    'Tajlandia'::text,
    'Mąka pszenna 58%, skrobia z tapioki, olej palmowy, zabielacz (syrop glukozowy, uwodorniony olej palmowy, kazeina (mleko), środek przeciwzbrylający (E551)), maltodekstryna, skrobia modyfikowana z kukurydzy), olej ryżowy, cukier, sól, białko sojowe , aromat ( mleko ) 0.68%, wzmacniacze smaku (E621, E635), przyprawy, regulatory kwasowości (E500, E501, E451), jaja w proszku, sos sojowy (ziarno sojowe , sól, ekstrakt słodowy ( jęczmień ), pszenica , ekstrakt drożdżowy, olej palmowy), drożdże w proszku, substancja zagęszczająca (E466), środek przeciwzbrylający (E551), płatki pietruszki, kwas cytrynowy (E330).'::text,
    'Mąka pszenna 58%, skrobia z tapioki, olej palmowy, zabielacz (syrop glukozowy, uwodorniony olej palmowy, kazeina (mleko), środek przeciwzbrylający (E551)), maltodekstryna, skrobia modyfikowana z kukurydzy), olej ryżowy, cukier, sól, białko sojowe , aromat ( mleko ) 0.68%, wzmacniacze smaku (E621, E635), przyprawy, regulatory kwasowości (E500, E501, E451), jaja w proszku, sos sojowy (ziarno sojowe , sól, ekstrakt słodowy ( jęczmień ), pszenica , ekstrakt drożdżowy, olej palmowy), drożdże w proszku, substancja zagęszczająca (E466), środek przeciwzbrylający (E551), płatki pietruszki, kwas cytrynowy (E330).'::text,
    '82.24'::numeric,
    'KG'::text,
    '43098ab7-106a-47f1-b91b-aa497c1c62db'::uuid,
    'Dania gotowe'::text,
    'dania-gotowe'::text,
    ARRAY['storageZone'::text]::text[]
  ),
  (
    'ADG-001121'::text,
    '45dc6a6c-fa19-4e20-a27f-6ec5f1081b36'::uuid,
    'dacb831a-e132-49f8-a92a-35e670352bb8'::uuid,
    'Zupa makaron Mala o smaku wołowiny 85g - MAMA Oriental Kitchen'::text,
    'zupa-makaron-mala-o-smaku-wolowiny-85g-mama-oriental-kitchen'::text,
    '2026-07-08 12:12:07.93723+00:00'::timestamptz,
    '["cereals"]'::jsonb,
    '["cereals"]'::jsonb,
    '["crustaceans","eggs","milk","celery","sesame","molluscs"]'::jsonb,
    '["crustaceans","eggs","milk","celery","sesame","molluscs"]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    '{"fat":4,"salt":0.82,"carbs":13,"sugar":0.5,"protein":1.7,"calories":95,"servingSize":"w 100g/100ml","saturatedFat":2}'::jsonb,
    '{"fat":4,"salt":0.82,"carbs":13,"sugar":0.5,"protein":1.7,"calories":95,"servingSize":"w 100g/100ml","saturatedFat":2}'::jsonb,
    'Tajlandia'::text,
    'Tajlandia'::text,
    'Mąka pszenna 58%, olej palmowy, modyfikowana skrobia z tapioki, sól, cukier, chili w proszku, wzmacniacze smaku (E621, E635), regulatory kwasowości (E500, E501, E451), aromat, przyprawy, barwniki (E150c, E160c), substancja zagęszczająca (E466), dymka suszona, papryka oleoresin, substancja przeciwzbrylająca (E551).'::text,
    'Mąka pszenna 58%, olej palmowy, modyfikowana skrobia z tapioki, sól, cukier, chili w proszku, wzmacniacze smaku (E621, E635), regulatory kwasowości (E500, E501, E451), aromat, przyprawy, barwniki (E150c, E160c), substancja zagęszczająca (E466), dymka suszona, papryka oleoresin, substancja przeciwzbrylająca (E551).'::text,
    '82.24'::numeric,
    'KG'::text,
    '43098ab7-106a-47f1-b91b-aa497c1c62db'::uuid,
    'Dania gotowe'::text,
    'dania-gotowe'::text,
    ARRAY['storageZone'::text]::text[]
  ),
  (
    'ADG-001129'::text,
    '1ac6ad82-2f23-452c-abca-90e5a170a74b'::uuid,
    '516b3ef8-1154-42c1-8cc5-ebd7c4f927e9'::uuid,
    'Danie makaron udon Sesame Teriyaki Bowl 240g - Obento'::text,
    'danie-makaron-udon-sesame-teriyaki-bowl-240g-obento'::text,
    '2026-07-08 12:12:07.93723+00:00'::timestamptz,
    '["cereals","soybeans","sesame"]'::jsonb,
    '["cereals","soybeans","sesame"]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    '{"fat":2,"salt":1.1,"carbs":28,"sugar":6.3,"protein":4.8,"calories":155,"servingSize":"w 100g/100ml","saturatedFat":0.2}'::jsonb,
    '{"fat":2,"salt":1.1,"carbs":28,"sugar":6.3,"protein":4.8,"calories":155,"servingSize":"w 100g/100ml","saturatedFat":0.2}'::jsonb,
    'Chiny'::text,
    'Chiny'::text,
    'Makaron (78,3%) : woda, mąka pszenna , zmodyfikowana skrobia z tapioki, sól, regulator kwasowości E270. Sos (20%) : cukier, sos sojowy (woda, pszenica , soja , sól), czosnek, koncentrat syropu z cytrusów (woda, cukier, koncentrat soku jabłkowego, koncentrat soku z cytryny, stabilizator E466), regulator kwasowości E330, zagęszczacze: E412, E440; przeciwutleniacz E300), modyfikowana skrobia kukurydziana, pasta sezamowa (1,6%), olej sojowy , sól, ekstrakt drożdżowy, przyprawy, olej sezamowy (0,8%), regulator kwasowości E330. Suszone warzywa (0,8%) : marchewka, czerwona papryka, cebulka. Posypka (0,8%) : nasiona prażonego sezamu.'::text,
    'Makaron (78,3%) : woda, mąka pszenna , zmodyfikowana skrobia z tapioki, sól, regulator kwasowości E270. Sos (20%) : cukier, sos sojowy (woda, pszenica , soja , sól), czosnek, koncentrat syropu z cytrusów (woda, cukier, koncentrat soku jabłkowego, koncentrat soku z cytryny, stabilizator E466), regulator kwasowości E330, zagęszczacze: E412, E440; przeciwutleniacz E300), modyfikowana skrobia kukurydziana, pasta sezamowa (1,6%), olej sojowy , sól, ekstrakt drożdżowy, przyprawy, olej sezamowy (0,8%), regulator kwasowości E330. Suszone warzywa (0,8%) : marchewka, czerwona papryka, cebulka. Posypka (0,8%) : nasiona prażonego sezamu.'::text,
    '57.92'::numeric,
    'KG'::text,
    '43098ab7-106a-47f1-b91b-aa497c1c62db'::uuid,
    'Dania gotowe'::text,
    'dania-gotowe'::text,
    ARRAY['storageZone'::text]::text[]
  ),
  (
    'ADG-001130'::text,
    '2baa3d40-f01d-4040-bb16-db824f0525da'::uuid,
    '1d4e401e-fa58-40a2-b37c-dc1ba4282965'::uuid,
    'Danie makaron udon Spicy Kung Pao Bowl 240g - Obento'::text,
    'danie-makaron-udon-spicy-kung-pao-bowl-240g-obento'::text,
    '2026-07-08 12:12:07.93723+00:00'::timestamptz,
    '["cereals","soybeans","nuts","sesame","peanuts"]'::jsonb,
    '["cereals","soybeans","nuts","sesame","peanuts"]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    '{"fat":3.3,"salt":2,"carbs":26,"sugar":5.3,"protein":4.9,"calories":158,"servingSize":"w 100g/100ml","saturatedFat":0.5}'::jsonb,
    '{"fat":3.3,"salt":2,"carbs":26,"sugar":5.3,"protein":4.9,"calories":158,"servingSize":"w 100g/100ml","saturatedFat":0.5}'::jsonb,
    'Chiny'::text,
    'Chiny'::text,
    'Makaron (78,3%) : woda, mąka pszenna , zmodyfikowana skrobia z tapioki, sól, regulator kwasowości E270. Sos (19,6%) : woda, cukier, sos sojowy (woda, pszenica , soja , sól), pasta sojowa (woda, soja , sól), czosnek, sól, pasta orzechowa , hydrolizowane białko sojowe , olej sojowy , olej sezamowy , pasta sezamowa , modyfikowana skrobia kukurydziana, przyprawy, imbir, regulator kwasowości E330. Suszone warzywa (1,3%) : marchewka, czerwona papryka, cebulka. Posypka (0,8%) : prażone orzeszki ziemne.'::text,
    'Makaron (78,3%) : woda, mąka pszenna , zmodyfikowana skrobia z tapioki, sól, regulator kwasowości E270. Sos (19,6%) : woda, cukier, sos sojowy (woda, pszenica , soja , sól), pasta sojowa (woda, soja , sól), czosnek, sól, pasta orzechowa , hydrolizowane białko sojowe , olej sojowy , olej sezamowy , pasta sezamowa , modyfikowana skrobia kukurydziana, przyprawy, imbir, regulator kwasowości E330. Suszone warzywa (1,3%) : marchewka, czerwona papryka, cebulka. Posypka (0,8%) : prażone orzeszki ziemne.'::text,
    '57.92'::numeric,
    'KG'::text,
    '43098ab7-106a-47f1-b91b-aa497c1c62db'::uuid,
    'Dania gotowe'::text,
    'dania-gotowe'::text,
    ARRAY['storageZone'::text]::text[]
  ),
  (
    'ADG-001205'::text,
    '4722669d-4afa-4c08-b99e-0b6c92e82c38'::uuid,
    'd94c32ce-f996-4a35-8f42-19d65e274bf7'::uuid,
    'Danie makaron Tom Yum z krewetkami 85g - MAMA Oriental Kitchen'::text,
    'danie-makaron-tom-yum-z-krewetkami-85g-mama-oriental-kitchen'::text,
    '2026-07-08 12:12:07.93723+00:00'::timestamptz,
    '["cereals","fish","soybeans","crustaceans"]'::jsonb,
    '["cereals","fish","soybeans","crustaceans"]'::jsonb,
    '["crustaceans","celery","sesame","molluscs"]'::jsonb,
    '["crustaceans","celery","sesame","molluscs"]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    '{"fat":18,"salt":3.9,"carbs":65,"sugar":7.1,"protein":9.4,"calories":460,"servingSize":"w 100g/100ml","saturatedFat":8}'::jsonb,
    '{"fat":18,"salt":3.9,"carbs":65,"sugar":7.1,"protein":9.4,"calories":460,"servingSize":"w 100g/100ml","saturatedFat":8}'::jsonb,
    'Tajlandia'::text,
    'Tajlandia'::text,
    'Mąka pszenna 58%, olej palmowy, skrobia modyfikowana z tapioki, cukier, sól, przyprawy, chili 0.9%, wzmacniacz smaku: E621, E635, suszone krewetki 0.74%, cukier palmowy, sos rybny ( anchois , sól , cukier), regulator kwasowości: E500, E501, E451, E330; suszona zielona cebulka, krewetki w proszku 0.15%, substancja zagęszczająca: E466, papryka w proszku, aromat (zawiera soję ), ekstrakt z chili.'::text,
    'Mąka pszenna 58%, olej palmowy, skrobia modyfikowana z tapioki, cukier, sól, przyprawy, chili 0.9%, wzmacniacz smaku: E621, E635, suszone krewetki 0.74%, cukier palmowy, sos rybny ( anchois , sól , cukier), regulator kwasowości: E500, E501, E451, E330; suszona zielona cebulka, krewetki w proszku 0.15%, substancja zagęszczająca: E466, papryka w proszku, aromat (zawiera soję ), ekstrakt z chili.'::text,
    '82.24'::numeric,
    'KG'::text,
    '43098ab7-106a-47f1-b91b-aa497c1c62db'::uuid,
    'Dania gotowe'::text,
    'dania-gotowe'::text,
    ARRAY['storageZone'::text]::text[]
  );

DO $$
DECLARE affected integer;
BEGIN
  IF (SELECT COUNT(*) FROM _adg_metadata_target_salon) <> 1 THEN
    RAISE EXCEPTION 'Expected exactly one active pinned asiandeligo channel';
  END IF;
  IF to_regclass('public.asiandeligo_catalog_metadata_batch6_product_backup_20260722') IS NULL
     OR to_regclass('public.asiandeligo_catalog_metadata_batch6_audit_20260722') IS NULL THEN
    RAISE EXCEPTION 'Required batch backup/audit table is missing';
  END IF;
  IF (
    SELECT COUNT(*)
    FROM public.asiandeligo_catalog_metadata_batch6_product_backup_20260722
    WHERE batch_key = 'asiandeligo-catalog-metadata-batch6-20260722-v1'
      AND decision_sha256 = '19d2a71766d82e9ac4089b60472959412bd49b772820b75521260ae112e7844f'
      AND salon_id = 'e73271a9-53e3-4a20-a02e-791726b452aa'::uuid
  ) <> 14 THEN
    RAISE EXCEPTION 'Expected exactly 14 tenant- and decision-scoped backup rows';
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM public.asiandeligo_catalog_metadata_batch6_audit_20260722
    WHERE batch_key = 'asiandeligo-catalog-metadata-batch6-20260722-v1'
      AND decision_sha256 = '19d2a71766d82e9ac4089b60472959412bd49b772820b75521260ae112e7844f'
      AND salon_id = 'e73271a9-53e3-4a20-a02e-791726b452aa'::uuid
      AND action = 'backup_captured'
      AND product_rows = 14
  ) OR NOT EXISTS (
    SELECT 1 FROM public.asiandeligo_catalog_metadata_batch6_audit_20260722
    WHERE batch_key = 'asiandeligo-catalog-metadata-batch6-20260722-v1'
      AND decision_sha256 = '19d2a71766d82e9ac4089b60472959412bd49b772820b75521260ae112e7844f'
      AND salon_id = 'e73271a9-53e3-4a20-a02e-791726b452aa'::uuid
      AND action = 'apply_complete'
      AND product_rows = 14
  ) OR EXISTS (
    SELECT 1 FROM public.asiandeligo_catalog_metadata_batch6_audit_20260722
    WHERE batch_key = 'asiandeligo-catalog-metadata-batch6-20260722-v1'
      AND decision_sha256 = '19d2a71766d82e9ac4089b60472959412bd49b772820b75521260ae112e7844f'
      AND salon_id = 'e73271a9-53e3-4a20-a02e-791726b452aa'::uuid
      AND action = 'rollback_complete'
  ) THEN
    RAISE EXCEPTION 'Required apply audit chain is incomplete or rollback already completed';
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_catalog.pg_trigger
    WHERE tgrelid = 'public.products'::regclass
      AND tgname = 'zz_enforce_products_monotonic_updated_at'
      AND NOT tgisinternal
      AND tgenabled = 'O'
  ) OR EXISTS (
    SELECT 1
    FROM _adg_metadata_decisions decision
    CROSS JOIN _adg_metadata_target_salon tenant
    LEFT JOIN public.asiandeligo_catalog_metadata_batch6_product_backup_20260722 backup
      ON backup.batch_key = 'asiandeligo-catalog-metadata-batch6-20260722-v1'
     AND backup.decision_sha256 = '19d2a71766d82e9ac4089b60472959412bd49b772820b75521260ae112e7844f'
     AND backup.salon_id = tenant.salon_id
     AND backup.sku = decision.sku
     AND backup.product_id = decision.product_id
    AND backup.variant_id = decision.variant_id
    AND backup.category_id = decision.category_id
    AND backup.changed_fields = decision.changed_fields
    AND backup.original_updated_at = decision.expected_updated_at
    AND backup.applied_updated_at IS NOT NULL
    AND backup.applied_updated_at > backup.original_updated_at
    AND backup.allergens IS NOT DISTINCT FROM decision.expected_allergens
    AND backup.may_contain_allergens IS NOT DISTINCT FROM decision.expected_may_contain_allergens
    AND backup.storage_zone IS NOT DISTINCT FROM decision.expected_storage_zone
    AND backup.nutrition_facts IS NOT DISTINCT FROM decision.expected_nutrition_facts
    AND backup.country_of_origin IS NOT DISTINCT FROM decision.expected_country_of_origin
    AND backup.ingredients IS NOT DISTINCT FROM decision.expected_ingredients
    AND backup.price_per_unit IS NOT DISTINCT FROM decision.expected_price_per_unit
    AND backup.unit_of_measure IS NOT DISTINCT FROM decision.expected_unit_of_measure
    WHERE backup.sku IS NULL
  ) THEN
    RAISE EXCEPTION 'Required timestamp trigger or exact reviewed backup snapshot is missing';
  END IF;

  PERFORM 1
  FROM _adg_metadata_decisions decision
  CROSS JOIN _adg_metadata_target_salon tenant
  JOIN public.asiandeligo_catalog_metadata_batch6_product_backup_20260722 backup
    ON backup.batch_key = 'asiandeligo-catalog-metadata-batch6-20260722-v1'
   AND backup.decision_sha256 = '19d2a71766d82e9ac4089b60472959412bd49b772820b75521260ae112e7844f'
   AND backup.salon_id = tenant.salon_id
   AND backup.sku = decision.sku
   AND backup.product_id = decision.product_id
    AND backup.variant_id = decision.variant_id
    AND backup.category_id = decision.category_id
    AND backup.changed_fields = decision.changed_fields
    AND backup.original_updated_at = decision.expected_updated_at
    AND backup.applied_updated_at IS NOT NULL
    AND backup.applied_updated_at > backup.original_updated_at
    AND backup.allergens IS NOT DISTINCT FROM decision.expected_allergens
    AND backup.may_contain_allergens IS NOT DISTINCT FROM decision.expected_may_contain_allergens
    AND backup.storage_zone IS NOT DISTINCT FROM decision.expected_storage_zone
    AND backup.nutrition_facts IS NOT DISTINCT FROM decision.expected_nutrition_facts
    AND backup.country_of_origin IS NOT DISTINCT FROM decision.expected_country_of_origin
    AND backup.ingredients IS NOT DISTINCT FROM decision.expected_ingredients
    AND backup.price_per_unit IS NOT DISTINCT FROM decision.expected_price_per_unit
    AND backup.unit_of_measure IS NOT DISTINCT FROM decision.expected_unit_of_measure
  JOIN public.product_variants variant
    ON variant.id = decision.variant_id
    AND variant.sku = decision.sku
    AND variant.salon_id = tenant.salon_id
   AND variant.is_active = TRUE
   AND variant.is_published = FALSE
   AND variant.is_for_sale = TRUE
   AND variant.sync_status = 'synced'
   AND variant.availability_status = 'IN_STOCK'
    AND variant.deleted_at IS NULL
  JOIN public.products product
    ON product.id = decision.product_id
    AND product.id = variant.template_id
    AND product.salon_id = tenant.salon_id
   AND product.name = decision.expected_name
   AND product.slug = decision.expected_slug
    AND product.updated_at = backup.applied_updated_at
   AND product.is_active = TRUE
   AND product.is_published = TRUE
   AND product.is_visible = TRUE
   AND product.status = 'active'
    AND product.deleted_at IS NULL
  JOIN public.categories category
    ON category.id = decision.category_id
   AND category.id = product.category_id
   AND category.salon_id = tenant.salon_id
   AND category.name = decision.category_name
   AND category.slug = decision.category_slug
   AND category.is_active = TRUE
  WHERE product.allergens IS NOT DISTINCT FROM decision.target_allergens
    AND product.may_contain_allergens IS NOT DISTINCT FROM decision.target_may_contain_allergens
    AND product.storage_zone IS NOT DISTINCT FROM decision.target_storage_zone
    AND product.nutrition_facts IS NOT DISTINCT FROM decision.target_nutrition_facts
    AND product.country_of_origin IS NOT DISTINCT FROM decision.target_country_of_origin
    AND product.ingredients IS NOT DISTINCT FROM decision.target_ingredients
    AND product.price_per_unit IS NOT DISTINCT FROM decision.expected_price_per_unit
    AND product.unit_of_measure IS NOT DISTINCT FROM decision.expected_unit_of_measure
  ORDER BY product.id
  FOR UPDATE OF product, variant, category;
  GET DIAGNOSTICS affected = ROW_COUNT;
  IF affected <> 14 THEN
    RAISE EXCEPTION 'Expected 14 exact target row locks; refusing to overwrite intervening edits';
  END IF;
END $$;

DO $$
DECLARE affected integer;
BEGIN
  UPDATE public.products product
  SET allergens = backup.allergens,
      may_contain_allergens = backup.may_contain_allergens,
      storage_zone = backup.storage_zone,
      nutrition_facts = backup.nutrition_facts,
      country_of_origin = backup.country_of_origin,
      ingredients = backup.ingredients
  FROM _adg_metadata_decisions decision,
       _adg_metadata_target_salon tenant,
       public.asiandeligo_catalog_metadata_batch6_product_backup_20260722 backup
  WHERE backup.batch_key = 'asiandeligo-catalog-metadata-batch6-20260722-v1'
    AND backup.decision_sha256 = '19d2a71766d82e9ac4089b60472959412bd49b772820b75521260ae112e7844f'
    AND backup.salon_id = tenant.salon_id
    AND backup.sku = decision.sku
    AND backup.product_id = product.id
    AND product.salon_id = tenant.salon_id
    AND product.name = decision.expected_name
    AND product.slug = decision.expected_slug
    AND product.updated_at = backup.applied_updated_at
    AND product.is_active = TRUE
    AND product.is_published = TRUE
    AND product.is_visible = TRUE
    AND product.status = 'active'
    AND product.deleted_at IS NULL
    AND backup.product_id = decision.product_id
    AND backup.variant_id = decision.variant_id
    AND backup.category_id = decision.category_id
    AND backup.changed_fields = decision.changed_fields
    AND backup.original_updated_at = decision.expected_updated_at
    AND backup.applied_updated_at IS NOT NULL
    AND backup.applied_updated_at > backup.original_updated_at
    AND backup.allergens IS NOT DISTINCT FROM decision.expected_allergens
    AND backup.may_contain_allergens IS NOT DISTINCT FROM decision.expected_may_contain_allergens
    AND backup.storage_zone IS NOT DISTINCT FROM decision.expected_storage_zone
    AND backup.nutrition_facts IS NOT DISTINCT FROM decision.expected_nutrition_facts
    AND backup.country_of_origin IS NOT DISTINCT FROM decision.expected_country_of_origin
    AND backup.ingredients IS NOT DISTINCT FROM decision.expected_ingredients
    AND backup.price_per_unit IS NOT DISTINCT FROM decision.expected_price_per_unit
    AND backup.unit_of_measure IS NOT DISTINCT FROM decision.expected_unit_of_measure
    AND product.allergens IS NOT DISTINCT FROM decision.target_allergens
    AND product.may_contain_allergens IS NOT DISTINCT FROM decision.target_may_contain_allergens
    AND product.storage_zone IS NOT DISTINCT FROM decision.target_storage_zone
    AND product.nutrition_facts IS NOT DISTINCT FROM decision.target_nutrition_facts
    AND product.country_of_origin IS NOT DISTINCT FROM decision.target_country_of_origin
    AND product.ingredients IS NOT DISTINCT FROM decision.target_ingredients
    AND product.price_per_unit IS NOT DISTINCT FROM decision.expected_price_per_unit
    AND product.unit_of_measure IS NOT DISTINCT FROM decision.expected_unit_of_measure;
  GET DIAGNOSTICS affected = ROW_COUNT;
  IF affected <> 14 THEN
    RAISE EXCEPTION 'Expected 14 exact product restorations, got %', affected;
  END IF;

  IF (
    SELECT COUNT(*)
    FROM public.products product
    JOIN public.asiandeligo_catalog_metadata_batch6_product_backup_20260722 backup
      ON backup.product_id = product.id
     AND backup.batch_key = 'asiandeligo-catalog-metadata-batch6-20260722-v1'
     AND backup.decision_sha256 = '19d2a71766d82e9ac4089b60472959412bd49b772820b75521260ae112e7844f'
     AND backup.salon_id = product.salon_id
    WHERE product.salon_id = 'e73271a9-53e3-4a20-a02e-791726b452aa'::uuid
      AND product.updated_at > backup.applied_updated_at
      AND product.allergens IS NOT DISTINCT FROM backup.allergens
      AND product.may_contain_allergens IS NOT DISTINCT FROM backup.may_contain_allergens
      AND product.storage_zone IS NOT DISTINCT FROM backup.storage_zone
      AND product.nutrition_facts IS NOT DISTINCT FROM backup.nutrition_facts
      AND product.country_of_origin IS NOT DISTINCT FROM backup.country_of_origin
      AND product.ingredients IS NOT DISTINCT FROM backup.ingredients
      AND product.price_per_unit IS NOT DISTINCT FROM backup.price_per_unit
      AND product.unit_of_measure IS NOT DISTINCT FROM backup.unit_of_measure
  ) <> 14 THEN
    RAISE EXCEPTION 'Rollback post-state verification failed';
  END IF;

  INSERT INTO public.asiandeligo_catalog_metadata_batch6_audit_20260722 (
    batch_key, decision_sha256, channel_slug, salon_id, action, product_rows
  )
  SELECT 'asiandeligo-catalog-metadata-batch6-20260722-v1', '19d2a71766d82e9ac4089b60472959412bd49b772820b75521260ae112e7844f', channel_slug, salon_id,
         'rollback_complete', 14
  FROM _adg_metadata_target_salon;
END $$;

SELECT backup.sku, backup.changed_fields, audit.recorded_at, audit.transaction_id
FROM public.asiandeligo_catalog_metadata_batch6_product_backup_20260722 backup
JOIN public.asiandeligo_catalog_metadata_batch6_audit_20260722 audit
  ON audit.batch_key = backup.batch_key
 AND audit.salon_id = backup.salon_id
 AND audit.action = 'rollback_complete'
WHERE backup.batch_key = 'asiandeligo-catalog-metadata-batch6-20260722-v1'
  AND backup.decision_sha256 = '19d2a71766d82e9ac4089b60472959412bd49b772820b75521260ae112e7844f'
  AND backup.salon_id = 'e73271a9-53e3-4a20-a02e-791726b452aa'::uuid
ORDER BY backup.sku;

COMMIT;
