-- Generated by scripts/folder14-draft-quality-plan.mjs
-- Roll back only the folder14 quality cleanup and 11 added gallery rows.
-- Do not use after later manual admin edits without reviewing the affected drafts.

BEGIN;

CREATE TEMP TABLE _adg_f14_quality_rollback (
  review_id text PRIMARY KEY,
  draft_sku text UNIQUE NOT NULL,
  proposed_pl_name text NOT NULL,
  proposed_en_name text NOT NULL,
  proposed_brand text,
  proposed_category_slug text NOT NULL,
  proposed_pl_slug text NOT NULL,
  proposed_en_slug text NOT NULL,
  quality_flags text[] NOT NULL,
  review_note text NOT NULL,
  old_pl_name text NOT NULL,
  old_en_name text NOT NULL,
  old_brand text,
  old_category_slug text NOT NULL,
  old_slug text NOT NULL
) ON COMMIT DROP;

INSERT INTO _adg_f14_quality_rollback (
  review_id, draft_sku, proposed_pl_name, proposed_en_name, proposed_brand,
  proposed_category_slug, proposed_pl_slug, proposed_en_slug, quality_flags,
  review_note, old_pl_name, old_en_name, old_brand, old_category_slug, old_slug
) VALUES
  ('folder14-001', 'ADG-001792', 'Pałeczki bambusowe jednorazowe Asia Foods w czerwonych osłonkach', 'Asia Foods disposable bamboo chopsticks in red sleeves', 'Asia Foods', 'pałeczki-i-sztućce', 'paleczki-bambusowe-jednorazowe-asia-foods-w-czerwonych-oslonkach', 'asia-foods-disposable-bamboo-chopsticks-in-red-sleeves', ARRAY['pack_count_unknown']::text[], 'Potwierdzić liczbę sztuk przed publikacją', 'Asia Foods red-sleeve disposable bamboo chopsticks / Paleczki Bambusowe Jednorazowego Uzytku', 'Asia Foods red-sleeve disposable bamboo chopsticks / Paleczki Bambusowe Jednorazowego Uzytku', NULL, 'pałeczki-i-sztućce', 'asia-foods-red-sleeve-disposable-bamboo-chopsticks-paleczki-bambusowe-jednorazowego-uzytku'),
  ('folder14-002', 'ADG-001793', 'Pałeczki bambusowe jednorazowe w zielono-białych osłonkach', 'Disposable bamboo chopsticks in green-white sleeves', NULL, 'pałeczki-i-sztućce', 'paleczki-bambusowe-jednorazowe-w-zielono-bialych-oslonkach', 'disposable-bamboo-chopsticks-in-green-white-sleeves', ARRAY['brand_and_pack_count_unknown']::text[], 'Bezpieczna nazwa ogólna do czasu odczytania etykiety', 'Green-white sleeve disposable chopsticks, exact brand/count unclear', 'Green-white sleeve disposable chopsticks, exact brand/count unclear', NULL, 'pałeczki-i-sztućce', 'green-white-sleeve-disposable-chopsticks-exact-brand-count-unclear'),
  ('folder14-003', 'ADG-001794', 'Talerze owalne piankowe Huhtamaki Econo XPS 26,2 x 19,3 cm - 50 szt.', 'Huhtamaki Econo XPS oval foam plates 26.2 x 19.3 cm - 50 pcs', 'Huhtamaki', 'naczynia', 'talerze-owalne-piankowe-huhtamaki-econo-xps-26-2-x-19-3-cm-50-szt', 'huhtamaki-econo-xps-oval-foam-plates-26-2-x-19-3-cm-50-pcs', ARRAY[]::text[], 'Dane rozmiaru i liczby sztuk są widoczne na opakowaniu', 'Huhtamaki Econo XPS oval plates 26.2 x 19.3cm, 50 pcs', 'Huhtamaki Econo XPS oval plates 26.2 x 19.3cm, 50 pcs', NULL, 'naczynia', 'huhtamaki-econo-xps-oval-plates-26-2-x-19-3cm-50-pcs'),
  ('folder14-004', 'ADG-001795', 'Pojemnik obiadowy piankowy z pokrywką i przegrodami', 'Foam takeaway food box with lid and compartments', NULL, 'naczynia', 'pojemnik-obiadowy-piankowy-z-pokrywka-i-przegrodami', 'foam-takeaway-food-box-with-lid-and-compartments', ARRAY['size_and_pack_count_unknown']::text[], 'Potwierdzić rozmiar oraz liczbę sztuk', 'White foam takeaway clamshell food boxes, multiple compartments', 'White foam takeaway clamshell food boxes, multiple compartments', NULL, 'naczynia', 'white-foam-takeaway-clamshell-food-boxes-multiple-compartments'),
  ('folder14-005', 'ADG-001796', 'Łopatka do woka ze stalowym trzonkiem i drewnianym uchwytem', 'Wok spatula with steel shaft and wooden handle', NULL, 'patelnie-wok-grill', 'lopatka-do-woka-ze-stalowym-trzonkiem-i-drewnianym-uchwytem', 'wok-spatula-with-steel-shaft-and-wooden-handle', ARRAY['size_unknown']::text[], 'Bezpieczna nazwa ogólna', 'Metal wok spatula / Chinese cooking turner with wooden handle', 'Metal wok spatula / Chinese cooking turner with wooden handle', NULL, 'patelnie-wok-grill', 'metal-wok-spatula-chinese-cooking-turner-with-wooden-handle'),
  ('folder14-006', 'ADG-001797', 'Ceramiczna miska z pokrywką i podgrzewaczem IPS Ceramic', 'Ceramic lidded bowl with warmer by IPS Ceramic', 'IPS Ceramic', 'miski', 'ceramiczna-miska-z-pokrywka-i-podgrzewaczem-ips-ceramic', 'ceramic-lidded-bowl-with-warmer-by-ips-ceramic', ARRAY['size_unknown']::text[], 'Potwierdzić rozmiar', 'Ceramic lidded bowl with warmer/stand, IPS Ceramic', 'Ceramic lidded bowl with warmer/stand, IPS Ceramic', NULL, 'miski', 'ceramic-lidded-bowl-with-warmer-stand-ips-ceramic'),
  ('folder14-007', 'ADG-001798', 'Druciana łyżka cedzakowa do woka z bambusowym uchwytem', 'Wire spider skimmer for wok with bamboo handle', NULL, 'patelnie-wok-grill', 'druciana-lyzka-cedzakowa-do-woka-z-bambusowym-uchwytem', 'wire-spider-skimmer-for-wok-with-bamboo-handle', ARRAY['diameter_unknown']::text[], 'To nie jest ten sam produkt co ADG-001814', 'Bamboo-handle wire spider strainer / skimmer', 'Bamboo-handle wire spider strainer / skimmer', NULL, 'patelnie-wok-grill', 'bamboo-handle-wire-spider-strainer-skimmer'),
  ('folder14-008', 'ADG-001799', 'Wok ze stali węglowej z drewnianym uchwytem', 'Carbon steel wok with wooden handle', NULL, 'patelnie-wok-grill', 'wok-ze-stali-weglowej-z-drewnianym-uchwytem', 'carbon-steel-wok-with-wooden-handle', ARRAY['diameter_unknown']::text[], 'Potwierdzić średnicę', 'Carbon steel wok with single wooden handle, size unclear', 'Carbon steel wok with single wooden handle, size unclear', NULL, 'patelnie-wok-grill', 'carbon-steel-wok-with-single-wooden-handle-size-unclear'),
  ('folder14-009', 'ADG-001800', 'Wok ze stali węglowej z dwoma uchwytami bocznymi', 'Carbon steel wok with two side handles', NULL, 'patelnie-wok-grill', 'wok-ze-stali-weglowej-z-dwoma-uchwytami-bocznymi', 'carbon-steel-wok-with-two-side-handles', ARRAY['diameter_unknown']::text[], 'Potwierdzić średnicę', 'Carbon steel wok with two side handles, size unclear', 'Carbon steel wok with two side handles, size unclear', NULL, 'patelnie-wok-grill', 'carbon-steel-wok-with-two-side-handles-size-unclear'),
  ('folder14-010', 'ADG-001801', 'Stalowy durszlak perforowany do gotowania na parze', 'Stainless perforated colander for steaming', NULL, 'naczynia', 'stalowy-durszlak-perforowany-do-gotowania-na-parze', 'stainless-perforated-colander-for-steaming', ARRAY['size_unknown']::text[], 'Kategoria poprawiona z patelni na naczynia', 'Stainless perforated colander / steamer insert bowl', 'Stainless perforated colander / steamer insert bowl', NULL, 'patelnie-wok-grill', 'stainless-perforated-colander-steamer-insert-bowl'),
  ('folder14-011', 'ADG-001802', 'Chiński tasak kuchenny z drewnianą rękojeścią', 'Chinese kitchen cleaver with wooden handle', NULL, 'noże', 'chinski-tasak-kuchenny-z-drewniana-rekojescia', 'chinese-kitchen-cleaver-with-wooden-handle', ARRAY['size_and_model_unknown']::text[], 'Potwierdzić długość ostrza', 'Wooden-handle Chinese cleaver / kitchen knife, exact model unclear', 'Wooden-handle Chinese cleaver / kitchen knife, exact model unclear', NULL, 'noże', 'wooden-handle-chinese-cleaver-kitchen-knife-exact-model-unclear'),
  ('folder14-013', 'ADG-001804', 'Ceramiczna podstawka do gotowania na parze', 'Ceramic steaming rack', NULL, 'naczynia', 'ceramiczna-podstawka-do-gotowania-na-parze', 'ceramic-steaming-rack', ARRAY['diameter_unknown']::text[], 'Potwierdzić średnicę', 'Round ceramic steaming rack / trivet, size unclear', 'Round ceramic steaming rack / trivet, size unclear', NULL, 'naczynia', 'round-ceramic-steaming-rack-trivet-size-unclear'),
  ('folder14-014', 'ADG-001805', 'Chochla ze stali nierdzewnej z długim uchwytem', 'Stainless steel ladle with long handle', NULL, 'naczynia', 'chochla-ze-stali-nierdzewnej-z-dlugim-uchwytem', 'stainless-steel-ladle-with-long-handle', ARRAY['size_unknown']::text[], 'Nazwa poprawiona z liczby mnogiej na pojedynczy produkt widoczny na zdjęciu', 'Assorted metal soup ladles, multiple handle styles/sizes', 'Assorted metal soup ladles, multiple handle styles/sizes', NULL, 'naczynia', 'assorted-metal-soup-ladles-multiple-handle-styles-sizes'),
  ('folder14-015', 'ADG-001806', 'Azjatycki nóż szefa kuchni z drewnianą rękojeścią', 'Asian chef knife with wooden handle', NULL, 'noże', 'azjatycki-noz-szefa-kuchni-z-drewniana-rekojescia', 'asian-chef-knife-with-wooden-handle', ARRAY['size_and_model_unknown']::text[], 'Potwierdzić długość ostrza', 'Wooden-handle Asian chef knife / santoku-style knife, exact model unclear', 'Wooden-handle Asian chef knife / santoku-style knife, exact model unclear', NULL, 'noże', 'wooden-handle-asian-chef-knife-santoku-style-knife-exact-model-unclear'),
  ('folder14-016', 'ADG-001807', 'Nóż kuchenny z czarną rękojeścią', 'Kitchen knife with black handle', NULL, 'noże', 'noz-kuchenny-z-czarna-rekojescia', 'kitchen-knife-with-black-handle', ARRAY['size_and_model_unknown']::text[], 'Potwierdzić długość ostrza', 'Black-handle kitchen knife / cleaver, exact model unclear', 'Black-handle kitchen knife / cleaver, exact model unclear', NULL, 'noże', 'black-handle-kitchen-knife-cleaver-exact-model-unclear'),
  ('folder14-017', 'ADG-001808', 'Wietnamski zaparzacz do kawy phin Long Cam ze stali nierdzewnej', 'Long Cam stainless steel Vietnamese phin coffee filter', 'Long Cam', 'zaparzacze-do-kawy', 'wietnamski-zaparzacz-do-kawy-phin-long-cam-ze-stali-nierdzewnej', 'long-cam-stainless-steel-vietnamese-phin-coffee-filter', ARRAY['capacity_unknown']::text[], 'Potwierdzić pojemność', 'LCT Long Cam stainless Vietnamese coffee filter / phin ca phe', 'LCT Long Cam stainless Vietnamese coffee filter / phin ca phe', NULL, 'zaparzacze-do-kawy', 'lct-long-cam-stainless-vietnamese-coffee-filter-phin-ca-phe'),
  ('folder14-018', 'ADG-001809', 'Bambusowa mata do zwijania sushi makisu', 'Bamboo sushi rolling mat makisu', NULL, 'maty-do-zwijania', 'bambusowa-mata-do-zwijania-sushi-makisu', 'bamboo-sushi-rolling-mat-makisu', ARRAY['size_unknown']::text[], 'Potwierdzić rozmiar', 'Bamboo sushi rolling mat / makisu', 'Bamboo sushi rolling mat / makisu', NULL, 'maty-do-zwijania', 'bamboo-sushi-rolling-mat-makisu'),
  ('folder14-019', 'ADG-001810', 'Czarne pałeczki wielorazowe - zestaw', 'Black reusable chopsticks set', NULL, 'pałeczki-i-sztućce', 'czarne-paleczki-wielorazowe-zestaw', 'black-reusable-chopsticks-set', ARRAY['material_and_pack_count_unknown']::text[], 'Bezpieczna nazwa ogólna', 'Black chopsticks bundle, unlabelled', 'Black chopsticks bundle, unlabelled', NULL, 'pałeczki-i-sztućce', 'black-chopsticks-bundle-unlabelled'),
  ('folder14-022', 'ADG-001812', 'Koreańskie pałeczki drewniane TQ - zestaw 5 par', 'TQ Korean-style wooden chopsticks - set of 5 pairs', 'TQ', 'pałeczki-i-sztućce', 'koreanskie-paleczki-drewniane-tq-zestaw-5-par', 'tq-korean-style-wooden-chopsticks-set-of-5-pairs', ARRAY[]::text[], 'Liczba par jest widoczna na opakowaniu', 'TQ Korean-style wooden chopsticks set, 5 pairs', 'TQ Korean-style wooden chopsticks set, 5 pairs', NULL, 'pałeczki-i-sztućce', 'tq-korean-style-wooden-chopsticks-set-5-pairs'),
  ('folder14-023', 'ADG-001813', 'Długie pałeczki do gotowania i hot potu - 1 para', 'Long cooking and hot-pot chopsticks - 1 pair', NULL, 'pałeczki-i-sztućce', 'dlugie-paleczki-do-gotowania-i-hot-potu-1-para', 'long-cooking-and-hot-pot-chopsticks-1-pair', ARRAY['length_unknown']::text[], 'Potwierdzić długość', 'Long hot-pot / cooking chopsticks, 1 pair', 'Long hot-pot / cooking chopsticks, 1 pair', NULL, 'pałeczki-i-sztućce', 'long-hot-pot-cooking-chopsticks-1-pair'),
  ('folder14-024', 'ADG-001814', 'Sitko do makaronu z bambusowym uchwytem', 'Noodle strainer with bamboo handle', NULL, 'patelnie-wok-grill', 'sitko-do-makaronu-z-bambusowym-uchwytem', 'noodle-strainer-with-bamboo-handle', ARRAY['size_unknown']::text[], 'To nie jest ten sam produkt co ADG-001798', 'Bamboo-handle wire spider strainer / skimmer', 'Bamboo-handle wire spider strainer / skimmer', NULL, 'patelnie-wok-grill', 'bamboo-handle-wire-spider-strainer-skimmer-adg-001814'),
  ('folder14-026', 'ADG-001815', 'Karty do gry Best 888 - czerwone opakowanie', 'Best 888 playing cards - red pack', 'Best 888', 'pozostałe-produkty', 'karty-do-gry-best-888-czerwone-opakowanie', 'best-888-playing-cards-red-pack', ARRAY[]::text[], 'Produkt detaliczny widoczny na zdjęciu', 'Best 888 playing cards, red pack', 'Best 888 playing cards, red pack', NULL, 'pozostałe-produkty', 'best-888-playing-cards-red-pack'),
  ('folder14-027', 'ADG-001816', 'Prostokątna osełka do ostrzenia noży', 'Rectangular knife sharpening stone', NULL, 'noże', 'prostokatna-oselka-do-ostrzenia-nozy', 'rectangular-knife-sharpening-stone', ARRAY['grit_unknown']::text[], 'Potwierdzić gradację', 'Rectangular knife sharpening stone', 'Rectangular knife sharpening stone', NULL, 'noże', 'rectangular-knife-sharpening-stone'),
  ('folder14-030', 'ADG-001818', 'Czerwony lampion dekoracyjny w stylu azjatyckim', 'Red Asian-style decorative lantern', NULL, 'koty-szczęścia-i-inne-gadżety', 'czerwony-lampion-dekoracyjny-w-stylu-azjatyckim', 'red-asian-style-decorative-lantern', ARRAY['size_unknown']::text[], 'Potwierdzić rozmiar', 'Red Chinese/Vietnamese hanging lantern decoration', 'Red Chinese/Vietnamese hanging lantern decoration', NULL, 'koty-szczęścia-i-inne-gadżety', 'red-chinese-vietnamese-hanging-lantern-decoration'),
  ('folder14-031', 'ADG-001819', 'Bambusowy parowar z pokrywką', 'Bamboo steamer with lid', NULL, 'parowary-bambusowe', 'bambusowy-parowar-z-pokrywka', 'bamboo-steamer-with-lid', ARRAY['diameter_unknown']::text[], 'Potwierdzić średnicę', 'Bamboo steamer baskets/lids, size variants unclear', 'Bamboo steamer baskets/lids, size variants unclear', NULL, 'parowary-bambusowe', 'bamboo-steamer-baskets-lids-size-variants-unclear'),
  ('folder14-032', 'ADG-001820', 'Parowar bambusowy z obręczą i pokrywką', 'Bamboo steamer with rim and lid', NULL, 'parowary-bambusowe', 'parowar-bambusowy-z-obrecza-i-pokrywka', 'bamboo-steamer-with-rim-and-lid', ARRAY['diameter_unknown']::text[], 'Potwierdzić średnicę', 'Bamboo/plastic rim steamer or lidded basket', 'Bamboo/plastic rim steamer or lidded basket', NULL, 'parowary-bambusowe', 'bamboo-plastic-rim-steamer-or-lidded-basket'),
  ('folder14-033', 'ADG-001821', 'Biała miseczka ceramiczna', 'Plain white ceramic bowl', NULL, 'miski', 'biala-miseczka-ceramiczna', 'plain-white-ceramic-bowl', ARRAY['diameter_unknown']::text[], 'Potwierdzić średnicę', 'Plain white ceramic bowl', 'Plain white ceramic bowl', NULL, 'miski', 'plain-white-ceramic-bowl'),
  ('folder14-034', 'ADG-001822', 'Miseczka ceramiczna biało-niebieska', 'Blue and white ceramic bowl', NULL, 'miski', 'miseczka-ceramiczna-bialo-niebieska', 'blue-and-white-ceramic-bowl', ARRAY['diameter_unknown']::text[], 'Potwierdzić średnicę', 'Blue-white ceramic rice bowl', 'Blue-white ceramic rice bowl', NULL, 'miski', 'blue-white-ceramic-rice-bowl'),
  ('folder14-035', 'ADG-001823', 'Łyżka ceramiczna do zupy z zielonym wzorem', 'Ceramic soup spoon with green pattern', NULL, 'pałeczki-i-sztućce', 'lyzka-ceramiczna-do-zupy-z-zielonym-wzorem', 'ceramic-soup-spoon-with-green-pattern', ARRAY['size_unknown']::text[], 'Kategoria poprawiona z naczyń na sztućce', 'White ceramic soup spoons with green pattern', 'White ceramic soup spoons with green pattern', NULL, 'naczynia', 'white-ceramic-soup-spoons-with-green-pattern'),
  ('folder14-036', 'ADG-001824', 'Owalna żeliwna płyta grillowa z drewnianą podstawką', 'Oval cast-iron sizzling plate with wooden base', NULL, 'patelnie-wok-grill', 'owalna-zeliwna-plyta-grillowa-z-drewniana-podstawka', 'oval-cast-iron-sizzling-plate-with-wooden-base', ARRAY['size_unknown']::text[], 'Potwierdzić rozmiar', 'Cast iron oval sizzling plate with wooden base', 'Cast iron oval sizzling plate with wooden base', NULL, 'patelnie-wok-grill', 'cast-iron-oval-sizzling-plate-with-wooden-base'),
  ('folder14-037', 'ADG-001825', 'Dekoracyjna żeliwna płyta grillowa z drewnianą podstawką', 'Decorative cast-iron sizzling plate with wooden base', NULL, 'patelnie-wok-grill', 'dekoracyjna-zeliwna-plyta-grillowa-z-drewniana-podstawka', 'decorative-cast-iron-sizzling-plate-with-wooden-base', ARRAY['size_unknown']::text[], 'Inny kształt niż ADG-001824', 'Cast iron decorative sizzling plate with wooden base', 'Cast iron decorative sizzling plate with wooden base', NULL, 'patelnie-wok-grill', 'cast-iron-decorative-sizzling-plate-with-wooden-base'),
  ('folder14-038', 'ADG-001826', 'Ceremonialny zestaw dekoracji papierowych w pudełku', 'Boxed ceremonial paper decoration set', NULL, 'koty-szczęścia-i-inne-gadżety', 'ceremonialny-zestaw-dekoracji-papierowych-w-pudelku', 'boxed-ceremonial-paper-decoration-set', ARRAY['exact_contents_unknown']::text[], 'Nazwa ogólna do czasu potwierdzenia zawartości', 'Boxed ceremonial / altar paper decoration set, size variants unclear', 'Boxed ceremonial / altar paper decoration set, size variants unclear', NULL, 'koty-szczęścia-i-inne-gadżety', 'boxed-ceremonial-altar-paper-decoration-set-size-variants-unclear'),
  ('folder14-039', 'ADG-001827', 'Zestaw trzech figurek chińskich bóstw', 'Set of three Chinese deity figurines', NULL, 'koty-szczęścia-i-inne-gadżety', 'zestaw-trzech-figurek-chinskich-bostw', 'set-of-three-chinese-deity-figurines', ARRAY['size_unknown']::text[], 'Potwierdzić rozmiar zestawu', 'Three Chinese/Vietnamese deity figurines set', 'Three Chinese/Vietnamese deity figurines set', NULL, 'koty-szczęścia-i-inne-gadżety', 'three-chinese-vietnamese-deity-figurines-set'),
  ('folder14-040', 'ADG-001828', 'Ceramiczna kadzielnica biało-niebieska', 'Blue and white ceramic incense burner', NULL, 'koty-szczęścia-i-inne-gadżety', 'ceramiczna-kadzielnica-bialo-niebieska', 'blue-and-white-ceramic-incense-burner', ARRAY['size_unknown']::text[], 'Potwierdzić rozmiar', 'Blue-white ceramic incense burner / ashtray-style pot', 'Blue-white ceramic incense burner / ashtray-style pot', NULL, 'koty-szczęścia-i-inne-gadżety', 'blue-white-ceramic-incense-burner-ashtray-style-pot'),
  ('folder14-041', 'ADG-001829', 'Czerwone kadzidełka Hang Viet', 'Hang Viet red incense sticks', 'Hang Viet', 'koty-szczęścia-i-inne-gadżety', 'czerwone-kadzidelka-hang-viet', 'hang-viet-red-incense-sticks', ARRAY['pack_count_unknown']::text[], 'Potwierdzić liczbę sztuk', 'Hang Viet red incense sticks / Nhang Viet, Vietnam origin', 'Hang Viet red incense sticks / Nhang Viet, Vietnam origin', NULL, 'koty-szczęścia-i-inne-gadżety', 'hang-viet-red-incense-sticks-nhang-viet-vietnam-origin'),
  ('folder14-042', 'ADG-001830', 'Papier rytualny - symboliczne banknoty ofiarne', 'Joss paper - ceremonial imitation money', NULL, 'koty-szczęścia-i-inne-gadżety', 'papier-rytualny-symboliczne-banknoty-ofiarne', 'joss-paper-ceremonial-imitation-money', ARRAY['pack_count_unknown']::text[], 'Potwierdzić liczbę arkuszy', 'Joss paper / ceremonial imitation money pack', 'Joss paper / ceremonial imitation money pack', NULL, 'koty-szczęścia-i-inne-gadżety', 'joss-paper-ceremonial-imitation-money-pack'),
  ('folder14-043', 'ADG-001831', 'Złota dekoracja ołtarzowa ze smokiem', 'Gold dragon altar decoration', NULL, 'koty-szczęścia-i-inne-gadżety', 'zlota-dekoracja-oltarzowa-ze-smokiem', 'gold-dragon-altar-decoration', ARRAY['size_unknown']::text[], 'Potwierdzić rozmiar', 'Gold dragon / altar hanging decoration piece', 'Gold dragon / altar hanging decoration piece', NULL, 'koty-szczęścia-i-inne-gadżety', 'gold-dragon-altar-hanging-decoration-piece'),
  ('folder14-046', 'ADG-001833', 'Czerwone torby prezentowe Szczęśliwego Nowego Roku', 'Happy New Year red gift bags', NULL, 'prezenty', 'czerwone-torby-prezentowe-szczesliwego-nowego-roku', 'happy-new-year-red-gift-bags', ARRAY['pack_count_and_size_unknown']::text[], 'Potwierdzić liczbę i rozmiar', 'Happy New Year red paper gift bags / envelopes', 'Happy New Year red paper gift bags / envelopes', NULL, 'prezenty', 'happy-new-year-red-paper-gift-bags-envelopes'),
  ('folder14-047', 'ADG-001834', 'Mieszanka suszonych owoców Mứt Tết Hiep Long 600 g', 'Hiep Long Mứt Tết dried fruit mix gift box 600 g', 'Hiep Long', 'słodycze-przekąski', 'mieszanka-suszonych-owocow-mut-tet-hiep-long-600-g', 'hiep-long-mut-tet-dried-fruit-mix-gift-box-600-g', ARRAY['ingredients_allergens_expiry_pending']::text[], 'Żywność pozostaje draft do uzupełnienia etykiety', 'Hiep Long Mut Tet dried fruit mix gift box 600g', 'Hiep Long Mut Tet dried fruit mix gift box 600g', NULL, 'słodycze-przekąski', 'hiep-long-mut-tet-dried-fruit-mix-gift-box-600g'),
  ('folder14-048', 'ADG-001835', 'Zielona herbata Phuong Vy 100 g', 'Phuong Vy green tea 100 g', 'Phuong Vy', 'herbaty', 'zielona-herbata-phuong-vy-100-g', 'phuong-vy-green-tea-100-g', ARRAY['ingredients_expiry_pending']::text[], 'Żywność pozostaje draft do uzupełnienia etykiety', 'Phuong Vy green tea 100g', 'Phuong Vy green tea 100g', NULL, 'herbaty', 'phuong-vy-green-tea-100g'),
  ('folder14-049', 'ADG-001836', 'Wietnamskie ciastka z fasoli mung Minh Ngoc 300 g', 'Minh Ngoc Vietnamese mung bean cakes 300 g', 'Minh Ngoc', 'słodycze-przekąski', 'wietnamskie-ciastka-z-fasoli-mung-minh-ngoc-300-g', 'minh-ngoc-vietnamese-mung-bean-cakes-300-g', ARRAY['ingredients_allergens_expiry_pending']::text[], 'Żywność pozostaje draft do uzupełnienia etykiety', 'Minh Ngoc green bean cake / Banh dau xanh 300g', 'Minh Ngoc green bean cake / Banh dau xanh 300g', NULL, 'słodycze-przekąski', 'minh-ngoc-green-bean-cake-banh-dau-xanh-300g'),
  ('folder14-051', 'ADG-001838', 'Elektryczny garnek do ryżu Cuckoo SR-4600', 'Cuckoo SR-4600 electric rice cooker', 'Cuckoo', 'pozostałe-produkty', 'elektryczny-garnek-do-ryzu-cuckoo-sr-4600', 'cuckoo-sr-4600-electric-rice-cooker', ARRAY['capacity_condition_warranty_pending']::text[], 'Model SR-4600 jest widoczny na panelu', 'Cuckoo electric rice cooker, model unclear', 'Cuckoo electric rice cooker, model unclear', NULL, 'pozostałe-produkty', 'cuckoo-electric-rice-cooker-model-unclear'),
  ('folder14-052', 'ADG-001839', 'Brązowa taca do serwowania ze złotym wzorem', 'Brown serving tray with gold pattern', NULL, 'naczynia', 'brazowa-taca-do-serwowania-ze-zlotym-wzorem', 'brown-serving-tray-with-gold-pattern', ARRAY['size_unknown']::text[], 'Potwierdzić rozmiar', 'Brown serving / tea tray with gold pattern', 'Brown serving / tea tray with gold pattern', NULL, 'naczynia', 'brown-serving-tea-tray-with-gold-pattern'),
  ('folder14-053', 'ADG-001840', 'Duży garnek ze stali nierdzewnej z pokrywką', 'Large stainless steel stock pot with lid', NULL, 'naczynia', 'duzy-garnek-ze-stali-nierdzewnej-z-pokrywka', 'large-stainless-steel-stock-pot-with-lid', ARRAY['capacity_unknown']::text[], 'Potwierdzić pojemność', 'Large stainless stock pot with lid and side handles', 'Large stainless stock pot with lid and side handles', NULL, 'naczynia', 'large-stainless-stock-pot-with-lid-and-side-handles'),
  ('folder14-055', 'ADG-001842', 'Elektryczny garnek do ryżu Cuckoo CR-3511', 'Cuckoo CR-3511 electric rice cooker', 'Cuckoo', 'pozostałe-produkty', 'elektryczny-garnek-do-ryzu-cuckoo-cr-3511', 'cuckoo-cr-3511-electric-rice-cooker', ARRAY['capacity_condition_warranty_pending']::text[], 'Model CR-3511 jest widoczny na panelu', 'Electric rice cooker / warmer, model unclear', 'Electric rice cooker / warmer, model unclear', NULL, 'pozostałe-produkty', 'electric-rice-cooker-warmer-model-unclear'),
  ('folder14-056', 'ADG-001843', 'Wielopoziomowy garnek do gotowania na parze Manh Hung', 'Manh Hung multi-tier stainless steel steamer set', 'Manh Hung', 'naczynia', 'wielopoziomowy-garnek-do-gotowania-na-parze-manh-hung', 'manh-hung-multi-tier-stainless-steel-steamer-set', ARRAY['diameter_and_capacity_unknown']::text[], 'Potwierdzić średnicę i pojemność', 'Manh Hung stainless multi-tier steamer / pot set', 'Manh Hung stainless multi-tier steamer / pot set', NULL, 'naczynia', 'manh-hung-stainless-multi-tier-steamer-pot-set'),
  ('folder14-057', 'ADG-001844', 'Wykałaczki bambusowe Tam Nga - 200 szt.', 'Tam Nga bamboo toothpicks - 200 pcs', 'Tam Nga', 'pałeczki-i-sztućce', 'wykalaczki-bambusowe-tam-nga-200-szt', 'tam-nga-bamboo-toothpicks-200-pcs', ARRAY[]::text[], 'Liczba sztuk jest widoczna na opakowaniu', 'Tam Nga bamboo toothpicks, 200 pcs', 'Tam Nga bamboo toothpicks, 200 pcs', NULL, 'pałeczki-i-sztućce', 'tam-nga-bamboo-toothpicks-200-pcs');

WITH target AS (
  SELECT salon_id FROM channels WHERE slug = 'asiandeligo' AND is_active = true
)
DELETE FROM product_images pi
USING target t
WHERE pi.salon_id = t.salon_id
  AND pi.image_large_url IN ('https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001792/02-PETE7660.JPG', 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001792/03-PETE7661.JPG', 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001792/04-PETE7662.JPG', 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001794/02-PETE7760.JPG', 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001795/02-PETE8030.JPG', 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001795/03-PETE8031.JPG', 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001800/02-PETE8074.JPG', 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001819/02-PETE8130.JPG', 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001838/02-PETE8176.JPG', 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001840/02-PETE8194.JPG', 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001841/02-PETE8185.JPG');

WITH target AS (
  SELECT salon_id FROM channels WHERE slug = 'asiandeligo' AND is_active = true
), resolved AS (
  SELECT s.*, c.id AS old_category_id, p.id AS product_id, t.salon_id
  FROM _adg_f14_quality_rollback s
  CROSS JOIN target t
  JOIN products p
    ON p.salon_id = t.salon_id
   AND p.deleted_at IS NULL
   AND p.external_metadata->>'batch' = 'asiandeligo-new-products-folder14-20260713'
   AND p.external_metadata->>'review_id' = s.review_id
  JOIN categories c
    ON c.salon_id = t.salon_id
   AND c.slug = s.old_category_slug
   AND c.is_active = true
)
UPDATE products p
SET name = r.old_pl_name,
    slug = r.old_slug,
    category_id = r.old_category_id,
    brand = r.old_brand,
    name_translations = jsonb_build_object('pl', r.old_pl_name, 'en', r.old_en_name),
    external_metadata = COALESCE(p.external_metadata, '{}'::jsonb) - 'quality_review'
FROM resolved r
WHERE p.salon_id = r.salon_id AND p.id = r.product_id;

WITH target AS (
  SELECT salon_id FROM channels WHERE slug = 'asiandeligo' AND is_active = true
), resolved AS (
  SELECT s.*, p.id AS product_id, t.salon_id
  FROM _adg_f14_quality_rollback s
  CROSS JOIN target t
  JOIN products p
    ON p.salon_id = t.salon_id
   AND p.deleted_at IS NULL
   AND p.external_metadata->>'batch' = 'asiandeligo-new-products-folder14-20260713'
   AND p.external_metadata->>'review_id' = s.review_id
)
UPDATE product_variants pv
SET name = r.old_pl_name,
    display_name = r.old_pl_name,
    external_metadata = COALESCE(pv.external_metadata, '{}'::jsonb)
      - 'quality_reviewed_at' - 'quality_flags'
FROM resolved r
WHERE pv.salon_id = r.salon_id
  AND pv.template_id = r.product_id
  AND pv.deleted_at IS NULL
  AND pv.sku = r.draft_sku;

WITH target AS (
  SELECT salon_id FROM channels WHERE slug = 'asiandeligo' AND is_active = true
), resolved AS (
  SELECT s.*, p.id AS product_id, t.salon_id
  FROM _adg_f14_quality_rollback s
  CROSS JOIN target t
  JOIN products p
    ON p.salon_id = t.salon_id
   AND p.deleted_at IS NULL
   AND p.external_metadata->>'batch' = 'asiandeligo-new-products-folder14-20260713'
   AND p.external_metadata->>'review_id' = s.review_id
)
UPDATE product_translations pt
SET product_name = CASE pt.lang_id WHEN 'pl' THEN r.old_pl_name ELSE r.old_en_name END,
    slug = r.old_slug
FROM resolved r
WHERE pt.salon_id = r.salon_id
  AND pt.template_id = r.product_id
  AND pt.lang_id IN ('pl', 'en');

WITH target AS (
  SELECT salon_id FROM channels WHERE slug = 'asiandeligo' AND is_active = true
), resolved AS (
  SELECT s.*, p.id AS product_id, t.salon_id
  FROM _adg_f14_quality_rollback s
  CROSS JOIN target t
  JOIN products p
    ON p.salon_id = t.salon_id
   AND p.deleted_at IS NULL
   AND p.external_metadata->>'batch' = 'asiandeligo-new-products-folder14-20260713'
   AND p.external_metadata->>'review_id' = s.review_id
)
UPDATE product_images pi
SET alt_text = r.old_pl_name
FROM resolved r
WHERE pi.salon_id = r.salon_id
  AND pi.template_id = r.product_id;

COMMIT;
