-- Generated by scripts/catalog-data-remediation-plan.mjs
-- Purpose: roll back the exact-six Asia Deli Go catalog-data remediation.
-- Batch: asiandeligo-catalog-data-fix-20260721-v1
-- Decision SHA-256: 2cfcbb9f10277a814d33c8ded770f005f35b80ad7e9024f7c0cd61b7febe30d7
-- Only products rows are mutated. Variants and categories are read-only identity/status guards.
--
-- JOIN contract (schema-introspect verified against production 2026-07-21):
--   product_variants.template_id (uuid) = products.id (uuid), FK declared.
--   products.category_id (uuid) = categories.id (uuid), FK declared.
--   channels.salon_id/products.salon_id/product_variants.salon_id/categories.salon_id are uuid.
-- Assumptions:
--   1. Every business-table join is scoped by the one active asiandeligo channel and pinned salon UUID.
--   2. Exact product/variant statuses and soft-delete states match the reviewed decision snapshots.
--   3. products/product_variants/categories/channels are canonical; the dated backup/audit tables are intentional recovery artifacts.
-- Production trigger zz_enforce_products_monotonic_updated_at advances updated_at on every products UPDATE.

\set ON_ERROR_STOP on
BEGIN;
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '120s';
SET LOCAL search_path = public, pg_catalog;

CREATE TEMP TABLE _adg_catalog_data_target_salon (salon_id uuid PRIMARY KEY) ON COMMIT DROP;
INSERT INTO _adg_catalog_data_target_salon (salon_id)
SELECT salon_id
FROM channels
WHERE salon_id = 'e73271a9-53e3-4a20-a02e-791726b452aa'::uuid
  AND slug = 'asiandeligo'
  AND is_active = TRUE;

CREATE TEMP TABLE _adg_catalog_data_run (
  batch_key text PRIMARY KEY,
  decision_sha256 text NOT NULL,
  channel_slug text NOT NULL,
  salon_id uuid NOT NULL UNIQUE,
  recorded_at timestamptz NOT NULL
) ON COMMIT DROP;
INSERT INTO _adg_catalog_data_run (
  batch_key, decision_sha256, channel_slug, salon_id, recorded_at
)
SELECT 'asiandeligo-catalog-data-fix-20260721-v1', '2cfcbb9f10277a814d33c8ded770f005f35b80ad7e9024f7c0cd61b7febe30d7', 'asiandeligo',
       salon_id, transaction_timestamp()
FROM _adg_catalog_data_target_salon;

CREATE TEMP TABLE _adg_catalog_data_decisions (
  sku text PRIMARY KEY,
  product_id uuid NOT NULL UNIQUE,
  variant_id uuid NOT NULL UNIQUE,
  product_name text NOT NULL,
  product_slug text NOT NULL,
  expected_updated_at timestamptz NOT NULL,
  expected_product_is_active boolean NOT NULL,
  expected_product_is_published boolean NOT NULL,
  expected_product_is_visible boolean NOT NULL,
  expected_product_status text NOT NULL,
  expected_product_deleted_at timestamptz,
  expected_variant_is_active boolean NOT NULL,
  expected_variant_is_published boolean NOT NULL,
  expected_variant_is_for_sale boolean NOT NULL,
  expected_variant_sync_status text NOT NULL,
  expected_variant_availability_status text NOT NULL,
  expected_variant_deleted_at timestamptz,
  expected_allergens jsonb,
  target_allergens jsonb,
  expected_storage_zone text,
  target_storage_zone text,
  expected_nutrition_facts jsonb,
  target_nutrition_facts jsonb,
  expected_price_per_unit numeric,
  target_price_per_unit numeric,
  expected_unit_of_measure text,
  target_unit_of_measure text,
  expected_category_id uuid NOT NULL,
  expected_category_name text NOT NULL,
  expected_category_slug text NOT NULL,
  expected_category_is_active boolean NOT NULL,
  target_category_id uuid NOT NULL,
  target_category_name text NOT NULL,
  target_category_slug text NOT NULL,
  target_category_is_active boolean NOT NULL,
  confidence text NOT NULL CHECK (confidence = 'high'),
  reason text NOT NULL,
  evidence_urls jsonb NOT NULL CHECK (jsonb_typeof(evidence_urls) = 'array')
) ON COMMIT DROP;
INSERT INTO _adg_catalog_data_decisions (
  sku, product_id, variant_id, product_name, product_slug, expected_updated_at,
  expected_product_is_active, expected_product_is_published, expected_product_is_visible,
  expected_product_status, expected_product_deleted_at,
  expected_variant_is_active, expected_variant_is_published, expected_variant_is_for_sale,
  expected_variant_sync_status, expected_variant_availability_status, expected_variant_deleted_at,
  expected_allergens, target_allergens, expected_storage_zone, target_storage_zone,
  expected_nutrition_facts, target_nutrition_facts,
  expected_price_per_unit, target_price_per_unit,
  expected_unit_of_measure, target_unit_of_measure,
  expected_category_id, expected_category_name, expected_category_slug, expected_category_is_active,
  target_category_id, target_category_name, target_category_slug, target_category_is_active,
  confidence, reason, evidence_urls
) VALUES
  (
    'ADG-000404', '66852048-369d-4dc3-9b32-07d1bc68df24'::uuid, '851bbd63-66a5-4ddc-92c9-27f461dbb556'::uuid,
    'Kimchi Hot 300g - Runoland', 'kimchi-hot-300g-runoland', '2026-07-08T12:12:07.93723Z'::timestamptz,
    TRUE, TRUE, TRUE, 'active', NULL::timestamptz,
    TRUE, FALSE, TRUE, 'synced', 'IN_STOCK', NULL::timestamptz,
    '["cereals"]'::jsonb, '["cereals","fish"]'::jsonb,
    'AMBIENT'::text, 'AMBIENT'::text,
    '{"fat":0.5,"salt":2.2,"carbs":9.7,"sugar":3.3,"protein":2.2,"calories":50,"servingSize":"w 100g/100ml","saturatedFat":0.1}'::jsonb, '{"fat":0.5,"salt":2.2,"carbs":9.7,"sugar":3.3,"protein":2.2,"calories":50,"servingSize":"w 100g/100ml","saturatedFat":0.1}'::jsonb,
    '36.33'::numeric, '36.33'::numeric,
    'KG'::text, 'KG'::text,
    '8c4c679a-f5e8-427c-b734-1b20eb12a97b'::uuid, 'Kimchi', 'kimchi', TRUE,
    '8c4c679a-f5e8-427c-b734-1b20eb12a97b'::uuid, 'Kimchi', 'kimchi', TRUE,
    'high', 'The supplier label lists wheat and fish sauce; retain cereals and add fish.', '[{"url":"https://kimchi.pl/product-pol-2168.html","kind":"supplier-label","supports":"Ingredient and allergen warning lists wheat and fish sauce."},{"url":"https://asiandeligo.eshoper.pro/products/kimchi-hot-300g-runoland","kind":"public-pdp","supports":"Confirms the public product identity and current 300g pack."}]'::jsonb
  ),
  (
    'ADG-000702', '83a6fbe5-3152-4a0c-9a89-8a1c00decfd5'::uuid, '935a36fc-900a-4047-b262-6ee23c2fb7f1'::uuid,
    'Edomae Inari Age, smażone kieszonki tofu (24 szt.) 540g - Nishimoto', 'edomae-inari-age-smazone-kieszonki-tofu-24-szt-540g-nishimoto', '2026-07-08T12:12:07.93723Z'::timestamptz,
    TRUE, TRUE, TRUE, 'active', NULL::timestamptz,
    TRUE, FALSE, TRUE, 'synced', 'IN_STOCK', NULL::timestamptz,
    '[]'::jsonb, '["cereals","soybeans"]'::jsonb,
    NULL::text, 'AMBIENT'::text,
    NULL::jsonb, '{"calories":263,"fat":13.2,"saturatedFat":2.45,"carbs":29.5,"sugar":27.9,"protein":8.3,"salt":1.48,"servingSize":"w 100g/100ml"}'::jsonb,
    '59.26'::numeric, '59.26'::numeric,
    'KG'::text, 'KG'::text,
    'd7442ca6-6767-46e4-9e12-ff8d0f824d89'::uuid, 'Tofu', 'tofu', TRUE,
    'd7442ca6-6767-46e4-9e12-ff8d0f824d89'::uuid, 'Tofu', 'tofu', TRUE,
    'high', 'Two independent retail listings agree on wheat/soy allergens, ambient storage, and the complete per-100g nutrition panel.', '[{"url":"https://yamatomarket.pl/product/tofu-inari-540g-nishimoto/","kind":"retailer-label","supports":"Product ingredients, allergen, storage, and nutrition label."},{"url":"https://paleczkami.pl/product-pol-3396-Inari-smazone-kieszonki-tofu-540g-Nishimoto.html","kind":"retailer-label","supports":"Independent corroboration of the 540g Nishimoto product metadata."},{"url":"https://asiandeligo.eshoper.pro/products/edomae-inari-age-smazone-kieszonki-tofu-24-szt-540g-nishimoto","kind":"public-pdp","supports":"Confirms the public product identity."}]'::jsonb
  ),
  (
    'ADG-001014', 'f530e430-4d1d-42d4-a1d3-d33d90b0a395'::uuid, '6f1272e3-05c0-4df9-be94-ee15c8cc2291'::uuid,
    'Bento Squid Snack Sweet & Spicy, przekąska z kałamarnicy słodko-ostra 20g - Bento & Co', 'bento-squid-snack-sweet-and-spicy-przekaska-z-kalamarnicy-slodko-ostra-20g-bento-and-co', '2026-07-09T12:38:27.209063Z'::timestamptz,
    TRUE, TRUE, TRUE, 'active', NULL::timestamptz,
    TRUE, FALSE, TRUE, 'synced', 'IN_STOCK', NULL::timestamptz,
    '["cereals","fish","molluscs"]'::jsonb, '["cereals","fish","molluscs"]'::jsonb,
    'AMBIENT'::text, 'AMBIENT'::text,
    '{"fat":0.5,"salt":6.6,"carbs":52,"sugar":26,"protein":23,"calories":610,"servingSize":"w 100g/100ml"}'::jsonb, '{"calories":347,"fat":2.1,"saturatedFat":0.5,"carbs":57,"sugar":30,"protein":24,"salt":5,"servingSize":"w 100g/100ml"}'::jsonb,
    '480.00'::numeric, '480.00'::numeric,
    'KG'::text, 'KG'::text,
    '43098ab7-106a-47f1-b91b-aa497c1c62db'::uuid, 'Dania gotowe', 'dania-gotowe', TRUE,
    '5825ea08-e9d9-4786-aaad-05c4dde1131e'::uuid, 'Słodycze / Przekąski', 'słodycze-przekąski', TRUE,
    'high', 'Three current retailer records tied to EAN 8850157405836 agree on the same per-100g nutrition panel; this is a packaged squid snack, not a ready meal.', '[{"url":"https://asiapoint.de/tintenfisch-snack-sweet-spicy-bento-20g","kind":"retailer-label","supports":"EAN 8850157405836 and the reviewed per-100g nutrition panel."},{"url":"https://www.fiksuruoka.fi/product/29091/bento-mixed-seafood-snack-sweet--spicy-merenelavasnacks-20g","kind":"retailer-label","supports":"Independent EAN 8850157405836 record with the same nutrition values."},{"url":"https://www.tavato.de/p/8850157405836","kind":"retailer-label","supports":"Independent EAN-keyed record with the same nutrition values."},{"url":"https://asiandeligo.eshoper.pro/products/bento-squid-snack-sweet-and-spicy-przekaska-z-kalamarnicy-slodko-ostra-20g-bento-and-co","kind":"public-pdp","supports":"Confirms the public product identity and current category."}]'::jsonb
  ),
  (
    'ADG-001382', '7f821fb2-729b-411d-aa9a-f34886fea0ec'::uuid, 'b9ff2de6-0788-4336-b756-846afff9fc8a'::uuid,
    '2 x Dubai Chocolate, zestaw czekolad dubajskich z kremem pistacjowym i ciastem kataifi - mleczna i biała 160g Q Chew', '2-x-dubai-chocolate-zestaw-czekolad-dubajskich-z-kremem-pistacjowym-i-ciastem-kataifi-mleczna-i-biala-160g-q-chew', '2026-07-08T12:12:07.93723Z'::timestamptz,
    TRUE, TRUE, TRUE, 'active', NULL::timestamptz,
    TRUE, FALSE, TRUE, 'synced', 'IN_STOCK', NULL::timestamptz,
    '["cereals","soybeans","milk","nuts"]'::jsonb, '["cereals","soybeans","milk","nuts"]'::jsonb,
    'AMBIENT'::text, 'AMBIENT'::text,
    '{"fat":32.9,"salt":50.7,"carbs":53.1,"sugar":40.4,"protein":10.9,"calories":552,"servingSize":"w 100g/100ml","saturatedFat":19.4}'::jsonb, '{"fat":32.9,"salt":50.7,"carbs":53.1,"sugar":40.4,"protein":10.9,"calories":552,"servingSize":"w 100g/100ml","saturatedFat":19.4}'::jsonb,
    '623.75'::numeric, '311.88'::numeric,
    'KG'::text, 'KG'::text,
    '5825ea08-e9d9-4786-aaad-05c4dde1131e'::uuid, 'Słodycze / Przekąski', 'słodycze-przekąski', TRUE,
    '5825ea08-e9d9-4786-aaad-05c4dde1131e'::uuid, 'Słodycze / Przekąski', 'słodycze-przekąski', TRUE,
    'high', 'The bundle contains two 160g bars, so the unit-price denominator is 320g. The suspicious salt value remains unchanged pending a physical or importer-label check.', '[{"url":"https://kimchi.pl/product-pol-5215.html","kind":"supplier-label","supports":"Confirms the two 160g component products used for the unit-price denominator; salt is not changed in this batch."},{"url":"https://asiandeligo.eshoper.pro/products/2-x-dubai-chocolate-zestaw-czekolad-dubajskich-z-kremem-pistacjowym-i-ciastem-kataifi-mleczna-i-biala-160g-q-chew","kind":"public-pdp","supports":"Confirms the public bundle identity and current unit price."}]'::jsonb
  ),
  (
    'ADG-001383', 'adcd2bb3-9284-4ac4-9766-2d39c319ad86'::uuid, 'a4516e39-1a7b-466d-8c29-4cd5ac1b0269'::uuid,
    '2 x Angel Hair Chocolate, zestaw czekolad z anielskim włosiem i pistacjami - biała i różowa 80g Mistachio', '2-x-angel-hair-chocolate-zestaw-czekolad-z-anielskim-wlosiem-i-pistacjami-biala-i-rozowa-80g-mistachio', '2026-07-08T12:12:07.93723Z'::timestamptz,
    TRUE, TRUE, TRUE, 'active', NULL::timestamptz,
    TRUE, FALSE, TRUE, 'synced', 'IN_STOCK', NULL::timestamptz,
    '["cereals","soybeans","milk","nuts"]'::jsonb, '["cereals","soybeans","milk","nuts"]'::jsonb,
    'AMBIENT'::text, 'AMBIENT'::text,
    '{"fat":25,"salt":0.45,"carbs":57,"sugar":38,"protein":10,"calories":493,"servingSize":"w 100g/100ml","saturatedFat":17}'::jsonb, '{"fat":25,"salt":0.45,"carbs":57,"sugar":38,"protein":10,"calories":493,"servingSize":"w 100g/100ml","saturatedFat":17}'::jsonb,
    '886.25'::numeric, '443.13'::numeric,
    'KG'::text, 'KG'::text,
    '5825ea08-e9d9-4786-aaad-05c4dde1131e'::uuid, 'Słodycze / Przekąski', 'słodycze-przekąski', TRUE,
    '5825ea08-e9d9-4786-aaad-05c4dde1131e'::uuid, 'Słodycze / Przekąski', 'słodycze-przekąski', TRUE,
    'high', 'The bundle visibly contains two 80g packs, so its total comparison-price denominator is 160g rather than 80g.', '[{"url":"https://img.zira.pl/asiandeligo/products/KIMCHI-5216/1.webp","kind":"public-product-image","supports":"Shows two component packs, each marked 80g."},{"url":"https://kimchi.pl/product-pol-5216.html","kind":"supplier-listing","supports":"Confirms the two-pack bundle identity."},{"url":"https://asiandeligo.eshoper.pro/products/2-x-angel-hair-chocolate-zestaw-czekolad-z-anielskim-wlosiem-i-pistacjami-biala-i-rozowa-80g-mistachio","kind":"public-pdp","supports":"Confirms the public bundle identity and current unit price."}]'::jsonb
  ),
  (
    'ADG-001750', 'afb16814-879c-48ce-aa7e-d444740c35ad'::uuid, 'd5f36da0-410e-4c16-8519-0e6b13ee754c'::uuid,
    'Buldak Hot Sauce Carbonara Flavour - sos o smaku pikantnego kurczaka carbonara 165ml Samyang', 'buldak-hot-sauce-carbonara-flavour-sos-o-smaku-pikantnego-kurczaka-carbonara-165ml-samyang', '2026-07-08T12:12:07.93723Z'::timestamptz,
    TRUE, TRUE, TRUE, 'active', NULL::timestamptz,
    TRUE, FALSE, TRUE, 'synced', 'IN_STOCK', NULL::timestamptz,
    '["cereals","soybeans","celery"]'::jsonb, '["cereals","soybeans","celery"]'::jsonb,
    'AMBIENT'::text, 'AMBIENT'::text,
    '{"fat":17,"salt":5.8,"carbs":42,"sugar":23,"protein":4.1,"calories":346,"servingSize":"w 100g/100ml","saturatedFat":5.4}'::jsonb, '{"fat":17,"salt":5.8,"carbs":42,"sugar":23,"protein":4.1,"calories":346,"servingSize":"w 100g/100ml","saturatedFat":5.4}'::jsonb,
    '166.67'::numeric, '166.67'::numeric,
    'LITER'::text, 'LITER'::text,
    '7da30509-aad0-475e-ab39-ca7764bffda2'::uuid, 'Ramyun / Ramen', 'ramyun-ramen', TRUE,
    '691e2a51-4453-4fd9-bd02-f9abdf9a0def'::uuid, 'Sosy, marynaty', 'sosy-marynaty', TRUE,
    'high', 'The item is a 165ml bottled hot sauce; move it from instant noodles to the sauce and marinade taxonomy.', '[{"url":"https://kimchi.pl/product-pol-5783.html","kind":"supplier-listing","supports":"Title and contents identify a 165ml hot sauce."},{"url":"https://asiandeligo.eshoper.pro/products/buldak-hot-sauce-carbonara-flavour-sos-o-smaku-pikantnego-kurczaka-carbonara-165ml-samyang","kind":"public-pdp","supports":"Confirms the public product identity and current Ramyun category."}]'::jsonb
  );


DO $$
BEGIN
  IF (SELECT COUNT(*) FROM _adg_catalog_data_target_salon) <> 1 THEN
    RAISE EXCEPTION 'Expected exactly one active pinned Asia Deli Go channel';
  END IF;
  IF (SELECT COUNT(*) FROM _adg_catalog_data_decisions) <> 6 THEN
    RAISE EXCEPTION 'Expected exactly 6 catalog-data decisions';
  END IF;
  IF (
    SELECT COUNT(*)
    FROM asiandeligo_catalog_data_product_backup_20260721 backup
    JOIN _adg_catalog_data_run run
      ON backup.batch_key = run.batch_key
     AND backup.decision_sha256 = run.decision_sha256
     AND backup.channel_slug = run.channel_slug
     AND backup.salon_id = run.salon_id
  ) <> 6 THEN
    RAISE EXCEPTION 'Expected exactly 6 tenant- and decision-scoped backup rows';
  END IF;
  IF EXISTS (
    SELECT decision.sku
    FROM _adg_catalog_data_decisions decision
    CROSS JOIN _adg_catalog_data_run run
    LEFT JOIN asiandeligo_catalog_data_product_backup_20260721 backup
      ON backup.batch_key = run.batch_key
     AND backup.decision_sha256 = run.decision_sha256
     AND backup.channel_slug = run.channel_slug
     AND backup.salon_id = run.salon_id
     AND backup.sku = decision.sku
     AND backup.product_id = decision.product_id
     AND backup.variant_id = decision.variant_id
     AND backup.product_name = decision.product_name
     AND backup.product_slug = decision.product_slug
     AND backup.original_updated_at = decision.expected_updated_at
     AND backup.original_product_is_active = decision.expected_product_is_active
     AND backup.original_product_is_published = decision.expected_product_is_published
     AND backup.original_product_is_visible = decision.expected_product_is_visible
     AND backup.original_product_status = decision.expected_product_status
     AND backup.original_product_deleted_at IS NOT DISTINCT FROM decision.expected_product_deleted_at
     AND backup.original_variant_is_active = decision.expected_variant_is_active
     AND backup.original_variant_is_published = decision.expected_variant_is_published
     AND backup.original_variant_is_for_sale = decision.expected_variant_is_for_sale
     AND backup.original_variant_sync_status = decision.expected_variant_sync_status
     AND backup.original_variant_availability_status = decision.expected_variant_availability_status
     AND backup.original_variant_deleted_at IS NOT DISTINCT FROM decision.expected_variant_deleted_at
     AND backup.original_allergens IS NOT DISTINCT FROM decision.expected_allergens
     AND backup.target_allergens IS NOT DISTINCT FROM decision.target_allergens
     AND backup.original_storage_zone IS NOT DISTINCT FROM decision.expected_storage_zone
     AND backup.target_storage_zone IS NOT DISTINCT FROM decision.target_storage_zone
     AND backup.original_nutrition_facts IS NOT DISTINCT FROM decision.expected_nutrition_facts
     AND backup.target_nutrition_facts IS NOT DISTINCT FROM decision.target_nutrition_facts
     AND backup.original_price_per_unit IS NOT DISTINCT FROM decision.expected_price_per_unit
     AND backup.target_price_per_unit IS NOT DISTINCT FROM decision.target_price_per_unit
     AND backup.original_unit_of_measure IS NOT DISTINCT FROM decision.expected_unit_of_measure
     AND backup.target_unit_of_measure IS NOT DISTINCT FROM decision.target_unit_of_measure
     AND backup.original_category_id = decision.expected_category_id
     AND backup.original_category_name = decision.expected_category_name
     AND backup.original_category_slug = decision.expected_category_slug
     AND backup.original_category_is_active = decision.expected_category_is_active
     AND backup.target_category_id = decision.target_category_id
     AND backup.target_category_name = decision.target_category_name
     AND backup.target_category_slug = decision.target_category_slug
     AND backup.target_category_is_active = decision.target_category_is_active
     AND backup.confidence = decision.confidence
     AND backup.reason = decision.reason
     AND backup.evidence_urls = decision.evidence_urls
    WHERE backup.product_id IS NULL
  ) THEN
    RAISE EXCEPTION 'Persistent backup does not exactly match the reviewed decision file';
  END IF;
  IF (
    SELECT COUNT(*)
    FROM asiandeligo_catalog_data_audit_20260721 audit
    JOIN _adg_catalog_data_run run
      ON audit.batch_key = run.batch_key
     AND audit.decision_sha256 = run.decision_sha256
     AND audit.channel_slug = run.channel_slug
     AND audit.salon_id = run.salon_id
    WHERE audit.action IN ('backup_captured', 'apply_complete')
  ) <> 2 OR EXISTS (
    SELECT 1
    FROM asiandeligo_catalog_data_audit_20260721 audit
    JOIN _adg_catalog_data_run run
      ON audit.batch_key = run.batch_key
     AND audit.decision_sha256 = run.decision_sha256
     AND audit.channel_slug = run.channel_slug
     AND audit.salon_id = run.salon_id
    WHERE audit.action = 'rollback_complete'
  ) THEN
    RAISE EXCEPTION 'Apply audit precondition failed or this one-shot batch was already rolled back';
  END IF;

  IF EXISTS (
    SELECT backup.sku
    FROM asiandeligo_catalog_data_product_backup_20260721 backup
    JOIN _adg_catalog_data_run run
      ON backup.batch_key = run.batch_key
     AND backup.decision_sha256 = run.decision_sha256
     AND backup.channel_slug = run.channel_slug
     AND backup.salon_id = run.salon_id
    LEFT JOIN product_variants variant
      ON variant.salon_id = run.salon_id
     AND variant.id = backup.variant_id
     AND variant.template_id = backup.product_id
     AND variant.sku = backup.sku
     AND variant.is_active = backup.original_variant_is_active
     AND variant.is_published = backup.original_variant_is_published
     AND variant.is_for_sale = backup.original_variant_is_for_sale
     AND variant.sync_status = backup.original_variant_sync_status
     AND variant.availability_status = backup.original_variant_availability_status
     AND variant.deleted_at IS NOT DISTINCT FROM backup.original_variant_deleted_at
    LEFT JOIN products product
      ON product.salon_id = run.salon_id
     AND product.id = backup.product_id
     AND product.id = variant.template_id
     AND product.name = backup.product_name
     AND product.slug = backup.product_slug
     AND product.updated_at = backup.applied_updated_at
     AND product.is_active = backup.original_product_is_active
     AND product.is_published = backup.original_product_is_published
     AND product.is_visible = backup.original_product_is_visible
     AND product.status = backup.original_product_status
     AND product.deleted_at IS NOT DISTINCT FROM backup.original_product_deleted_at
     AND product.allergens IS NOT DISTINCT FROM backup.target_allergens
     AND product.storage_zone IS NOT DISTINCT FROM backup.target_storage_zone
     AND product.nutrition_facts IS NOT DISTINCT FROM backup.target_nutrition_facts
     AND product.price_per_unit IS NOT DISTINCT FROM backup.target_price_per_unit
     AND product.unit_of_measure IS NOT DISTINCT FROM backup.target_unit_of_measure
     AND product.category_id = backup.target_category_id
    LEFT JOIN categories source_category
      ON source_category.salon_id = run.salon_id
     AND source_category.id = backup.original_category_id
     AND source_category.name = backup.original_category_name
     AND source_category.slug = backup.original_category_slug
     AND source_category.is_active = backup.original_category_is_active
    LEFT JOIN categories target_category
      ON target_category.salon_id = run.salon_id
     AND target_category.id = backup.target_category_id
     AND target_category.name = backup.target_category_name
     AND target_category.slug = backup.target_category_slug
     AND target_category.is_active = backup.target_category_is_active
    WHERE variant.id IS NULL
       OR product.id IS NULL
       OR source_category.id IS NULL
       OR target_category.id IS NULL
       OR backup.applied_updated_at IS NULL
  ) THEN
    RAISE EXCEPTION 'Exact post-apply state changed; refusing to overwrite intervening edits';
  END IF;
END $$;

DO $$
DECLARE
  affected integer;
BEGIN
  UPDATE products product
  SET allergens = backup.original_allergens,
      storage_zone = backup.original_storage_zone,
      nutrition_facts = backup.original_nutrition_facts,
      price_per_unit = backup.original_price_per_unit,
      unit_of_measure = backup.original_unit_of_measure,
      category_id = backup.original_category_id
  FROM _adg_catalog_data_run run,
       asiandeligo_catalog_data_product_backup_20260721 backup,
       product_variants variant,
       categories source_category,
       categories target_category
  WHERE backup.batch_key = run.batch_key
    AND backup.decision_sha256 = run.decision_sha256
    AND backup.channel_slug = run.channel_slug
    AND backup.salon_id = run.salon_id
    AND product.salon_id = run.salon_id
    AND product.id = backup.product_id
    AND product.name = backup.product_name
    AND product.slug = backup.product_slug
    AND product.updated_at = backup.applied_updated_at
    AND product.is_active = backup.original_product_is_active
    AND product.is_published = backup.original_product_is_published
    AND product.is_visible = backup.original_product_is_visible
    AND product.status = backup.original_product_status
    AND product.deleted_at IS NOT DISTINCT FROM backup.original_product_deleted_at
    AND product.allergens IS NOT DISTINCT FROM backup.target_allergens
    AND product.storage_zone IS NOT DISTINCT FROM backup.target_storage_zone
    AND product.nutrition_facts IS NOT DISTINCT FROM backup.target_nutrition_facts
    AND product.price_per_unit IS NOT DISTINCT FROM backup.target_price_per_unit
    AND product.unit_of_measure IS NOT DISTINCT FROM backup.target_unit_of_measure
    AND product.category_id = backup.target_category_id
    AND variant.salon_id = run.salon_id
    AND variant.id = backup.variant_id
    AND variant.template_id = product.id
    AND variant.sku = backup.sku
    AND variant.is_active = backup.original_variant_is_active
    AND variant.is_published = backup.original_variant_is_published
    AND variant.is_for_sale = backup.original_variant_is_for_sale
    AND variant.sync_status = backup.original_variant_sync_status
    AND variant.availability_status = backup.original_variant_availability_status
    AND variant.deleted_at IS NOT DISTINCT FROM backup.original_variant_deleted_at
    AND source_category.salon_id = run.salon_id
    AND source_category.id = backup.original_category_id
    AND source_category.name = backup.original_category_name
    AND source_category.slug = backup.original_category_slug
    AND source_category.is_active = backup.original_category_is_active
    AND target_category.salon_id = run.salon_id
    AND target_category.id = backup.target_category_id
    AND target_category.name = backup.target_category_name
    AND target_category.slug = backup.target_category_slug
    AND target_category.is_active = backup.target_category_is_active;
  GET DIAGNOSTICS affected = ROW_COUNT;
  IF affected <> 6 THEN
    RAISE EXCEPTION 'Expected 6 exact product restorations, got %', affected;
  END IF;

  IF EXISTS (
    SELECT backup.sku
    FROM asiandeligo_catalog_data_product_backup_20260721 backup
    JOIN _adg_catalog_data_run run
      ON backup.batch_key = run.batch_key
     AND backup.decision_sha256 = run.decision_sha256
     AND backup.channel_slug = run.channel_slug
     AND backup.salon_id = run.salon_id
    LEFT JOIN products product
      ON product.salon_id = run.salon_id
     AND product.id = backup.product_id
     AND product.name = backup.product_name
     AND product.slug = backup.product_slug
     AND product.updated_at > backup.applied_updated_at
     AND product.is_active = backup.original_product_is_active
     AND product.is_published = backup.original_product_is_published
     AND product.is_visible = backup.original_product_is_visible
     AND product.status = backup.original_product_status
     AND product.deleted_at IS NOT DISTINCT FROM backup.original_product_deleted_at
     AND product.allergens IS NOT DISTINCT FROM backup.original_allergens
     AND product.storage_zone IS NOT DISTINCT FROM backup.original_storage_zone
     AND product.nutrition_facts IS NOT DISTINCT FROM backup.original_nutrition_facts
     AND product.price_per_unit IS NOT DISTINCT FROM backup.original_price_per_unit
     AND product.unit_of_measure IS NOT DISTINCT FROM backup.original_unit_of_measure
     AND product.category_id = backup.original_category_id
    WHERE product.id IS NULL
  ) THEN
    RAISE EXCEPTION 'Exact rollback restoration or monotonic updated_at verification failed';
  END IF;

  INSERT INTO asiandeligo_catalog_data_audit_20260721 (
    batch_key, decision_sha256, channel_slug, salon_id, recorded_at, action, product_rows
  )
  SELECT batch_key, decision_sha256, channel_slug, salon_id, clock_timestamp(),
         'rollback_complete', 6
  FROM _adg_catalog_data_run;
  GET DIAGNOSTICS affected = ROW_COUNT;
  IF affected <> 1 THEN
    RAISE EXCEPTION 'Expected one rollback audit row, got %', affected;
  END IF;
END $$;

SELECT backup.sku, product.name, backup.target_category_slug, backup.original_category_slug,
       backup.target_price_per_unit, backup.original_price_per_unit,
       audit.recorded_at AS rolled_back_at
FROM _adg_catalog_data_run run
JOIN asiandeligo_catalog_data_product_backup_20260721 backup
  ON backup.batch_key = run.batch_key
 AND backup.decision_sha256 = run.decision_sha256
 AND backup.channel_slug = run.channel_slug
 AND backup.salon_id = run.salon_id
JOIN products product
  ON product.salon_id = run.salon_id
 AND product.id = backup.product_id
JOIN asiandeligo_catalog_data_audit_20260721 audit
  ON audit.batch_key = run.batch_key
 AND audit.decision_sha256 = run.decision_sha256
 AND audit.channel_slug = run.channel_slug
 AND audit.salon_id = run.salon_id
 AND audit.action = 'rollback_complete'
ORDER BY backup.sku;

COMMIT;
