-- Generated by scripts/folder14-duplicate-merge-plan.mjs
-- Confirmed owner decision: merge ADG-001811 into ADG-001803.
-- The duplicate product/variant are soft-deleted; its image is moved to the survivor gallery.
-- No product is published or enabled for sale.
--
-- JOIN contract (schema-introspect verified 2026-07-13):
--   product_variants.template_id (uuid) = products.id (uuid), FK declared.
--   product_images.template_id (uuid) = products.id (uuid), FK declared.
--   Every business table is filtered by the active asiandeligo salon_id.

BEGIN;

DO $$
DECLARE
  target_salon_id uuid;
  channel_count integer;
  target_count integer;
  duplicate_count integer;
  duplicate_image_count integer;
  new_url_conflict_count integer;
BEGIN
  SELECT count(*) INTO channel_count
  FROM channels WHERE slug = 'asiandeligo' AND is_active = true;
  IF channel_count <> 1 THEN
    RAISE EXCEPTION 'Expected one active asiandeligo channel, got %', channel_count;
  END IF;
  SELECT salon_id INTO STRICT target_salon_id
  FROM channels WHERE slug = 'asiandeligo' AND is_active = true;

  SELECT count(*) INTO target_count
  FROM products p
  JOIN product_variants pv
    ON pv.salon_id = target_salon_id
   AND pv.template_id = p.id
   AND pv.deleted_at IS NULL
   AND pv.sku = 'ADG-001803'
  WHERE p.salon_id = target_salon_id
    AND p.deleted_at IS NULL
    AND p.external_metadata->>'batch' = 'asiandeligo-new-products-folder14-20260713'
    AND p.external_metadata->>'review_id' = 'folder14-012'
    AND p.status = 'draft'
    AND p.is_published = false
    AND pv.is_published = false
    AND pv.is_for_sale = false;
  IF target_count <> 1 THEN
    RAISE EXCEPTION 'Survivor guard failed, got % rows', target_count;
  END IF;

  SELECT count(*) INTO duplicate_count
  FROM products p
  JOIN product_variants pv
    ON pv.salon_id = target_salon_id
   AND pv.template_id = p.id
   AND pv.deleted_at IS NULL
   AND pv.sku = 'ADG-001811'
  WHERE p.salon_id = target_salon_id
    AND p.deleted_at IS NULL
    AND p.external_metadata->>'batch' = 'asiandeligo-new-products-folder14-20260713'
    AND p.external_metadata->>'review_id' = 'folder14-020'
    AND p.status = 'draft'
    AND p.is_published = false
    AND pv.is_published = false
    AND pv.is_for_sale = false;
  IF duplicate_count <> 1 THEN
    RAISE EXCEPTION 'Duplicate guard failed, got % rows', duplicate_count;
  END IF;

  SELECT count(*) INTO duplicate_image_count
  FROM products p
  JOIN product_images pi
    ON pi.salon_id = target_salon_id
   AND pi.template_id = p.id
   AND pi.image_large_url = 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001811/01-PETE8104.JPG'
   AND pi.file_hash = 'e51a856a30c62a39a3f0779ccc6c74f591762b6cd4030aa75a16ca7bd75b2184'
  WHERE p.salon_id = target_salon_id
    AND p.deleted_at IS NULL
    AND p.external_metadata->>'review_id' = 'folder14-020';
  IF duplicate_image_count <> 1 THEN
    RAISE EXCEPTION 'Expected one duplicate image row, got %', duplicate_image_count;
  END IF;

  SELECT count(*) INTO new_url_conflict_count
  FROM product_images pi
  WHERE pi.salon_id = target_salon_id
    AND pi.image_large_url = 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001803/02-PETE8104.JPG?v=20260713';
  IF new_url_conflict_count <> 0 THEN
    RAISE EXCEPTION 'Merged image URL already exists';
  END IF;
END $$;

WITH target_channel AS (
  SELECT salon_id FROM channels WHERE slug = 'asiandeligo' AND is_active = true
), resolved AS (
  SELECT survivor.id AS survivor_id, duplicate.id AS duplicate_id, tc.salon_id
  FROM target_channel tc
  JOIN products survivor
    ON survivor.salon_id = tc.salon_id
   AND survivor.deleted_at IS NULL
   AND survivor.external_metadata->>'batch' = 'asiandeligo-new-products-folder14-20260713'
   AND survivor.external_metadata->>'review_id' = 'folder14-012'
  JOIN products duplicate
    ON duplicate.salon_id = tc.salon_id
   AND duplicate.deleted_at IS NULL
   AND duplicate.external_metadata->>'batch' = 'asiandeligo-new-products-folder14-20260713'
   AND duplicate.external_metadata->>'review_id' = 'folder14-020'
)
UPDATE product_images pi
SET template_id = r.survivor_id,
    priority = 1,
    is_primary = false,
    image_large_url = 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001803/02-PETE8104.JPG?v=20260713',
    image_medium_url = 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001803/02-PETE8104.JPG?v=20260713',
    image_small_url = 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001803/02-PETE8104.JPG?v=20260713',
    url_small = 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001803/02-PETE8104.JPG?v=20260713',
    url_thumbnail = 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001803/02-PETE8104.JPG?v=20260713',
    url_micro = 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001803/02-PETE8104.JPG?v=20260713',
    r2_keys = jsonb_build_array('owner-images/folder14/ADG-001803/02-PETE8104.JPG'),
    alt_text = (SELECT name FROM products WHERE id = r.survivor_id)
FROM resolved r
WHERE pi.salon_id = r.salon_id
  AND pi.template_id = r.duplicate_id
  AND pi.image_large_url = 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001811/01-PETE8104.JPG'
  AND pi.file_hash = 'e51a856a30c62a39a3f0779ccc6c74f591762b6cd4030aa75a16ca7bd75b2184';

WITH target_channel AS (
  SELECT salon_id FROM channels WHERE slug = 'asiandeligo' AND is_active = true
), duplicate_product AS (
  SELECT p.id, tc.salon_id
  FROM target_channel tc
  JOIN products p
    ON p.salon_id = tc.salon_id
   AND p.deleted_at IS NULL
   AND p.external_metadata->>'batch' = 'asiandeligo-new-products-folder14-20260713'
   AND p.external_metadata->>'review_id' = 'folder14-020'
)
UPDATE product_variants pv
SET deleted_at = now(),
    is_active = false,
    is_published = false,
    is_for_sale = false,
    external_metadata = COALESCE(pv.external_metadata, '{}'::jsonb)
      || jsonb_build_object('merged_into_sku', 'ADG-001803', 'merge_confirmed_at', '2026-07-13')
FROM duplicate_product d
WHERE pv.salon_id = d.salon_id
  AND pv.template_id = d.id
  AND pv.deleted_at IS NULL
  AND pv.sku = 'ADG-001811';

WITH target_channel AS (
  SELECT salon_id FROM channels WHERE slug = 'asiandeligo' AND is_active = true
)
UPDATE products p
SET deleted_at = now(),
    is_active = false,
    is_published = false,
    external_metadata = COALESCE(p.external_metadata, '{}'::jsonb)
      || jsonb_build_object('merged_into_sku', 'ADG-001803', 'merge_confirmed_at', '2026-07-13')
FROM target_channel tc
WHERE p.salon_id = tc.salon_id
  AND p.deleted_at IS NULL
  AND p.external_metadata->>'batch' = 'asiandeligo-new-products-folder14-20260713'
  AND p.external_metadata->>'review_id' = 'folder14-020';

WITH target_channel AS (
  SELECT salon_id FROM channels WHERE slug = 'asiandeligo' AND is_active = true
)
UPDATE products p
SET external_metadata = COALESCE(p.external_metadata, '{}'::jsonb)
  || jsonb_build_object('merged_duplicate_skus', jsonb_build_array('ADG-001811'))
FROM target_channel tc
WHERE p.salon_id = tc.salon_id
  AND p.deleted_at IS NULL
  AND p.external_metadata->>'batch' = 'asiandeligo-new-products-folder14-20260713'
  AND p.external_metadata->>'review_id' = 'folder14-012';

DO $$
DECLARE
  target_salon_id uuid;
  survivor_count integer;
  duplicate_active_count integer;
  merged_image_count integer;
  active_batch_count integer;
BEGIN
  SELECT salon_id INTO STRICT target_salon_id
  FROM channels WHERE slug = 'asiandeligo' AND is_active = true;

  SELECT count(*) INTO survivor_count
  FROM products p
  JOIN product_variants pv
    ON pv.salon_id = target_salon_id
   AND pv.template_id = p.id
   AND pv.deleted_at IS NULL
   AND pv.sku = 'ADG-001803'
  WHERE p.salon_id = target_salon_id
    AND p.deleted_at IS NULL
    AND p.external_metadata->>'review_id' = 'folder14-012';
  IF survivor_count <> 1 THEN
    RAISE EXCEPTION 'Survivor post-check failed';
  END IF;

  SELECT count(*) INTO duplicate_active_count
  FROM products p
  WHERE p.salon_id = target_salon_id
    AND p.deleted_at IS NULL
    AND p.external_metadata->>'review_id' = 'folder14-020';
  IF duplicate_active_count <> 0 THEN
    RAISE EXCEPTION 'Duplicate product is still active';
  END IF;

  SELECT count(*) INTO merged_image_count
  FROM products p
  JOIN product_images pi
    ON pi.salon_id = target_salon_id
   AND pi.template_id = p.id
   AND pi.image_large_url = 'https://img.zira.pl/asiandeligo/owner-images/folder14/ADG-001803/02-PETE8104.JPG?v=20260713'
   AND pi.file_hash = 'e51a856a30c62a39a3f0779ccc6c74f591762b6cd4030aa75a16ca7bd75b2184'
   AND pi.is_primary = false
  WHERE p.salon_id = target_salon_id
    AND p.deleted_at IS NULL
    AND p.external_metadata->>'review_id' = 'folder14-012';
  IF merged_image_count <> 1 THEN
    RAISE EXCEPTION 'Merged gallery image post-check failed';
  END IF;

  SELECT count(*) INTO active_batch_count
  FROM products p
  WHERE p.salon_id = target_salon_id
    AND p.deleted_at IS NULL
    AND p.external_metadata->>'batch' = 'asiandeligo-new-products-folder14-20260713';
  IF active_batch_count <> 52 THEN
    RAISE EXCEPTION 'Expected 52 active folder14 products after merge, got %', active_batch_count;
  END IF;
END $$;

COMMIT;
