-- Generated by scripts/catalog-taxonomy-remediation-plan.mjs
-- Purpose: apply the guarded Asia Deli Go taxonomy consolidation.
-- No product price, stock, content, publication, order, or reservation field is changed.
-- Source categories are deactivated, never deleted.
--
-- JOIN contract (schema-introspect verified 2026-07-13):
--   channels.salon_id (uuid) scopes categories, products, and product_variants.
--   products.category_id (uuid) = categories.id (uuid), FK declared.
--   product_variants.template_id (uuid) = products.id (uuid), FK declared.
--   Canonical tables are categories/products/product_variants; backup tables are excluded.

\set ON_ERROR_STOP on
BEGIN;

CREATE TEMP TABLE _adg_taxonomy_target_salon (salon_id uuid PRIMARY KEY) ON COMMIT DROP;
INSERT INTO _adg_taxonomy_target_salon (salon_id)
SELECT salon_id FROM channels WHERE slug = 'asiandeligo' AND is_active = TRUE;

CREATE TEMP TABLE _adg_taxonomy_moves (
  sku text PRIMARY KEY,
  expected_category_slug text NOT NULL,
  target_category_slug text NOT NULL,
  target_category_expected_active boolean NOT NULL
) ON COMMIT DROP;
INSERT INTO _adg_taxonomy_moves (
  sku, expected_category_slug, target_category_slug, target_category_expected_active
) VALUES
  ('ADG-000103', 'unmapped', 'sosy-marynaty', TRUE),
  ('ADG-000277', 'pozostałe-produkty', 'ryż-i-inne-ziarna', TRUE),
  ('ADG-000393', 'unmapped', 'ryż-i-inne-ziarna', TRUE),
  ('ADG-000527', 'sosy-sojowe', 'sos-sojowy', TRUE),
  ('ADG-000528', 'sosy-sojowe', 'sos-sojowy', TRUE),
  ('ADG-000529', 'sosy-sojowe', 'sos-sojowy', TRUE),
  ('ADG-000530', 'sosy-sojowe', 'sos-sojowy', TRUE),
  ('ADG-000607', 'kategoria-tymczasowa', 'prezenty', TRUE),
  ('ADG-000641', 'unmapped', 'pasty-smakowe', TRUE),
  ('ADG-000648', 'unmapped', 'pasty-smakowe', TRUE),
  ('ADG-000668', 'sosy-sojowe', 'sos-sojowy', TRUE),
  ('ADG-000690', 'kategoria-tymczasowa', 'przyprawy', TRUE),
  ('ADG-000781', 'unmapped', 'ryż-i-inne-ziarna', TRUE),
  ('ADG-000791', 'unmapped', 'buliony', TRUE),
  ('ADG-001413', 'sosy-sojowe', 'sos-sojowy', TRUE),
  ('ADG-001414', 'sosy-sojowe', 'sos-sojowy', TRUE),
  ('ADG-001694', 'kategoria-tymczasowa', 'przyprawy', TRUE),
  ('ADG-001712', 'sosy-i-marynaty', 'sosy-marynaty', TRUE);

CREATE TEMP TABLE _adg_taxonomy_category_state (
  slug text PRIMARY KEY,
  expected_active boolean NOT NULL,
  target_active boolean NOT NULL,
  expected_products integer NOT NULL
) ON COMMIT DROP;
INSERT INTO _adg_taxonomy_category_state (
  slug, expected_active, target_active, expected_products
) VALUES
  ('kategoria-tymczasowa', TRUE, FALSE, 3),
  ('sosy-i-marynaty', TRUE, FALSE, 1),
  ('sosy-sojowe', TRUE, FALSE, 7),
  ('unmapped', TRUE, FALSE, 6);

DO $$
DECLARE
  affected integer;
BEGIN
  IF (SELECT COUNT(*) FROM _adg_taxonomy_target_salon) <> 1 THEN
    RAISE EXCEPTION 'Expected exactly one active Asia Deli Go channel';
  END IF;

  IF EXISTS (
    SELECT state.slug
    FROM _adg_taxonomy_category_state state
    CROSS JOIN _adg_taxonomy_target_salon tenant
    LEFT JOIN categories category
      ON category.salon_id = tenant.salon_id
     AND category.slug = state.slug
    LEFT JOIN products product
      ON product.salon_id = tenant.salon_id
     AND product.category_id = category.id
     AND product.deleted_at IS NULL
    GROUP BY state.slug, state.expected_active, state.expected_products
    HAVING COUNT(DISTINCT category.id) <> 1
       OR BOOL_OR(category.is_active) IS DISTINCT FROM state.expected_active
       OR COUNT(DISTINCT product.id) <> state.expected_products
  ) THEN
    RAISE EXCEPTION 'Source category state precondition failed; aborting all changes';
  END IF;

  IF EXISTS (
    SELECT move.sku
    FROM _adg_taxonomy_moves move
    CROSS JOIN _adg_taxonomy_target_salon tenant
    LEFT JOIN product_variants variant
      ON variant.salon_id = tenant.salon_id
     AND variant.sku = move.sku
     AND variant.is_active = TRUE
     AND variant.deleted_at IS NULL
    LEFT JOIN products product
      ON product.salon_id = tenant.salon_id
     AND product.id = variant.template_id
     AND product.is_active = TRUE
     AND product.is_published = TRUE
     AND product.deleted_at IS NULL
    LEFT JOIN categories current_category
      ON current_category.salon_id = tenant.salon_id
     AND current_category.id = product.category_id
    LEFT JOIN categories target_category
      ON target_category.salon_id = tenant.salon_id
     AND target_category.slug = move.target_category_slug
    GROUP BY move.sku, move.expected_category_slug, move.target_category_expected_active
    HAVING COUNT(DISTINCT variant.id) <> 1
       OR COUNT(DISTINCT product.id) <> 1
       OR COUNT(DISTINCT current_category.id) <> 1
       OR MIN(current_category.slug) IS DISTINCT FROM move.expected_category_slug
       OR BOOL_OR(current_category.is_active) IS DISTINCT FROM TRUE
       OR COUNT(DISTINCT target_category.id) <> 1
       OR BOOL_OR(target_category.is_active) IS DISTINCT FROM move.target_category_expected_active
  ) THEN
    RAISE EXCEPTION 'Product/category mapping precondition failed; aborting all changes';
  END IF;



  UPDATE products product
  SET category_id = target_category.id,
      updated_at = NOW()
  FROM _adg_taxonomy_target_salon tenant,
       _adg_taxonomy_moves move,
       product_variants variant,
       categories current_category,
       categories target_category
  WHERE product.salon_id = tenant.salon_id
    AND variant.salon_id = tenant.salon_id
    AND variant.template_id = product.id
    AND variant.sku = move.sku
    AND variant.is_active = TRUE
    AND variant.deleted_at IS NULL
    AND current_category.salon_id = tenant.salon_id
    AND current_category.id = product.category_id
    AND current_category.slug = move.expected_category_slug
    AND target_category.salon_id = tenant.salon_id
    AND target_category.slug = move.target_category_slug
    AND product.is_active = TRUE
    AND product.is_published = TRUE
    AND product.deleted_at IS NULL;
  GET DIAGNOSTICS affected = ROW_COUNT;
  IF affected <> 18 THEN
    RAISE EXCEPTION 'Expected 18 product category updates, got %', affected;
  END IF;

  IF EXISTS (
    SELECT state.slug
    FROM _adg_taxonomy_category_state state
    CROSS JOIN _adg_taxonomy_target_salon tenant
    JOIN categories category
      ON category.salon_id = tenant.salon_id
     AND category.slug = state.slug
    JOIN products product
      ON product.salon_id = tenant.salon_id
     AND product.category_id = category.id
     AND product.deleted_at IS NULL
  ) THEN
    RAISE EXCEPTION 'A source category still owns products after remapping';
  END IF;

  UPDATE categories category
  SET is_active = state.target_active,
      updated_at = NOW()
  FROM _adg_taxonomy_target_salon tenant,
       _adg_taxonomy_category_state state
  WHERE category.salon_id = tenant.salon_id
    AND category.slug = state.slug
    AND category.is_active = state.expected_active;
  GET DIAGNOSTICS affected = ROW_COUNT;
  IF affected <> 4 THEN
    RAISE EXCEPTION 'Expected 4 category deactivations, got %', affected;
  END IF;
END $$;

SELECT variant.sku, product.name, category.name AS category_name, category.slug AS category_slug
FROM _adg_taxonomy_target_salon tenant
JOIN product_variants variant ON variant.salon_id = tenant.salon_id
JOIN _adg_taxonomy_moves move ON move.sku = variant.sku
JOIN products product ON product.salon_id = tenant.salon_id AND product.id = variant.template_id
JOIN categories category ON category.salon_id = tenant.salon_id AND category.id = product.category_id
ORDER BY variant.sku;

SELECT category.slug, category.is_active
FROM _adg_taxonomy_target_salon tenant
JOIN categories category ON category.salon_id = tenant.salon_id
JOIN _adg_taxonomy_category_state state ON state.slug = category.slug
ORDER BY category.slug;

COMMIT;
