-- Generated by scripts/catalog-review-remediation-plan.mjs
-- Purpose: apply the guarded Asia Deli Go catalog review remediation.
-- No price, product content, dietary tag, order, reservation, or publication fields are changed.
--
-- JOIN contract (schema-introspect verified 2026-07-13):
--   channels.salon_id (uuid) scopes every business-table operation.
--   product_variants.template_id (uuid) = products.id (uuid), FK declared.
--   stock_quants.variant_id (uuid) = product_variants.id (uuid), FK declared.
--   product_variants.salon_id/products.salon_id/stock_quants.salon_id all equal the channel salon_id.
--   products and product_variants exclude deleted_at rows; stock_quants has no soft-delete column.
--   trg_stock_quants_sync_variant synchronizes variant aggregate stock after quant updates.

\set ON_ERROR_STOP on
BEGIN;

CREATE TEMP TABLE _adg_catalog_target_salon (salon_id uuid PRIMARY KEY) ON COMMIT DROP;
INSERT INTO _adg_catalog_target_salon (salon_id)
SELECT salon_id FROM channels WHERE slug = 'asiandeligo' AND is_active = TRUE;

CREATE TEMP TABLE _adg_catalog_stock_target (
  sku text PRIMARY KEY,
  expected_quantity numeric NOT NULL,
  target_quantity numeric NOT NULL
) ON COMMIT DROP;
INSERT INTO _adg_catalog_stock_target (sku, expected_quantity, target_quantity) VALUES
  ('ADG-000144', 0, 100),
  ('ADG-000201', 0, 100),
  ('ADG-000426', 0, 100),
  ('ADG-000637', 0, 100),
  ('ADG-000647', 0, 100),
  ('ADG-000660', 0, 100),
  ('ADG-000725', 0, 100),
  ('ADG-000885', 0, 100),
  ('ADG-000889', 0, 100),
  ('ADG-000946', 0, 100),
  ('ADG-001054', 0, 100),
  ('ADG-001314', 0, 100),
  ('ADG-001423', 0, 100),
  ('ADG-001551', 0, 100),
  ('ADG-001639', 0, 100),
  ('ADG-001684', 0, 100),
  ('ADG-001744', 0, 100);

CREATE TEMP TABLE _adg_catalog_ean_target (
  sku text PRIMARY KEY,
  expected_ean text NOT NULL,
  target_ean text NOT NULL UNIQUE
) ON COMMIT DROP;
INSERT INTO _adg_catalog_ean_target (sku, expected_ean, target_ean) VALUES
  ('ADG-000392', 'mpn:749', '078895123395'),
  ('ADG-000393', 'mpn:837', '5020580400156');

DO $$
DECLARE
  affected integer;
BEGIN
  IF (SELECT COUNT(*) FROM _adg_catalog_target_salon) <> 1 THEN
    RAISE EXCEPTION 'Expected exactly one active Asia Deli Go channel';
  END IF;

  IF EXISTS (
    SELECT s.sku
    FROM _adg_catalog_stock_target s
    CROSS JOIN _adg_catalog_target_salon t
    LEFT JOIN product_variants pv
      ON pv.salon_id = t.salon_id
     AND pv.sku = s.sku
     AND pv.is_active = TRUE
     AND pv.deleted_at IS NULL
    LEFT JOIN products p
      ON p.salon_id = t.salon_id
     AND p.id = pv.template_id
     AND p.is_active = TRUE
     AND p.is_published = TRUE
     AND p.deleted_at IS NULL
    LEFT JOIN stock_quants sq
      ON sq.salon_id = t.salon_id
     AND sq.variant_id = pv.id
    GROUP BY s.sku, s.expected_quantity
    HAVING COUNT(sq.id) <> 1
       OR COUNT(p.id) <> 1
       OR MIN(sq.quantity) <> s.expected_quantity
       OR MIN(sq.reserved_quantity) <> 0
  ) THEN
    RAISE EXCEPTION 'Stock precondition failed; aborting all changes';
  END IF;

  IF EXISTS (
    SELECT e.sku
    FROM _adg_catalog_ean_target e
    CROSS JOIN _adg_catalog_target_salon t
    LEFT JOIN product_variants pv
      ON pv.salon_id = t.salon_id
     AND pv.sku = e.sku
     AND pv.is_active = TRUE
     AND pv.deleted_at IS NULL
    LEFT JOIN products p
      ON p.salon_id = t.salon_id
     AND p.id = pv.template_id
     AND p.is_active = TRUE
     AND p.is_published = TRUE
     AND p.deleted_at IS NULL
    GROUP BY e.sku, e.expected_ean
    HAVING COUNT(pv.id) <> 1
       OR COUNT(p.id) <> 1
       OR MIN(pv.ean) IS DISTINCT FROM e.expected_ean
  ) THEN
    RAISE EXCEPTION 'EAN precondition failed; aborting all changes';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM _adg_catalog_ean_target e
    CROSS JOIN _adg_catalog_target_salon t
    JOIN product_variants pv
      ON pv.salon_id = t.salon_id
     AND pv.ean = e.target_ean
     AND pv.deleted_at IS NULL
  ) THEN
    RAISE EXCEPTION 'A target EAN is already assigned to another variant';
  END IF;

  UPDATE stock_quants sq
  SET quantity = s.target_quantity
  FROM _adg_catalog_target_salon t,
       _adg_catalog_stock_target s,
       product_variants pv,
       products p
  WHERE sq.salon_id = t.salon_id
    AND pv.salon_id = t.salon_id
    AND p.salon_id = t.salon_id
    AND pv.sku = s.sku
    AND pv.is_active = TRUE
    AND pv.deleted_at IS NULL
    AND p.id = pv.template_id
    AND p.is_active = TRUE
    AND p.is_published = TRUE
    AND p.deleted_at IS NULL
    AND sq.variant_id = pv.id
    AND sq.quantity = s.expected_quantity
    AND sq.reserved_quantity = 0;
  GET DIAGNOSTICS affected = ROW_COUNT;
  IF affected <> 17 THEN
    RAISE EXCEPTION 'Expected 17 stock updates, got %', affected;
  END IF;

  IF EXISTS (
    SELECT s.sku
    FROM _adg_catalog_stock_target s
    CROSS JOIN _adg_catalog_target_salon t
    JOIN product_variants pv
      ON pv.salon_id = t.salon_id
     AND pv.sku = s.sku
     AND pv.is_active = TRUE
     AND pv.deleted_at IS NULL
    WHERE pv.total_stock_qty IS DISTINCT FROM s.target_quantity
       OR pv.reserved_stock_qty IS DISTINCT FROM 0
  ) THEN
    RAISE EXCEPTION 'Variant stock synchronization failed; aborting all changes';
  END IF;

  UPDATE product_variants pv
  SET ean = e.target_ean
  FROM _adg_catalog_target_salon t,
       _adg_catalog_ean_target e,
       products p
  WHERE pv.salon_id = t.salon_id
    AND pv.sku = e.sku
    AND pv.is_active = TRUE
    AND pv.deleted_at IS NULL
    AND pv.ean = e.expected_ean
    AND p.salon_id = t.salon_id
    AND p.id = pv.template_id
    AND p.is_active = TRUE
    AND p.is_published = TRUE
    AND p.deleted_at IS NULL;
  GET DIAGNOSTICS affected = ROW_COUNT;
  IF affected <> 2 THEN
    RAISE EXCEPTION 'Expected 2 EAN updates, got %', affected;
  END IF;
END $$;

SELECT pv.sku, sq.quantity, sq.reserved_quantity, pv.total_stock_qty
FROM _adg_catalog_target_salon t
JOIN product_variants pv ON pv.salon_id = t.salon_id
JOIN stock_quants sq ON sq.salon_id = t.salon_id AND sq.variant_id = pv.id
JOIN _adg_catalog_stock_target s ON s.sku = pv.sku
ORDER BY pv.sku;

SELECT pv.sku, pv.ean
FROM _adg_catalog_target_salon t
JOIN product_variants pv ON pv.salon_id = t.salon_id
JOIN _adg_catalog_ean_target e ON e.sku = pv.sku
ORDER BY pv.sku;

COMMIT;
