\set ON_ERROR_STOP on
-- Generated by scripts/catalog-metadata-batch3-plan.mjs
-- Purpose: roll back the reviewed Asia Deli Go metadata batch.
-- Decision SHA-256: 01e138ed3f76c4871e981bec117a4e1051ba18d3bfdc8566364012c4c46fa00e
--
-- JOIN contract (schema-introspect verified on production 2026-07-22):
--   product_variants.template_id (uuid) = products.id (uuid) — FK declared; sampled match OK.
--   products.category_id (uuid) = categories.id (uuid) — FK declared; sampled match OK.
--   channels.salon_id = products/product_variants/categories.salon_id (uuid) — tenant pinned on every table.
-- Status values: products.status=active; variant sync_status=synced and availability_status=IN_STOCK.
-- Soft-delete policy: products and variants require deleted_at IS NULL; category/channel require active.
-- Canonical tables only: products, product_variants, categories, channels; no backup/legacy table is joined.

BEGIN;
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
SET LOCAL search_path = pg_catalog, public;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '120s';

CREATE TEMP TABLE _adg_metadata_target_salon (
  salon_id uuid PRIMARY KEY,
  channel_slug text NOT NULL
) ON COMMIT DROP;

INSERT INTO _adg_metadata_target_salon (salon_id, channel_slug)
SELECT salon_id, slug
FROM public.channels
WHERE salon_id = 'e73271a9-53e3-4a20-a02e-791726b452aa'::uuid
  AND slug = 'asiandeligo'
  AND is_active = TRUE
FOR SHARE;

CREATE TEMP TABLE _adg_metadata_decisions (
  sku text PRIMARY KEY,
  product_id uuid UNIQUE NOT NULL,
  variant_id uuid UNIQUE NOT NULL,
  expected_name text NOT NULL,
  expected_slug text NOT NULL,
  expected_updated_at timestamptz NOT NULL,
  expected_allergens jsonb,
  target_allergens jsonb,
  expected_may_contain_allergens jsonb,
  target_may_contain_allergens jsonb,
  expected_storage_zone text,
  target_storage_zone text,
  expected_nutrition_facts jsonb,
  target_nutrition_facts jsonb,
  expected_country_of_origin text,
  target_country_of_origin text,
  expected_ingredients text,
  target_ingredients text,
  expected_price_per_unit numeric,
  expected_unit_of_measure text,
  category_id uuid NOT NULL,
  category_name text NOT NULL,
  category_slug text NOT NULL,
  changed_fields text[] NOT NULL
) ON COMMIT DROP;

INSERT INTO _adg_metadata_decisions VALUES
  (
    'ADG-000104'::text,
    '556b36b1-99c5-44b5-9458-218a02b7cce5'::uuid,
    '1364ed29-c46d-4c5a-9aa5-80e769162deb'::uuid,
    'Makaron ryżowy 10mm 400g - Farmer'::text,
    'makaron-ryzowy-10mm-400g-farmer'::text,
    '2026-07-08 12:12:07.93723+00:00'::timestamptz,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    '{"fat":0.8,"salt":0.01,"carbs":80,"sugar":0,"protein":7,"calories":356,"servingSize":"w 100g/100ml","saturatedFat":0.3}'::jsonb,
    '{"fat":0.8,"salt":0.01,"carbs":80,"sugar":0,"protein":7,"calories":356,"servingSize":"w 100g/100ml","saturatedFat":0.3}'::jsonb,
    'Tajlandia'::text,
    'Tajlandia'::text,
    'Mąka ryżowa 90%, woda'::text,
    'Mąka ryżowa 90%, woda'::text,
    '22.47'::numeric,
    'KG'::text,
    'f331b4dd-5539-4137-8320-e14795d23f5f'::uuid,
    'Makaron ryżowy'::text,
    'makaron-ryżowy'::text,
    ARRAY['storageZone'::text]::text[]
  ),
  (
    'ADG-000123'::text,
    'dc18a337-8019-4687-84e3-da6fba30adad'::uuid,
    '15d873d8-6d59-4f7b-93a3-352c7a42a1e4'::uuid,
    'Makaron sojowy Vermicelli 500g, pakowane po 5x100g - LongKou'::text,
    'makaron-sojowy-vermicelli-500g-pakowane-po-5x100g-longkou'::text,
    '2026-07-08 12:12:07.93723+00:00'::timestamptz,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    '{"fat":0.5,"salt":0.04,"carbs":86,"sugar":0.5,"protein":0.5,"calories":344,"servingSize":"w 100g/100ml","saturatedFat":0.1}'::jsonb,
    '{"fat":0.5,"salt":0.04,"carbs":86,"sugar":0.5,"protein":0.5,"calories":344,"servingSize":"w 100g/100ml","saturatedFat":0.1}'::jsonb,
    'Chiny'::text,
    'Chiny'::text,
    'Skrobia grochowa, skrobia z fasoli mung, woda'::text,
    'Skrobia grochowa, skrobia z fasoli mung, woda'::text,
    '31.98'::numeric,
    'KG'::text,
    'da5d01bb-6b68-4317-abbf-a93c5a05f8f2'::uuid,
    'Makaron szklisty'::text,
    'makaron-szklisty'::text,
    ARRAY['storageZone'::text]::text[]
  ),
  (
    'ADG-000250'::text,
    '8f80102c-7330-4f9f-b25f-f47f23732672'::uuid,
    '35c5c38a-caa2-4d17-bf8c-96a1d7f9c9af'::uuid,
    'Makaron ryżowy 1mm 400g - Farmer'::text,
    'makaron-ryzowy-1mm-400g-farmer'::text,
    '2026-07-08 12:12:07.93723+00:00'::timestamptz,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    '{"fat":0.8,"salt":0.01,"carbs":80,"protein":7,"calories":356,"servingSize":"w 100g/100ml","saturatedFat":0.3}'::jsonb,
    '{"fat":0.8,"salt":0.01,"carbs":80,"protein":7,"calories":356,"servingSize":"w 100g/100ml","saturatedFat":0.3}'::jsonb,
    'Tajlandia'::text,
    'Tajlandia'::text,
    'Mąka ryżowa 90%, woda'::text,
    'Mąka ryżowa 90%, woda'::text,
    '22.47'::numeric,
    'KG'::text,
    'f331b4dd-5539-4137-8320-e14795d23f5f'::uuid,
    'Makaron ryżowy'::text,
    'makaron-ryżowy'::text,
    ARRAY['storageZone'::text]::text[]
  ),
  (
    'ADG-000251'::text,
    '8a77487b-0a91-4f6e-aef7-16b150ebd6ad'::uuid,
    'c726b307-63a3-49c6-a567-298d62392005'::uuid,
    'Makaron Shirataki Konjac, nitki 400g - City Aroma'::text,
    'makaron-shirataki-konjac-nitki-400g-city-aroma'::text,
    '2026-07-08 12:12:07.93723+00:00'::timestamptz,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    '{"fat":0,"salt":0.1355,"carbs":1.5,"sugar":0,"protein":0,"calories":9.5,"servingSize":"w 100g/100ml"}'::jsonb,
    '{"fat":0,"salt":0.1355,"carbs":1.5,"sugar":0,"protein":0,"calories":9.5,"servingSize":"w 100g/100ml"}'::jsonb,
    'Chiny'::text,
    'Chiny'::text,
    'Woda, mąka z Konjac 3,8%, regulator kwasowości: wodorotlenek wapnia'::text,
    'Woda, mąka z Konjac 3,8%, regulator kwasowości: wodorotlenek wapnia'::text,
    '19.75'::numeric,
    'KG'::text,
    'faa71799-801c-42f7-9108-0964f390adc9'::uuid,
    'Makaron konjac'::text,
    'makaron-konjac'::text,
    ARRAY['storageZone'::text]::text[]
  ),
  (
    'ADG-000280'::text,
    '21da15e1-9601-454a-a501-5453470ec95e'::uuid,
    '137420d1-ee61-4af9-bdad-3a6a011998af'::uuid,
    'Makaron sojowy vermicelli LongKou 1kg, porcjowany 20 x 50g'::text,
    'makaron-sojowy-vermicelli-longkou-1kg-porcjowany-20-x-50g'::text,
    '2026-07-08 12:12:07.93723+00:00'::timestamptz,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    '{"fat":0.5,"salt":0.04,"carbs":86,"sugar":0.5,"protein":0.5,"calories":344,"servingSize":"w 100g/100ml","saturatedFat":0.1}'::jsonb,
    '{"fat":0.5,"salt":0.04,"carbs":86,"sugar":0.5,"protein":0.5,"calories":344,"servingSize":"w 100g/100ml","saturatedFat":0.1}'::jsonb,
    'Chiny'::text,
    'Chiny'::text,
    'Skrobia grochowa, skrobia z fasoli mung, woda'::text,
    'Skrobia grochowa, skrobia z fasoli mung, woda'::text,
    '27.80'::numeric,
    'KG'::text,
    '1811cca7-2499-4ff3-acf5-d521ce5affff'::uuid,
    'Makarony'::text,
    'makarony'::text,
    ARRAY['storageZone'::text]::text[]
  ),
  (
    'ADG-000346'::text,
    '4d779243-f64b-4ee6-ae19-a96c3cd05ef6'::uuid,
    '8091a7ab-f11a-405f-8ea5-f9f44725aaf8'::uuid,
    'Ryż czarny kleisty (Ketan Itam) 400g - North South'::text,
    'ryz-czarny-kleisty-ketan-itam-400g-north-south'::text,
    '2026-07-08 12:12:07.93723+00:00'::timestamptz,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    '{"fat":2.3,"salt":0,"carbs":73,"sugar":0,"protein":9.4,"calories":350,"servingSize":"w 100g/100ml"}'::jsonb,
    '{"fat":2.3,"salt":0,"carbs":73,"sugar":0,"protein":9.4,"calories":350,"servingSize":"w 100g/100ml"}'::jsonb,
    'Singapur'::text,
    'Singapur'::text,
    '100% ryż czarny kleisty'::text,
    '100% ryż czarny kleisty'::text,
    '39.98'::numeric,
    'KG'::text,
    '62db9128-0d76-4643-87fb-e9c5e875e9cf'::uuid,
    'Ryż i inne ziarna'::text,
    'ryż-i-inne-ziarna'::text,
    ARRAY['storageZone'::text]::text[]
  ),
  (
    'ADG-000419'::text,
    'c5d55aea-8dca-482e-8002-7053ffa3c19a'::uuid,
    'c571525e-7bdf-4a98-b3e9-2c5c614568fd'::uuid,
    'Zupa Kimchi ramen Hot & Spicy z prawdziwym kimchi 122g - Jongga'::text,
    'zupa-kimchi-ramen-hot-and-spicy-z-prawdziwym-kimchi-122g-jongga'::text,
    '2026-07-08 12:12:07.93723+00:00'::timestamptz,
    '["cereals","crustaceans","fish","soybeans","milk"]'::jsonb,
    '["cereals","crustaceans","fish","soybeans","milk"]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    '{"fat":10.1,"salt":3.9,"carbs":53.7,"sugar":4.7,"protein":7.7,"calories":330,"servingSize":"w 100g/100ml","saturatedFat":4.5}'::jsonb,
    '{"fat":10.1,"salt":3.9,"carbs":53.7,"sugar":4.7,"protein":7.7,"calories":330,"servingSize":"w 100g/100ml","saturatedFat":4.5}'::jsonb,
    NULL::text,
    'Korea Południowa'::text,
    'Makaron: Mąka pszenna , olej palmowy, skrobia ziemniaczana, modyfikowana skrobia z tapioki, sól, guma guar (E412), tripolifosforan sodu, węglan potasu (E501), węglan sodu (E500), kolor kurkumy. Zupa: Kimchi w proszku (skrobia kukurydziana, sól, sos z anchois, kwas mlekowy (E270)), sól, aromat (maltodekstryna, sól, cebula w proszku, ekstrakt drożdżowy, sztuczny aromat), cukier, glutaminian monosodowy (E621), proszek chili , sos sojowy , ( soja , pszenica , sól, maltodekstryna), suszone płatki cebuli, kremy nie-Nabiałowe, czosnek w proszku, czarny pieprz, barwnik papryka, E355, cebula w proszku, maltodekstryna, E330, E635, E150a, przeciwutleniacz. Kimchi: kapusta, skrobia, proszek z czerwonej papryki, fruktoza, czosnek, sfermentowany sos krewetkowy ( krewetki , sól), por, szczypiorek, glutaminian sodu (E621), syrop kukurydziany, fermentowany sos anchois ( sardela , sól), ekstrakt z bonito , Guma ksantanowa (E415), cukier, imbir, ocet, kwas jabłkowy (E296).'::text,
    'Makaron: Mąka pszenna , olej palmowy, skrobia ziemniaczana, modyfikowana skrobia z tapioki, sól, guma guar (E412), tripolifosforan sodu, węglan potasu (E501), węglan sodu (E500), kolor kurkumy. Zupa: Kimchi w proszku (skrobia kukurydziana, sól, sos z anchois, kwas mlekowy (E270)), sól, aromat (maltodekstryna, sól, cebula w proszku, ekstrakt drożdżowy, sztuczny aromat), cukier, glutaminian monosodowy (E621), proszek chili , sos sojowy , ( soja , pszenica , sól, maltodekstryna), suszone płatki cebuli, kremy nie-Nabiałowe, czosnek w proszku, czarny pieprz, barwnik papryka, E355, cebula w proszku, maltodekstryna, E330, E635, E150a, przeciwutleniacz. Kimchi: kapusta, skrobia, proszek z czerwonej papryki, fruktoza, czosnek, sfermentowany sos krewetkowy ( krewetki , sól), por, szczypiorek, glutaminian sodu (E621), syrop kukurydziany, fermentowany sos anchois ( sardela , sól), ekstrakt z bonito , Guma ksantanowa (E415), cukier, imbir, ocet, kwas jabłkowy (E296).'::text,
    '72.95'::numeric,
    'KG'::text,
    '7da30509-aad0-475e-ab39-ca7764bffda2'::uuid,
    'Ramyun / Ramen'::text,
    'ramyun-ramen'::text,
    ARRAY['storageZone'::text, 'countryOfOrigin'::text]::text[]
  ),
  (
    'ADG-000547'::text,
    '9bce68bf-7b1c-4e01-90a6-6326112df584'::uuid,
    '98d1a0c7-0b2d-4acb-b86f-815d8ea326ad'::uuid,
    'Ryż do sushi Tsuru 1kg - Curtiriso'::text,
    'ryz-do-sushi-tsuru-1kg-curtiriso'::text,
    '2026-07-08 12:12:07.93723+00:00'::timestamptz,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    'AMBIENT'::text,
    'AMBIENT'::text,
    '{"fat":0.4,"salt":0.01,"carbs":80.4,"sugar":0.2,"protein":6.7,"calories":354,"servingSize":"w 100g/100ml","saturatedFat":0.1}'::jsonb,
    '{"fat":0.4,"salt":0.01,"carbs":80.4,"sugar":0.2,"protein":6.7,"calories":354,"servingSize":"w 100g/100ml","saturatedFat":0.1}'::jsonb,
    NULL::text,
    'Włochy'::text,
    '100% ryż okrągłoziarnisty (short grain)'::text,
    '100% ryż okrągłoziarnisty (short grain)'::text,
    '12.99'::numeric,
    'KG'::text,
    '62db9128-0d76-4643-87fb-e9c5e875e9cf'::uuid,
    'Ryż i inne ziarna'::text,
    'ryż-i-inne-ziarna'::text,
    ARRAY['countryOfOrigin'::text]::text[]
  ),
  (
    'ADG-000578'::text,
    '5ce19b8e-4f1a-4d52-9e72-ed1e05c6f67b'::uuid,
    '6a4a9bac-6c50-4e7b-b437-0a758a9223a7'::uuid,
    'Kluski ryżowe do Tteokbokki, małe słupki 600g (3 x 200g) - Matamun'::text,
    'kluski-ryzowe-do-tteokbokki-male-slupki-600g-3-x-200g-matamun'::text,
    '2026-07-08 12:12:07.93723+00:00'::timestamptz,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    '{"fat":0.2,"salt":0.33,"carbs":55,"sugar":2.2,"protein":4.5,"calories":238,"servingSize":"w 100g/100ml","saturatedFat":0.2}'::jsonb,
    '{"fat":0.2,"salt":0.33,"carbs":55,"sugar":2.2,"protein":4.5,"calories":238,"servingSize":"w 100g/100ml","saturatedFat":0.2}'::jsonb,
    'Korea Południowa'::text,
    'Korea Południowa'::text,
    'Ryż 99,1%, sól, regulator kwasowości: kwas cytrynowy; alkohol'::text,
    'Ryż 99,1%, sól, regulator kwasowości: kwas cytrynowy; alkohol'::text,
    '29.98'::numeric,
    'KG'::text,
    '6a1b2166-3379-4014-adec-99172d5336b0'::uuid,
    'Kluski tteok do dań'::text,
    'kluski-tteok-do-dań'::text,
    ARRAY['storageZone'::text]::text[]
  ),
  (
    'ADG-000581'::text,
    'b91e7213-af53-460f-8515-5ac5740bae93'::uuid,
    'c9729d80-2190-42fe-a06e-86fb82a64a71'::uuid,
    'Kluski ryżowe do Tteokguk, małe plasterki 600g (3 x 200g) - Matamun'::text,
    'kluski-ryzowe-do-tteokguk-male-plasterki-600g-3-x-200g-matamun'::text,
    '2026-07-08 12:12:07.93723+00:00'::timestamptz,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    '{"fat":0.2,"salt":0.33,"carbs":55,"sugar":2.2,"protein":4.5,"calories":238,"servingSize":"w 100g/100ml","saturatedFat":0.2}'::jsonb,
    '{"fat":0.2,"salt":0.33,"carbs":55,"sugar":2.2,"protein":4.5,"calories":238,"servingSize":"w 100g/100ml","saturatedFat":0.2}'::jsonb,
    'Korea Południowa'::text,
    'Korea Południowa'::text,
    'Ryż 99,1%, sól, regulator kwasowości: kwas cytrynowy; alkohol'::text,
    'Ryż 99,1%, sól, regulator kwasowości: kwas cytrynowy; alkohol'::text,
    '38.32'::numeric,
    'KG'::text,
    '6a1b2166-3379-4014-adec-99172d5336b0'::uuid,
    'Kluski tteok do dań'::text,
    'kluski-tteok-do-dań'::text,
    ARRAY['storageZone'::text]::text[]
  ),
  (
    'ADG-000640'::text,
    '4a561e87-71ce-478a-87fa-f2cc4830cd9e'::uuid,
    '63b2bbc4-513a-49ee-9035-75eff13212c7'::uuid,
    'Zupa makaronowa Demae Ramen o smaku kaczki 100g - Nissin'::text,
    'zupa-makaronowa-demae-ramen-o-smaku-kaczki-100g-nissin'::text,
    '2026-07-08 12:12:07.93723+00:00'::timestamptz,
    '["cereals","crustaceans","fish","soybeans","celery","molluscs","milk"]'::jsonb,
    '["cereals","crustaceans","fish","soybeans","celery","molluscs","milk"]'::jsonb,
    '["mustard","sesame"]'::jsonb,
    '["mustard","sesame"]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    '{"fat":21,"carbs":57,"sugar":2,"protein":10,"calories":450,"servingSize":"w porcji 100g","saturatedFat":8}'::jsonb,
    '{"fat":21,"carbs":57,"sugar":2,"protein":10,"calories":450,"servingSize":"w porcji 100g","saturatedFat":8}'::jsonb,
    NULL::text,
    'Węgry'::text,
    'Makaron (92,2%): mąka pszenna , olej palmowy, substancje spulchniające: węglan sodu, trifosforany; stabilizator: węglan potasu; zagęstnik: guma guar; przeciwutleniacz: ekstrakt nasycony tokoferolem Przyprawy (7,8%): sól, cukier, aromaty (zawierają pszenicę, soję, mleko ), sos sojowy w proszku ( soja, pszenica , sól, maltodekstryna), wzmacniacze smaku: glutaminian sodu, guanylan disodowy, inozynian disodowy; czosnek w proszku, zestaw przypraw, aromat kaczki, mięso drobiowe w proszku, barwnik: karmel amoniakalny; regulatory kwasowości: octan sodu, kwas cytrynowy; por, substancja przeciwzbrylająca: dwutlenek krzemu'::text,
    'Makaron (92,2%): mąka pszenna , olej palmowy, substancje spulchniające: węglan sodu, trifosforany; stabilizator: węglan potasu; zagęstnik: guma guar; przeciwutleniacz: ekstrakt nasycony tokoferolem Przyprawy (7,8%): sól, cukier, aromaty (zawierają pszenicę, soję, mleko ), sos sojowy w proszku ( soja, pszenica , sól, maltodekstryna), wzmacniacze smaku: glutaminian sodu, guanylan disodowy, inozynian disodowy; czosnek w proszku, zestaw przypraw, aromat kaczki, mięso drobiowe w proszku, barwnik: karmel amoniakalny; regulatory kwasowości: octan sodu, kwas cytrynowy; por, substancja przeciwzbrylająca: dwutlenek krzemu'::text,
    '53.00'::numeric,
    'KG'::text,
    '7da30509-aad0-475e-ab39-ca7764bffda2'::uuid,
    'Ramyun / Ramen'::text,
    'ramyun-ramen'::text,
    ARRAY['storageZone'::text, 'countryOfOrigin'::text]::text[]
  ),
  (
    'ADG-000693'::text,
    '02c517b1-1b8f-4085-9465-f573d043f844'::uuid,
    '537cd1ba-094d-4f35-8317-dd20990ab14b'::uuid,
    'Zupa makaronowa Demae Ramen o smaku miso 100g - Nissin'::text,
    'zupa-makaronowa-demae-ramen-o-smaku-miso-100g-nissin'::text,
    '2026-07-08 12:12:07.93723+00:00'::timestamptz,
    '["cereals","soybeans","sesame"]'::jsonb,
    '["cereals","soybeans","sesame"]'::jsonb,
    '["crustaceans","milk","celery","mustard","molluscs"]'::jsonb,
    '["crustaceans","milk","celery","mustard","molluscs"]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    '{"fat":3.7,"salt":0.97,"carbs":11.6,"sugar":0.8,"protein":2,"calories":90,"servingSize":"w 100g/100ml","saturatedFat":2}'::jsonb,
    '{"calories":90,"fat":3.7,"saturatedFat":2,"carbs":11.6,"sugar":0.8,"protein":2,"salt":0.97,"servingSize":"100 ml gotowego produktu"}'::jsonb,
    NULL::text,
    'Węgry'::text,
    'Makaron (90,8%): mąka pszenna , olej palmowy, sól, substancje spulchniające: węglan sodu, trifosforany; stabilizator: węglan potasu; zagęstnik: guma guar; przeciwutleniacz: tokoferol Przyprawa bulionowa (9,2%): sól, cukier, wzmacniacze smaku: glutaminian sodu, guanylan disodowy, inozynian disodowy; syrop glukozowy, pasta miso w proszku ( soja , ryż, sól) Przyprawy (7,6%): przyprawy, zagęstnik: guma guar; cebula w proszku, aromaty (zawiera pszenicę, soję, sezam ), barwniki: karmel amoniakalny, ekstrakt z papryki; sos sojowy w proszku ( soja, pszenica , sól, maltodekstryna), substancja przeciwzbrylająca: dwutlenek krzemu; ekstrakt drożdżowy, hydrolizowane białko kukurydziane, regulator kwasowości: kwas bursztynowy'::text,
    'Makaron (90,8%): mąka pszenna , olej palmowy, sól, substancje spulchniające: węglan sodu, trifosforany; stabilizator: węglan potasu; zagęstnik: guma guar; przeciwutleniacz: tokoferol Przyprawa bulionowa (9,2%): sól, cukier, wzmacniacze smaku: glutaminian sodu, guanylan disodowy, inozynian disodowy; syrop glukozowy, pasta miso w proszku ( soja , ryż, sól) Przyprawy (7,6%): przyprawy, zagęstnik: guma guar; cebula w proszku, aromaty (zawiera pszenicę, soję, sezam ), barwniki: karmel amoniakalny, ekstrakt z papryki; sos sojowy w proszku ( soja, pszenica , sól, maltodekstryna), substancja przeciwzbrylająca: dwutlenek krzemu; ekstrakt drożdżowy, hydrolizowane białko kukurydziane, regulator kwasowości: kwas bursztynowy'::text,
    '53.00'::numeric,
    'KG'::text,
    '7da30509-aad0-475e-ab39-ca7764bffda2'::uuid,
    'Ramyun / Ramen'::text,
    'ramyun-ramen'::text,
    ARRAY['storageZone'::text, 'nutritionFacts'::text, 'countryOfOrigin'::text]::text[]
  ),
  (
    'ADG-000781'::text,
    'c655f731-bd4e-4903-a4a0-c3332daf3bc0'::uuid,
    'f299c15b-f02a-42ca-8892-df4b88230477'::uuid,
    'Ryż jaśminowy Premium Quality Orange 5kg - Royal Umbrella'::text,
    'ryz-jasminowy-premium-quality-orange-5kg-royal-umbrella'::text,
    '2026-07-20 19:36:16.250253+00:00'::timestamptz,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    'AMBIENT'::text,
    'AMBIENT'::text,
    NULL::jsonb,
    '{"calories":353,"fat":0.6,"saturatedFat":0.3,"carbs":79,"sugar":0,"protein":7.6,"salt":0,"servingSize":"100g"}'::jsonb,
    'Tajlandia'::text,
    'Kambodża'::text,
    'Ryż jaśminowy 100%'::text,
    'Ryż jaśminowy 100%'::text,
    '9.38'::numeric,
    'KG'::text,
    '62db9128-0d76-4643-87fb-e9c5e875e9cf'::uuid,
    'Ryż i inne ziarna'::text,
    'ryż-i-inne-ziarna'::text,
    ARRAY['nutritionFacts'::text, 'countryOfOrigin'::text]::text[]
  ),
  (
    'ADG-000968'::text,
    'b0afc235-8b9d-4b73-984c-9ea9c01b29e4'::uuid,
    'a4765272-5f8a-47f1-8e4e-f99350a72ae5'::uuid,
    'Makaron ryżowy Vermicelli Bun Gao 400g - ICV'::text,
    'makaron-ryzowy-vermicelli-bun-gao-400g-icv'::text,
    '2026-07-08 12:12:07.93723+00:00'::timestamptz,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    '{"fat":1.06,"salt":0.0034,"carbs":79.8,"sugar":0.24,"protein":5.91,"calories":352,"servingSize":"w 100g/100ml","saturatedFat":0.52}'::jsonb,
    '{"fat":1.06,"salt":0.0034,"carbs":79.8,"sugar":0.24,"protein":5.91,"calories":352,"servingSize":"w 100g/100ml","saturatedFat":0.52}'::jsonb,
    'Kambodża'::text,
    'Kambodża'::text,
    'Mąka ryżowa, woda.'::text,
    'Mąka ryżowa, woda.'::text,
    '24.25'::numeric,
    'KG'::text,
    'f331b4dd-5539-4137-8320-e14795d23f5f'::uuid,
    'Makaron ryżowy'::text,
    'makaron-ryżowy'::text,
    ARRAY['storageZone'::text]::text[]
  ),
  (
    'ADG-001008'::text,
    '1be21c1b-ce11-432f-aaca-7b617e314f8b'::uuid,
    '8d0cc93c-d64b-45be-94da-b200d7a52681'::uuid,
    'Kluski ryżowe do tteokbokki krojone, małe słupki A+ 500g - HoSan'::text,
    'kluski-ryzowe-do-tteokbokki-krojone-male-slupki-a-500g-hosan'::text,
    '2026-07-08 12:12:07.93723+00:00'::timestamptz,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    '{"fat":0.3,"salt":0.5,"carbs":31.3,"sugar":0,"protein":2.4,"calories":139,"servingSize":"w 100g/100ml"}'::jsonb,
    '{"fat":0.3,"salt":0.5,"carbs":31.3,"sugar":0,"protein":2.4,"calories":139,"servingSize":"w 100g/100ml"}'::jsonb,
    'Korea Południowa'::text,
    'Korea Południowa'::text,
    'Ryż (98,9%), sól, alkohol, regulator kwasowości: kwas cytrynowy (E330)'::text,
    'Ryż (98,9%), sól, alkohol, regulator kwasowości: kwas cytrynowy (E330)'::text,
    '29.98'::numeric,
    'KG'::text,
    '6a1b2166-3379-4014-adec-99172d5336b0'::uuid,
    'Kluski tteok do dań'::text,
    'kluski-tteok-do-dań'::text,
    ARRAY['storageZone'::text]::text[]
  ),
  (
    'ADG-001021'::text,
    '27937c35-4d6e-43de-85bc-37e078c3c327'::uuid,
    'a5faddd3-a1a4-43ec-8374-0befc704b0b6'::uuid,
    'Ryż Basmati Original 1kg - Swad'::text,
    'ryz-basmati-original-1kg-swad'::text,
    '2026-07-08 12:12:07.93723+00:00'::timestamptz,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    '{"fat":0.5,"salt":0.1,"carbs":84,"sugar":0.1,"protein":8,"calories":351,"servingSize":"w 100g/100ml","saturatedFat":0.1}'::jsonb,
    '{"fat":0.5,"salt":0.1,"carbs":84,"sugar":0.1,"protein":8,"calories":351,"servingSize":"w 100g/100ml","saturatedFat":0.1}'::jsonb,
    'Pakistan'::text,
    'Indie'::text,
    '100% ryż basmati'::text,
    '100% ryż basmati'::text,
    '20.99'::numeric,
    'KG'::text,
    '62db9128-0d76-4643-87fb-e9c5e875e9cf'::uuid,
    'Ryż i inne ziarna'::text,
    'ryż-i-inne-ziarna'::text,
    ARRAY['storageZone'::text, 'countryOfOrigin'::text]::text[]
  ),
  (
    'ADG-001039'::text,
    'bbd40b6f-2dc1-44dd-872f-2f0e7ee9c21e'::uuid,
    'aa24aea0-d582-4130-9497-eeb62fdb851a'::uuid,
    'Ryż jaśminowy Thai Hom Mali Rice 1kg - Aroy-D'::text,
    'ryz-jasminowy-thai-hom-mali-rice-1kg-aroy-d'::text,
    '2026-07-08 12:12:07.93723+00:00'::timestamptz,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    '{"fat":1.2,"salt":0,"carbs":78,"sugar":0,"protein":6.9,"calories":353,"servingSize":"w 100g/100ml","saturatedFat":0.3}'::jsonb,
    '{"fat":1.2,"salt":0,"carbs":78,"sugar":0,"protein":6.9,"calories":353,"servingSize":"w 100g/100ml","saturatedFat":0.3}'::jsonb,
    'Tajlandia'::text,
    'Tajlandia'::text,
    '100% ryż jaśminowy długoziarnisty'::text,
    '100% ryż jaśminowy długoziarnisty'::text,
    '16.99'::numeric,
    'KG'::text,
    '62db9128-0d76-4643-87fb-e9c5e875e9cf'::uuid,
    'Ryż i inne ziarna'::text,
    'ryż-i-inne-ziarna'::text,
    ARRAY['storageZone'::text]::text[]
  ),
  (
    'ADG-001415'::text,
    '7f628ce5-d117-4045-927e-b93c4cd15f8c'::uuid,
    '2f8b1397-26d6-43af-a9c1-b8ae4b9f7d51'::uuid,
    'Ryż Basmati Premium Quality 1kg - Royal Tiger'::text,
    'ryz-basmati-premium-quality-1kg-royal-tiger'::text,
    '2026-07-08 12:12:07.93723+00:00'::timestamptz,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL::text,
    'AMBIENT'::text,
    '{"fat":0.5,"salt":0,"carbs":77,"sugar":0.5,"protein":8,"calories":349,"servingSize":"w 100g/100ml","saturatedFat":0.5}'::jsonb,
    '{"fat":0.5,"salt":0,"carbs":77,"sugar":0.5,"protein":8,"calories":349,"servingSize":"w 100g/100ml","saturatedFat":0.5}'::jsonb,
    'Pakistan'::text,
    'Pakistan'::text,
    '100% ryż basmati'::text,
    '100% ryż basmati'::text,
    '18.50'::numeric,
    'KG'::text,
    '3c1c6a11-79fd-4a60-a5df-27ed5c60d860'::uuid,
    'Ryż do sushi i nie tylko'::text,
    'ryż-do-sushi-i-nie-tylko'::text,
    ARRAY['storageZone'::text]::text[]
  );

DO $$
DECLARE affected integer;
BEGIN
  IF (SELECT COUNT(*) FROM _adg_metadata_target_salon) <> 1 THEN
    RAISE EXCEPTION 'Expected exactly one active pinned asiandeligo channel';
  END IF;
  IF to_regclass('public.asiandeligo_catalog_metadata_batch3_product_backup_20260722') IS NULL
     OR to_regclass('public.asiandeligo_catalog_metadata_batch3_audit_20260722') IS NULL THEN
    RAISE EXCEPTION 'Required batch backup/audit table is missing';
  END IF;
  IF (
    SELECT COUNT(*)
    FROM public.asiandeligo_catalog_metadata_batch3_product_backup_20260722
    WHERE batch_key = 'asiandeligo-catalog-metadata-batch3-20260722-v1'
      AND decision_sha256 = '01e138ed3f76c4871e981bec117a4e1051ba18d3bfdc8566364012c4c46fa00e'
      AND salon_id = 'e73271a9-53e3-4a20-a02e-791726b452aa'::uuid
  ) <> 18 THEN
    RAISE EXCEPTION 'Expected exactly 18 tenant- and decision-scoped backup rows';
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM public.asiandeligo_catalog_metadata_batch3_audit_20260722
    WHERE batch_key = 'asiandeligo-catalog-metadata-batch3-20260722-v1'
      AND decision_sha256 = '01e138ed3f76c4871e981bec117a4e1051ba18d3bfdc8566364012c4c46fa00e'
      AND salon_id = 'e73271a9-53e3-4a20-a02e-791726b452aa'::uuid
      AND action = 'backup_captured'
      AND product_rows = 18
  ) OR NOT EXISTS (
    SELECT 1 FROM public.asiandeligo_catalog_metadata_batch3_audit_20260722
    WHERE batch_key = 'asiandeligo-catalog-metadata-batch3-20260722-v1'
      AND decision_sha256 = '01e138ed3f76c4871e981bec117a4e1051ba18d3bfdc8566364012c4c46fa00e'
      AND salon_id = 'e73271a9-53e3-4a20-a02e-791726b452aa'::uuid
      AND action = 'apply_complete'
      AND product_rows = 18
  ) OR EXISTS (
    SELECT 1 FROM public.asiandeligo_catalog_metadata_batch3_audit_20260722
    WHERE batch_key = 'asiandeligo-catalog-metadata-batch3-20260722-v1'
      AND decision_sha256 = '01e138ed3f76c4871e981bec117a4e1051ba18d3bfdc8566364012c4c46fa00e'
      AND salon_id = 'e73271a9-53e3-4a20-a02e-791726b452aa'::uuid
      AND action = 'rollback_complete'
  ) THEN
    RAISE EXCEPTION 'Required apply audit chain is incomplete or rollback already completed';
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_catalog.pg_trigger
    WHERE tgrelid = 'public.products'::regclass
      AND tgname = 'zz_enforce_products_monotonic_updated_at'
      AND NOT tgisinternal
      AND tgenabled <> 'D'
  ) OR EXISTS (
    SELECT 1
    FROM _adg_metadata_decisions decision
    CROSS JOIN _adg_metadata_target_salon tenant
    LEFT JOIN public.asiandeligo_catalog_metadata_batch3_product_backup_20260722 backup
      ON backup.batch_key = 'asiandeligo-catalog-metadata-batch3-20260722-v1'
     AND backup.decision_sha256 = '01e138ed3f76c4871e981bec117a4e1051ba18d3bfdc8566364012c4c46fa00e'
     AND backup.salon_id = tenant.salon_id
     AND backup.sku = decision.sku
     AND backup.product_id = decision.product_id
    AND backup.variant_id = decision.variant_id
    AND backup.category_id = decision.category_id
    AND backup.changed_fields = decision.changed_fields
    AND backup.original_updated_at = decision.expected_updated_at
    AND backup.applied_updated_at IS NOT NULL
    AND backup.applied_updated_at > backup.original_updated_at
    AND backup.allergens IS NOT DISTINCT FROM decision.expected_allergens
    AND backup.may_contain_allergens IS NOT DISTINCT FROM decision.expected_may_contain_allergens
    AND backup.storage_zone IS NOT DISTINCT FROM decision.expected_storage_zone
    AND backup.nutrition_facts IS NOT DISTINCT FROM decision.expected_nutrition_facts
    AND backup.country_of_origin IS NOT DISTINCT FROM decision.expected_country_of_origin
    AND backup.ingredients IS NOT DISTINCT FROM decision.expected_ingredients
    AND backup.price_per_unit IS NOT DISTINCT FROM decision.expected_price_per_unit
    AND backup.unit_of_measure IS NOT DISTINCT FROM decision.expected_unit_of_measure
    WHERE backup.sku IS NULL
  ) THEN
    RAISE EXCEPTION 'Required timestamp trigger or exact reviewed backup snapshot is missing';
  END IF;

  PERFORM 1
  FROM _adg_metadata_decisions decision
  CROSS JOIN _adg_metadata_target_salon tenant
  JOIN public.asiandeligo_catalog_metadata_batch3_product_backup_20260722 backup
    ON backup.batch_key = 'asiandeligo-catalog-metadata-batch3-20260722-v1'
   AND backup.decision_sha256 = '01e138ed3f76c4871e981bec117a4e1051ba18d3bfdc8566364012c4c46fa00e'
   AND backup.salon_id = tenant.salon_id
   AND backup.sku = decision.sku
   AND backup.product_id = decision.product_id
    AND backup.variant_id = decision.variant_id
    AND backup.category_id = decision.category_id
    AND backup.changed_fields = decision.changed_fields
    AND backup.original_updated_at = decision.expected_updated_at
    AND backup.applied_updated_at IS NOT NULL
    AND backup.applied_updated_at > backup.original_updated_at
    AND backup.allergens IS NOT DISTINCT FROM decision.expected_allergens
    AND backup.may_contain_allergens IS NOT DISTINCT FROM decision.expected_may_contain_allergens
    AND backup.storage_zone IS NOT DISTINCT FROM decision.expected_storage_zone
    AND backup.nutrition_facts IS NOT DISTINCT FROM decision.expected_nutrition_facts
    AND backup.country_of_origin IS NOT DISTINCT FROM decision.expected_country_of_origin
    AND backup.ingredients IS NOT DISTINCT FROM decision.expected_ingredients
    AND backup.price_per_unit IS NOT DISTINCT FROM decision.expected_price_per_unit
    AND backup.unit_of_measure IS NOT DISTINCT FROM decision.expected_unit_of_measure
  JOIN public.product_variants variant
    ON variant.id = decision.variant_id
    AND variant.sku = decision.sku
    AND variant.salon_id = tenant.salon_id
   AND variant.is_active = TRUE
   AND variant.is_published = FALSE
   AND variant.is_for_sale = TRUE
   AND variant.sync_status = 'synced'
   AND variant.availability_status = 'IN_STOCK'
    AND variant.deleted_at IS NULL
  JOIN public.products product
    ON product.id = decision.product_id
    AND product.id = variant.template_id
    AND product.salon_id = tenant.salon_id
   AND product.name = decision.expected_name
   AND product.slug = decision.expected_slug
    AND product.updated_at = backup.applied_updated_at
   AND product.is_active = TRUE
   AND product.is_published = TRUE
   AND product.is_visible = TRUE
   AND product.status = 'active'
    AND product.deleted_at IS NULL
  JOIN public.categories category
    ON category.id = decision.category_id
   AND category.id = product.category_id
   AND category.salon_id = tenant.salon_id
   AND category.name = decision.category_name
   AND category.slug = decision.category_slug
   AND category.is_active = TRUE
  WHERE product.allergens IS NOT DISTINCT FROM decision.target_allergens
    AND product.may_contain_allergens IS NOT DISTINCT FROM decision.target_may_contain_allergens
    AND product.storage_zone IS NOT DISTINCT FROM decision.target_storage_zone
    AND product.nutrition_facts IS NOT DISTINCT FROM decision.target_nutrition_facts
    AND product.country_of_origin IS NOT DISTINCT FROM decision.target_country_of_origin
    AND product.ingredients IS NOT DISTINCT FROM decision.target_ingredients
    AND product.price_per_unit IS NOT DISTINCT FROM decision.expected_price_per_unit
    AND product.unit_of_measure IS NOT DISTINCT FROM decision.expected_unit_of_measure
  ORDER BY product.id
  FOR UPDATE OF product, variant, category;
  GET DIAGNOSTICS affected = ROW_COUNT;
  IF affected <> 18 THEN
    RAISE EXCEPTION 'Expected 18 exact target row locks; refusing to overwrite intervening edits';
  END IF;
END $$;

DO $$
DECLARE affected integer;
BEGIN
  UPDATE public.products product
  SET allergens = backup.allergens,
      may_contain_allergens = backup.may_contain_allergens,
      storage_zone = backup.storage_zone,
      nutrition_facts = backup.nutrition_facts,
      country_of_origin = backup.country_of_origin,
      ingredients = backup.ingredients
  FROM _adg_metadata_decisions decision,
       _adg_metadata_target_salon tenant,
       public.asiandeligo_catalog_metadata_batch3_product_backup_20260722 backup
  WHERE backup.batch_key = 'asiandeligo-catalog-metadata-batch3-20260722-v1'
    AND backup.decision_sha256 = '01e138ed3f76c4871e981bec117a4e1051ba18d3bfdc8566364012c4c46fa00e'
    AND backup.salon_id = tenant.salon_id
    AND backup.sku = decision.sku
    AND backup.product_id = product.id
    AND product.salon_id = tenant.salon_id
    AND product.name = decision.expected_name
    AND product.slug = decision.expected_slug
    AND product.updated_at = backup.applied_updated_at
    AND product.is_active = TRUE
    AND product.is_published = TRUE
    AND product.is_visible = TRUE
    AND product.status = 'active'
    AND product.deleted_at IS NULL
    AND backup.product_id = decision.product_id
    AND backup.variant_id = decision.variant_id
    AND backup.category_id = decision.category_id
    AND backup.changed_fields = decision.changed_fields
    AND backup.original_updated_at = decision.expected_updated_at
    AND backup.applied_updated_at IS NOT NULL
    AND backup.applied_updated_at > backup.original_updated_at
    AND backup.allergens IS NOT DISTINCT FROM decision.expected_allergens
    AND backup.may_contain_allergens IS NOT DISTINCT FROM decision.expected_may_contain_allergens
    AND backup.storage_zone IS NOT DISTINCT FROM decision.expected_storage_zone
    AND backup.nutrition_facts IS NOT DISTINCT FROM decision.expected_nutrition_facts
    AND backup.country_of_origin IS NOT DISTINCT FROM decision.expected_country_of_origin
    AND backup.ingredients IS NOT DISTINCT FROM decision.expected_ingredients
    AND backup.price_per_unit IS NOT DISTINCT FROM decision.expected_price_per_unit
    AND backup.unit_of_measure IS NOT DISTINCT FROM decision.expected_unit_of_measure
    AND product.allergens IS NOT DISTINCT FROM decision.target_allergens
    AND product.may_contain_allergens IS NOT DISTINCT FROM decision.target_may_contain_allergens
    AND product.storage_zone IS NOT DISTINCT FROM decision.target_storage_zone
    AND product.nutrition_facts IS NOT DISTINCT FROM decision.target_nutrition_facts
    AND product.country_of_origin IS NOT DISTINCT FROM decision.target_country_of_origin
    AND product.ingredients IS NOT DISTINCT FROM decision.target_ingredients
    AND product.price_per_unit IS NOT DISTINCT FROM decision.expected_price_per_unit
    AND product.unit_of_measure IS NOT DISTINCT FROM decision.expected_unit_of_measure;
  GET DIAGNOSTICS affected = ROW_COUNT;
  IF affected <> 18 THEN
    RAISE EXCEPTION 'Expected 18 exact product restorations, got %', affected;
  END IF;

  IF (
    SELECT COUNT(*)
    FROM public.products product
    JOIN public.asiandeligo_catalog_metadata_batch3_product_backup_20260722 backup
      ON backup.product_id = product.id
     AND backup.batch_key = 'asiandeligo-catalog-metadata-batch3-20260722-v1'
     AND backup.decision_sha256 = '01e138ed3f76c4871e981bec117a4e1051ba18d3bfdc8566364012c4c46fa00e'
     AND backup.salon_id = product.salon_id
    WHERE product.salon_id = 'e73271a9-53e3-4a20-a02e-791726b452aa'::uuid
      AND product.updated_at > backup.applied_updated_at
      AND product.allergens IS NOT DISTINCT FROM backup.allergens
      AND product.may_contain_allergens IS NOT DISTINCT FROM backup.may_contain_allergens
      AND product.storage_zone IS NOT DISTINCT FROM backup.storage_zone
      AND product.nutrition_facts IS NOT DISTINCT FROM backup.nutrition_facts
      AND product.country_of_origin IS NOT DISTINCT FROM backup.country_of_origin
      AND product.ingredients IS NOT DISTINCT FROM backup.ingredients
      AND product.price_per_unit IS NOT DISTINCT FROM backup.price_per_unit
      AND product.unit_of_measure IS NOT DISTINCT FROM backup.unit_of_measure
  ) <> 18 THEN
    RAISE EXCEPTION 'Rollback post-state verification failed';
  END IF;

  INSERT INTO public.asiandeligo_catalog_metadata_batch3_audit_20260722 (
    batch_key, decision_sha256, channel_slug, salon_id, action, product_rows
  )
  SELECT 'asiandeligo-catalog-metadata-batch3-20260722-v1', '01e138ed3f76c4871e981bec117a4e1051ba18d3bfdc8566364012c4c46fa00e', channel_slug, salon_id,
         'rollback_complete', 18
  FROM _adg_metadata_target_salon;
END $$;

SELECT backup.sku, backup.changed_fields, audit.recorded_at, audit.transaction_id
FROM public.asiandeligo_catalog_metadata_batch3_product_backup_20260722 backup
JOIN public.asiandeligo_catalog_metadata_batch3_audit_20260722 audit
  ON audit.batch_key = backup.batch_key
 AND audit.salon_id = backup.salon_id
 AND audit.action = 'rollback_complete'
WHERE backup.batch_key = 'asiandeligo-catalog-metadata-batch3-20260722-v1'
  AND backup.decision_sha256 = '01e138ed3f76c4871e981bec117a4e1051ba18d3bfdc8566364012c4c46fa00e'
  AND backup.salon_id = 'e73271a9-53e3-4a20-a02e-791726b452aa'::uuid
ORDER BY backup.sku;

COMMIT;
