-- Generated by scripts/product-translation-sql-plan.mjs
-- Safe behavior: Kenmito channel only; upserts one language; backs up existing rows first.
BEGIN;

CREATE TABLE IF NOT EXISTS kenmito_product_translations_backup_20260627 (LIKE product_translations INCLUDING ALL);

WITH source(template_id, slug, product_name, short_description, meta_title, meta_description) AS (
  VALUES
  ('adcd2bb3-9284-4ac4-9766-2d39c319ad86', 'KIMCHI-5216', '2 x Angel Hair Chocolate, chocolate set with angel hair and pistachios - white and pink 80g Mistachio', '2 x Angel Hair Chocolate, chocolate set with angel hair and pistachios - white and pink 80g Mistachio', '2 x Angel Hair Chocolate, chocolate set with angel hair and pistachios - white and pink 80g Mistachio', '2 x Angel Hair Chocolate, chocolate set with angel hair and pistachios - white and pink 80g Mistachio'),
  ('7f821fb2-729b-411d-aa9a-f34886fea0ec', 'KIMCHI-5215', '2 x Dubai Chocolate, set of Dubai chocolates with pistachio cream and kataifi cake - milk and white 160g Q Chew', 'A unique set of Dubai chocolates featuring intense chocolate, crispy kataifi, and smooth pistachio filling. Experience a delightful contrast in texture and flavor.', '2 x Dubai Chocolate, set of Dubai chocolates with pistachio cream and kataifi cake - milk and white 160g Q Chew', 'A unique set of Dubai chocolates featuring intense chocolate, crispy kataifi, and smooth pistachio filling. Experience a delightful contrast in texture and flavor.'),
  ('4afbcbc4-fb57-4059-b114-c1853c9fc1c6', 'KIMCHI-5034', 'Ajitsuke Menma, marinated fermented bamboo shoots slices 100g - Momoya', 'Marinated fermented bamboo shoots in slices, 100g - Momoya', 'Ajitsuke Menma, marinated fermented bamboo shoots slices 100g - Momoya', 'Marinated fermented bamboo shoots in slices, 100g - Momoya'),
  ('1e6b429d-24aa-4f7f-9c60-2c8fb969f7f4', 'KIMCHI-1428', 'Ajitsuke Shiitake, mushrooms in sweet marinade 500g - Asia Kitchen', '500-gram package filled with delicious Ajitsuke Shiitake! Sliced shiitake mushrooms in a sweet soy sauce-based marinade, perfect for sushi, rice, noodles, stir-fry, or as a standalone appetizer.', 'Ajitsuke Shiitake, mushrooms in sweet marinade 500g - Asia Kitchen', '500-gram package filled with delicious Ajitsuke Shiitake! Sliced shiitake mushrooms in a sweet soy sauce-based marinade, perfect for sushi, rice, noodles, stir-fry, or as a standalone appetizer.'),
  ('25a2c3c5-267e-41f7-9a00-a66d22c9407a', 'KIMCHI-14', 'Nori Seaweed for Sushi, 6 Sheets - House of Asia', 'Thin sheets of dried seaweed, an essential element for sushi and a popular addition to Asian dishes.', 'Nori Seaweed for Sushi, 6 Sheets - House of Asia', 'Thin sheets of dried seaweed, an essential element for sushi and a popular addition to Asian dishes.'),
  ('9772939b-e59e-4f3f-b110-0c629561662a', 'KIMCHI-2761', 'Sen Soy Nori Gold 50 Sheets', 'High-quality roasted seaweed sheets, perfect for making sushi. This large pack contains 50 sheets, suitable for 50 large or 100 small sushi rolls.', 'Sen Soy Nori Gold 50 Sheets', 'High-quality roasted seaweed sheets, perfect for making sushi. This large pack contains 50 sheets, suitable for 50 large or 100 small sushi rolls.'),
  ('3c560dda-81db-4518-983b-c57dddd07b56', 'KIMCHI-2505', 'Sushi Nori Seaweed Premium Gold 10 pcs - Asia Kitchen', '10 sheets of Premium Gold roasted nori seaweed, ideal for Japanese sushi. Perfect for making hosomaki, futomaki, uramaki, and temaki.', 'Sushi Nori Seaweed Premium Gold 10 pcs - Asia Kitchen', '10 sheets of Premium Gold roasted nori seaweed, ideal for Japanese sushi. Perfect for making hosomaki, futomaki, uramaki, and temaki.'),
  ('cc9d23b3-fb57-4788-8a28-e73456484a76', 'KIMCHI-2506', 'Asia Kitchen Premium Gold Sushi Nori 3 x 10 sheets', '30 sheets of premium roasted nori seaweed, ideal for making Japanese sushi. Perfect for hosomaki, futomaki, uramaki, and temaki.', 'Asia Kitchen Premium Gold Sushi Nori 3 x 10 sheets', '30 sheets of premium roasted nori seaweed, ideal for making Japanese sushi. Perfect for hosomaki, futomaki, uramaki, and temaki.'),
  ('15562453-ea2a-486c-af9b-69f839c457e8', 'KIMCHI-2507', 'Sushi Nori Seaweed Premium Gold 5 x 10 pcs - Asia Kitchen', 'Premium Gold roasted nori seaweed sheets, ideal for making Japanese sushi. Perfect for hosomaki, futomaki, uramaki, and temaki.', 'Sushi Nori Seaweed Premium Gold 5 x 10 pcs - Asia Kitchen', 'Premium Gold roasted nori seaweed sheets, ideal for making Japanese sushi. Perfect for hosomaki, futomaki, uramaki, and temaki.'),
  ('2cafcfd0-c8e2-4a5c-8d44-a01c2b52b34d', 'KIMCHI-5450', 'Aloe 97% Soothing Gel Lotion Intensive Moisturizing 240ml - Holika Holika', 'Aloe 97% Soothing Gel Lotion provides intensive moisture and soothing effects for the skin. Ideal for daily use to maintain hydration.', 'Aloe 97% Soothing Gel Lotion Intensive Moisturizing 240ml - Holika Holika', 'Aloe 97% Soothing Gel Lotion provides intensive moisture and soothing effects for the skin. Ideal for daily use to maintain hydration.'),
  ('dd214412-72a5-48c9-a6d0-8af96e14c5c2', 'KIMCHI-5449', 'Aloe 99% Soothing Gel 250ml - multifunctional aloe gel for face, body, and hair - Holika Holika', 'Holika Holika Aloe 99% Soothing Gel is a multifunctional gel for body, face, and hair, providing hydration and refreshment. It soothes irritated skin and enhances elasticity.', 'Aloe 99% Soothing Gel 250ml - multifunctional aloe gel for face, body, and hair - Holika Holika', 'Holika Holika Aloe 99% Soothing Gel is a multifunctional gel for body, face, and hair, providing hydration and refreshment. It soothes irritated skin and enhances elasticity.'),
  ('3bf41da3-be08-4b66-aa9c-842cff3be645', 'KIMCHI-5452', 'Aloe CICA Waterproof Sunscreen SPF 50+ PA++++ 100ml Holika Holika', 'Aloe CICA Waterproof Sunscreen SPF 50+ PA++++ is a soothing and moisturizing sunscreen gel that provides maximum UV protection while caring for sensitive skin.', 'Aloe CICA Waterproof Sunscreen SPF 50+ PA++++ 100ml Holika Holika', 'Aloe CICA Waterproof Sunscreen SPF 50+ PA++++ is a soothing and moisturizing sunscreen gel that provides maximum UV protection while caring for sensitive skin.'),
  ('5ad12147-8c27-425f-a503-711c2a89e59b', 'KIMCHI-5451', 'Aloe Facial Cleansing Foam 150ml Holika Holika', 'Aloe Facial Cleansing Foam is a gentle cleanser for the face with aloe vera extract. It cleanses while maintaining skin''s pH and soothes irritation for a fresh look.', 'Aloe Facial Cleansing Foam 150ml Holika Holika', 'Aloe Facial Cleansing Foam is a gentle cleanser for the face with aloe vera extract. It cleanses while maintaining skin''s pH and soothes irritation for a fresh look.'),
  ('9989a4cc-b93d-4e84-96ed-e67661426a5a', 'KIMCHI-5454', 'Aloe Soothing Jelly Mask Fresh 23ml - Holika Holika', 'Holika Holika Aloe Soothing Jelly Mask Fresh is a sheet mask containing 99% aloe leaf juice extract, providing hydration and soothing for sensitive skin.', 'Aloe Soothing Jelly Mask Fresh 23ml - Holika Holika', 'Holika Holika Aloe Soothing Jelly Mask Fresh is a sheet mask containing 99% aloe leaf juice extract, providing hydration and soothing for sensitive skin.'),
  ('53d0154b-fa66-4312-b8a1-cd25fc308052', 'KIMCHI-5214', 'Angel Hair White Chocolate with Pistachios 80g - Mistachio', 'Delicious angel hair white chocolate with pistachios, perfect for a sweet treat or snack.', 'Angel Hair White Chocolate with Pistachios 80g - Mistachio', 'Delicious angel hair white chocolate with pistachios, perfect for a sweet treat or snack.'),
  ('1c4a4fb7-4e6c-418d-8f1e-250b4f2c72dd', 'KIMCHI-3440', 'Star Anise Whole 50g - TRS', 'Star anise is a unique spice with a wonderful flavor and appearance. It is commonly used whole or ground in various dishes, desserts, and beverages.', 'Star Anise Whole 50g - TRS', 'Star anise is a unique spice with a wonderful flavor and appearance. It is commonly used whole or ground in various dishes, desserts, and beverages.'),
  ('ae4fe4e9-04e4-4d1d-becf-ec16718eef46', 'KIMCHI-5463', 'Aqua Petit BB 30ml - Light BB Cream with Green Tea Extract - Holika Holika', 'Holika Holika Aqua Petit BB AD is a light BB cream with SPF 25 PA++ that hydrates and evens skin tone while protecting against UV rays. Suitable for most skin types.', 'Aqua Petit BB 30ml - Light BB Cream with Green Tea Extract - Holika Holika', 'Holika Holika Aqua Petit BB AD is a light BB cream with SPF 25 PA++ that hydrates and evens skin tone while protecting against UV rays. Suitable for most skin types.'),
  ('46403f5b-6402-4512-ad23-08e0cc2fdde0', 'KIMCHI-5832', 'Aqua Petit Jelly BB SPF20 40ml - Light BB Cream + Sponge - Holika Holika', 'Holika Holika Aqua Petit Jelly BB SPF20 is a lightweight BB cream with mint extract that helps even skin tone and conceal minor imperfections. It provides a natural finish and UV protection.', 'Aqua Petit Jelly BB SPF20 40ml - Light BB Cream + Sponge - Holika Holika', 'Holika Holika Aqua Petit Jelly BB SPF20 is a lightweight BB cream with mint extract that helps even skin tone and conceal minor imperfections. It provides a natural finish and UV protection.'),
  ('762e8c58-8152-4369-aeb0-f3bf39f653b2', 'KIMCHI-3795', 'Bancha, Green Tea from Late Harvest 60g - Maruka', 'Bancha green tea from the Shizuoka prefecture, harvested in late summer and autumn. It has a mild, refreshing flavor and can be brewed multiple times.', 'Bancha, Green Tea from Late Harvest 60g - Maruka', 'Bancha green tea from the Shizuoka prefecture, harvested in late summer and autumn. It has a mild, refreshing flavor and can be brewed multiple times.'),
  ('1d859284-0386-4d9f-8a13-7f38235880f0', 'KIMCHI-5722', 'Hot Pot Soup Base, Very Spicy 220g - HAIDILAO', 'Hot pot soup base with a very spicy flavor, perfect for enhancing your hot pot dishes.', 'Hot Pot Soup Base, Very Spicy 220g - HAIDILAO', 'Hot pot soup base with a very spicy flavor, perfect for enhancing your hot pot dishes.'),
  ('a1174ab6-9194-4509-898d-e5d7237173bb', 'KIMCHI-5721', 'Hot Pot Soup Base, Medium Hot 220g - HAIDILAO', 'Hot Pot Soup Base, Medium Hot 220g - HAIDILAO', 'Hot Pot Soup Base, Medium Hot 220g - HAIDILAO', 'Hot Pot Soup Base, Medium Hot 220g - HAIDILAO'),
  ('2430258e-f9a6-4e22-8168-903c6f9c773e', 'KIMCHI-5720', 'Hot Pot Soup Base Cubes, Spicy 4x90g (360g) - HAIDILAO', 'Hot Pot Soup Base Cubes, Spicy 4x90g (360g) - HAIDILAO. A flavorful base for hot pot, easy to prepare with water or broth, perfect for adding meats and vegetables.', 'Hot Pot Soup Base Cubes, Spicy 4x90g (360g) - HAIDILAO', 'Hot Pot Soup Base Cubes, Spicy 4x90g (360g) - HAIDILAO. A flavorful base for hot pot, easy to prepare with water or broth, perfect for adding meats and vegetables.'),
  ('d7190b58-a944-4fbc-a488-f56c7abd6435', 'KIMCHI-2004', 'Hot Pot Base Paste Sichuan Style 70g - Lee Kum Kee', 'Hot Pot Base Paste Sichuan Style for creating a flavorful broth. Mix the contents with 1.5L of water (6 cups) to prepare your Hot Pot base.', 'Hot Pot Base Paste Sichuan Style 70g - Lee Kum Kee', 'Hot Pot Base Paste Sichuan Style for creating a flavorful broth. Mix the contents with 1.5L of water (6 cups) to prepare your Hot Pot base.'),
  ('dda2f6bc-84b6-4ecb-afe1-e3c4d36882fd', 'KIMCHI-2578', 'Pho Soup Base, Mild 80g - Sen Soy', 'Liquid base for preparing aromatic Vietnamese Pho soup, combining fish sauce, scallions, ginger, and essential spices. Easy to use and flavorful.', 'Pho Soup Base, Mild 80g - Sen Soy', 'Liquid base for preparing aromatic Vietnamese Pho soup, combining fish sauce, scallions, ginger, and essential spices. Easy to use and flavorful.'),
  ('c9fb3005-1b8c-440e-8390-122b1c88a26a', 'KIMCHI-2579', 'Tom Yum Soup Base, Mild 80g - Sen Soy', 'Liquid base for preparing sweet and sour Thai Tom Yum soup. Contains essential ingredients like coconut cream and fish sauce.', 'Tom Yum Soup Base, Mild 80g - Sen Soy', 'Liquid base for preparing sweet and sour Thai Tom Yum soup. Contains essential ingredients like coconut cream and fish sauce.')
), matched AS (
  SELECT
    p.salon_id,
    p.id AS template_id,
    s.slug,
    s.product_name,
    s.short_description,
    s.meta_title,
    s.meta_description
  FROM source s
  JOIN channels ch ON ch.slug = 'kenmito' AND ch.is_active = true
  JOIN products p ON p.id = s.template_id::uuid AND p.salon_id = ch.salon_id
  WHERE p.deleted_at IS NULL
), backup_insert AS (
  INSERT INTO kenmito_product_translations_backup_20260627
  SELECT pt.*
  FROM product_translations pt
  JOIN matched m ON m.template_id = pt.template_id AND m.salon_id = pt.salon_id
  WHERE pt.lang_id = 'en'
    AND NOT EXISTS (SELECT 1 FROM kenmito_product_translations_backup_20260627 b WHERE b.id = pt.id)
  RETURNING id
), upserted AS (
  INSERT INTO product_translations (
    id, salon_id, template_id, lang_id, product_name, short_description,
    meta_title, meta_description, created_at, updated_at
  )
  SELECT
    gen_random_uuid(),
    salon_id,
    template_id,
    'en',
    product_name,
    short_description,
    meta_title,
    meta_description,
    NOW(),
    NOW()
  FROM matched
  ON CONFLICT (template_id, lang_id) DO UPDATE SET
    product_name = EXCLUDED.product_name,
    short_description = EXCLUDED.short_description,
    meta_title = EXCLUDED.meta_title,
    meta_description = EXCLUDED.meta_description,
    updated_at = NOW()
  WHERE product_translations.salon_id = EXCLUDED.salon_id
  RETURNING template_id
)
SELECT
  (SELECT COUNT(*) FROM source) AS source_rows,
  (SELECT COUNT(*) FROM matched) AS matched_rows,
  (SELECT COUNT(*) FROM backup_insert) AS backed_up_rows,
  (SELECT COUNT(*) FROM upserted) AS upserted_rows;

-- Verify the printed counts after running. The backup table can be used to restore previous EN rows if needed.
COMMIT;
